dolthub/dolt

bats/git-dolt.bats, go/Godeps/LICENSES, go/cmd/git-dolt/git-dolt.go, go/go.mod, go/go.sum
A [video](https://www.youtube.com/watch?v=WvWPGVKLvR4) about [Cobra](https://github.com/spf13/cobra) came on YouTube autoplay and I was bored so I decided to try migrating `git-dolt` to it. It was easy and comes with [some](https://github.com/spf13/cobra#help-command) [nice](https://github.com/spf13/cobra#usage-message) [benefits](https://github.com/spf13/cobra#suggestions-when-unknown-command-happens). Look how pretty!
```
$ git-dolt
Run a git-dolt subcommand.
Valid subcommands are: fetch, help, install, link, update.
Usage:
git-dolt [command]
Available Commands:
fetch       Fetches the Dolt repository referred to in the given git-dolt pointer file
help        Help about any command
install     Installs the git-dolt smudge filter for this Git repository
link        Links the given Dolt …
```
=> Update git-dolt to use cobra for better UI

go/cmd/dolt/commands/tblcmds/import.go, go/libraries/doltcore/mvdata/data_loc.go, go/libraries/doltcore/mvdata/data_loc_test.go, go/libraries/doltcore/mvdata/data_mover.go
Previous versions of import required csv files to use commas.  This change allows the delimiter to be a string passed on the command line.
=> csv import delim param

go/store/nbs/table_reader.go
The declaration of the variables readStart, readEnd, and batch are declared outside of the for loop, and it is possible that their value can change before the go routine calls readAtOffsets causing some or all of these values to be incorrect.  The fix is to save them to variables scoped to the loop before calling the go routine.
=> fix race condition which caused reproducible crash

go/Godeps/LICENSES, go/go.mod, go/go.sum
I changed line 17 of `go.mod`; the other changes were automatic.
Before this, I was getting this error when trying to use any of the go tools on this project on a fairly fresh installation of Linux Mint 19.2:
```
github.com/edsrzf/mmap-go@v1.0.0-20181222142022-904c4ced31cd: invalid pseudo-version: does not match version-control timestamp (2019-01-08T06:59:03Z)
```
Now it seems to be working.
=> go/go.{mod,sum}: Fix mmap-go dependency version

Jenkinsfile, go/Godeps/LICENSES, go/go.mod, go/go.sum
Development ergonomics are much worse and the runtime library will maintain
compability with the generator major version anyway, or it will explicitly
break compilation.
=> go/go.mod: Do not depend on //proto/third_party/golang-protobuf.

go/libraries/doltcore/table/pipeline/errors.go, go/libraries/doltcore/table/pipeline/pipeline.go, go/libraries/doltcore/table/pipeline/procfunc_help.go
When a pipeline is being run, any stage can write to the bad row channel when an error is encountered.  There is a go routine reading from this channel that will not exit until the channel is closed, or an error is encountered. In typical operation the pipeline's sink would close the bad row channel once the pipeline finishes (either via an error triggered stoppage, or successful completion).  However, in the case where multiple errors are getting written to the bad row channel from multiple go routines, it is possible for the bad row channel to be written to, which triggers the pipeline to be stopped, and the channel to be closed, and then have a go routine write to that closed channel.
The fix here is to not close the channel in the sink, but instead to write a marker to the channel …
=> Fixes a panic that occurs if multiple bad rows are found during import

go/cmd/dolt/commands/remote.go, go/cmd/dolt/commands/remote_test.go
Before we were using `dolthub.com` as the default, which is incorrect. I've changed it to the appropriate environment constant so that it also properly updates when we change from our beta domain.
=> Changed default remote host to use the env constant

go/cmd/dolt/commands/remote.go, go/libraries/doltcore/dbfactory/aws.go, go/store/config/config_test.go, go/store/nbs/NBS-on-AWS.md, go/store/nbs/README.md, go/store/spec/spec.go, go/store/spec/spec_test.go
See https://go.googlesource.com/go/+/61bb56ad63992a3199acc55b2537c8355ef887b6
for context on the changes.
=> go/store/spec: Move to aws://[table:bucket] for NBS on AWS specs because of Go URL parsing changes.

bats/1pk5col-ints.bats, bats/2pk5cols-ints.bats, go/go.mod, go/go.sum, go/libraries/doltcore/sql/sqltestutil/insertqueries.go, go/libraries/doltcore/sql/sqltestutil/replacequeries.go, go/libraries/doltcore/sqle/sqlreplace_test.go, go/libraries/doltcore/sqle/tables.go
Mostly tests since this just uses the `Delete` and `Insert` functions that we already have. The previous delete would ignore a delete on a non-existent row, so I just changed it to throw the correct error if the row does not exist so that `REPLACE` works properly now (else it will always say a `REPLACE` did both a delete & insert).
=> Implemented REPLACE

go/cmd/dolt/commands/sql.go, go/cmd/dolt/commands/sql_test.go
I mean this works but it's ugly and I'm not sure of a better way to do it really
=> Naked deletes now just delete everything instead of iterating

go/store/nbs/table_reader.go, go/store/nbs/table_set.go
When we do things like push, pull or (soon-to-be) garbage collection, we have large sets of Chunk addresses that we pass into `ChunkStore#GetMany` and then go off and process. Clients largely try to control the memory overhead and pipeline depth by passing in a buffered channel of an appropriate size. The expectation is that the implementation of `GetMany` will have an amount of data in flight at any give in time that is in some reasonable way proportional to the channel size.
In the current implementation, there is unbounded concurrency on the read destination allocations and the reads themselves, with one go routine spawned for each byte range we want to read. This results in absolutely massive (virtual) heap utilization and unreasonable I/O parallelism and context switch thrashing in …
=> go: store/nbs: table_reader: getManyAtOffsetsWithReadFunc: Stop unbounded I/O parallelism in GetMany implementation.

bats/1pk5col-ints.bats, bats/advanced-sql.bats, go/cmd/dolt/commands/sql.go, go/go.mod, go/go.sum, go/libraries/doltcore/sql/sqltestutil/updatequeries.go, go/libraries/doltcore/sqle/sqlupdate_test.go, go/libraries/doltcore/sqle/tables.go
I think we should delete the old SQL methods that are in the `sql.go` file. I know at first you mentioned keeping them there for reference, but they're not being used at all at this point, and they're still in git history if we want to look at them again in the future for some reason. It's clutter at this point.
I'm skipping that one test at the end because of a WHERE decision in `go-mysql-server`. The code looks intentional, in that converting strings to ints will return 0 if the string is not parsable. I'll file it as a non-conforming bug on their end, but for now I'm skipping the test.
=> Implemented UPDATE

bats/diff.bats, go/cmd/dolt/commands/diff.go, go/libraries/doltcore/diff/diff_summary.go, go/libraries/doltcore/diff/schema_diff.go, go/store/types/tuple.go
Example output using [Liquidata/tatoeba-sentence-translations](https://www.dolthub.com/repositories/Liquidata/tatoeba-sentence-translations):
```
$ dolt diff --summary rnfm50gmumlettuebt2latmer617ni3t
diff --dolt a/sentences b/sentences
--- a/sentences @ gd1v6fsc04k5676c105d046m04hla3ia
+++ b/sentences @ 2ttci8id13mijhv8u94qlioqegh7lgpo
7,800,102 Rows Unmodified (99.99%)
15,030 Rows Added (0.19%)
108 Rows Deleted (0.00%)
960 Rows Modified (0.01%)
1,888 Cells Modified (0.00%)
(7,801,170 Entries vs 7,816,092 Entries)
diff --dolt a/translations b/translations
--- a/translations @ p2355o6clst8ssvr9jha2bfgqbrstkmm
+++ b/translations @ 62ri8lmohbhs1mc01m9o4rbvj6rbl8ee
5,856,845 Rows Unmodified (90.91%)
468,173 Rows Added (7.27%)
578,242 Rows Deleted (8.98%)
7,626 Rows Modified (0.12%)
7,626 …
```
=> dolt diff --summary

bats/1pk5col-strings.bats, go/cmd/dolt/commands/sql.go
Fixes SQL bug as found in new Bats test introduced here: https://github.com/liquidata-inc/dolt/pull/124
=> Fixed SQL batch insert breaking on semicolons in strings

bats/1pk5col-strings.bats, go/cmd/dolt/commands/sql.go
Added a new bats test to demonstrate, but originally the function didn't handle `\\''` properly, and now it does. Had to add 4 backslashes on the test because bash does its own escaping before passing it to dolt.
=> Batch inserts handle backslashes better

README.md, bats/1pk5col-ints.bats, bats/empty-repo.bats, go/libraries/doltcore/doltdb/doltdb.go
This is the style [recommended for contributions to Git itself](https://git.kernel.org/pub/scm/git/git.git/tree/Documentation/SubmittingPatches?id=HEAD#n135) and used by GitHub by default:
=> go/libraries/doltcore/doltdb/doltdb.go: Change initial commit message to imperative tense

bats/empty-repo.bats, go/go.sum, go/libraries/doltcore/ref/branchname.go, go/libraries/doltcore/ref/branchname_test.go
Looked into supporting periods in branch names, but it looks like `noms` relies on periods specifically pretty heavily. Seems to be excluded from the regex below by design, since they build some types on the expectation that a branch name or `ref` contain  a period.
My understanding is that a user's branch name is used to look up a particular dataset within the `noms` layer and this variable (go/store/datas/dataset.go): 
```
// DatasetRe is a regexp that matches a legal Dataset name anywhere within the
// target string.
var DatasetRe = regexp.MustCompile(`[a-zA-Z0-9\-_/]+`)
```
acts as the regex source of "truth" for branch names/ dataset look ups, and I believe more. 
Noms also expects to be able to append a `.` to this string in order to parse the string later and correctly create it's …
=> fix branch name panic with period

bats/1pk5col-ints.bats, bats/create-tables.bats, bats/helper/1pk5col-ints.sql, bats/schema-changes.bats, go/cmd/dolt/commands/diff.go, go/go.mod, go/libraries/doltcore/sql/schema.go, go/libraries/doltcore/sql/schema_test.go, go/libraries/doltcore/sql/sqlshow.go, go/libraries/doltcore/sql/sqlshow_test.go, go/libraries/doltcore/sqle/types/bool.go, go/libraries/doltcore/sqle/types/float.go, go/libraries/doltcore/sqle/types/int.go, go/libraries/doltcore/sqle/types/string.go, go/libraries/doltcore/sqle/types/types.go, go/libraries/doltcore/sqle/types/uint.go, go/libraries/doltcore/sqle/types/uuid.go
In my last PR, it looks like I missed that we were using the old `DoltToSQLType` hardcoded map from the original SQL implementation. I didn't change it everywhere (it's used heavily in the old SQL code that isn't even being called anymore), but it's changed where it matters. Added a new interface function and changed the printing code to be a bit more consistent (we were mixing uppercase with lowercase).
I'm also returning different values, such as `BIGINT` for `sql.Int64`, as `int` parses in MySQL to a 32-bit integer, which isn't correct. Essentially made it so that if you took the `CREATE` statement exactly as-is and exported your data to a bunch of inserts and ran it in MySQL then it wouldn't error out, as it previously would have.
=> Missed Kind to String

go/Godeps/LICENSES, go/cmd/dolt/commands/sqlserver/server.go, go/cmd/dolt/commands/sqlserver/server_test.go, go/cmd/dolt/commands/sqlserver/servercontroller.go, go/cmd/dolt/commands/sqlserver/sqlserver.go, go/go.mod, go/go.sum, go/libraries/doltcore/rowconv/row_converter_test.go, go/libraries/doltcore/sql/schema_test.go, go/libraries/doltcore/sql/sqlshow_test.go, go/libraries/doltcore/sqle/types/datetime.go, go/libraries/doltcore/sqle/types/float.go, go/libraries/doltcore/sqle/types/int.go, go/libraries/doltcore/sqle/types/string.go, go/libraries/doltcore/sqle/types/tests/datetime_test.go, go/libraries/doltcore/sqle/types/tests/types_test.go, go/libraries/doltcore/sqle/types/types.go, go/libraries/doltcore/sqle/types/uint.go, go/libraries/doltcore/sqle/types/uuid.go, go/libraries/doltcore/type_conversion_test.go, go/store/types/float.go, go/store/types/int.go, go/store/types/map_test.go, go/store/types/noms_kind.go, go/store/types/string.go, go/store/types/timestamp.go, go/store/types/uint.go
Have a look!
I ran into an import cycle issue that I just could not figure out how to avoid, except by putting the tests into their own test folder (`sqle/types/tests`), so that's why they're in there. In particular, the cycle was that `sqle` imports `sqle/types`, and the tests rely on (and thus must import) `sqle`, causing the cycle.
I'm thinking of adding tests for the other SQL types later so that we have a few more built-in tests using the server portion, rather than everything using the `-q` pathway. That will be a different/future PR though.
=> Added Timestamp to Dolt and Datetime to SQL

go/go.mod, go/store/types/noms_kind.go, go/store/types/value.go, go/store/types/value_decoder.go
This fixes a performance regression in value decoding after the work to make it easier to add primitive types to the storage layer.
First, we change some map lookups into slice lookups, because hashing the small integers on hot decode paths dominates CPU profiles.
Next, we inline logic for some frequently used primitive types in `value_decoder.go`, as opposed to going through the table indirection. This is about a 30% perf improvement for linear scans on `skipValue()`, which is worth the duplication here.
Code for adding a kind remains correct if the decoder isn't changed to include an inlined decode path. We omit inlining `UUID` and `InlineBlob` here for now.
=> go/store/types: Improve perf of value decoding for primitive types.

go/libraries/doltcore/row/tagged_values.go
ParseTaggedValues used to call Tuple.Get(0)...Tuple.Get(n), but Tuple.Get(x)
has O(n) perf, so the function did O(n^2) decoding work to decode a tuple.
Use a TupleIterator instead.
=> go/libraries/doltcore/row: tagged_values.go: Fix n^2 behavior in ParseTaggedValues.

go/performance/benchmarks/benchmarks.go, go/performance/benchmarks/dataset.go, go/performance/benchmarks/helpers.go, go/performance/benchmarks/main.go, go/performance/benchmarks/results.go, go/performance/benchmarks/seed_schema.go
Initial approach is to write a script that will run _n_ benchmarks, collect their results, then serialize those results to later be imported into `dolt`. Looking for feedback on approach before I head too far down this path, if it is suboptimal.
In it's current state, there are a lot of switch statements and panics and it only accounts for types `int` and `string` and only accounts for `.csv` style test data formats, but I'd like to make my data generation functions robust enough to be able to account for all file formats that dolt supports and all noms types...
=> dolt benchmarking

README.md
I ran into this typo while using Dolt yesterday. The command keywords were in the incorrect order in the README.
=> Fix typo in README for table import

bats/diff.bats, go/cmd/dolt/commands/diff.go, go/cmd/dolt/commands/select_where.go
Fixes diff where so that you no longer need to use to_col or from_col.
--where col=val
is evaluated as:
where to_col=val || from_col=val
=> Fix diff where clause

bats/dolt-docs.bats, go/cmd/dolt/commands/reset.go, go/cmd/dolt/commands/status.go, go/libraries/doltcore/doltdb/root_val.go, go/libraries/doltcore/env/actions/staged.go, go/libraries/doltcore/env/dolt_docs.go, go/libraries/doltcore/env/environment.go, go/libraries/doltcore/env/environment_test.go, go/libraries/doltcore/env/paths.go
This PR includes:
* Adding docs to `dolt reset --hard`, with tests
* Adding docs to `dolt reset --soft`, `dolt reset .`, `dolt reset`, `dolt reset <doc>`, with tests
* Refactor `doltcore/env/dolt_docs` to more general use
* ...and other helper functions in `doltcore/env/environment.go` to help stage and unstage docs
=> dolt reset --soft and --hard for dolt docs

go/libraries/doltcore/sql/sqltestutil/selectqueries.go, go/libraries/doltcore/sqle/diff_table.go, go/libraries/doltcore/sqle/history_table.go
fix select on a system table that has a valid prefix but whose suffix does not match a valid table.
What makes this a little bit tough is that you can query diffs or the history of a table that no longer exists. So need to process the entire history and then see if at any time there was a schema'd table with the given name.
=> fix select on system table that doesn't exist

go/store/types/buffered_sequence_iterator.go
Batching happens in two places: on initialization and each time the current batch is exhausted. Incorrect logic on lines 53 & 54 was preventing batching once the initial batch was exhausted.
=> fixed conditional that was preventing batching

go/store/nbs/aws_table_persister.go, go/store/nbs/s3_table_reader.go
It is necessary and correct that we close these readers. Helps with persistent
connection reuse, accurate logging and timing metrics, timely resource
finalization, etc.
=> go/store/nbs: s3_table_reader: Be certain to close body readers when reading from S3.

bats/query-catalog.bats, go/cmd/dolt/commands/sql.go, go/libraries/doltcore/row/tagged_values.go, go/libraries/doltcore/sqle/query_catalog_table.go, go/libraries/doltcore/sqle/query_catalog_table_test.go
Implements:
```
dolt sql -x <saved_query_name>
dolt sql --list-saved
```
Changes
* `dolt sql -s <name> -q <query>` now saves the query with id = name
=> execute saved query

go/cmd/dolt/commands/diff.go
I was just poking around a little bit and noticed that we weren't handling this error.
=> go/cmd/dolt/commands/diff.go: Handle error from `rowconv.NewJoiner` in `diffRows`

go/libraries/doltcore/remotestorage/chunk_store.go, go/store/datas/database.go, go/store/datas/pull_test.go, go/store/nbs/nbs_metrics_wrapper.go, go/store/nbs/store.go, go/store/nbs/table.go
The TableFileStore optimizations accidentally broke push support for
non-dotlremoteapi/non-filepath chunk stores. Attempting to push an AWS remote
currently results in an error.
This is a quick minimal PR to check for write support in a TableFileStore and
not use the push/pull fast path if it isn't supported.
=> store/datas/database.go: Update datas.CanUsePuller to check for write support in TableFileStore.

go/libraries/doltcore/env/dolt_docs.go
=> go/libraries/doltcore/env/dolt_docs.go: Add newline to end of initial LICENSE/README text

bats/git-dolt.bats
Is this fine? By putting it at the end of the `setup` function, it's equivalent to manually putting a skip on every test. Then whenever we fix it, we can just delete it in one place.
=> Skipping git-dolt bats tests on Windows due to flakiness

bats/compatibility/test_files/bats/compatibility.bats, bats/compatibility/test_files/setup_repo.sh, go/libraries/doltcore/rebase/rebase_tag.go
If a repo created with an old client ( < 0.16.0) has a branch with only the init commit, newer clients will always register that repo as un-migrated.
This change ignores init commits when checking if a repo has been migrated
=> Andy/Init commits don't need migration

go/store/config/config_test.go
This can happen when building and running in a golang docker container, for
example.
=> go/store/config: config_test.go: Fix test that fails when running test suite as root.

go/cmd/dolt/cli/arg_helpers.go, go/cmd/dolt/cli/arg_helpers_test.go, go/cmd/dolt/commands/sql_test.go, go/libraries/doltcore/doltdb/key_itr.go, go/libraries/doltcore/doltdb/table.go, go/libraries/doltcore/merge/merge.go, go/libraries/doltcore/rebase/rebase_tag.go, go/libraries/doltcore/row/noms_row.go, go/libraries/doltcore/row/tagged_values.go, go/libraries/doltcore/row/tagged_values_test.go, go/libraries/doltcore/schema/alterschema/dropcolumn.go
The primary fix is in the [first commit](https://github.com/liquidata-inc/dolt/pull/626/commits/a7d9667509ea9b4e2a232b7a5275ca123167b313). I changed the the `TaggedValues` api to make this mistake harder to make in the future. 
Before this changes, Noms tuples were being reordered by a column deletion which was causing erroneous diffs. The same column values were stored in different orders, leading to different content addresses between root values. 
_Should we add a pipeline stage to `diff` to filter out rows that are unchanged?_
=> fixing column ordering after deleted columns

bats/no-repo.bats, go/cmd/dolt/commands/sqlserver/serverconfig.go, go/cmd/dolt/commands/sqlserver/sqlserver.go, go/cmd/dolt/commands/sqlserver/yaml_config.go, go/cmd/dolt/commands/sqlserver/yaml_config_test.go
```
NAME
dolt sql-server - Start a MySQL-compatible server.
SYNOPSIS
dolt sql-server --config <file>
dolt sql-server [-H <host>] [-P <port>] [-u <user>] [-p <password>] [-t <timeout>] [-l <loglevel>] [--multi-db-dir <directory>] [-r]
DESCRIPTION
By default, starts a MySQL-compatible server which allows only one user connection ata time to the dolt repository in the current directory. Any edits made through this server will be automatically reflected
in the working set.  This behavior can be modified using a yaml configuration file passed to the server via --config <file>, or by using the supported switches and flags to configure the server directly on
the command line (If --config <file> is provided all other command line arguments are ignored).
This is an example yaml configuration file …
```
=> sql-server command documentation

benchmark/sql_regressions/run_regressions.sh
`nightly` and `releases` now push to `master`. (`regressions`) has been merged into master
=> /benchmark/sql_regressions/run_regressions.sh: Update jobs to push to master, not regressions

go/libraries/doltcore/doltdb/table_test.go
Tags for Dolt system tables are defined with `const` definitions and need to be consistent across Dolt versions. Using `iota` within const definitions can lead to unexpected results:
```
const (
name = "Andy"
mood = "ugh"
a = iota + 1
b
c
)
func main() {
fmt.Println(a) 
fmt.Println(b)
fmt.Println(c)
}
```
```
3
4
5
```
These unit tests lock these constants in place.
=> Verify System Table Tag Constants

bats/index.bats, bats/query-catalog.bats, go/libraries/doltcore/sqle/dolt_index.go, go/libraries/doltcore/sqle/filtered_reader.go
`SELECT` `<`, `<=`, `>`, `>=`, and `BETWEEN` all now use indexes. Previously, only `=` used indexes or primary keys, so this should be a pretty huge win.
=> SELECT comparisons and BETWEEN now use indexes

go/store/marshal/decode.go
This PR changes the decode side of Noms marshalling. If/when we decide to change the encode side of marshalling, all Dolt clients after this change will not see any broken behavior. 
Changing marshal encoding is backward compatible because we can attempt to decode `types.Int` and `types.Uint` in both the updated and legacy encodings. 
However, changing the encoding side will break older Dolt clients that expect to decode `Int` and `Uint` as `types.Float`.
=> Prep for breaking change to marshalling

go/gen/proto/dolt/services/eventsapi/v1alpha1/client_event.pb.go, go/gen/proto/dolt/services/eventsapi/v1alpha1/event_constants.pb.go, go/gen/proto/dolt/services/remotesapi/v1alpha1/chunkstore.pb.go, go/gen/proto/dolt/services/remotesapi/v1alpha1/credentials.pb.go, go/libraries/doltcore/doltdb/table_editor.go, go/libraries/doltcore/doltdb/table_editor_test.go, go/libraries/doltcore/merge/merge.go, go/libraries/doltcore/merge/resolve.go, go/libraries/doltcore/mvdata/table_data_loc.go, go/libraries/doltcore/sqle/table_editor.go, go/libraries/utils/async/action_executor.go, go/libraries/utils/async/action_executor_test.go, go/libraries/utils/async/wait_group.go, go/libraries/utils/async/wait_group_test.go
@bheni mentioned that we did not flush concurrently while performing other writes, and this idea was taken and executed upon. Lowering the flush threshold from `65536` to `16384` also seemed to improve performance just a bit with the new parallelism, which was not true with the previous implementation.
For performance numbers, we have `Original`, which is how it performed before I did any of the write path merging stuff. We have `Thread Safe`, which are my most recent changes. Then we have `Concurrent`, which is this current PR. Just for fun, we have `No-op` last. Here I made all of the write functions on `TableEditor` immediately return, just to see the true overhead that `TableEditor` actually adds to any particular write path.
Importing a 10 million row `.psv`:
```
Original:    53.521s …
```
=> SQL Write Performance Improvements

bats/schema-export.bats, go/cmd/dolt/commands/diff.go, go/cmd/dolt/commands/schcmds/export.go, go/cmd/dolt/commands/schcmds/import.go, go/cmd/dolt/commands/schcmds/show.go, go/libraries/doltcore/diff/sql_diff.go, go/libraries/doltcore/diff/sql_diff_test.go, go/libraries/doltcore/sqle/sqlfmt/row_fmt_test.go, go/libraries/doltcore/sqle/sqlfmt/schema_fmt.go, go/libraries/doltcore/sqle/sqlfmt/schema_fmt_test.go, go/libraries/doltcore/table/untyped/sqlexport/sqlwriter.go, go/libraries/doltcore/table/untyped/sqlexport/sqlwriter_test.go
I only changed `dolt schema export`. Other commands like `dolt show tables` or `dolt diff --sql` still output tags. This is easy to change on case by case basis.
=> added --with-tags flag to schema export

bats/foreign-keys.bats, go/cmd/dolt/commands/commit.go, go/cmd/dolt/commands/sql.go, go/libraries/doltcore/doltdb/foreign_key_coll.go, go/libraries/doltcore/doltdb/root_val.go, go/libraries/doltcore/doltdb/sessioned_table_editor.go, go/libraries/doltcore/doltdb/table_edit_session.go, go/libraries/doltcore/doltdb/table_editor.go, go/libraries/doltcore/dtestutils/testcommands/command.go, go/libraries/doltcore/env/actions/commit.go, go/libraries/doltcore/env/actions/resolve.go, go/libraries/doltcore/merge/merge.go, go/libraries/doltcore/merge/merge_test.go, go/libraries/doltcore/merge/resolve.go, go/libraries/doltcore/mvdata/data_loc_test.go, go/libraries/doltcore/mvdata/data_mover.go, go/libraries/doltcore/mvdata/table_data_loc.go, go/libraries/doltcore/schema/index.go, go/libraries/doltcore/schema/index_coll.go, go/libraries/doltcore/schema/schema.go, go/libraries/doltcore/sqle/database.go, go/libraries/doltcore/sqle/dolt_session.go, go/libraries/doltcore/sqle/table_editor.go, go/libraries/doltcore/sqle/table_editor_fk_test.go, go/libraries/doltcore/sqle/table_editor_index_test.go, go/libraries/doltcore/sqle/table_editor_test.go
This PR implements the commit functionality, along with `commit --force`.
=> Foreign Keys Part 3

bats/sql.bats
Also, added || false on some regexes to create deterministic behavior in old versions of bash.
=> Added skipped test for json DATETIME bug. 

.github/workflows/ci-check-repo.yaml, go/utils/checkcommitters/main.go, go/utils/prepr/prepr.sh
looking into fixing this: https://github.com/liquidata-inc/dolt/pull/767/checks?check_run_id=808971285#step:4:296
```
2020/06/25 21:04:02 Error running `git merge-base remotes/origin/db/ci-github-actions-check-repo remotes/origin/master` to find merge parent: exit status 128
exit status 1
```
the `exit status 128` is from `//go/utils/checkcommiters/main.go` ... im thinking could be the go version? i had to use `1.13` here to get past the error that occurred when i used go version `^1.13` regarding the `-mod=readonly` flag....
=> /.github/workflows/ci-check-repo.yaml: Iterating on github actions check repo

bats/back-compat.bats, bats/conflict-detection.bats, bats/index.bats, go/libraries/doltcore/envtestutils/rebase_tag_test.go, go/libraries/doltcore/envtestutils/super_schema_test.go, go/libraries/doltcore/merge/merge.go
As discussed (and in relation to https://github.com/liquidata-inc/dolt/issues/773), we will fail on all merges where the schemas are not the same. As a result, one index bats test no longer makes sense, and all other tests that rely on the behavior have been skipped/commented out.
=> Merge Block

bats/merge.bats, go/cmd/dolt/commands/commit.go, go/libraries/doltcore/env/actions/commit.go
I realized when working on a blog post that `dolt commit` will currently go ahead and create the merge commit even if there are unstaged conflicts in one of the merged tables. This is not the behavior we want.
Currently, we do not allow staging tables that have conflicts. This change makes it so `dolt commit` also fails if there are any conflicts in any of the tables in the working set.
=> go/libraries/doltcore/env/actions: commit.go: Error when attempting to create a commit with unresolved conflicts still in the working set.

go/libraries/doltcore/doltdb/table_editor.go
Fixes a memory leak that was observed during a large import. It appears that the primary key tuples were never deallocating, although I could not pinpoint what's holding on to the tuples. The `tableEditAccumulator` seems to be the only place, and it is discarded after it goes through `flushEditAccumulator`, so that doesn't seem to be it. However, setting its fields to `nil` fixes the leak, indicating that there is somewhere holding on to old `tableEditAccumulator`s. I also checked if `async.ActionExecutor` was the culprit, but manual debugging and testing showed that it wasn't holding on to any references once they went through the `work` method. This isn't a true fix, as there is still technically a leak for whatever is holding on to the `tableEditAccumulator`, but it's a leak of mere …
=> Resolved memory leak

go/libraries/doltcore/doltdb/table_edit_session.go, go/libraries/doltcore/sqle/dolt_session.go, go/libraries/doltcore/sqle/logictest/dolt/doltharness.go
Performance seems roughly the same compared to the pre-FK changes from my testing. Perhaps not the best solution, but it fixes the leak while preserving performance.
=> Fixed memory leak when running sqllogictests

bats/foreign-keys.bats, go/libraries/doltcore/sqle/tables.go
This change makes a special case for foreign keys that reference primary key(s) in the parent table. If all of the parent table columns are primary keys, we create an index to use for the foreign key.
Ideally we'd make use of the existing clustered index as the parent table index. Because we will soon be adding keyless tables and allowing primary key changes, I'm punting, for now, on a more elegant implementation.
=> foreign keys can use primary keys as parent table indexes

go/libraries/doltcore/doltdb/commit.go
As far as I can tell, the constants in `doltdb/Commit.go` only work because they match the constants [here](https://github.com/liquidata-inc/dolt/blob/ac8e8840c4cab2d43317acc0362d9b4fe44d3a93/go/store/datas/commit.go#L41)
Also, there is currently a mismatch between `doltdb.parentListField` and `datas.ParentListField` which should cause the list of parents to never be [found](https://github.com/liquidata-inc/dolt/blob/ac8e8840c4cab2d43317acc0362d9b4fe44d3a93/go/libraries/doltcore/doltdb/commit.go#L52)
=> Tie Dolt commit struct fields to Noms commit struct fields

go/libraries/doltcore/table/read_ahead_table_reader.go, go/libraries/utils/async/async_read_test.go, go/libraries/utils/async/async_reader.go
The pipeline framework already handles this, but when reading outside a pipeline it can have performance benefit to having a go routine reading the data than the go routine that is processing it.
=> add ReadAheadTableReader.go

go/cmd/dolt/commands/sql_statement_scanner.go
Signed-off-by: Zach Musgrave <zach@liquidata.co>
=> Increase maxiumum SQL statement length to 100MB (initially 512K)

go/cmd/dolt/commands/clone.go, go/go.mod, go/go.sum, go/store/datas/pull.go
I parallelized the table file writing process by using go routines. Specifically, I made use of the "golang.org/x/sync/errgroup" package which allows for convenient error management across a waitgroup.
A couple of benchmarks I tested this on were 
1. Dolt-benchmarks-test: No difference in speed really
2. Coronavirus: Original ~30sec. Current 15sec
3. Tatoeba Sentence Translation: Original: ~17mins Current: 10mins
=> Add go routine to clone

go/libraries/doltcore/diff/diff_summary.go, go/libraries/doltcore/row/tagged_values.go, go/store/types/tuple.go
fix for https://github.com/dolthub/dolt/issues/899
The from root in this repo has NULL values written to the map which causes erroneous diffs.
https://www.dolthub.com/repositories/dolthub/us-supreme-court-cases/compare/master/hb502v6tf3uj43ijfhot6dopmgdm1muk
=> /go/libraries/doltcore/diff: Ignore NULLs in cell-wise diff

go/libraries/doltcore/doltdb/index_editor.go
Used a pre-existing 16 million row repo to test `CREATE INDEX` memory usage on.
Before:
72.47GB RAM Usage
18min 48sec
After:
1.88GB RAM Usage
2min 2sec
Copied the same strategy as used in `table_editor.go` to periodically flush the contents once some arbitrary amount of operations have been performed.
=> Memory fix for CREATE INDEX

.github/workflows/bump-brew-formula.yml
From failed run on most recent release:
=> Fix typo in brew bump

go/cmd/dolt/commands/tblcmds/export.go, go/cmd/dolt/commands/tblcmds/import.go, go/libraries/doltcore/mvdata/data_loc.go, go/libraries/doltcore/mvdata/data_loc_test.go, go/libraries/doltcore/mvdata/file_data_loc.go, go/libraries/doltcore/mvdata/stream_data_loc.go, go/libraries/doltcore/mvdata/table_data_loc.go, go/store/types/value_store.go
There might be a better fix for this, but `dolthubapi` uses `NewCreatingWriter` which breaks with Andy's [recent changes](https://github.com/dolthub/dolt/commit/b6be196af9b31fd1d37cf423e7777202cf8e7843#diff-f6b6f55f2e449395d3b8e0d758e8f3e1de084bdd6369d9e8e8fe1d69c4878920R100) (it's being used in dolthubapi [here](https://github.com/dolthub/ld/blob/master/go/services/dolthubapi/pkg/domain/repositorydata.go#L1922))
=> NewCreatingWriter breaks dolthubapi with recent changes

bats/sql.bats, go/cmd/dolt/commands/sqlserver/serverconfig.go, go/cmd/dolt/dolt.go, go/libraries/doltcore/sqle/dfunctions/init.go, go/libraries/doltcore/sqle/dfunctions/version.go
As `version()` is used to emulate the target MySQL version, I've added `dolt_version()` so that one may specifically query the dolt version.
=> Added dolt_version()

go/libraries/doltcore/sqle/index_lookup.go, go/libraries/doltcore/sqle/index_row_iter.go
A better implementation would make use of partitions of some form. My current idea is to split up the ranges so that each partition handles a subsection of a range, however I'd likely rewrite a portion of the ranges to facilitate this, along with some additions to the Value types (such as a new interface). In the meantime, this is a rather quick and dirty implementation of parallelizing reads on an index so that queries don't come to a standstill when adding an index.
I initially had a faster and less ugly implementation, but it completely changed the order of the output (still correct since order is arbitrary without an `ORDER BY` clause). Instead of rewriting every test, I changed it so that the old order is preserved by writing into a buffer. It's still far, far faster than the old …
=> Temporary parallelism implementation on indexes

bats/multiple-tables.bats, bats/sql-commit.bats, go/cmd/dolt/cli/arg_parser_helpers.go, go/cmd/dolt/commands/add.go, go/cmd/dolt/commands/commit.go, go/libraries/doltcore/diff/diffs.go, go/libraries/doltcore/dtestutils/testcommands/command.go, go/libraries/doltcore/env/actions/commit.go, go/libraries/doltcore/env/actions/staged.go, go/libraries/doltcore/env/environment.go, go/libraries/doltcore/env/repo_state.go, go/libraries/doltcore/sqle/dfunctions/dolt_commit.go
This pr adds a `-a` flag to `dolt commit` and `DOLT_COMMIT`. It stages all tables. 
It also cleans up some of the previous work done in #1056 by removing all method handlers in repo_state and moving them to the RepoStateReader and RepoStateWriter
It does not refactor the RSR/RSW interfaces in environment.go. This will be done in a subsequent pr.
=> Add -a flag to cli and DOLT_COMMIT

go/libraries/doltcore/doltdb/index_editor.go, go/libraries/doltcore/doltdb/index_editor_test.go
Fixes https://github.com/dolthub/dolt/issues/1079
=> Fixed shell error loop on UNIQUE violation

go/cmd/dolt/commands/blame.go, go/cmd/dolt/commands/sql_test.go, go/libraries/doltcore/doltdb/dolt_docs.go, go/libraries/doltcore/doltdb/foreign_key_coll.go, go/libraries/doltcore/doltdb/root_val.go, go/libraries/doltcore/doltdb/root_val_test.go, go/libraries/doltcore/doltdb/table.go, go/libraries/doltcore/env/environment.go, go/libraries/doltcore/mvdata/data_mover.go, go/libraries/doltcore/rowconv/row_converter.go, go/libraries/doltcore/rowconv/row_converter_test.go, go/libraries/doltcore/schema/alterschema/addcolumn.go, go/libraries/doltcore/sqle/tables.go, go/libraries/doltcore/table/access.go, go/libraries/doltcore/table/editor/sessioned_table_editor.go, go/libraries/doltcore/table/pipeline/row.go, go/libraries/doltcore/table/typed/noms/read_write_test.go, go/libraries/doltcore/table/writer.go
Removed:
- Table.GetRowByPKVals()
- Table.GetRow()
- Table.GetRows()
Had do to some refactoring along the way to fix dependency cycles. 
Reversed dependency `rowconv -> pipeline` to `pipeline -> rowconv`
=> go/libraries/doltcore/{doltdb,table}: remove row access methods from doltdb.Table

bats/sql-server.bats, go/libraries/doltcore/sqle/dfunctions/dolt_commit.go
Fails loudly when autocommit is off for dolt_commit.
=> Add dolt_commit error check when autocommit is off

bats/server_multiclient_test.py, bats/sql-server.bats, go/libraries/doltcore/sqle/dfunctions/commit.go, go/libraries/doltcore/sqle/dfunctions/dolt_commit.go, go/libraries/doltcore/sqle/dfunctions/init.go, go/libraries/doltcore/sqle/dfunctions/merge.go, go/libraries/doltcore/sqle/enginetest/dolt_harness.go
COMMIT('-m', 'hi', '--author', 'John Doe <john@doe.com>')
MERGE('feature-branch',  '--author', 'John Doe <john@doe.com>')
=> Add --author, -m to COMMIT. Add --author to MERGE()

go/cmd/dolt/commands/status.go
The function `printStagedDiffs` always returned 0, even when there were diffs not staged. This return was also causing it to print in `printStatus ` "nothing to commit, working tree clean". This was not the case.  
I changed  `printStagedDiffs` to return the number of the staged tables plus the number of staged docs instead. This prevents it from entering the if statement with the print also.
I've attached a picture of the bug with debug statements: 
and here is it after the fix:
=> Fixed dolt status output incorrectly displayed for staged files

go/libraries/doltcore/schema/typeinfo/decimal.go, go/libraries/doltcore/schema/typeinfo/typeinfo.go
Not sure if this is the behavior we want or if this is correct at all, but I'm implementing schema updates on the front end and I'm getting this error if I select the decimal type (all other types work)
=> Attempt to add default decimal type to FromKind

go/libraries/doltcore/diff/diffs.go, go/libraries/doltcore/env/actions/commit.go, go/libraries/doltcore/env/actions/staged.go, go/libraries/doltcore/env/environment.go, go/libraries/doltcore/env/repo_state.go, go/libraries/doltcore/sqle/dfunctions/dolt_commit.go
First step in cleaning up RepoStatReader/Writer interface.
=> Remove root methods from rsr and rsw

bats/arg-parsing.bats, bats/column_tags.bats, bats/compatibility/test_files/bats/compatibility.bats, bats/import-create-tables.bats, bats/keyless.bats, go/libraries/doltcore/mvdata/data_loc_test.go, go/libraries/doltcore/mvdata/data_mover.go, go/libraries/doltcore/mvdata/table_data_loc.go, go/libraries/doltcore/row/keyless_row.go, go/libraries/doltcore/row/noms_row.go, go/libraries/doltcore/row/row.go, go/libraries/doltcore/table/keyless_reader.go, go/libraries/doltcore/table/pk_reader.go, go/libraries/doltcore/table/table_reader.go, go/store/types/uuid.go
Adds keyless table support for `dolt table import ...`. `table import -c` now creates keyless tables if the `-pk` option is not provided.
=> Andy/keyless import/export

.github/workflows/cd-release-notify.yaml, .github/workflows/cd-release.yaml, .github/workflows/ci-bats-tests.yaml, .github/workflows/ci-check-repo.yaml, .github/workflows/ci-compatibility-tests.yaml, .github/workflows/ci-go-tests.yaml, .github/workflows/ci-mysql-client-tests.yaml
This implements the following policy:
- notify on cancellation or failure of any job
- notify on release, including success
Currently release notifications are broken by a shortcoming in GitHub Actions, namely that one workflow cannot kick of another when using `GITHUB_TOKEN`. We will devise a workaround.
=> First cut of Discrod notifications

go/libraries/doltcore/sqle/database.go, go/libraries/doltcore/sqle/dolt_session.go
I'm ambivalent about where the table cache lives, but we need to have access to it when we change the root of a `sqle.Database`
This PR purges the table cache when we change roots. IE `SET @@dolt_head = hashof(...)`. The intention is to limit the scope of edit sessions, and table mutations in general, and contain them to the working root of a `sqle.Database`. 
Currently there is a tricky reference chain within the table cache: `sqle.tableCache` -> `sqle.WritableDoltTable` -> `sqle.sqlTableEditor` -> `table/editor.TableEditSesson`
When we change roots in the database we also change the root within the `TableEditSession`. They're both referencing the new working root. Without purging the cache, we will keep old tables from the previous working root that still have a reference to the …
=> /go/libraries/doltcore/sqle: move table cache to DoltSession, purge on root change

go/store/types/codec.go, go/store/types/codec_test.go
30% faster on the benchmark in this PR.
BenchmarkUnrolledDecodeUVarint/binary.UVarint-8         	1000000000	         0.0372 ns/op
BenchmarkUnrolledDecodeUVarint/unrolled-8               	1000000000	         0.0258 ns/op
=> unrolled decode varint decode loop

go/Godeps/LICENSES, go/cmd/dolt/commands/filter-branch.go, go/cmd/dolt/commands/sql.go, go/cmd/dolt/commands/sqlserver/server.go, go/cmd/dolt/dolt.go, go/go.mod, go/go.sum, go/libraries/doltcore/diff/querydiff/query_differ.go, go/libraries/doltcore/sqle/show_create_table.go, go/libraries/utils/tracing/tracing.go, go/store/nbs/store.go, go/store/types/meta_sequence.go
This adds a --jaeger flag to dolt CLI which installs a Jaeger Tracer as the
global opentracing Tracer. The Tracer is configured to report to an HTTP
collector running on http://localhost:14268, which is the port that docker
image `jaegertracing/all-in-one` listens on.
Also adds some parameters in places where Dolt constructs sql.Contexts to pass
the correct Tracer through.
Also adds a few new Span points, in things like nbs.Get and
metaSequenceImpl.getChildSequence.
=> go/cmd/dolt: Add debugging flag to run with Jaeger span reporting to localhost.

go/libraries/doltcore/sqle/dolt_map_iter.go, go/libraries/doltcore/sqle/rows.go, go/libraries/doltcore/sqle/tables.go, go/store/types/map.go, go/store/types/map_iterator.go
Before
```
~/datasets/wikipedia-ngrams>GOMAXPROCS=1 time dolt sql -r null -q 'SELECT * FROM bigram_counts'
310.13 real       285.36 user         9.16 sys
```
After
```
~/datasets/wikipedia-ngrams>GOMAXPROCS=1 time dolt sql -r null -q 'SELECT * FROM bigram_counts'
253.91 real       233.10 user         9.67 sys
```
=> Use map.IterRange for iterating over rows

go/libraries/doltcore/schema/typeinfo/datetime.go
For `DATE`, we accidentally forgot to add the time truncation during the perf improvements, so this adds it back in.
=> Restored proper DATE functionality

.github/scripts/performance-benchmarking/get-job-json.sh, .github/workflows/ci-performance-benchmarks.yaml
This PR updates the query run for PR performance benchmarks and changes the comment trigger to `#benchmark`.
`average_time_change_query` measures the change in average `latency_sum`/ average `sql_transactions` for each sysbench test between `master` and the PR branch and will result in table similar to:
```
test_name              average_time_percent_change  is_faster
---------------------  ---------------------------  ---------
oltp_delete            -1.0                         1        
oltp_point_select      -2.0                         1        
oltp_read_only         7.0                          0        
oltp_read_write        3.0                          0        
oltp_update_index      1.0                          0        
oltp_update_non_index  -3.0                         1 …
```
=> Update PR comment benchmarking queries

go/cmd/dolt/commands/sql_print.go
Fixes issue https://github.com/dolthub/dolt/issues/1219 by not calling on an iterator after it's already returned EOF
=> Print pipeline fix

.github/workflows/cd-release.yaml, .github/workflows/ci-bats-tests.yaml, .github/workflows/ci-check-repo.yaml, .github/workflows/ci-compatibility-tests.yaml, .github/workflows/ci-go-tests.yaml, .github/workflows/ci-mysql-client-tests.yaml, .github/workflows/ci-performance-benchmarks.yaml
This PR pins the Github-hosted runners at ubuntu-18.04.
=> /.github/workflows: use ubuntu-18.04 as ubuntu-latest will soon be 20.04

bats/sql-shell.bats, bats/sql-shell.expect, go/cmd/dolt/commands/sql.go
This pr fixes a bug where the root gets written on every loop of the dolt sql shell.
=> Write to root on every loop of sql shell.

.github/scripts/performance-benchmarking/get-dolt-dolt-job-json.sh, .github/scripts/performance-benchmarking/get-mysql-dolt-job-json.sh, .github/scripts/performance-benchmarking/run-benchmarks.sh
This PR updates performance benchmarking queries to display the more stable latency median for each sysbench test. It also increases the PR benchmarking timeout to 90mins, since a job now takes ~52 mins.
=> Update performance benchmarking queries and timeout

.github/scripts/performance-benchmarking/get-mysql-dolt-job-json.sh
This PR adds a mean multiplier query to the performance benchmarks email on release.
=> Add mean multiplier query to performance benchmarks on release

.github/scripts/performance-benchmarking/get-dolt-dolt-job-json.sh, .github/scripts/performance-benchmarking/get-mysql-dolt-job-json.sh
This PR updates the job specs used in performance benchmarking by specifying the limits that ensure each pod receives its own node.
=> Update performance benchmarking job specs with container limits

.github/scripts/performance-benchmarking/get-dolt-dolt-job-json.sh
This PR fixes a performance benchmarking queries case statement that incorrectly uses the percent `10.0` instead of the decimal `.10`.
=> Fix performance benchmarking query to use decimal instead of percentage

.gitignore, go/store/metrics/histogram.go, go/store/metrics/histogram_test.go
The `atomic` package has the following [limitation on 32-bit platforms:](https://golang.org/pkg/sync/atomic/#pkg-note-BUG)
> On both ARM and x86-32, it is the caller's responsibility to arrange for 64-bit alignment of 64-bit words accessed atomically. The first word in a variable or in an allocated struct, array, or slice can be relied upon to be 64-bit aligned.
=> fixes panic in the atomic package

.github/workflows/ci-workflow-receiver.yaml, .github/workflows/ci-workflow-trigger.yaml
This PR adds two temporary workflow files used for testing the `repository_dispatch` github actions event. Once the work successfully for this repository, this files will be removed, and the performance-benchmarking-release and release workflows will be updated.
=> Testing Repository Dispatch workflows

go/libraries/doltcore/sqle/logictest/main/main.go
This PR enables `csv` formatted parsed `sqllogictest` results.
=> Enable sqllogictest runner to parse results to csv

.github/scripts/performance-benchmarking/get-dolt-dolt-job-json.sh, .github/scripts/performance-benchmarking/get-mysql-dolt-job-json.sh
=> [no-release-notes] /.github/scripts/performance-benchmarking: fix split benchmarking tables

benchmark/perf_tools/sysbench_scripts/lua/local_sysbench.sh, go/libraries/doltcore/sqle/async_indexed_lookups.go, go/libraries/doltcore/sqle/dolt_index_test.go, go/libraries/doltcore/sqle/index_row_iter.go, go/libraries/doltcore/sqle/sqlinsert_test.go, go/libraries/doltcore/sqle/sqlreplace_test.go, go/libraries/doltcore/sqle/table_editor_test.go, go/libraries/utils/async/ring_buffer.go, go/libraries/utils/async/ring_buffer_test.go
Current implementation can create a 100s of millions of go routines.  This creates a fixed pool of routines to do random access lookups.
=> Fixed worker pool used for index lookups

.github/workflows/cd-release.yaml, go/utils/publishrelease/bump-version.sh
Reverts dolthub/dolt#1296, needs some coordination work in order to fetch the newly created tag
=> Revert "[no-release-notes] /.github/workflows/cd-release.yaml: bump version and commit"

bats/foreign-keys.bats, go/libraries/doltcore/env/actions/commit.go, go/libraries/doltcore/fkconstrain/checks.go, go/libraries/doltcore/fkconstrain/diffitr.go, go/libraries/doltcore/fkconstrain/errors.go, go/libraries/doltcore/fkconstrain/validate.go, go/libraries/doltcore/row/tagged_values.go
Previous validation implementation did full scans for every foreign key constraint.  New implementation only validates against rows that have changed from the previous commit.
=> Diff based foreign key validation

go/store/types/codec.go
if `length = length * 2` overflowed before it was greater than the necessary size `ensureCapacity` would loop forever.  After 2 gigs we allocate a half gig at a time and if the allocation size exceeds a uint32 we panic, rather than fail later.
=> fix infinite loop

bats/foreign-keys.bats, go/cmd/dolt/commands/merge.go, go/cmd/dolt/commands/verify_constraints.go, go/libraries/doltcore/merge/merge.go
Foreign key constraint violations on merge had the potential to make resolving conflicts between two commits impossible.  Merges are now done without foreign key constraint validation.  A new warning message was added when there is potential for this to be an issue.  Foreign key constraint validation is enforced on commit.
=> disable foreign key checks on merge with warning

go/store/types/codec.go, go/store/types/map_leaf_sequence.go, go/store/types/meta_sequence.go, go/store/types/ordered_sequences.go
Merges were failing when the changes were sufficiently large.  This was really exacerbated by merges where the common ancestor is extremely old.  getCompositeChildSequence would try to allocate contiguous blocks and encode the entire composite child sequence into it.  If the size of the data exceeded the max value of a uint32 then the indexes being used to access the buffers would overflow and wrap around and cause all kinds of badness.
=> fix overflow issue

go/libraries/doltcore/doltdb/root_val.go, go/libraries/doltcore/merge/merge.go, go/libraries/doltcore/sqle/enginetest/dolt_harness.go, go/store/datas/commit.go, go/store/marshal/decode.go, go/store/types/encode_human_readable.go, go/store/types/list.go, go/store/types/list_test.go
`{Map, List, Set}.IterAll()` spins up multiple go routines to parallelize the IO of loading a data structure, but when the data is small (unmarshalling Schema/SuperSchema) it seems to be causing issues. Changing these instances of `IterAll()` to `Iter()` fixes `context cancelled` errors seen during `dolt merge`. The errors have not yet been reproduced in a test case, but they have been fixed in the affected repos.
=> Fix Schema Unmarshalling Error

go/libraries/doltcore/merge/merge.go, go/libraries/doltcore/merge/merge_schema.go, go/libraries/doltcore/merge/merge_test.go, go/libraries/doltcore/merge/schema_integration_test.go
This fixes dropped code and test `err` variables in `libraries/doltcore/merge`.
=> libraries/doltcore/merge: fix dropped errors

go/libraries/doltcore/rebase/rebase.go, go/libraries/doltcore/rebase/rebase_tag.go
This fixes dropped `err` variables in `libraries/doltcore/rebase`.
=> libraries/doltcore/rebase: fix dropped errors

go/libraries/doltcore/schema/alterschema/dropcolumn_test.go
This fixes dropped test errors in `libraries/doltcore/schema/alterschema`.
=> libraries/doltcore/schema/alterschema: fix dropped errors

go/libraries/doltcore/schema/typeinfo/typeinfo_test.go, go/libraries/doltcore/schema/typeinfo/varstring.go
This fixes a dropped test error and a dropped code error in `libraries/doltcore/schema/typeinfo`.
=> libraries/doltcore/schema/typeinfo: fix dropped errors

go/libraries/doltcore/diff/diff_splitter.go
This fixes a dropped `err` in `libraries/doltcore/diff`.
=> libraries/doltcore/diff: fix dropped error

go/store/nbs/aws_chunk_source_test.go, go/store/nbs/aws_table_persister_test.go, go/store/nbs/block_store_test.go, go/store/nbs/byte_sink_test.go, go/store/nbs/conjoiner_test.go, go/store/nbs/dynamo_manifest_test.go, go/store/nbs/dynamo_table_reader_test.go, go/store/nbs/fd_cache_test.go, go/store/nbs/file_manifest.go, go/store/nbs/file_manifest_test.go, go/store/nbs/file_table_persister_test.go, go/store/nbs/fs_table_cache_test.go, go/store/nbs/manifest_cache_test.go, go/store/nbs/mem_table_test.go, go/store/nbs/mmap_table_reader_test.go, go/store/nbs/persisting_chunk_source_test.go, go/store/nbs/root_tracker_test.go, go/store/nbs/s3_table_reader_test.go, go/store/nbs/stats_test.go, go/store/nbs/store_test.go, go/store/nbs/table_persister_test.go, go/store/nbs/table_set_test.go, go/store/nbs/table_test.go
This replaces most instances of `assert.NoError()` with `require.NoError()`, and picks up several dropped `err` variables in code and tests.
=> Replace assert.NoError with require.NoError in tests

go/store/datas/commit.go, go/store/datas/database_common.go, go/store/datas/database_test.go, go/store/datas/puller_test.go, go/store/datas/tag_test.go
This fixes dropped `err` variables in the `store/datas` package.
=> store/datas: fix dropped errors

go/libraries/doltcore/sqle/dtables/diff_table.go, go/libraries/doltcore/sqle/sqlddl_test.go, go/libraries/doltcore/sqle/tables.go
This fixes two dropped code `err` variables and a test `err` variable in `libraries/doltcore/sqle`.
=> libraries/doltcore/sqle: fix dropped errors

go/libraries/doltcore/doltdb/commit_meta.go
More granular error reporting for when a user or email is not provided.
=> improved error message when committing without a name or email set.

go/libraries/doltcore/sqle/dfunctions/commit.go, go/libraries/doltcore/sqle/dfunctions/dolt_commit.go, go/libraries/doltcore/sqle/dfunctions/dolt_merge.go, go/libraries/doltcore/sqle/dfunctions/dolt_reset.go, go/libraries/doltcore/sqle/dfunctions/hashof.go, go/libraries/doltcore/sqle/dfunctions/merge.go
This fixes dropped test & code `err` variables, as well as some `err` variables that were being passed into functions and then dropped immediately.
This PR goes beyond straightforward `err` drop fixes into spookier territory.
=> Fixed dropped errors in libraries/doltcore/sqle/dfunctions

go/libraries/doltcore/table/untyped/csv/writer_test.go, go/libraries/doltcore/table/untyped/xlsx/reader.go
This fixes dropped errors in `libraries/doltcore/table/untyped/csv` and `libraries/doltcore/table/untyped/xlsx`.
=> libraries/doltcore/table/untyped: fix dropped errors

.github/workflows/ci-check-repo.yaml, go/utils/repofmt/check_bats_fmt.sh, integration-tests/bats/common.bash.bats, integration-tests/bats/sql-load-data.bats, integration-tests/bats/sql-show.bats
This enforces the new naming scheme for bats tests that I implemented in https://github.com/dolthub/dolt/pull/1386. This just adds a check to the `Check Formatting and Committers` task to ensure that future tests continue to follow the naming scheme.
=> Added test to CI for bats test names

go/store/marshal/decode.go, go/store/marshal/decode_test.go, go/store/marshal/encode.go, go/store/marshal/encode_test.go
This picks up a dropped error in`store/marshal`, changes the tests to use `require.NoError` instead of `assert.NoError`, and prunes some dead code.
=> store/marshal: dropped error and test refactor

go/libraries/doltcore/sqle/async_indexed_lookups.go, go/libraries/doltcore/sqle/index_row_iter.go, go/libraries/utils/async/ring_buffer.go, go/libraries/utils/async/ring_buffer_test.go
When a query with an index lookup as a LIMIT, it's possible for the result
iterator to be closed before all the index results have been streamed. When
that happens, we can end up with queueRows goroutine which is enqueuing rows
into a ring buffer that is going to be used by a different query later.
This PR adds two mechanisms, one to stop the wrong results from being seen and
to cancel the unnecessary work.
1. RingBuffer gets an epoch, which is incremented on each Reset(). If a given
Push does not match the current epoch, then nothing is added to the ring
buffer.
2. queueRows is run with a cancelable (sub-)Context, and that Context is
canceled when the corresponding iterator is Closed().
=> go/libraries/doltcore/sqle/async_indexed_lookups.go: Fix leaking of results from one index lookup to another.

integration-tests/bats/doltpy.bats
Some bats that if failed indicate a doltpy incompatibility. The tests could be more involved, but the goal here isn't row-output correctness.
This list will grow as I rewrite more dolt commands to use SQL features.
=> Add few doltpy commands that broke with dolt compatibility changes

go/utils/publishrelease/buildbinaries.sh
This lets Dolt release binaries work on Linux distributions that do not use glibc, like Alpine.
Fixes #1489.
=> go/utils/publishrelease/buildbinaries.sh: Use CGO_ENABLED=0 to statically link release binaries on Linux.

go/libraries/doltcore/doltdocs/docs.go, go/libraries/doltcore/doltdocs/docs_table.go, go/libraries/doltcore/doltdocs/docs_test.go
Fixes dropped errors, changes tests to use `require.NoError()`.
=> Fix dropped errors in libraries/doltcore/doltdocs

go/libraries/doltcore/rowconv/field_mapping.go, go/libraries/doltcore/rowconv/joiner_test.go, go/libraries/doltcore/rowconv/row_converter_test.go
This fixes dropped errors in `libraries/doltcore/rowconv` and replaces `assert.NoError()` with `require.NoError()` in tests.
=> libraries/doltcore/rowconv: error handling

go/cmd/dolt/commands/sql_statement_scanner.go, integration-tests/bats/sql.bats
Fixes https://github.com/dolthub/dolt/issues/1495
`DELIMITER` had to be terminated by the previous delimiter, similar to other statements. However, MySQL does not have this requirement (a newline is adequate for termination). This PR removes this requirement.
=> Added DELIMITER newline termination

go/libraries/doltcore/row/fmt_test.go, go/libraries/doltcore/row/noms_row_test.go, go/libraries/doltcore/row/row_test.go, go/libraries/doltcore/row/tagged_values.go, go/libraries/doltcore/row/tagged_values_test.go
This fixes dropped errors in `libraries/doltcore/row`, as well as replacing `assert.NoError()` with `require.NoError()`.
=> Fixed dropped errors in libraries/doltcore/row

go/libraries/doltcore/env/actions/branch.go, go/libraries/doltcore/env/actions/infer_schema_test.go, go/libraries/doltcore/env/actions/reset.go
This fixes dropped errors in `libraries/doltcore/env/actions` and replaces use of `assert.NoError()` with `require.NoError()`.
=> libraries/doltcore/env/actions: error handling

go/go.mod, go/go.sum, go/libraries/doltcore/sqle/dolt_index.go, go/libraries/doltcore/sqle/dolt_index_test.go, go/libraries/doltcore/sqle/enginetest/dolt_engine_test.go, go/libraries/doltcore/sqle/mergeable_indexes_setup_test.go, go/libraries/doltcore/sqle/mergeable_indexes_test.go, go/libraries/doltcore/sqle/single_table_info_db.go, go/libraries/doltcore/sqle/tables.go, integration-tests/bats/index-on-writes.bats
This adds partial indexes to composite (multi-column) indexes. That means that `INDEX (v1, v2, v3)` now allows for partial matches, so accessing `v1` and `v1, v2` will make use of the index.
=> Added generated partial indexes for multi-column indexes

go/libraries/doltcore/fkconstrain/validate.go
This fixes two dropped error variables in `libraries/doltcore/fkconstrain`.
=> libraries/doltcore/fkconstrain: fix dropped errors

go/store/nbs/store.go
Fixes https://github.com/dolthub/dolt/issues/1530 by replacing a call to io.Copy with a new function writeTo.  Existing reader implementation replaces read calls to HTTP requests and larger read sizes here has a very big impact on Perf.
takes gcs clone of 600MB repo from 
```
real    28m2.168s
user    0m21.606s
sys     0m15.104s
```
to
```
real	0m17.885s
user	0m1.607s
sys	0m2.443s
```
has similar performance improvements for AWS repos and has small Dolthub clone perf improvements.
=> replace io.Copy to improve clone perf

go/store/types/tuple.go, integration-tests/bats/regression-tests.bats
Some `VARBINARY` strings were misreading their length, leading to other values reading garbage and erroring. Not sure how some `VARBINARY` strings were reading correctly, but this fixes the issue. Was caught by the fuzzer, but I stripped out the other queries for the bats test (still reproduces without them).
=> Fixed some VARBINARY strings reading their length incorrectly

go/store/types/tuple.go, integration-tests/bats/regression-tests.bats
Similar to https://github.com/dolthub/dolt/pull/1528, except dealing with the kind. Still surprised this was not caught earlier, seems like it should be completely broken. Some test repos have had thousands of rows with a `BLOB`-type column and they all worked without issue.
=> Fixed TINYBLOB errors with specific inputs

go/libraries/doltcore/env/config.go, go/libraries/doltcore/env/environment.go, go/libraries/doltcore/envtestutils/history.go
This fixes dropped errors in `libraries/doltcore/env` and `libraries/doltcore/envtestutils`.
=> fixed dropped errors in libraries/doltcore/env

go/cmd/dolt/commands/diff.go, go/cmd/dolt/commands/ls.go
This fixes some dropped errors in `diff` and `ls`.
=> cmd/dolt/commands: fix dropped errors

go/store/cmd/noms/noms_map.go, go/store/cmd/noms/noms_root.go, go/store/cmd/noms/noms_sync_test.go, go/store/datas/puller.go, go/store/diff/apply_patch_test.go, go/store/diff/diff_test.go, go/store/diff/patch_test.go, go/store/nomdl/parser.go, go/store/nomdl/parser_test.go
This fixes dropped errors and replaces `assert.NoError()` in multiple `store` subpackages.
=> store: more error handling

go/store/perf/suite/suite.go, go/store/perf/suite/suite_test.go
This fixes a dropped error and replaces most `assert.NoError()` with `require.NoError()`.
=> store/perf/suite: errors and tests

go/cmd/dolt/commands/tblcmds/import.go, go/libraries/doltcore/mvdata/table_data_loc.go
New `dolt table import` flag --no-gc, and parameter tuning to run gcs less during import.
=> gc changes for import

go/libraries/doltcore/sqle/json/noms_json_value_test.go
JSON structural sharing test writes a non-deterministic number of chunks to the in-memory chunk store.
=> fix flaky chunk test

.github/workflows/cd-release.yaml
ensure the release has identical commit as the binaries
=> [no-release-notes] /.github/workflows/cd-release.yaml: fix release commit off by one

go/libraries/doltcore/sqle/enginetest/dolt_engine_test.go, go/libraries/doltcore/table/editor/index_editor.go, go/libraries/doltcore/table/editor/index_operation_stack.go, go/libraries/doltcore/table/editor/index_operation_stack_test.go, go/libraries/doltcore/table/editor/pk_table_editor.go, go/libraries/doltcore/table/editor/pk_table_editor_test.go
Previously, if you had two or more indexes on a table and one of the indexes threw an error (such as a `UNIQUE` violation), the other index(es) would have whatever it was written to it still, leaving the table and index in an inconsistent state. This adds a small stack to index editors that allow one to undo the last few operations. In addition, the pk table editor tracks how many successful operations have been made per index editor and calls the equivalent number of undo statements, so that they're reset.
I chose to panic rather than error as, if these fail for whatever reason, we need to completely start over since things are broken and it's not really recoverable without rebuilding the entire index.
=> Fixed index editors getting to an invalid state on error

go/libraries/doltcore/table/editor/pk_table_editor.go, go/libraries/doltcore/table/editor/sessioned_table_editor.go
Optimization decreases the amount of time spent calculating index schemas.
=> index schema cache

go/libraries/doltcore/doltdb/root_val.go, go/libraries/doltcore/envtestutils/rebase_tag_test.go, go/libraries/doltcore/schema/schema.go, go/libraries/doltcore/schema/schema_test.go, go/libraries/doltcore/sqle/database.go, go/libraries/doltcore/sqle/sqlinsert_test.go, go/libraries/doltcore/sqle/sqlutil/convert.go, go/libraries/doltcore/sqle/sqlutil/schema.go, go/libraries/doltcore/sqle/tables.go, integration-tests/bats/foreign-keys.bats, integration-tests/bats/replace.bats, integration-tests/mysql-client-tests/go/go-sql-driver-mysql-test.go
- If a table is not in working,  is in head, and has the same schema as the table in head, re-use the tags and add the empty table back.
- The diff doesn't show `TRUNCATE table` or `DELETE from table` immediately after the create. I would have to edit the SQL path to change that.
- Bats tests added
todo:
-  engine tests?
- more complicated replace workflows. ex: replace table with extra column is easy, because I can do a one-way length check on columns and use a map for name/kind checks. Replace with delete column would be the same. Change column maybe also the same? If you do a series of replaces with column tags disappearing and reappearing, is it OK to enforce the re-use? Table moves should be explicit, that isn't a concern of replace workflows.
=> Initial tag-reuse within working

go/libraries/doltcore/diff/async_differ.go, go/libraries/doltcore/diff/async_differ_test.go
I think I'm going to need this to get the right amount of diff rows if a filter is applied. The current implementation of  `listRowDiffs` in dolthubapi gets a set amount of diff rows based on the offset and pageCount using `GetDiffs`
=> [no-release-notes] Add GetDiffsWithFilter async differ

go/libraries/doltcore/remotestorage/chunk_store.go, go/libraries/doltcore/remotestorage/concurrency.go, go/libraries/doltcore/remotestorage/hedge.go, go/libraries/doltcore/remotestorage/hedge_test.go, go/libraries/doltcore/remotestorage/retry.go
Allow URLs to be refreshed when signing credentials are expired or revoked. Increase small fetch concurrency. Limit hedged downloads to one per fetch. Avoid hedging large downloads for now.
=> Improve fetch and pull performance and reliability.

go/store/types/value_store.go
A deadlock can occur when the chunk size is greater than the maximum chunk size and a chunk with children gets removed, but it isn't removed from the withBufferedChildren map.
=> fixes infinite loop

go/libraries/doltcore/sqle/dolt_session.go
I don't love this... it's meant to address this failure in dolthub:
https://github.com/dolthub/ld/pull/6605
Read-only is also kind of a bad name, it still writes to the chunk store if you issue a write query, it just won't call WriteRootValue when a transaction is committed
Thoughts?
=> Mark the session state clean upon init

go/cmd/dolt/commands/sqlserver/sqlclient.go, go/gen/proto/dolt/services/eventsapi/v1alpha1/client_event.pb.go, go/gen/proto/dolt/services/eventsapi/v1alpha1/client_event_grpc.pb.go, go/gen/proto/dolt/services/eventsapi/v1alpha1/event_constants.pb.go, go/gen/proto/dolt/services/remotesapi/v1alpha1/chunkstore.pb.go, go/gen/proto/dolt/services/remotesapi/v1alpha1/chunkstore_grpc.pb.go, go/gen/proto/dolt/services/remotesapi/v1alpha1/credentials.pb.go, go/gen/proto/dolt/services/remotesapi/v1alpha1/credentials_grpc.pb.go, go/libraries/doltcore/sqle/database.go, go/libraries/doltcore/sqle/dolt_session.go, go/libraries/doltcore/sqle/enginetest/dolt_transaction_commit_test.go, go/libraries/doltcore/sqle/transactions.go
This adds a new session variable named `dolt_transaction_commit` that, when enabled, will cause a dolt commit of all changes in the working set when a transaction commit is completed.
=> Added session var that matches dolt and transaction commits

go/store/datas/database_common.go, go/store/nbs/file_manifest.go
This patches the random `ACCESS DENIED` error that may occur on Windows when noms attempts to rename the manifest.
=> Patched random ACCESS DENIED error on Windows

go/cmd/dolt/commands/sql.go, go/libraries/doltcore/doltdb/errors.go, go/libraries/doltcore/sqle/dfunctions/dolt_merge.go, integration-tests/bats/sql-merge.bats
Previously when DOLT_MERGE would face conflicts on the merge root it would error out and not update the working session root. With this pr, when a merge conflicts occurs we write to the working session root thereby rendering the dolt_conflicts table appropriately.
=> Fix bug with conflicts for DOLT_MERGE

go/libraries/doltcore/table/untyped/csv/writer.go, go/libraries/doltcore/table/untyped/csv/writer_test.go, integration-tests/bats/export-tables.bats
- JSON strings were not serialized in CSV writing
- convert Dolt rows to SQL Rows, and lean on the `SqlColToStr` to correctly parse values to strings.
- manually handle nil values to match bats tests CSV export format
=> Fix csv export types

go/cmd/dolt/system_checks.go, go/cmd/git-dolt/utils/find_git_config_dir_test.go, go/libraries/utils/file/open.go, go/libraries/utils/file/open_windows.go, go/libraries/utils/filesys/localfs.go, go/performance/benchmarks/benchmarks.go, go/store/blobstore/local.go, go/store/cmd/noms/noms_merge_test.go, go/store/cmd/noms/noms_sync_test.go, go/store/datas/puller.go, go/store/nbs/benchmarks/main.go, go/store/nbs/block_store_test.go, go/store/nbs/byte_sink.go, go/store/nbs/cache.go, go/store/nbs/fd_cache_test.go, go/store/nbs/file_manifest.go, go/store/nbs/file_manifest_test.go, go/store/nbs/file_table_persister.go, go/store/nbs/file_table_persister_test.go, go/store/nbs/fs_table_cache.go, go/store/nbs/fs_table_cache_test.go, go/store/nbs/mmap_table_reader_test.go, go/store/nbs/stats_test.go, go/store/perf/suite/suite.go, go/store/perf/suite/suite_test.go, go/store/spec/spec_test.go, go/store/types/perf/perf_test.go, go/store/util/clienttest/client_test_suite.go, go/store/util/tempfiles/temp_files.go
This attempts to fix the additional errors seen in the following issue:
https://github.com/dolthub/dolt/issues/1774
We've previously released a PR (https://github.com/dolthub/dolt/pull/1811) that seemed successful at _"fixing"_ an `ACCESS DENIED` error that would occur on table import when GC was running and the manifest was being renamed. That PR, however, did not touch any other rename within the codebase, nor any deletions (which can also trigger this bug). The above mentioned issue points to deletions, therefore this PR attempts to fix those plus any others by implementing the same strategy employed by the manifest renames and applying it to every deletion and rename in the project.
I also investigated the linked issues inside of the above mentioned issue …
=> Further attempts to fix ACCESS_DENIED error on Windows

go/cmd/dolt/commands/add.go, go/cmd/dolt/commands/commit.go, go/cmd/dolt/commands/merge.go, go/cmd/dolt/commands/status.go, go/libraries/doltcore/doltdb/foreign_key_coll.go, go/libraries/doltcore/doltdb/root_val.go, go/libraries/doltcore/env/actions/staged.go, go/libraries/doltcore/env/repo_state.go, go/libraries/doltcore/merge/constraint_violations.go, go/libraries/doltcore/merge/merge.go, go/libraries/doltcore/merge/merge_stats.go, go/libraries/doltcore/sqle/dfunctions/dolt_merge.go, go/libraries/doltcore/sqle/dfunctions/merge.go, go/libraries/doltcore/sqle/dtables/constraint_violations.go, go/libraries/utils/set/strset.go, integration-tests/bats/1pk5col-ints.bats, integration-tests/bats/conflict-detection.bats, integration-tests/bats/constraint-violations.bats, integration-tests/bats/docs.bats, integration-tests/bats/sql-merge.bats
This PR has a few things. Most notably, we no longer allow fast forward merges if a merge may cause a constraint violation. This decision was discussed internally. Additionally, I've modified the command line messages to properly respond to the presence of constraint violations, which includes blocking some functionality until they have been resolved. Lastly are general fixes and whatnot.
=> Additional Constraint Violation Fixes

go/cmd/dolt/commands/remote.go, go/libraries/doltcore/merge/merge.go, integration-tests/bats/merge.bats
Also some other panics, and added more merge tests. Cleaned up merge short circuit code, and clarified the behavior when one branch edits a table another deletes during a merge.
=> Fixed panic when merging a branch that still contains a table that was deleted in the target

go/libraries/doltcore/table/editor/keyless_table_editor.go, go/libraries/doltcore/table/editor/pk_table_editor.go, go/libraries/doltcore/table/editor/sessioned_table_editor.go, go/libraries/doltcore/table/editor/table_edit_session.go
10x speedup for the Nautobot database:
before:
```bash
% time dolt --prof cpu merge add-ipaddress                                                      
Updating uaimen5cq6jucq3abr85klgj0g594qc1..d3922cbd8fop4ast7ohl9mm4d3dn3632
extras_objectchange | 1 +
ipam_ipaddress      | 1 +
2 tables changed, 2 rows added(+), 0 rows modified(*), 0 rows deleted(-)
dolt --prof cpu merge add-ipaddress  83.78s user 3.75s system 567% cpu 15.433 total
```
after:
```bash
% time dolt --prof cpu merge add-ipaddress
Updating uaimen5cq6jucq3abr85klgj0g594qc1..d3922cbd8fop4ast7ohl9mm4d3dn3632
extras_objectchange | 1 +
ipam_ipaddress      | 1 +
2 tables changed, 2 rows added(+), 0 rows modified(*), 0 rows deleted(-)
dolt --prof cpu merge add-ipaddress  2.27s user 0.17s system 158% cpu 1.545 total
```
=> Optimize merge by skipping tables without edits

integration-tests/bats/import-update-tables.bats
Skipped bats test for duplicate rows in a table import -u --continue producing non-deterministic imports when repeated
=> Skipped bats test for non-deterministic table import behavior 

go/cmd/dolt/commands/sqlserver/server.go, go/cmd/dolt/commands/sqlserver/server_test.go, integration-tests/bats/sql-server.bats
setting `@@GLOBAL.dolt_sql_server_branch_ref` overwrites the branch for new sql-server connections. Setting the variable does not change the current connection's branch. If the variable is set to an invalid ref (ex: branch does not exist), the behavior is undefined for new connections.
```
> set GLOBAL dolt_sql_server_branch_ref = 'refs/heads/new'
Query OK, 1 row affected (0.00 sec)
mysql> select @@GLOBAL.dolt_sql_server_branch_ref;
+-------------------------------------+
| @@GLOBAL.dolt_sql_server_branch_ref |
+-------------------------------------+
| refs/heads/new                      |
+-------------------------------------+
1 row in set (0.00 sec)
mysql> select active_branch();
+-----------------+
| active_branch() |
+-----------------+
| master          |
+-----------------+
mysql> …
```
=> global system var for sql-server session branch

go/store/types/format.go, go/store/types/tuple.go
creates empty tuples per format in advance so we don't create all this garbage
=> create empty tuples at start

go/cmd/dolt/commands/fetch.go, go/libraries/doltcore/dbfactory/grpc.go, go/libraries/doltcore/ref/ref_spec.go, go/libraries/doltcore/ref/remote_ref.go, integration-tests/bats/remotes.bats
This pr addresses three issues with fetching remotes. 
1. A panic with fetching a remote in the form "remotes/.." that is invalid 
2. A panic when an added remote that is then fetched is invalid
3. A lack of error when fetching an invalid remote
=>  Addresses different types of panics with remotes/fetches Issue: #2048

.github/workflows/ci-bats-unix.yaml, .github/workflows/ci-bats-windows.yaml
This should shave 1-6 minutes off of every bats job, including the ~90 windows ones which were 8-9 minutes.
=> Remove doltpy from CI

go/go.mod, go/go.sum, integration-tests/bats/types.bats
=> go.mod: Bump go-mysql-server to pick up date handling for YYYY-M-D format.

go/libraries/doltcore/row/row.go, integration-tests/bats/import-update-tables.bats
Closes #2103.
Before:
```python
A bad row was encountered while moving data.
Bad Row: 
"03AGDBQ24TPRIFU0LRPRHLHU8KBOK5SQSMCT8BMVFJNANULFUG4RDHNZPOV4PJNMN0DOD1PM2V5AQQTFP1HZXZG5J5BJTP7BN0A8WLBZYMBJIRU7BWTYCNXTCQUD1UYWITEJIZR5EWWP1NM4OR40P6FTQL4NHKIA870UAFXSPRF0AIK_45YNRU98ZQOZQNJFKNF89FW9" is not valid for "VarString(utf8mb4_0900_ai_ci, 180, SQL: VarChar)"
These can be ignored using the '--continue'
```
After:
```python
A bad row was encountered while moving data.
Bad Row: 
"03AGDBQ24TPRIFU0LRPRHLHU8KBOK5SQSMCT8BMVFJNANULFUG4RDHNZPOV4PJNMN0DOD1PM2V5AQQTFP1HZXZG5J5BJTP7BN0A8WLBZYMBJIRU7BWTYCNXTCQUD1UYWITEJIZR5EWWP1NM4OR40P6FTQL4NHKIA870UAFXSPRF0AIK_45YNRU98ZQOZQNJFKNF89FW9" is not valid for column "street_physical" (type "VarString(utf8mb4_0900_ai_ci, 180, SQL: VarChar)")
These can be …
```
=> Modify bad row error format

go/cmd/dolt/commands/clone.go, go/cmd/dolt/commands/read_tables.go, go/cmd/dolt/commands/remote.go, go/cmd/dolt/dolt.go, go/libraries/doltcore/dbfactory/aws.go, go/libraries/doltcore/dbfactory/factory.go, go/libraries/doltcore/dbfactory/file.go, go/libraries/doltcore/dbfactory/grpc.go, go/libraries/doltcore/dbfactory/gs.go, go/libraries/doltcore/dbfactory/mem.go, go/libraries/doltcore/doltdb/doltdb.go, go/libraries/doltcore/env/environment.go, go/libraries/doltcore/env/remotes.go, go/utils/remotesrv/main.go
Prior to this change, we used to set a global variable in the dbfactory package
which referred to whichever DoltEnv was loaded most recently. It was racey and
it has pretty terrible semantics.
=> go/libraries/doltcore/dbfactory: Change our GRPC remote DB factory to take the GRPC dialer through a param.

go/cmd/dolt/commands/cnfcmds/cat.go, go/cmd/dolt/commands/diff.go, go/libraries/doltcore/doltdb/foreign_key_coll.go, go/libraries/doltcore/sqle/dolt_index.go, go/libraries/doltcore/sqle/dtables/diff_table.go, go/libraries/doltcore/sqle/dtables/history_table.go, go/libraries/doltcore/sqle/tables.go, integration-tests/bats/regression-tests.bats
Previously we were using memory value stores in some places, and everything seemed to be working, but I think our garbage collection changes exposed some inconsistencies that were causing bugs. This PR threads values stores to where they need to be and removes the majority of the places where we were using memory value stores.
This also solves a multitude of fuzzer issues, including the `corrupted database` error:
https://github.com/dolthub/fuzzer/issues/337
And also the cause of some rows not being found and silently causing some operations to no-op (bats test included):
https://github.com/dolthub/fuzzer/issues/597
=> Fixed VRW reference issues

go/libraries/doltcore/diff/async_differ.go, go/libraries/doltcore/diff/async_differ_test.go
On dolthub we're using `diff.NewAsyncDiffer` instead of `diff.NewRowDiffer` to list row diffs (see [here](https://github.com/dolthub/ld/blob/master/go/services/dolthubapi/pkg/domain/repositorydata.go#L1534)), which doesn't have support for diffing keyless tables (https://www.dolthub.com/repositories/ttest/keyless/pulls/1/compare). In order to use `NewRowDiffer`, we need to add a `GetDiffsWithFilter` method for keyless tables.
I tried writing tests for this, but was having a hard time figuring out what the rows map for keyless tables should look like
=> Support GetDiffsWithFilter for keyless tables

go/cmd/dolt/commands/fetch.go, go/cmd/dolt/commands/migrate.go, go/libraries/doltcore/env/actions/remotes.go, go/libraries/doltcore/env/remotes.go, go/libraries/doltcore/sqle/dfunctions/dolt_fetch.go, integration-tests/bats/localbs-remotes.bats, integration-tests/bats/remotes-file-system.bats, integration-tests/bats/remotes.bats, integration-tests/bats/sql-fetch.bats
- consolidate `getRefSpecs` functions from cli/env
- fetch argument switching matches git more closely -- specifying the remote is necessary, no default to origin
=> Fetch refactor

go/libraries/doltcore/table/editor/bulk_import_tea.go
BulkImportIEA and BulkImportTEA only support Commit, and not Rollback.  Dolt uses these for import operations which do not get an explicit Commit or Rollback call.  When used on the web for the in memory implementation Commit is used, and should not error.
=> Fix update on web issue

go/libraries/doltcore/sqle/database_provider.go, integration-tests/bats/sql-create-database.bats
Warning is due to CREATE DATABASE not persisting after the server exits
=> Add a warning for CREATE DATABASE

go/cmd/dolt/commands/diff.go, go/libraries/doltcore/diff/sql_diff.go, go/libraries/doltcore/sqle/sqlfmt/row_fmt.go, go/libraries/doltcore/sqle/sqlfmt/row_fmt_test.go, go/libraries/doltcore/sqle/sqlfmt/schema_fmt.go, integration-tests/bats/diff.bats
Allows for dolt diff -sql to be used for keyless tables and add alter pk support for sql diffs.
=> Unblock Keyless SQL Diffs and Minimize SQL Diffs

integration-tests/bats/primary-key-changes.bats
=> Add skipped bats for adding a primary key to a column with NULL in it

go/libraries/doltcore/schema/alterschema/addpk.go, go/libraries/doltcore/sqle/sqlutil/sql_row.go, go/libraries/doltcore/sqle/table_editor.go, go/libraries/doltcore/table/editor/keyless_table_editor.go, go/libraries/doltcore/table/editor/keyless_table_editor_test.go, go/libraries/doltcore/table/editor/pk_table_editor.go, go/libraries/doltcore/table/editor/pk_table_editor_test.go, go/libraries/doltcore/table/editor/table_edit_session.go, go/store/types/tuple.go
Makes types.TupleFactory thread-safe. Allocates a new TupleFactory when we construct a SessionTableEditor, and threads that TupleFactory through to individual table editors that can use it to do their editing. Makes that TupleFactory available through an accessor that sqlTableEditor uses for a few tuple manipulations.
=> go/libraries/doltcore/table/editor: Thread some TupleFactories to places that allocate tuples.

go/cmd/dolt/commands/sql.go, go/cmd/dolt/dolt.go, go/libraries/doltcore/env/multi_repo_env.go, go/libraries/doltcore/sqle/dsess/dolt_session.go, go/libraries/doltcore/sqle/read_replica_database.go, integration-tests/bats/replication-multidb.bats
- Multidb uses global dolt config
- Each database locally sets the url for the named remote
- Error handling and async will work the same as single db
Consider a multidb dir `dbs` with a repo in `dbs/repo`. We initialize multidb replication in the global config:
```
$ dolt config --global sqlserver.global.dolt_replication_to_remote replication_middleman
```
`repo` is responsible for setting the replication remote endpoint:
```
$ cd dbs/repo
$ dolt remote add replication_middleman file://../remotes/repo1-middleman
```
=> replication with multi-db mode

go/libraries/doltcore/table/untyped/xlsx/marshaling.go
These lines were not visible from the CLI because of color, but it still cost
performance. In an embedded context, these could end up in stdout.
=> go/libraries/doltcore/table/untyped/xlsx: Fix bug where this spammed internal representation of the imported rows to Stdout.

go/cmd/dolt/cli/command.go, integration-tests/bats/config.bats
Running `dolt init` before configuring `user.email` and `user.name` results (correctly) in error; however, the CLI hint itself is incorrect:
```text
Author identity unknown
*** Please tell me who you are.
Run
dolt config --global user.email "you@example.com"
dolt config --global user.name "Your Name"
to set your account's default identity.
Omit --global to set the identity only in this repository.
fatal: empty ident name not allowed
```
The proposed commands for identity configuration do not include the `--add` flag, resulting in a new error message: `Exactly one of the -add, -get, -unset, -list flags must be set.`
This PR fixes the CLI message by adding the `--add` flag to the proposed commands.
=> fix: userNameRequiredError message in CLI

benchmark/import_tester/csv_gen.py, benchmark/import_tester/run_importer.sh, go/cmd/dolt/commands/tblcmds/import.go
Two noticeable problems.
1) No longer using BulkImportTableEditor. Needs to be threaded through in case the batch mode is set in the session.
2) Performance overhead from DoltRow to SqlRow conversion throughout the insert process. This should be reduced in the future as row.Row is deprecated
Current results
```
generating test file
Running the current version of import
Successfully initialized dolt data repository.
Rows Processed: 1000000, Additions: 1000000, Modifications: 0, Had No Effect: 0
Import completed successfully.
real	0m47.759s
user	1m16.795s
sys	0m25.848s
Running version 0.34.5
Rows Processed: 1000000, Additions: 1000000, Modifications: 0, Had No Effect: 0
Import completed successfully.
real	0m37.736s
user	1m12.005s
sys	0m30.281s
```
=> Add import benchmarks and add in import performance fix

integration-tests/bats/sql-checkout.bats
SQL Checkout should not change the branch in command line context. It only changes the branch for the session which ends after the statement. Resolves #2468.
=> Modified bats for SQL checkout to assert that the branch should not change on the CLI. 

integration-tests/bats/index.bats
Added skipped bats test for the issue where an index is used inappropriately when a function modifies the column producing incorrect results.
=> Skipped test for Index overuse issue

benchmark/import_tester/run_importer.sh, go/cmd/dolt/commands/tblcmds/export.go, go/libraries/doltcore/mvdata/engine_mover.go, go/libraries/doltcore/mvdata/engine_table_reader.go, go/libraries/doltcore/table/table_writer.go, go/libraries/doltcore/table/typed/json/writer.go, go/libraries/doltcore/table/typed/parquet/writer.go, go/libraries/doltcore/table/untyped/csv/writer.go
This pr removes the need of TableDataLoc from export and moves it towards an engine based table reader. It also modifies the writer implementations to work with sql.Row
TODO: I don't think export should support either --continue or --mapping. They were never tested nor are they relevant. If there is an error reading a row from a table, you should fail hard.
=> Refactor the Export path to read from the engine

go/libraries/doltcore/merge/merge.go, go/libraries/doltcore/merge/resolve.go, go/libraries/doltcore/sqle/dsess/transactions.go
Remove uses of `EditSession` outside of `sqle`. This refactor paves the way to re-implement foreign keys in a storage-agnostic way
=> /go/libraries/doltcore/merge: Remove `editor.EditSession`

go/go.mod, go/go.sum, integration-tests/bats/import-update-tables.bats
This PR addresses a customer issue where --update,--continue on a table import were dropping rows. The error comes from the facts that INSERT IGNORE semantics were not correctly handling issues with data conversions (type conversions, string lengths, etc.)
=> Fix bug with import update dropping rows

go/cmd/dolt/commands/engine/sqlengine.go, integration-tests/bats/sql-server-mysql.expect, integration-tests/bats/sql-server.bats
In the migration to *SqlEngine in 0.34.4 to 0.34.5, the server config's respect
for the default value for autocommit regressed. In 0.34.5 - 0.35.3,
`autocommit` is always turned on by default for incoming connections,
regardless of the setting in the config.yaml file or the flag
`--no-auto-commit` being passed at the command line.
=> sql-server: Fix regression: Respect autocommit config.

go/libraries/doltcore/doltdb/foreign_key_coll.go, go/libraries/doltcore/merge/merge_schema.go, go/libraries/doltcore/schema/index.go, go/libraries/doltcore/sqle/enginetest/dolt_transaction_commit_test.go
The logic that handled foreign key merging during transaction commits did not take unresolved foreign keys into consideration, therefore errors were produced. This fixes that bug.
=> Fixed bug with unresolved foreign keys being resolved in transactions

go/cmd/dolt/dolt.go
Allow for stdout and stderr to be redirected to a file via a command line argument.  When running outside of a terminal window it can be really inconvenient to redirect io.  These parameters were added to make that easier.
=> std out and err redirects

go/cmd/dolt/commands/cvcmds/verify_constraints.go, go/cmd/dolt/commands/dump_docs.go
`dump_docs` doesn't dump the docs for `verify constraints`, which means they're not visible in the online documentation. Hopefully this fixes that.
After building I checked that it worked locally and seemed to produce the right output.
Context: this is my first PR and my first time editing go code. Entering the great unknown here.  :-)
=> dump_docs.go now includes verifyConstraintsDocs

integration-tests/bats/sql-create-database.bats
Fails if used in the same session as creating the database.
=> Skipped bats test for creating tables using the database.table syntax

go/libraries/doltcore/merge/merge_schema.go, go/libraries/doltcore/sqle/enginetest/dolt_transaction_queries.go
Still need to add test cases here
=> Add ordinal to merge schema after merge

go/store/datas/database_common.go
This fixes a dropped `err` variable in the `store/datas` package.
=> store/datas: fix dropped error

go/libraries/doltcore/doltdb/durable/index.go, go/libraries/doltcore/sqle/tables.go
`Format_7_18` is still used in `ld` in some cases
=> /go/libraries/doltcore/{doltdb/durable, sqle}: Added Format_7_18 to NomsBinFormat switch statements

go/libraries/doltcore/merge/constraint_violations.go
This fixes a dropped error in `libraries/doltcore/merge`.
=> libraries/doltcore/merge: fix dropped error

go/libraries/doltcore/table/editor/table_edit_accumulator_test.go
This fixes two dropped test `err` variables in `libraries/doltcore/table/editor`.
=> libraries/doltcore/table/editor: fix dropped test errors

go/libraries/doltcore/env/actions/remotes.go, integration-tests/bats/remotes.bats
We were missing a test for push --set-upstream where
the feature branch had already been pushed from another
clone.
=> Fix --set-upstream bug when feature branch already exists on remote

go/libraries/doltcore/sqle/dtables/filtered_reader.go, go/libraries/doltcore/sqle/dtables/filtered_reader_test.go, go/libraries/doltcore/sqle/dtables/history_table.go, go/libraries/doltcore/sqle/enginetest/dolt_engine_test.go, go/libraries/doltcore/sqle/enginetest/dolt_queries.go, integration-tests/bats/system-tables.bats
Panic occurs when selecting from `DOLT_HISTORY_<TABLE>` using a filter expression and the underlying table that doesn't have a primary key.
=> Bug fix for an index out of bounds panic in DOLT_HISTORY_<TABLE>

go/libraries/doltcore/sqle/dtables/unscoped_diff_table.go
I added the table_name column as part of the primary key, then changed the order, not realizing that would mess up the test data.
=> Fixing schema ordering to unbreak tests

go/store/nbs/index_transformer.go, go/store/nbs/index_transformer_test.go, go/store/nbs/table.go
IndexTransformer is an io.Reader that takes an io.Reader of the table file index. It specifically transforms the lengths into offsets.
=> Index Transformer

integration-tests/bats/auto_increment.bats, integration-tests/bats/foreign-keys.bats, integration-tests/bats/index.bats
Added tests for using different database than current for ALTER TABLE - CREATE INDEX and ADD CONSTRAINT. 
Added tests for ADD CONSTRAINT FOREIGN KEY query should be failing, but currently does not.
=> add bats test for different db stmts

go/store/nbs/aws_chunk_source.go, go/store/nbs/aws_table_persister_test.go, go/store/nbs/block_store_test.go, go/store/nbs/bs_persister.go, go/store/nbs/chunk_source_adapter.go, go/store/nbs/cmp_chunk_table_writer_test.go, go/store/nbs/conjoiner_test.go, go/store/nbs/dynamo_fake_test.go, go/store/nbs/file_table_persister_test.go, go/store/nbs/mem_table_test.go, go/store/nbs/mmap_table_reader.go, go/store/nbs/persisting_chunk_source.go, go/store/nbs/root_tracker_test.go, go/store/nbs/s3_fake_test.go, go/store/nbs/store.go, go/store/nbs/table.go, go/store/nbs/table_persister.go, go/store/nbs/table_persister_test.go, go/store/nbs/table_reader.go, go/store/nbs/table_reader_test.go, go/store/nbs/table_set.go, go/store/nbs/table_test.go, go/store/nbs/util.go
In preparation for a disk `tableIndex`, I altered the tableIndex functions to return errors and fixed any code that needs to return errors. 
The Ordinals() and Prefixes() functions have also been changed to return errors, but for TOW I'm not sure we can return an entire slice of all ordinals or prefixes without blowing up.
=> Add errors to tableIndex interface funcs

go/Godeps/LICENSES, go/go.mod, go/go.sum, go/libraries/doltcore/env/actions/clone.go, go/libraries/doltcore/remotestorage/chunk_store.go, go/libraries/utils/iohelp/read_with_stats.go, go/store/datas/pull/clone.go, go/store/datas/pull/pull_test.go, go/store/datas/pull/puller.go, go/store/nbs/file_table_persister.go, go/store/nbs/persisting_chunk_source.go, go/store/nbs/store.go, go/store/nbs/store_test.go, go/store/nbs/table.go, go/store/nbs/table_reader.go
Previously, it was difficult to understand the progress of `dolt clone`, especially when you are cloning a db with a small number of large table files. `dolt clone` now lists which table files are being concurrently downloaded and shows the progress and download rate for each. 
An example:
@reltuk Brought up the concern for compatibility between the new `uilive` dep and `github.com/faith/color`. In my testing there doesn't seem to be any issues:
=> go/cmd/dolt: Add download statistics to dolt clone

go/store/types/map.go
This fixes a dropped `err` variable in the `store/types` package.
=> store/types: fix dropped error

go/cmd/dolt/commands/backup.go, go/cmd/dolt/commands/fetch.go, go/cmd/dolt/commands/pull.go, go/cmd/dolt/commands/push.go, go/cmd/dolt/commands/read_tables.go, go/libraries/doltcore/env/actions/remotes.go, go/store/datas/pull/puller.go
Fixes #2798
For downloads (pulling chunks from a remote db to a local db), dolt will now report the number of tables files written to disk as `Files Written`. It will no longer report an `Upload Rate` for a download as that is the speed at which the file is copied from a temp directory.
For uploads (pulling chunks from a local db to a remote db), dolt will now report the number of table files created during the pull process as `Files Created` and the number of these tables files that have been uploaded as `Files Uploaded`.
=> go/dolt/cmd: Use download language when dolt pulls from a remote

go/libraries/utils/editor/edit.go
This fixes a dropped `err` variable in `libraries/utils/editor`.
=> libraries/utils/editor: fix dropped error

go/libraries/doltcore/sqle/writer/prolly_table_writer.go
Fetching and updating auto increment values is relatively expensive given the current implementation. Conditionally skipping this step makes deleted 2x faster
=> doltcore/sqle: Optimize Delete

go/libraries/doltcore/sqle/dtables/blame_view.go
Quick change to remove the SuperSchema reference from `Dolt_Blame` system view, now that we have migrated `Dolt_DIff_$tablename` off of SuperSchema's tag-suffixed column names.
=> Removing use of SuperSchema from Dolt_Blame system view.

go/libraries/doltcore/sqle/dtables/unscoped_diff_table.go, go/libraries/doltcore/sqle/enginetest/dolt_engine_test.go, go/libraries/doltcore/sqle/enginetest/dolt_queries.go
This change adds two new boolean columns to the unscoped `DOLT_DIFF` system table to enable customers to determine if a change to a table was a schema change or a data change (or both). 
Example Usage: 
```
> create table x (a int primary key, b int, c int);
> create table y (a int primary key, b int, c int);
> insert into x values (1, 2, 3), (2, 3, 4);
> select DOLT_COMMIT('-am', 'Creating tables x and y');
> select * from dolt_diff;
+----------------------------------+------------+-----------+-------------------------+----------------------------------+-------------------------+-------------+---------------+
| commit_hash                      | table_name | committer | email                   | date                             | message                 | data_change | schema_change | …
```
=> Expand DOLT_DIFF system table to indicate the type of change

go/libraries/doltcore/dbfactory/file.go
This fixes the panic when using very old repositories (7.18) or experimental formats in new ones.
=> [no-release-notes] go/libraries/doltcore/dbfactory: file.go: Fix the default NBF Format used when constructing the old gen to match the new gen.

go/libraries/doltcore/sqle/sqlfmt/row_fmt.go, go/libraries/doltcore/sqle/sqlfmt/row_fmt_test.go, integration-tests/bats/export-tables.bats
the issue covered all typeInfo types where null values were not getting exported correctly. 
the fix is to add `NULL` whenever the value is nil and cannot be converted into sql types.
=> fix null value being exported for any types into .sql file

go/utils/remotesrv/http.go, go/utils/remotesrv/main.go
This PR fixes an issue when pulling chunks from Dolt `remotesrv`. The symptom is a `throughput below minimum allowable` error. The problem is that the dolt client can't handle large http chunks without failing to meet its minimum required download throughput. 
Dolt `remotesrv` hosts a simple http file server that can be used to write new table files and read existing table files. When `remotesrv` receives a request to read a file it will currently read all of the requested range into memory. It then, writes the 
entire range to `http.ResponseWriter` in a single `Write` call. 
This causes a very large http chunk ([see chunked transfer encoding](https://en.wikipedia.org/wiki/Chunked_transfer_encoding)) to be sent over the wire. When the Dolt client tries to read the http response using …
=> go/utils/remotesrv: use io.Copy in the http file server to write table file data to http.ResponseWriter

go/go.mod, go/go.sum, go/libraries/doltcore/sqle/sqlutil/sql_row.go
Consider a table with a primary key defined in a different order than the schema:
```SQL
> create table a (x int, y int, primary key (y,x);
> insert into a values (0,1), (2,3);
Query OK, 1 row affected
```
Deletes were matching rows in the index and correctly tracking the affected row count, but generating intermediate schema-order key tuples incompatible with the table PK order. The incompatible keys failed to match the source keys in the roundtrip as the edits were applied to the table:
```SQL
> delete from a where x = 0;
Query OK, 1 row affected
> delete from a where x = 0;
Query OK, 1 row affected
> select * from a where x = 0:
+---+---+
| x | y |
+---+---+
| 0 | 1 |
| 2 | 3 |
+---+---+
```
i.e. we were matching `(1,0)` and then trying to delete `(0,1)`.
This fixes the intermediate …
=> Fix Pk ordinal delete bug

go/libraries/doltcore/dbfactory/aws.go, go/libraries/doltcore/dbfactory/aws_test.go, integration-tests/bats/aws-remotes.bats
This was previously forbidden because of how table files were stored in the
destination bucket, but that was changed long ago and this is now well
supported. Our internal remotes serving infrastructure uses chunk stores
constructed in the same way.
=> go/libraries/doltcore/dbfactory: aws.go: Support / as a character in database names for AWS remotes.

go/libraries/doltcore/remotestorage/chunk_store.go, go/libraries/doltcore/remotestorage/hedge.go, go/libraries/doltcore/remotestorage/hedge_test.go
`Strategy` has been renamed to `HedgeStrategy`. `HedgeStrategy`'s now control the nextTry durations directly and an `ExponentialHedgeStrategy` has been added that can be composed with other strategies to get the previous behavior.
=> Change HedgeStrategy  interface to control nextTry durations directly

go/cmd/dolt/cli/stdio.go, go/cmd/dolt/commands/diff.go, go/cmd/dolt/commands/login.go, go/cmd/dolt/commands/push.go, go/libraries/doltcore/env/actions/clone.go, go/libraries/doltcore/env/actions/remotes.go, integration-tests/bats/remotes.bats
`EphemeralPrinter` is tool that you can use to print temporary line(s) to the console. Every time `Display` is called, the previously written lines are cleared, and the new lines are flushed to the output.
Fixes #2964
=> Add Ephemeral Printer

go/go.mod, go/go.sum, go/libraries/doltcore/schema/alterschema/addpk.go, go/libraries/doltcore/schema/index_coll.go, go/libraries/doltcore/schema/schema_impl.go, go/libraries/doltcore/sqle/enginetest/dolt_engine_test.go, go/libraries/doltcore/sqle/index/noms_index_iter.go, go/libraries/doltcore/sqle/sqlutil/sql_row.go
The original bug was found by stabs: https://github.com/dolthub/dolt/issues/2991
Refer to the GMS PR with a script test for testing the condition that triggers the bug: https://github.com/dolthub/go-mysql-server/pull/881
A summary of the bug is: Secondary indexes were caching old pk orderings. Schema changes created an inconsistency between secondary indexes and the primary keys they referred to, causing errors in index lookups. This only impacts DDL statements involving a new pk ordering and preexisting secondary indexes.
There are several layers of indirection between pk source row and secondary index row. When creating an index row, a higher layer of code reads and formats keys in the correct index ordering (for example, reading schema order (x,y,z) -> (y,z,x)). However, we deconstruct …
=> Apply PK ordinals to secondary index pk tag ordering

go/libraries/doltcore/sqle/dfunctions/dolt_merge.go, go/libraries/doltcore/sqle/dfunctions/dolt_pull.go, go/libraries/doltcore/sqle/dfunctions/dolt_reset.go, go/libraries/doltcore/sqle/dsess/session.go, go/libraries/doltcore/sqle/writer/noms_write_session.go
This PR alters the life cycle of WriteSessions within a dolt session. WriteSessions now have a single working set ref throughout their existence, and assert that their working set ref is not changed by set or update calls. 
To switch branches/working set, the Session discards the existing (empty) WriteSession, and creates a new one
=> go/libraries/doltcore/sqle/dsess: Refactor Dolt Session update methods

go/cmd/dolt/cli/stdio.go, go/cmd/dolt/commands/diff.go, go/cmd/dolt/commands/login.go, go/cmd/dolt/commands/push.go, go/libraries/doltcore/env/actions/clone.go
Fixes: https://github.com/dolthub/dolt/issues/2941
The above reported bug is caused by `EphemeralPrinter`. It's related to how the underlying library of `uilive` clears terminal lines on Windows. `uilive` will only clear terminal lines successfully if it detects that the given `io.Writer` is a terminal. The package does this by checking if the io.Writer has a `Fd` function and using the returned file descriptor for its `istty` check.
When color.Output is used as the `io.Writer`, `uilive`'s terminal check fails since that does not declare `Fd`. The problem is that color.Output does use the initial `os.StdOut` which is in fact the terminal... 
This was fixed by wrapping color.Output with a struct that reports the correct file descriptor.
This PR also improves the display output of ephemeral …
=> go/cmd/dolt: Fix fetch printing newline for each progress update on Windows

go/cmd/dolt/commands/dump.go, go/cmd/dolt/commands/engine/utils.go, go/cmd/dolt/commands/filter-branch.go, go/cmd/dolt/commands/indexcmds/rebuild.go, go/cmd/dolt/commands/revert.go, go/cmd/dolt/commands/schcmds/export.go, go/cmd/dolt/commands/schcmds/show.go, go/libraries/doltcore/dtestutils/testcommands/command.go, go/libraries/doltcore/merge/action.go, go/libraries/doltcore/merge/resolve.go, go/libraries/doltcore/mvdata/data_loc_test.go, go/libraries/doltcore/schema/alterschema/droppk_test.go, go/libraries/doltcore/schema/alterschema/modifycolumn_test.go, go/libraries/doltcore/sqle/altertests/common_test.go, go/libraries/doltcore/sqle/common_test.go, go/libraries/doltcore/sqle/database.go, go/libraries/doltcore/sqle/enginetest/dolt_harness.go, go/libraries/doltcore/sqle/index/mergeable_indexes_setup_test.go, go/libraries/doltcore/sqle/logictest/dolt/doltharness.go, go/libraries/doltcore/sqle/schema_table_test.go, go/libraries/doltcore/sqle/sqlbatch_test.go, go/libraries/doltcore/sqle/testutil.go, go/libraries/doltcore/sqle/writer/noms_table_writer_test.go, go/libraries/doltcore/table/editor/index_editor.go, go/libraries/doltcore/table/editor/pk_table_editor.go
Two improvements with index rewriting:
1) Brian's `TupleFactory` optimizations were being skipped, and 70% of
the runtime was spent building `newBinaryNomsWriter` instances for tuple
construction. Removing this restores index inserts as the only memory
pressure.
2) Brian's `BulkEditAccumulator` lets the final Map sort skip
work materializing intermediate prolly trees.
On a 2000 row table, fix (1) reduces the runtime by 50% (80ms -> 40ms),
and fix (2) reduces the runtime by another 40% (40ms -> 10ms)%, for a
cumulative ~90% improvement.
=> Simplify RebuildIndex

go/libraries/doltcore/remotestorage/chunk_store.go, go/store/datas/pull/clone.go, go/store/datas/pull/pull_test.go, go/store/datas/pull/puller.go, go/store/nbs/generational_chunk_store.go, go/store/nbs/nbs_metrics_wrapper.go, go/store/nbs/store.go, go/store/nbs/store_test.go, go/store/nbs/table.go
For each table file upload, we now call GetUploadLocations for that a single table file, and upload it in the same retriable
operation.
=> DoltChunkStore: Table file uploads now retry both the GetUploadLocations call and the PUT call

go/libraries/doltcore/sqle/enginetest/dolt_engine_test.go, go/libraries/doltcore/sqle/enginetest/dolt_queries.go
Enables Dolt to support `describe table as of <commit>` or `show columns from table as of <commit>`.
Depends on:
* Vitess support: https://github.com/dolthub/vitess/pull/150
* Go-mysql-server support: https://github.com/dolthub/go-mysql-server/pull/923
=> Adding tests to validate as of support for describe table.

go/cmd/dolt/commands/login.go, go/libraries/doltcore/env/config.go
This PR adds the `--auth-endpoint`, `--login-url`, and `--insecure` arguments to the `dolt login` command so that it can authenticate against remotes beyond `doltremoteapi.dolthub.com:443`. This supports `dolt login`'s use with DoltLab instances. It also adds a dolt config option `doltlab.insecure`, which if `true` will establish an insecure gRPC connection to the remote authentication server (currently required for DoltLab's remote auth server).
`dolt login` will continue to use `doltremoteapi.dolthub.com:443` as the default remote `authEndpoint` and `https://www.dolthub.com/settings/credentials` as the `loginUrl` opened by the browser. 
If a local or global dolt config file sets `remotes.default_host` and `remotes.default_port`, the values specified in the config will be used over the …
=> /go/cmd/dolt/commands/login.go: make `dolt login` command configurable, can authenticate against different remotes

go/cmd/dolt/commands/dump.go, go/libraries/doltcore/sqle/sqlfmt/row_fmt.go, go/libraries/doltcore/table/untyped/sqlexport/sqlwriter.go, integration-tests/bats/dump.bats
fix for: https://github.com/dolthub/dolt/issues/3159
instead of dumping certain dolt tables, create the views, triggers, and procedures.
=> `dolt dump` should include views, triggers, and procedures

go/libraries/doltcore/doltdb/doltdb.go, go/libraries/doltcore/doltdb/errors.go, go/libraries/doltcore/env/actions/branch.go, go/libraries/doltcore/sqle/enginetest/dolt_queries.go
Fix error message for ErrBranchNotFound to include the branch that wasn't found.
helps for: https://github.com/dolthub/dolt/issues/3270
=> Fixing bad error message for `ErrBranchNotFound`

go/cmd/dolt/commands/checkout.go, integration-tests/bats/checkout.bats
Closes #3276 
Instead of showing the following when trying to checkout a specific commit:
```
dolt checkout 400435pip70vh165ggsq4etmggdh6h5i
error: could not find 400435pip70vh165ggsq4etmggdh6h5
```
We instead show:
```
dolt checkout 400435pip70vh165ggsq4etmggdh6h5i
dolt does not support a detached head state. To create a branch at this commit instead, run:
dolt checkout 400435pip70vh165ggsq4etmggdh6h5i -b {new_branch_name}
```
=> go/cmd/dolt: Add create new branch suggestion to dolt checkout {commit_hash}

go/store/nbs/table_reader.go
In the case where we find a matching prefix but no matching suffixes, we were
failing to appropriately set remaining = true.
=> [no-release-notes] go/store/nbs/table_reader.go: Fix a bug in findOffsets where we returning remaining == false sometimes.

go/cmd/dolt/commands/diff.go, go/libraries/doltcore/sqle/tables.go, integration-tests/bats/diff.bats
Fixes: https://github.com/dolthub/dolt/issues/3300
The `dolt diff` command was previously omitting schema and data diffs if tables were created or dropped within the commit range, and only outputting diff summary information with tabular output. This change causes the schema changes and data changes to be included in tabular output. 
Old behavior: 
```
❯ dolt diff mhgva1kfcljign82ntcmr6ftmpbmemko j6n5727at9652tri8ncsa02v794h1fi4
diff --dolt a/a b/a
added table
❯ dolt diff mhgva1kfcljign82ntcmr6ftmpbmemko ccm9bfiv6jhft1tmeu1cqd0ghduhg4v7
diff --dolt a/a b/a
added table
❯ dolt diff qd507o2jjlckjgmn2polsmiifk62vo8n js1bb2cvdr7h4tdj2d3m33jhp9rc9ee9
diff --dolt a/a b/a
deleted table
```
New behavior:
```
❯ dolt diff mhgva1kfcljign82ntcmr6ftmpbmemko j6n5727at9652tri8ncsa02v794h1fi4
diff --dolt …
```
=> Display schema and data for created and dropped tables in `dolt diff` command 

go/Godeps/LICENSES, go/libraries/doltcore/merge/merge.go, go/libraries/doltcore/merge/merge_test.go, go/libraries/doltcore/merge/row_merge_test.go, integration-tests/bats/merge.bats
A bug was discovered where a composite index is left in an inconsistent state after a merge. This PR adds a bats test to catch this bug, and fixes it.
In preparation for the new storage format, this PR also rewrites the merge tests in a universal way. This will allow us to test both the old format and new format functionality with the same test cases.
=> Fix composite index merge bug

go/store/prolly/address_map.go, go/store/prolly/conflicts_map.go, go/store/prolly/map.go, go/store/prolly/map_test.go, go/store/prolly/message/address_map.go, go/store/prolly/message/message.go, go/store/prolly/message/prolly_map.go, go/store/prolly/message/prolly_map_test.go, go/store/prolly/mutable_map.go, go/store/prolly/mutable_map_read_test.go, go/store/prolly/mutable_map_write_test.go, go/store/prolly/ordered_tree.go, go/store/prolly/tree/chunker.go, go/store/prolly/tree/content_address_test.go, go/store/prolly/tree/merge.go, go/store/prolly/tree/mutator.go, go/store/prolly/tree/node_builder.go, go/store/prolly/tree/node_cursor.go, go/store/prolly/tree/node_cursor_test.go, go/store/prolly/tree/node_splitter_test.go, go/store/prolly/tree/testutils.go, go/store/prolly/write_amplification_test.go
Some degree of builder polymorphism is needed to support prolly trees nodes backed by multiple flatbuffers messages. This PR reduces the scope of that polymorphism, simplifying the write path throughout the `prolly` and `tree` packages.
=> [no-release-notes] Replace `tree.NodeBuilder` with `message.Serializer`

go/cmd/dolt/commands/merge.go, integration-tests/bats/constraint-violations.bats
Fixes #3336 
Slightly improves the failure messages for merge. Basically adds a better hint that `dolt conflicts` should be used to investigate and resolve any conflicts.
Before:
```
-> dolt merge right
Updating j2pj08g8rkm8o348fr13vbo9fafv0ck8..rbdk7ovdugbnsnimrjjqq6rbq09idh7p
Auto-merging t
CONFLICT (content): Merge conflict in t
Automatic merge failed; fix conflicts and then commit the result.
-> dolt merge right
error: Merging is not possible because you have unmerged tables.
hint: Fix them up in the working tree, and then use 'dolt add <table>'
hint: as appropriate to mark resolution and make a commit.
fatal: Exiting because of an unresolved conflict.
```
After:
```
-> dolt merge right
Updating j2pj08g8rkm8o348fr13vbo9fafv0ck8..rbdk7ovdugbnsnimrjjqq6rbq09idh7p
Auto-merging t
CONFLICT …
```
=> Improve merge failure messages

go/libraries/doltcore/merge/conflict_splitter.go, go/libraries/doltcore/merge/merge.go, go/libraries/doltcore/merge/row_merge_test.go, integration-tests/bats/conflict-cat.bats
Fixes a one-liner bug where the conflicted rows wouldn't show with the union schema between left, right, and base. Added a bats test as well.
=> Fix `dolt conflicts cat` failing to show conflicted rows in the union-ed schema between left, right, and base.

go/libraries/doltcore/env/actions/reset.go, go/libraries/doltcore/sqle/dfunctions/dolt_reset.go, go/libraries/doltcore/sqle/enginetest/dolt_engine_test.go, go/libraries/doltcore/sqle/enginetest/dolt_queries.go, integration-tests/bats/reset.bats
Closes #3371 
When `dolt reset --hard` is called, it now clears the merge state if set.
=> dolt reset --hard clears any merge state

.github/workflows/ci-go-tests.yaml
Enginetest -race has it's own CI job that is only run on merge main. As part of that PR, I tried to skip enginetest -race during routine PR tests. I mistakenly did the opposite, running only enginetest -race on ubuntu.
=> Only skip engine, not inverse

go/libraries/doltcore/doltdb/durable/conflict_index.go, go/libraries/doltcore/doltdb/durable/index.go, go/libraries/doltcore/doltdb/durable/table.go, go/libraries/doltcore/doltdb/table.go, go/libraries/doltcore/merge/conflict_source.go, go/libraries/doltcore/merge/keyless_integration_test.go, go/libraries/doltcore/merge/merge.go, go/libraries/doltcore/merge/merge_prolly.go, go/libraries/doltcore/merge/merge_prolly_indexes.go, go/libraries/doltcore/merge/merge_test.go, go/libraries/doltcore/merge/mutable_secondary_index.go, go/libraries/doltcore/merge/resolve.go, go/libraries/doltcore/sqle/dtables/table_of_tables_in_conflict.go, go/store/prolly/conflicts_map.go, go/store/prolly/shim.go
- New storage format passes `merge.bats` after this PR except on one test which relies on `MergeStats`. MergeStats is a TODO.
- Adds and implements `durable.ConflictIndex`. 
- Adds conflict handling logic to `mergeTableData`. 
- Fixes a new storage format bug that occurs when the same two tables are added in left and right.
- Moves secondary index merges into its own file for clarity.
When a conflict occurs, we also need to update the secondary indexes so that the left value's index entires are kept post-merge. The edit simply resets the right value.
Resetting values is the inverse of the original operation (Update -> Update, Insert -> Delete, Delete -> Insert). Previously, MutableSecondaryIndex only supported the Update operation, but with conflicts we needed to add all three. In order …
=> [no-release-notes] adds merge conflicts for the new storage format.

go/store/prolly/benchmark/benchmark_read_test.go, go/store/prolly/benchmark/benchmark_write_test.go, go/store/prolly/message/prolly_map.go, go/store/prolly/message/serialize.go, go/store/prolly/mutable_map.go, go/store/prolly/tree/chunker.go, go/store/prolly/tree/chunker_test.go, go/store/prolly/tree/node_builder.go, go/store/prolly/tree/node_cache.go, go/store/prolly/tree/node_splitter.go, go/store/prolly/tree/node_store.go, go/store/skip/list.go
- Adds parallel benchmarks for `prolly.Map.Get()`
- Adds stripe-locked chunk cache to reduce lock-contention on `tree.NodeStore`
- Adds `sync.Pool` for `tree.nodeBuilder`
- Cleans up unneeded allocations on the write path
=> [no-release-notes] go/store/prolly/tree: stripe-locked node store cache

go/libraries/doltcore/dtestutils/environment.go, go/libraries/doltcore/env/multi_repo_env.go, go/libraries/doltcore/sqle/enginetest/dolt_harness.go
DoltHarness was tracking a single DoltEnv for all databases, meaning the DoltDB, working set, etc were shared. After fixing a transaction initialization bug, that fix triggered the tests to start failing because of the DoltDB sharing. 
This change moves DoltHarness to use a MultiRepoEnv for tracking test databases, instead of a single DoltEnv.
=> [no-release-notes] Changing Dolt Harness to track a MultiRepoEnv 

go/cmd/dolt/commands/sqlserver/server_test.go, go/libraries/doltcore/sqle/database_provider.go, go/libraries/doltcore/sqle/dsess/revision_db_provider.go, go/libraries/doltcore/sqle/read_replica_database.go, integration-tests/bats/replication.bats
Read replica pull updates the session working set after pulling a
filtered set of branches from the tracking database. The original
(buggy) implementation updates the working set to the branch specified
at server-start time. The identity of that branch was fixed for the
duration of the server, so dolt_checkout would (appear to) have no
effect on the new branch's working set. What actually happened was more
pernicious: the working set was updated to the value of the
incorrect branch.
The fix no longer statically sets the active branch for a read replica
database. The active branch is pulled from the `*sql.Context`, so the
correct working set will be updated.
Note:
- Changing the remote name or remote endpoint would have a similar static state issue. We could read remote name and remote …
=> Read replica update working set fixes

go/libraries/doltcore/sqle/enginetest/dolt_harness.go, go/libraries/doltcore/sqle/writer/prolly_index_writer.go, go/libraries/doltcore/sqle/writer/prolly_table_writer.go, go/store/prolly/tree/testutils.go, go/store/types/value_store.go, go/store/val/keyless_tuple.go, go/store/val/tuple.go
Fixes a bug in `prollyKeylessWriter` where a cached chunk was being corrupted by an in-place edit to its buffer.
=> [no-release-notes] Fix chunk corruption for keyless tables

go/go.mod, go/go.sum, go/libraries/doltcore/env/actions/commit.go, go/libraries/doltcore/sqle/dtables/unscoped_diff_table.go, go/libraries/doltcore/sqle/enginetest/dolt_engine_test.go, go/libraries/doltcore/sqle/enginetest/dolt_harness.go, go/libraries/doltcore/sqle/enginetest/dolt_transaction_commit_test.go
Every engine test except `TestReadOnlyDatabase` and `TestVersioned` updated to new harness. Remove every use of `harness.NewDatabase`.
=> [no-release-notes] old harness refactors

go/go.mod, go/go.sum, go/libraries/doltcore/sqle/enginetest/dolt_engine_test.go, go/libraries/doltcore/sqle/index/dolt_index.go, go/libraries/doltcore/sqle/writer/prolly_fk_indexer.go, go/libraries/doltcore/sqle/writer/prolly_index_writer.go, go/libraries/doltcore/sqle/writer/prolly_table_writer.go, go/libraries/doltcore/sqle/writer/prolly_write_session.go
We, apparently, don't have any tests for referencing the primary key in a foreign key, so those have been failing in the new format. In addition, some changes ended up breaking new format keyless, which was also not caught due to lack of tests. Both of those issues have been fixed.
Tests have been added to GMS: https://github.com/dolthub/go-mysql-server/pull/1038
=> Fixed foreign key parent referencing + keyless referencing

go/libraries/doltcore/rowconv/field_mapping.go, go/libraries/doltcore/rowconv/row_converter.go, go/libraries/doltcore/sqle/dtables/diff_iter.go, go/libraries/doltcore/sqle/dtables/diff_table.go, go/libraries/doltcore/sqle/dtables/history_table.go, go/libraries/doltcore/sqle/dtables/prolly_row_conv.go, go/libraries/doltcore/sqle/enginetest/dolt_engine_test.go, go/libraries/doltcore/sqle/enginetest/dolt_queries.go
The dolt_diff_{table_name} system table now coerces schema by name only. The dolt_diff table uses the schema at head to interpret the tables at every prior commit. Previously the schema of the table at each prior commit was matched to the head schema using tags with a name fallback. Now it is matched by name only.
Let's consider an example between the new and old behaviors. Define table `t` with the following schema:
```sql
CREATE TABLE t (
pk int PRIMARY KEY,
a text
);
```
In commit1 we insert the following row:
```
INSERT INTO T VALUES (1, 'one');
```
In commit2 we rename col1 to col2:
```
ALTER TABLE T RENAME col1 TO col2
```
In the old behavior, we would see the following diffs. 
Between init and commit1:
```
+ (1, 'one')
```
No diff between commit1 and commit2.
In the new behavior, …
=> change dolt_diff system table to coerce schema by name only

go/libraries/doltcore/sqle/enginetest/validation.go
This validation stage runs after every engine test and asserts consistency between primary and secondary indexes.
For context, this GMS PR added enginetest validation: https://github.com/dolthub/go-mysql-server/pull/1043
=> [no-release-notes] Add `enginetest` validation stage for secondary index consistency

go/cmd/dolt/cli/arg_parser_helpers.go, go/cmd/dolt/commands/backup.go, go/cmd/dolt/commands/remote.go, go/libraries/doltcore/sqle/dfunctions/dolt_backup.go, integration-tests/bats/backup.bats, integration-tests/bats/sql-backup.bats
Adds `sync-url` to the backup command as a way to backup a database without having to add a backup.  This is useful in sql-server mode where you cannot add named backups.
=> dolt backup sync-url

go/store/types/polygon.go
```
geom_db> create table t (p polygon);
geom_db> insert into t values (polygon(linestring(point(1,1),point(2,2),point(3,3),point(1,1)),linestring(point(1,1),point(2,2),point(3,3),point(1,1)));
Query OK, 1 row affected
geom_db> select * from t;
panic in ExchangeIterPartitionRows: runtime error: slice bounds out of range [260:140]
```
fix was just a typo multiplying the index to be way out of range
enginetests for this case in GMS PR
=> fixing panic when creating a polygon with more than one linestring

go/cmd/dolt/commands/tblcmds/import.go, integration-tests/bats/import-create-tables.bats, integration-tests/bats/import-replace-tables.bats, integration-tests/bats/import-update-tables.bats
We should warn the user when executing a partial import as it may have antagonistic behaviors when import files do not properly match a table schema. For example consider a table with the schema (pk, val). If I import a file with schema (pk, va) the second column will get dropped by the importer.
=> Add a warning for imports where the file's schema is smaller than the table's schema

go/libraries/doltcore/sqle/dtables/unscoped_diff_table.go, go/libraries/doltcore/sqle/enginetest/dolt_queries.go, integration-tests/bats/system-tables.bats
The `dolt_diff` system table was returning literal `"NULL"` strings instead of `nil` values. This worked in the enginetests, but when they get printed out in a shell they couldn't be converted into a datetime and produced an error.
=> bugfix: using nils instead of "NULL" strings

go/cmd/dolt/commands/sql.go, integration-tests/bats/sql-branch.bats, integration-tests/bats/sql-spatial-types.bats
While debugging https://github.com/dolthub/dolt/issues/3512 , realized that if a multistatement exec fails during query execution, Dolt doesn't tell you which line failed. Updated the error message to include the failing statement's line and added a bats test for the original customer issue. 
Depends on: https://github.com/dolthub/go-mysql-server/pull/1066
=> Improved error message for multistatement query failing during exec

go/libraries/doltcore/doltdb/root_val.go, go/libraries/doltcore/sqle/history_table.go, go/libraries/doltcore/sqle/index/dolt_index.go, go/libraries/doltcore/sqle/index/dolt_index_test.go, go/libraries/doltcore/sqle/index/index_lookup.go, go/libraries/doltcore/sqle/index/noms_index_iter.go, go/libraries/doltcore/sqle/indexed_dolt_table.go, go/libraries/doltcore/sqle/procedures_table.go, go/libraries/doltcore/sqle/rows.go, go/libraries/doltcore/sqle/schema_table.go, go/libraries/doltcore/sqle/schema_table_test.go, go/libraries/doltcore/sqle/tables.go, go/libraries/doltcore/sqle/temp_table.go, go/libraries/doltcore/sqle/testutil.go
Introduce an instance-local cache which can refresh its value when
the working root of the underlying table changes.
In 4300e8460eccfc999059eca503748766b7327869 we changed DoltIndex
implementations to not store row data. Index implementations are retrieved at
analysis time and used at query time, and storing row data in them breaks
things like static lookups and index joins in things like prepared statements
and stored procedures.
Retrieving the row data from the doltdb.Table instance for every lookup turns
out to have a sizeable performance impact, especially on something like a large
join.
=> go/libraries/doltcore/sqle/index: Cache durable.Index values for primary and secondary data.

go/cmd/dolt/commands/cnfcmds/cat.go, go/libraries/doltcore/doltdb/root_val.go, go/libraries/doltcore/merge/merge.go, integration-tests/bats/merge.bats
This PR fixes `cherry-pick: commit with ALTER TABLE rename table name` flaky bats test. 
`doltdb.UnionTableNames()` method returns inconsistent/randomized ordered array of table names. Renaming table is not tracked when merging, so that it becomes the old name table being dropping and the new table being added. If the tableNames array has old table name first, then the error case is caught, but if the tableNames array has the new table name first, then MergeRoots try to add the exact same table, which returns error of same column tags. 
To avoid this, `doltdb.UnionTableNames()` method now returns unique table names present in order of RootValues passed in.
=> Fix cherry-pick flaky test

README.md
Without the HTTPS prefix, the link went to https://github.com/dolthub/dolt/blob/main/hosted.doltdb.com
=> Fix broken link for hosted dolt in readme.md

integration-tests/MySQLDockerfile
https://packagemanager.rstudio.com maintains binary versions of R packages so one doesn't have to compile them all to install on Linux
=> Speed up client tests by installing pre-compiled R packages

integration-tests/bats/sql-merge.bats
This pr temporarily skips some sql-merge.bats tests that have been causing other prs to be blocked.
=> [no-release-notes] Skip flakey sql-merge.bats tests

go/cmd/dolt/commands/commit.go, go/cmd/dolt/commands/status.go, integration-tests/bats/remotes.bats
Added remote tracking information for dolt status. If the local branch has upstream remote branch, `dolt status` outputs whether the local branch is ahead of, behind, diverged from or up-to-date with the tracked remote branch.
=> Add remote tracking info to dolt status

go/go.mod, go/go.sum, go/store/hash/hash_test.go
```
% go test -bench Benchmark
goos: darwin
goarch: amd64
pkg: github.com/dolthub/dolt/go/store/hash
cpu: Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
BenchmarkSha512-12        172446              6149   ns/op
BenchmarkBlake2-12        313255              3648   ns/op
BenchmarkBlake3-12        467600              2421   ns/op
BenchmarkXXHash-12       9873788               124.2 ns/op
PASS
ok      github.com/dolthub/dolt/go/store/hash   4.943s
```
=> [no-release-notes] Benchmarks for hash perf

go/cmd/dolt/commands/cvcmds/verify_constraints.go, integration-tests/bats/constraint-violations.bats, integration-tests/bats/verify-constraints.bats
Reimplements dolt constraints verify to use the sql path when outputting rows.
=> [no-release-notes] dolt constraints verify for new format

go/utils/publishrelease/buildbinaries.sh, go/utils/publishrelease/install.sh
I tested the build binaries script locally and confirmed it is producing the new `dolt-linux-arm64.tar.gz` artifact. I also ran the install script on an Ubuntu container and verified that it tries to download that same artifact from GitHub, then copied the new artifact over and verified that the dolt binary executes as expected. 
Anything else I need to do to get that new artifact to show up on GitHub in the next release? 
Resolves: https://github.com/dolthub/dolt/issues/3726
=> Build and install for for Linux OS on Mac arm64/aarch64 hardware

.github/workflows/cd-release.yaml
I previously updated the build and install scripts to support Linux OS running on Mac hardware (https://github.com/dolthub/dolt/pull/3727), but I missed this update to the GitHub workflow to copy the new artifact over and make it available on the GitHub release page.
=> Updating release workflow to include new Linux-ARM64 build

go/cmd/dolt/commands/checkout.go, go/cmd/dolt/commands/pull.go, go/libraries/doltcore/env/actions/remotes.go, go/libraries/doltcore/env/actions/table.go, go/libraries/doltcore/env/remotes.go, go/libraries/doltcore/sqle/dfunctions/dolt_checkout.go, go/libraries/doltcore/sqle/dfunctions/dolt_pull.go, go/libraries/doltcore/sqle/dfunctions/dolt_push.go, integration-tests/bats/remotes-file-system.bats, integration-tests/bats/remotes-localbs.bats, integration-tests/bats/remotes-sql-server.bats, integration-tests/bats/remotes.bats, integration-tests/bats/sql-pull.bats, integration-tests/bats/sql-push.bats
This PR fixes inconsistent behaviors of Dolt CLI against Git commands AND of Dolt SQL against Dolt CLI commands.
Inconsistencies between Dolt CLI and Git:
- `dolt checkout new_branch`: checking out a new branch without `-b` flag. If there is a remote branch with matching name, sets upstream.
- `dolt checkout -b new_branch`: if there is a remote branch with matching name, it does not set upstream.
- `dolt pull` and `dolt pull remote_name`: each gives separate errors when run on a branch that does not have upstream
Inconsistencies between Dolt CLI and Dolt SQL:
- `dolt pull` should match `dolt_pull()`
- `dolt_checkout()` and `dolt_push()` should set upstream that persists outside of sql session (added skipped tests)
=> fix inconsistencies of dolt checkout and pull commands

go/libraries/doltcore/sqle/enginetest/dolt_engine_test.go, go/store/prolly/tree/immutable_tree.go, go/store/prolly/tree/immutable_tree_test.go
Blob chunker panic fix. If we want to split at a chunk size of ex: 4000 bytes, then we can only fit 4000/20 hashes into internal nodes.
=> [no-release-notes]Blob internal chunksize different than leaf chunksize

go/libraries/doltcore/table/typed/parquet/reader.go, go/libraries/doltcore/table/typed/parquet/writer.go, integration-tests/bats/export-tables.bats
Fixes https://github.com/dolthub/dolt/issues/3517 
Issues for importing parquet file from Dolt export to pandas.
- Datetime type is exported as timestamp to avoid out of range issues.
- Time type is exported as timedelta to avoid being parsed as time and panics if val is negative
=> fix for datetime and time types for exporting parquet file

go/cmd/dolt/cli/arg_parser_helpers.go, go/cmd/dolt/commands/checkout.go, go/libraries/doltcore/env/remotes.go, integration-tests/bats/remotes.bats
Adds `--track` flag for dolt checkout.
Fixes local branch tracking remote tracking branch with different names
- `dolt checkout --track origin/feature` will create new branch named `feature` and set its upstream to `origin/feature` remote branch
- `dolt checkout -b branch1 --track origin/feature` will create new branch named `branch1` and set its upstream to `origin/feature` remote branch
- `dolt checkout -b branch1 origin/feature` will guess remote branch. If remote branch `origin/feature` exists, it will set upstream to it.
=> Add `--track` flag to dolt checkout

go/libraries/doltcore/sqle/dfunctions/dolt_checkout.go, go/libraries/doltcore/sqle/dsess/session.go, go/libraries/doltcore/sqle/read_replica_database.go, integration-tests/bats/replication.bats, integration-tests/bats/sql-pull.bats, integration-tests/bats/sql.bats
Sql path `dolt_checkout` used to create a new branch from HEAD
if the checkout name did not have a remote tracking ref. The CLI,
on the other hand, will initialize a local branch if a remote tracking
ref with the same name in the default remote exists. The SQl path
now mirrors the CLI checkout: if we checkout a new branch, like
'new_feature', and we have previously fetched that branch from our
default remote, `dolt_checkout('new_feature')` will initialize a branch
using the head commit from the remote `new_feature`.
Second, read replication was creating a local tracking branch for
remote branches (sourced from the master remote), but not creating
corresponding working sets. This let users attach to new branches with
`use db/new_feature` syntax, but prevented users from …
=> dolt_checkout and read replication working set fixes

go/go.mod, go/go.sum, integration-tests/bats/sql-privs.bats
tests for: https://github.com/dolthub/dolt/issues/3859
companion pr: https://github.com/dolthub/go-mysql-server/pull/1124
=> bats tests for reading `privs.json` and converting

go/cmd/dolt/commands/diff.go, go/libraries/doltcore/diff/async_differ.go, go/libraries/doltcore/diff/diff_summary.go, go/libraries/doltcore/diff/table_deltas.go, go/libraries/doltcore/merge/merge_rows.go, go/libraries/doltcore/merge/merge_schema.go, go/libraries/doltcore/merge/schema_integration_test.go, go/libraries/doltcore/merge/violations_fk.go, go/libraries/doltcore/schema/schema.go, go/libraries/doltcore/sqle/dtables/diff_iter.go, go/libraries/doltcore/sqle/dtables/diff_table.go, go/libraries/doltcore/sqle/enginetest/dolt_engine_test.go, go/libraries/doltcore/sqle/enginetest/dolt_queries.go, integration-tests/bats/schema-changes.bats
=> [no-release-notes] In __DOLT_1__, throw error if schemas have different primary key types

go/utils/remotesrv/main.go
Signed-off-by: Abirdcfly <fp544037857@gmail.com>
log.Fatalln is equivalent to Println() followed by a call to os.Exit(1).
see example:
https://go.dev/play/p/VcdbrSNK6wH
```go
package main
import (
"log"
"os"
)
func main() {
log.Fatalln("A")
log.Fatalln("B") // unreachable code
os.Exit(2)
}
/* output:
2009/11/10 23:00:00 A
Program exited.
*/
```
=> fix minor log.Fatalln output

go/cmd/dolt/dolt.go, go/libraries/doltcore/sqle/dsess/session.go, go/libraries/doltcore/sqle/dsess/variables.go, integration-tests/bats/sql-server.bats
Fix for https://github.com/dolthub/dolt/issues/3887
Persisting and loading `${branch_name}_default_branch` from config now works.
=> Fix for persisted database specific system variables failing to load

go/cmd/dolt/commands/log.go, go/cmd/dolt/commands/migrate.go, go/libraries/doltcore/doltdb/commit.go, go/libraries/doltcore/doltdb/doltdb.go, go/libraries/doltcore/doltdb/doltdb_test.go, go/libraries/doltcore/doltdb/root_val.go, go/libraries/doltcore/migrate/environment.go, go/libraries/doltcore/migrate/migrate.go, go/libraries/doltcore/migrate/progress.go, go/libraries/doltcore/migrate/transform.go, go/libraries/doltcore/migrate/traverse.go, go/libraries/doltcore/migrate/validation.go, go/libraries/doltcore/rebase/rebase.go, go/libraries/doltcore/sqle/json/noms_json_value_test.go, go/libraries/utils/filesys/fs.go, go/libraries/utils/filesys/fs_test.go, go/libraries/utils/filesys/inmemfs.go, go/libraries/utils/filesys/localfs.go, go/store/cmd/noms/noms_show_test.go, go/store/hash/hash.go, go/store/nbs/frag/main.go, go/store/types/map.go, go/store/types/ref.go, go/store/types/value_store.go, integration-tests/bats/helper/common.bash, integration-tests/bats/migrate.bats
implements a format migration for top-of-DAG objects from `__LD_1__` to `__DOLT_DEV__`
=> [no-release-notes] `__DOLT_DEV__` Migration

go/cmd/dolt/commands/pull.go, go/libraries/doltcore/env/actions/remotes.go, go/libraries/doltcore/env/remotes.go, go/libraries/doltcore/sqle/dfunctions/dolt_pull.go, integration-tests/bats/remotes.bats, integration-tests/bats/sql-pull.bats
Adds support for explicitly specifying the remote branch to merge into the current working head. 
I was tempted to work on combining these two duplicated code paths, but wanted to keep scope small and get several bugs fixed before taking that on. 
Fixes: https://github.com/dolthub/dolt/issues/3937
Documentation updates: https://github.com/dolthub/docs/pull/811
=> Add command line and SQL support for `dolt pull <remote> <remoteBranch>`

go/cmd/dolt/commands/engine/sqlengine.go, go/cmd/dolt/commands/engine/utils.go, go/cmd/dolt/commands/filter-branch.go, go/libraries/doltcore/sqle/database_provider.go, go/libraries/doltcore/sqle/dprocedures/dolt_remote.go, go/libraries/doltcore/sqle/dsess/revision_db_provider.go, go/libraries/doltcore/sqle/dsess/session_state_adapter.go, go/libraries/doltcore/sqle/dtables/remotes_table.go, go/libraries/doltcore/sqle/enginetest/dolt_harness.go, go/libraries/doltcore/sqle/enginetest/dolt_queries.go, go/libraries/doltcore/sqle/index/mergeable_indexes_setup_test.go, go/libraries/doltcore/sqle/logictest/dolt/doltharness.go, go/libraries/doltcore/sqle/show_create_table.go, go/libraries/doltcore/sqle/testutil.go, integration-tests/bats/remotes.bats
Changes DoltDatabaseProvider to track a Filesystem location for each database it manages. This allows callers, like the `dolt_remote` stored procedure to find the correct root directory for a database and update repo state correctly. 
Fixes #3936
=> Fix `dolt_remote` stored procedure to write to the correct database directory

go/libraries/utils/filesys/localfs.go, integration-tests/bats/remotes-file-system.bats
The problem with this is code is that the path gets interpreted as `C:/poop` which is valid to create directory on. In a unix system creating a`/poop` would be blocked without sudo permissions. It's likely that our ci system is using some administrator setting giving easier access. I'm not really sure if this is a valid testcase anymore cc: @bheni
=> [no-release-notes] Skip windows bats test

go/cmd/dolt/commands/clone.go, go/cmd/dolt/commands/clone_test.go, go/libraries/doltcore/env/remotes.go
This pr supports `dolt clone` for  `https://www.dolthub.com/repositories/..` databases
=> Clone Dolthub Links

go/libraries/doltcore/diff/table_deltas.go, go/libraries/doltcore/diff/table_deltas_test.go
Before this fix, tables with different names would attempted to be matched even if there was a pair of tables with a matching name.
=> Fix indeterministic diff delta matching

go/libraries/doltcore/schema/schema.go, go/libraries/doltcore/schema/schema_test.go, integration-tests/bats/diff.bats
Fixes #4037
The ordering of the primary key columns in returned by Schema.GetAllCols() should not determine diffability.
If and only if the primary key tags, their ordinal ordering, and their types (in the new format) are equal, two schemas are diffable.
Schema.GetPkCols() always returns the columns in ordinal order:
https://github.com/dolthub/dolt/blob/ad471682829fc379c95a41eb23f26c00cad0e099/go/libraries/doltcore/schema/schema_test.go#L106-L145
=> Dropping a non-pk column that is before a primary key column should be diffable.

go/cmd/dolt/cli/arg_parser_helpers.go, go/cmd/dolt/commands/init.go, go/cmd/dolt/commands/version.go, go/libraries/doltcore/env/multi_repo_env.go, go/libraries/doltcore/sqle/dfunctions/init.go, go/libraries/doltcore/sqle/dfunctions/storage_format.go, go/libraries/doltcore/sqle/enginetest/dolt_engine_test.go, go/utils/repofmt/check_prepared_tests.sh, integration-tests/bats/conflict-detection.bats, integration-tests/bats/drop-create.bats, integration-tests/bats/garbage_collection.bats, integration-tests/bats/helper/common.bash, integration-tests/bats/import-create-tables.bats, integration-tests/bats/index.bats, integration-tests/bats/init.bats, integration-tests/bats/json.bats, integration-tests/bats/merge.bats, integration-tests/bats/migrate.bats, integration-tests/bats/migration-integration.bats, integration-tests/bats/multidb.bats, integration-tests/bats/remotes-aws.bats, integration-tests/bats/schema-changes.bats, integration-tests/bats/sql-server.bats, integration-tests/bats/sql.bats
- Adds `--new-format` to `dolt init`. For example:
```
$ dolt init --new-format
```
- Adds storage format information to `dolt version`. For example:
```
$ dolt version
dolt version 0.40.24
database storage format: OLD ( __LD_1__ )
```
We considered making a separate command called `dolt storage_format`, but decided against it to promote discoverability of the current storage format that dolt is using.
- Adds a new sql function that returns the format used by the currently selected database. For example:
```
> SELECT dolt_storage_format();
+-----------------------+
| dolt_storage_format() |
+-----------------------+
| NEW ( __DOLT__ )      |
+-----------------------+
```
- `dolt_version()` is unchanged:
```
> SELECT dolt_version();
+----------------+
| dolt_version() |
+----------------+ …
```
=> Add storage format information to `dolt version` and add new sql function `dolt_storage_format()`. Add dolt init --new-format

go/libraries/doltcore/sqle/database_provider.go, integration-tests/bats/sql.bats
Fixes https://github.com/dolthub/dolt/issues/4030
Wrote a bats based on the repro in the issue, but there's an [unrelated panic](https://github.com/dolthub/dolt/issues/4067) causing the test to fail
```
taylor@MacBook-Pro-3 us-jails % dolt sql
us_jails> select * from dolt_log limit 1;
+----------------------------------+---------------+---------------------+-------------------------+-----------+
| commit_hash                      | committer     | email               | date                    | message   |
+----------------------------------+---------------+---------------------+-------------------------+-----------+
| gmlgmb9vp91a0hjpk35v54t0j43dshlf | Taylor Bantle | taylor@liquidata.co | 2022-08-11 20:16:43.467 | new table |
+----------------------------------+---------------+---------- …
```
=> Prevent `use [db]/[tag]` from creating duplicate revision db

go/cmd/dolt/commands/sqlserver/sqlserver.go, go/libraries/utils/argparser/option.go, go/libraries/utils/argparser/parser.go, integration-tests/bats/sql-server.bats
`--socket` flag can be defined without value, which should get default value of `/tmp/mysql.sock`
To allow empty string as value, added a new arg option type.
=> allow optional empty value for string value for arg parsing

go/store/datas/pull/puller.go, go/store/nbs/byte_sink.go, go/store/nbs/cmp_chunk_table_writer.go, go/store/nbs/gc_copier.go, go/store/nbs/store.go
In `NBSStore.WriteTableFile`, the code used to open the destination path with `O_TRUNC`, without checking in the file already exists or performing any synchronization with concurrent processes. It did this even before even calling `getRd()` to see if it would return an error.
As a result, a race condition exists, where a file gets written to the table file store and added to the manifest and then a later process calls `WriteTableFile` with that same filename and the file gets truncated. This is most likely to happen if there are two concurrent pulls for the same content, which will result in building up the same table files. One of the writes will win, and the later write will lose, but will still truncate the table file. In turn, this pull behavior is most likely to happen if you are a …
=> go/store/{nbs,datas/pull}: Fix race condition in concurrent pulls which can truncate a table file.

integration-tests/bats/sql-server.bats
We had a skipped BATS test for `dolt_commit` being disallowed, but `dolt_reset` also needs one since it modifies the branch HEAD.
=> Adding a skipped bats test for dolt_reset being disallowed in read-only mode

go/cmd/dolt/commands/dump_docs.go
Change the output of `dolt dump-docs` so that [the CLI reference docs](https://docs.dolthub.com/cli-reference/cli) will list commands in alphabetical order.
=> [no-release-notes] Sort subcommands in `dolt dump-docs` CLI reference output

go/libraries/doltcore/sqle/database_provider.go, integration-tests/bats/init.bats
`CREATE DATABASE` on new-format DB should create DB with new-format(same format as the currentDB)
=> create db with specific format depending on currentDB format

go/store/nbs/byte_sink.go, go/store/nbs/byte_sink_test.go
The buffered byte sink finish() implementation was expected to only be called,
but Reader() could be called multiple times for a retried upload.
=> go/store/nbs: byte_sink.go: Fix panic in some cases when we retry table file upload in push.

go/libraries/doltcore/doltdb/doltdb.go, go/libraries/doltcore/sqle/database_provider.go, go/libraries/doltcore/sqle/dfunctions/hashof.go, go/libraries/doltcore/sqle/enginetest/dolt_queries.go
Enables use of `~` and `^` to reference ancestors in database revision specifiers. 
Fixes: https://github.com/dolthub/dolt/issues/2146
=> Add support for ancestor references in database revision specifiers

go/libraries/doltcore/sqle/enginetest/dolt_queries.go, go/libraries/doltcore/table/typed/noms/range_reader.go, go/store/types/tuple.go, go/store/types/tuple_test.go
`Tuple.Compare` / `Tuple.Less` returns inconsistent results when comparing different types against a null value. This caused non-null values for most types to be ordered before null values, but other types like time/date/datetime to have non-null values _after_ null values in the index. That resulted in incorrect query execution because the index range reader saw the null values and exited out before ever evaluating the non-null values. 
Fixes: https://github.com/dolthub/dolt/issues/4199
=> Bug fix for Tuple.Compare to return consistent results when comparing against a null value

integration-tests/bats/sql-charsets-collations.bats
These tests can be unskipped when https://github.com/dolthub/go-mysql-server/pull/1224 makes it into Dolt.
=> Added skipped tests for charcter set matching tests back

go/libraries/doltcore/env/actions/branch.go, go/libraries/doltcore/env/environment.go, go/libraries/doltcore/sqle/dfunctions/dolt_branch.go, go/libraries/doltcore/sqle/dtables/branches_table.go, go/libraries/doltcore/sqle/enginetest/dolt_harness.go, go/libraries/doltcore/sqle/enginetest/dolt_queries.go, integration-tests/bats/deleted-branches.bats, integration-tests/bats/replication.bats, integration-tests/bats/sql-batch.bats, integration-tests/bats/sql-server.bats, integration-tests/bats/system-tables.bats
In sql session, if the current head on CLI is deleted, the repostate head is empty branch ref. 
If the current head on CLI is renamed, the repostate head is updated with new branch ref.
`dolt_branches` table is read-only now.
=> allow init with empty working set

go/libraries/doltcore/sqle/dtables/unscoped_diff_table.go, go/libraries/doltcore/sqle/enginetest/dolt_queries.go
This improves select query on unscoped `dolt_diff` table in old format for `commit_hash` column filter
=> use commitItr instead of commitwalk for querying dolt_diff table

go/libraries/doltcore/sqle/enginetest/dolt_queries.go, go/libraries/doltcore/sqle/history_table.go
Closes: https://github.com/dolthub/dolt/issues/4279
`sql.enumtype` contains a map, which in golang cannot be used in `==` operator
=> fix enum panics in history table

go/cmd/dolt/commands/commit.go, go/gen/fb/serial/workingset.go, go/libraries/doltcore/doltdb/system_table.go, go/libraries/doltcore/doltdb/workingset.go, go/libraries/doltcore/dtestutils/testcommands/command.go, go/libraries/doltcore/env/environment.go, go/libraries/doltcore/env/environment_test.go, go/libraries/doltcore/merge/action.go, go/libraries/doltcore/sqle/database.go, go/libraries/doltcore/sqle/dfunctions/dolt_merge.go, go/libraries/doltcore/sqle/dtables/merge_status_table.go, go/libraries/doltcore/sqle/enginetest/dolt_queries.go, go/serial/workingset.fbs, go/store/datas/dataset.go, go/store/datas/workingset.go, integration-tests/bats/merge.bats, integration-tests/bats/reset.bats
Closes https://github.com/dolthub/dolt/issues/3504
The `dolt_merge_status` system table tells a user if a merge is active. It has the following schema:
```sql
CREATE TABLE `dolt_merge_status` (
-- Whether a merge is currently active or not
`is_merging` tinyint NOT NULL, 
-- The commit spec that was used to initiate the merge
`source` text,
-- The commit that the commit spec resolved to at the time of merge
`source_commit` text, 
-- The target destination working set
`target` text, 
-- A list of tables that have conflicts or constraint violations
`unmerged_tables` text 
)
```
For example, lets create a simple conflict:
```bash
dolt sql -q "CREATE TABLE t (a INT PRIMARY KEY, b INT);"
dolt add .
dolt commit -am "base"
dolt checkout -b right
dolt sql <<SQL
ALTER TABLE t ADD c INT;
INSERT INTO …
```
=> Adds `dolt_merge_status` system table

go/libraries/doltcore/table/untyped/csv/reader.go, integration-tests/bats/import-update-tables.bats
Closes: https://github.com/dolthub/dolt/issues/4209
=> add nil check for string pointers during dolt table import

go/store/prolly/range_iter.go, go/store/skip/list.go, go/store/skip/list_test.go
Improves `skip.List` performance for large lists by increasing max tower height from 5 to 10, and decreasing height-promotion probabilities.
before:
```
BenchmarkList
BenchmarkList/benchmark_Get
BenchmarkList/benchmark_Get/n=64
BenchmarkList/benchmark_Get/n=64-12    	 6292303	       217.8 ns/op	       0 B/op	       0 allocs/op
BenchmarkList/benchmark_Get/n=512
BenchmarkList/benchmark_Get/n=512-12   	 4007974	       311.6 ns/op	       0 B/op	       0 allocs/op
BenchmarkList/benchmark_Get/n=4096
BenchmarkList/benchmark_Get/n=4096-12  	 2511993	       513.4 ns/op	       0 B/op	       0 allocs/op
BenchmarkList/benchmark_Get/n=32768
BenchmarkList/benchmark_Get/n=32768-12 	 1265131	       869.2 ns/op	       0 B/op	       0 allocs/op
BenchmarkList/benchmark_Put
BenchmarkList/benchmark_Put/n=64 …
```
=> [no-release-notes] Document and refactor `skip.List`

go/go.mod, go/go.sum, go/store/prolly/benchmark/benchmark_batch_writes_test.go, go/store/prolly/benchmark/benchmark_read_test.go, go/store/prolly/benchmark/utils_test.go
`Put()` latency for each row in a batch import of 65K rows (`Flush()` work amortized)
```
% go test -bench BenchmarkImport                               
goos: darwin
goarch: amd64
pkg: github.com/dolthub/dolt/go/store/prolly/benchmark
cpu: Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
BenchmarkImportBBolt/BBolt-12             427561              5794 ns/op
BenchmarkImportDolt/Dolt-12               680004              3575 ns/op
PASS
ok      github.com/dolthub/dolt/go/store/prolly/benchmark       5.613s
```
=> [no-release-notes] Benchmark Dolt against BBolt for batch writes

go/cmd/dolt/commands/diff.go, integration-tests/bats/diff.bats
Closes #790 
Adds a `--skinny` flag to `dolt diff`, which only shows primary keys and columns with changes.
Note that `writeDiffResults` has been split into 2 functions - `writeFilteredRows` and `getDiffRows`. The former is responsible for printing the rows, while the latter function collects the relevant columns, depending on if the `--skinny` flag is active.
Also note that in the event of row addition/deletions, all columns will be included when the `--skinny` flag is active.
=> Add dolt diff --skinny flag

go/libraries/doltcore/sqle/database_provider.go, integration-tests/bats/sql-server.bats
If there is no current database selected, use databases that are available within the session and use the common format for those databases.
=> create db when no current db is set should use the dbs available in session

go/libraries/doltcore/remotesrv/dbcache.go, go/libraries/doltcore/remotesrv/grpc.go, go/libraries/doltcore/remotesrv/http.go, go/libraries/doltcore/remotesrv/server.go, go/utils/remotesrv/cscache.go, go/utils/remotesrv/main.go, integration-tests/bats/remotesrv.bats
Adds some functionality to remotesrv:
* `-http-port` and `-grpc-port` can be the same, in which case there is only one listener and both gRPC and file server traffic are served over the same port.
* the grpc server will echo the incoming request's `:authority` header, with the supplied `-http-port`, if no `-http-host` is supplied. Changes the default behavior of `remotesrv` to be that, rather than generating URLs with an authority component containing `localhost` as the hostname.
=> go/utils/remotesrv: Make remotesrv implementation into a library which can be used from dolt proper.

go/cmd/dolt/commands/sqlserver/sqlserver.go, integration-tests/bats/sql-privs.bats
Closes: https://github.com/dolthub/dolt/issues/4333
=> cmd user/password arguments always override yaml config

go/cmd/dolt/commands/sqlserver/logformat.go, go/cmd/dolt/commands/sqlserver/server.go, go/cmd/dolt/commands/sqlserver/serverconfig.go, go/cmd/dolt/commands/sqlserver/sqlserver.go, go/cmd/dolt/commands/sqlserver/yaml_config.go, go/cmd/dolt/commands/sqlserver/yaml_config_test.go, go/libraries/doltcore/remotesrv/grpc.go, go/libraries/doltcore/remotesrv/http.go, go/libraries/doltcore/remotesrv/server.go, go/libraries/doltcore/sqle/remotesrv.go, go/store/nbs/store.go, go/utils/remotesrv/main.go, integration-tests/bats/sql-server-remotesrv.bats
`dolt sql-server` gets a new configuration option, `--remotesapi-port`, which if supplied will cause the sql-server process to run a remotesapi service. The service will expose the databases in the sql-server for access as a dolt remote from a dolt CLI or sql-server process.
Includes the following changes in the behavior of `go/utils/remotesrv`:
* `go/utils/remotesrv` now logs with logrus
* `go/utils/remotesrv` can serve gRPC and HTTP traffic over the same port.
* `go/utils/remotesrv` gRPC service, when generating file server URLs, will echo the request's `:authority` header as the hostname component of the host URL component if `-http-host` is not supplied. This changes the old default, which was `localhost`.
=> sql-server: Let sql-server expose a remotesapi service to allow cloning, fetching and read replication from its databases.

go/Godeps/LICENSES, go/cmd/dolt/cli/arg_parser_helpers.go, go/cmd/dolt/commands/commit.go, go/libraries/doltcore/sqle/dfunctions/dolt_commit.go, go/libraries/doltcore/sqle/enginetest/dolt_engine_test.go, go/libraries/doltcore/sqle/enginetest/dolt_queries.go, integration-tests/bats/commit.bats
`-A` adds all tables (including new tables) to the staged set before committing.
Closes #4309
=> Add -A (--ALL) to `dolt commit` and `CALL DOLT_COMMIT`

go/cmd/dolt/commands/diffsplitter.go, go/cmd/dolt/commands/diffsplitter_test.go
Fixes #4326 
- Fix a bug in `splitDiffResultRow` where a key existence is not being checked in a map. Specifically, `ds.fromTo[i]]` defaulted to `0` (the zero value for `int`) in the case where `i` did not exist as a key in `ds.fromTo`.
=> Fix bug in colDiffs

go/libraries/doltcore/sqle/database_provider.go, go/libraries/doltcore/sqle/dsess/variables.go, go/libraries/doltcore/sqle/read_replica_database.go, go/libraries/doltcore/sqle/system_variables.go, integration-tests/bats/replication.bats
This adds `@@global.dolt_read_replica_force_pull`, which will turn read replica fetches into force pulls, allowing a read replica to true-up with a remote which has experienced a force push.
=> go/libraries/doltcore/sqle: ReadReplicaDatabase: Add variable for force pulling remote branches.

go/cmd/dolt/commands/clone.go, go/cmd/dolt/commands/push.go, go/libraries/doltcore/dbfactory/grpc.go, go/libraries/doltcore/dtestutils/testcommands/multienv.go, go/libraries/doltcore/env/actions/remotes.go, go/libraries/doltcore/remotesrv/dbcache.go, go/libraries/doltcore/remotesrv/grpc.go, go/libraries/doltcore/remotesrv/http.go, go/libraries/doltcore/remotestorage/chunk_store.go, go/libraries/doltcore/sqle/database_provider.go, go/libraries/doltcore/sqle/dfunctions/dolt_push.go, go/libraries/doltcore/sqle/remotesrv.go, go/utils/remotesrv/cscache.go, go/utils/remotesrv/main.go, integration-tests/bats/sql-server-remotesrv.bats
This uses the repo_path parameter to allow single and 3+ path component paths for repository names.
=> remotestorage,remotesrv: Be less restrictive in repository paths for remotesapi repos that are not served through dolthub.

go/libraries/doltcore/sqle/sqlutil/sql_row.go
Related PR: https://github.com/dolthub/go-mysql-server/pull/1278
Since the `SQL` methods for `Point`, `LineString`, `Polygon`, and `Geometry` no longer return the hex formatted string, need to do a little extra work for prettier shell output.
=> print spatial types as hex in shells only

go/libraries/doltcore/sqle/enginetest/dolt_engine_test.go, go/libraries/doltcore/sqle/enginetest/dolt_queries.go, integration-tests/mysql-client-tests/node/concurrency.js
Fix for: https://github.com/dolthub/dolt/issues/4392
=> adding prepared tests for dolt stored procedures

README.md, go/Godeps/LICENSES, go/cmd/dolt/commands/diff.go, go/libraries/doltcore/dbfactory/oss.go, go/libraries/doltcore/sqle/dolt_diff_table_function.go, go/libraries/doltcore/sqle/enginetest/ddl_queries.go, go/libraries/doltcore/sqle/enginetest/dolt_queries.go
This PR updates argument ordering of `dolt_diff()` table function to match `dolt_diff_summary()` table function, which matches CLI command argument order.
=> reorder arguments of dolt_diff() table function

go/libraries/doltcore/sqle/database_provider.go, integration-tests/bats/sql-server.bats
This PR fixes two issues:
- if the server is running in the database itself, the database can be dropped regardless of being selected database.
- drop database with '-' in dir name and '_' in database name.
=> allow drop current database directory and fix drop db with '-'

go/cmd/dolt/commands/sqlserver/server.go, go/cmd/dolt/commands/sqlserver/serverconfig.go, integration-tests/bats/sql-server-remotesrv.bats, integration-tests/bats/sql-server.bats
Initial implementation of unix socket has opt-in feature for unix socket support. The default of mysql unix socket when socket flag is not defined is when host is defined as 'localhost' or undefined.
=> turn off opt-in feature for unix socket

go/libraries/doltcore/migrate/progress.go, go/libraries/doltcore/migrate/traverse.go
The commit mapping is persisted as dangling chunks. We don't expect it to remain after a GC and it will not be picked up during a push or pull.
=> Persist a commit mapping to the chunkstore after migration

go/store/datas/pull/puller.go
^ prevents the push / pull progress reporter from reporting very small BP/s units.
=> store/datas/pull: If the BPS is less than 1, report 0

go/libraries/doltcore/sqle/database_provider.go, integration-tests/bats/system-tables.bats
=> go/doltcore/sqle: Initialize remotes, backups, and branch config when constructing revision databases

go/cmd/dolt/commands/sqlserver/sqlserver.go
Replaces an incorrect ` ' ` character with the correct `` ` `` character.
The current code results in [broken docs html](https://docs.dolthub.com/cli-reference/cli#text-dolt-sql-server):
=> Replace incorrect character.

integration-tests/bats/helper/query-server-common.bash, integration-tests/bats/sql-jwt-auth.bats, integration-tests/bats/sql-privs.bats, integration-tests/bats/sql-server.bats, integration-tests/mysql-client-tests/mysql-client-tests.bats, integration-tests/orm-tests/orm-tests.bats
fixed in bats testing:
- if PORT in use, get the next unused PORT number when starting a sql-server
- kill a process only if it's still running when stopping a sql-server
=> get next port number if random port is in use

go/cmd/dolt/commands/engine/sqlengine.go, go/cmd/dolt/commands/sql.go, go/cmd/dolt/commands/sqlserver/serverconfig.go, go/cmd/dolt/commands/sqlserver/sqlserver.go, go/cmd/dolt/commands/sqlserver/yaml_config.go, go/libraries/doltcore/branch_control/access.go, go/libraries/doltcore/branch_control/binlog.go, go/libraries/doltcore/branch_control/branch_control.go, go/libraries/doltcore/branch_control/expr_parser.go, go/libraries/doltcore/branch_control/namespace.go, go/libraries/doltcore/sqle/dtables/binlog_table.go, go/libraries/doltcore/sqle/dtables/branch_control_table.go, go/libraries/doltcore/sqle/dtables/branch_namespace_control.go, go/libraries/doltcore/sqle/tables.go
This fixes a few issues found through testing, and also adds persistence for the tables. Also re-added the `binlog_table.go` file. I originally removed it, but misread the feedback that said to not expose it rather than to remove it.
=>  Branch Control Pt. 6

go/libraries/doltcore/sqle/enginetest/branch_control_test.go
Tests for branch control tables. Things left to do:
* Bats tests
* Logic and tests for the rest of the dolt procedures
* Moving the tables into the context
* Support for roles
=> Branch Control Pt. 7

go/libraries/doltcore/diff/column_identity_test.go, go/libraries/doltcore/doltdb/root_val.go, go/libraries/doltcore/schema/tag.go
During diff and merge operations, it is necessary to resolve table and column identity create an entity mapping between Dolt root values (logical databases). Currently, table and column identity is determined by [column tags](https://github.com/dolthub/dolt/blob/main/go/libraries/doltcore/schema/column.go#L65). During DDL operations, we make some effort to instantiate column tags such that common operations "just work". However, when these heuristics fails, the results can be hard to debug and the errors are often opaque to users. (See #4406 and #4526).
This PR includes (unimplemented) tests specifying new matching behavior. The proposed change would match tables and columns using only the SQL schema and table data.
=> [no-release-notes] Spec for Table, Column matching

go/libraries/doltcore/sqle/database_provider.go, go/libraries/doltcore/sqle/dolt_log_table_function.go, go/libraries/doltcore/sqle/enginetest/dolt_engine_test.go, go/libraries/doltcore/sqle/enginetest/dolt_queries.go
Supports `select * from dolt_log(<revision>)` (`<revision>` is optional). Adding more options in a follow up PR
=> Add basic `dolt_log` table function

.github/workflows/cd-release.yaml, docker/Dockerfile, docker/Dockerfile.arm64, docker/README.md, docker/hooks/post_checkout, docker/hooks/post_push, docker/hooks/pre_build
Added Docker Image for `linux/arm64` addition to `linux/amd64` architecture. Each will be pushed to DockerHub as separate tags, but both image will be available for `latest` or `<release_version>` tags.
=> Add Docker Image support for `linux/arm64`

go/libraries/doltcore/merge/merge_rows.go, go/libraries/doltcore/merge/merge_schema.go, go/libraries/doltcore/merge/schema_integration_test.go, integration-tests/bats/schema-changes.bats
This PR fixes a panic that occurs when merging tables that define a check constraint using some string literal. The panic's stacktrace is:
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x10 pc=0x10193c7f8]
goroutine 1 [running]:
github.com/dolthub/go-mysql-server/sql/parse.convertVal(0x0?, 0x14000e80520)
/Users/dhruv/go/pkg/mod/github.com/dolthub/go-mysql-server@v0.12.1-0.20221018190947-3e6ea0fb9c2b/sql/parse/parse.go:3392 +0x658
github.com/dolthub/go-mysql-server/sql/parse.ExprToExpression(0x0, {0x10282ae00?, 0x14000e80520?})
/Users/dhruv/go/pkg/mod/github.com/dolthub/go-mysql-server@v0.12.1-0.20221018190947-3e6ea0fb9c2b/sql/parse/parse.go:3100 +0x1ee4 …
```
=> Fix panic when merging tables that have a check constraint with some string literal

integration-tests/bats/helper/query-server-common.bash, integration-tests/bats/sql-server.bats
I noticed some errors with grep syntax in a failed BATS test. Looks like we just had an empty env var so there wasn't anything passed to `grep`, which caused errors and prevented us from fully checking if a port is in use.
=> Fixing variable name in `getPORT` helper function

go/cmd/dolt/commands/sqlserver/server.go, go/libraries/doltcore/remotesrv/grpc.go, go/libraries/doltcore/remotesrv/http.go, go/libraries/doltcore/remotesrv/sealer.go, go/libraries/doltcore/remotesrv/sealer_test.go, go/libraries/doltcore/remotesrv/server.go, go/utils/remotesrv/main.go, integration-tests/bats/sql-server-remotesrv.bats
This will allow us to add authn/z to the gRPC layer.
=> go/libraries/doltcore/remotesrv: Add a symmetric key encryption layer to seal URL returned from the gRPC service an unseal them in the HTTP service.

go/libraries/doltcore/env/actions/infer_schema.go, go/libraries/doltcore/env/actions/infer_schema_test.go, integration-tests/bats/import-create-tables.bats, integration-tests/bats/schema-import.bats
There was a change added that [samples the rows](https://github.com/dolthub/dolt/pull/4471/files) when doing large imports, but this can incorrectly give columns a `NOT NULL` constraint. We can either not sample tables or just not apply the `NOT NULL` constraintl. I chose to not apply the `NOT NULL` constraint. Additionally, the sampling change makes it possible to incorrectly make certain columns `UNISIGNED INT`, when they contain negative numbers. I changed it so infer will always treat columns as signed, so integers that are too large/small for signed int will become strings.
fix for: https://github.com/dolthub/dolt/issues/4620
=> more permissive constraints and types when importing

integration-tests/bats/sql-privs.bats
Give the server a chance to start up. Was failing weirdly on my Mac without this.
=> Add sleeps to a couple bats tests that were starting a SQL Server

go/libraries/doltcore/sqle/dolt_diff_summary_table_function.go, go/libraries/doltcore/sqle/dolt_diff_table_function.go, go/libraries/doltcore/sqle/enginetest/dolt_queries.go
Two dot: `dolt_diff_summary('main..feature', 'table')` (equivalent to `dolt_diff_summary('main', 'feature', 'table')`)
Three dot: `dolt_diff_summary('main...feature', 'table')`
=> Support two and three dot syntax in `dolt_diff_summary` table function

go/gen/fb/serial/rootvalue.go, go/go.mod, go/go.sum, go/libraries/doltcore/doltdb/root_val.go, go/libraries/doltcore/schema/collation.go, go/libraries/doltcore/schema/collation_comparator.go, go/libraries/doltcore/schema/schema_impl.go, go/libraries/doltcore/sqle/database.go, go/libraries/doltcore/sqle/database_provider.go, go/libraries/doltcore/sqle/enginetest/dolt_engine_test.go, go/libraries/doltcore/sqle/sqlselect_test.go, go/libraries/doltcore/sqle/sqlutil/schema.go, go/serial/rootvalue.fbs, go/store/datas/database.go, go/store/datas/database_common.go, integration-tests/bats/migration-integration.bats, integration-tests/bats/sql-charsets-collations.bats
This allows setting the database collation, such that all newly created tables within a database (that do not explicitly set their collation) will inherit the database collation.
Builds on
* https://github.com/dolthub/vitess/pull/199
* https://github.com/dolthub/go-mysql-server/pull/1351
Fixes
* https://github.com/dolthub/dolt/issues/4170
=> Added database collation support

go/libraries/doltcore/doltdb/foreign_key_coll.go
If we have committed tables before [this](https://github.com/dolthub/dolt/pull/4583) change, where the tables have a foreign key that references an index that could've been replace with an existing primary key, apply those changes, and we drop and recreate the parent/child tables in exactly the same way, we stage the parent table, but not the child table, which causes our foreign keys to enter a bad state.
repro for clarity:
```shell
// SWITCH TO DOLT v0.50.8
rm -rf .dolt
dolt init
dolt sql -q "create table payment(payment_id int primary key);"
dolt sql -q "create table subscription(id int primary key, payment_id int);"
dolt sql -q "alter table subscription add constraint subscription_pm_fk foreign key (payment_id) references payment(payment_id);"
dolt add .
dolt commit -m "commit from …
```
=> deeper comparison for foregin key indexes

go/store/val/codec.go
Previously, the year encoding did not support a value of 0. It now uses uint8 255 to represent 0 since that value is free in the encoding space.
Companion GMS PR:
https://github.com/dolthub/go-mysql-server/pull/1395
=> go/store/val: allow year encoding to store value 0

go/libraries/doltcore/env/actions/clone.go, go/libraries/doltcore/env/environment.go, go/libraries/doltcore/env/paths.go
Currently there is an issue where if you run something like:
```DOLT_ROOT_PATH=. dolt backup restore <remote> subfolder/reponame```
This fixes that by returning the absolute path.
=> fix DOLT_ROOT_PATH bug

go/cmd/dolt/commands/commit.go, go/cmd/dolt/commands/merge.go, go/libraries/doltcore/merge/action.go, integration-tests/bats/merge.bats
If the editor process is killed or the editor was saved with empty message, it gives error.
Fixes `dolt merge --no-ff --no-commit`, now it does not fast-forward and commit. It leaves the working set with changes.
=> fix merge --no-ff --no-commit

go/libraries/doltcore/sqle/enginetest/dolt_queries.go, go/libraries/doltcore/sqle/indexed_dolt_table.go
This error only applies to `DoltIndexedTable`, which as far as I can tell is limited to the history tables.
=> Fix missing projection on indexed table

go/go.mod, go/go.sum, go/libraries/doltcore/sqle/enginetest/dolt_engine_test.go, go/libraries/doltcore/sqle/enginetest/dolt_queries.go
tests that used to just work for dolt, now work for in-memory tables, so moving the tests there.
companion PR: https://github.com/dolthub/go-mysql-server/pull/1407
=> [no-release-notes] moving tests to gms

docker/docker-entrypoint.sh, docker/serverDockerfile
1. Fix unability to process .sql in initdb
If user has some .sql files in `/docker-entrypoint-initdb.d` they will have an error:
```
2022-11-21 11:02:13+00:00 [Note] [Entrypoint]: /usr/local/bin/docker-entrypoint.sh: running /docker-entrypoint-initdb.d/init.sql
/usr/local/bin/docker-entrypoint.sh: line 98: docker_process_sql: command not found
```
This PR fixes it
=> Fix issues with docker entrypoint

docker/Dockerfile, docker/serverDockerfile
It's helpful for avoiding zombie processes and provides signal handling such as `SIGTERM` from `docker stop`
=> use tini init system in docker container

go/libraries/doltcore/sqle/enginetest/dolt_queries.go, go/libraries/doltcore/sqle/history_table.go, go/libraries/doltcore/sqle/tables.go
history table was returning size-0 rows to the filter in the test case; the filter was erroring for the out of bounds index
=> history system table missing projections

go/cmd/dolt/commands/sqlserver/sqlserver.go, go/cmd/dolt/commands/sqlserver/yaml_config.go, integration-tests/bats/sql-server.bats
This allows the `loglevel` CLI param and `log_level` YAML config key to be case insensitive.
Fixes: https://github.com/dolthub/dolt/issues/4864
=> Changing `loglevel` param to be case insensitive. 

go/libraries/doltcore/migrate/integration_test.go, go/libraries/doltcore/migrate/transform.go, go/libraries/doltcore/schema/check_coll.go, go/libraries/doltcore/schema/col_coll_test.go, go/libraries/doltcore/schema/schema.go, go/libraries/doltcore/schema/schema_impl.go, go/libraries/doltcore/schema/schema_test.go, go/libraries/doltcore/sqle/sqlutil/convert.go, integration-tests/bats/migrate.bats, integration-tests/bats/migration-integration.bats
Fix for #4862 
Changes the way we instantiate schema.Schema in Dolt. In the past, we've had a couple bugs that have been caused by codepaths that build new schema objects. We've accidentally dropped primary key ordinals twice before and in #4862 we dropped indexes, checks, and collations.
=> Changes to schema instantiation

go/cmd/dolt/dolt.go, go/libraries/doltcore/dbfactory/file.go, go/performance/scripts/local_sysbench.sh, go/store/nbs/aws_table_persister.go, go/store/nbs/block_store_test.go, go/store/nbs/bs_persister.go, go/store/nbs/chunk_journal.go, go/store/nbs/chunk_journal_test.go, go/store/nbs/file_table_persister.go, go/store/nbs/journal_writer.go, go/store/nbs/journal_writer_test.go, go/store/nbs/root_tracker_test.go, go/store/nbs/store.go, go/store/nbs/store_test.go, go/store/nbs/table_persister.go, go/store/nbs/table_reader.go, go/store/nbs/table_set.go
Adds `chunkJournal`, a log-based `ChunkStore` that integrates into current `NomsBlockStore` machinery. `chunkJournal` implements `tablePersister` and `manifest`. When `memtable`s are passed to `Persist()`, their contents appended to the journal file at current offset and a `journalChunkSource` (implementing chunkSource) is returned. journalChunkSource is an in-memory object containing offset metadata for reading back chunks from the journal file. The chunkJournal also persists root hash updates to the log via the manifest interface. This PR is adapted from #4803, instead of returning a unique `journalChunkSource` on each `Persist()` call, a single chunk source is returned repeatedly. The `tableSet` naturally deduplicates these `chunkSource` references by storing them in a `chunkSourceSet` …
=> go/store/nbs: chunkJournal, journalWriter, and journalChunkSource

go/libraries/doltcore/sqle/database.go, go/libraries/doltcore/sqle/dtables/conflicts_tables.go, go/libraries/doltcore/sqle/dtables/conflicts_tables_prolly.go, go/libraries/doltcore/sqle/enginetest/dolt_engine_test.go, go/libraries/doltcore/sqle/enginetest/dolt_queries.go
Any columns prefixed with `our_` can now be updated on the `dolt_conflicts_$tbl_name` tables. Updates on the our columns get translated to updates on the conflict source table.
First pass on implementing the suggestion in #4854. Handles keyless and keyed tables. Does not add the auto-incrementing id to the conflict table. Will get this out to the customer first and then come back.
=> dolt_conflicts_$tbl_name: updates to the our version persist

go/cmd/dolt/commands/tblcmds/export.go, integration-tests/bats/export-tables.bats
`dolt table export` was previously appending "Successfully exported data." to the end of the csv file when using the redirect syntax (e.g. `dolt table export hospitals > hospitals.csv`). The success message didn't get appended when redirect syntax wasn't used (e.g. `dolt table export hospitals hospitals.csv`). This fix makes it so that both formats work as expected.
issue: https://github.com/dolthub/dolt/issues/4889
=> fixes dolt table export appending success message to csv when using redirect syntax

go/libraries/doltcore/sqle/dtables/conflicts_tables_prolly.go, go/libraries/doltcore/sqle/enginetest/dolt_queries.go, go/store/prolly/artifact_map.go, go/store/val/keyless_tuple.go
This PR makes manipulating the dolt_conflicts_$table_name tables easier. It adds a new `dolt_conflict_id` column. The column is a hash of the primary keys for a keyed table (or the value hash of the row for a keyless table) and the `from_root_ish` column. The `dolt_conflict_id` column uniquely identifies a conflict.
A sample:
```
dolt sql -q "select * from dolt_conflicts_t;"
+----------------------------------+---------+-----------+--------+----------+---------------+----------+------------+-----------------+------------------------+
| from_root_ish                    | base_pk | base_col1 | our_pk | our_col1 | our_diff_type | their_pk | their_col1 | their_diff_type | dolt_conflict_id       |
+----------------------------------+---------+-----------+--------+----------+---------------+---- …
```
=> Add dolt_conflict_id to dolt_conflicts_$table_name

go/libraries/utils/argparser/results.go
Found the same kind of bug as before this time in results.go. I changed the comparison to be correct as before.
Question about line 36. We are requiring exact order and not just content, is that correct or should we sort the args before comparing them?
=> found another minor bug in results.go

integration-tests/bats/merge-broken.bats
5 skipped bats showing how merge silently fails today.
After this PR, next steps is to throw an error if we are three-way merging these kinds of schema changes. Still thinking about how to detect these issues and fail-fast.
=> Adds skipped bats for silent merge failures

integration-tests/bats/sql-server.bats
skipped bats test and accompanying issue https://github.com/dolthub/dolt/issues/4885
=> [no-release-notes] /integration-tests/bats/sql-server.bats: add skipped bats test for creating savepoint without first using db

go/cmd/dolt/commands/checkout.go, go/libraries/doltcore/env/actions/branch.go, integration-tests/bats/checkout.bats
Block branch switches when both current and target branches have working set changes.
Allow this behavior to be skipped using the `-f` flag, in which case the two working sets are combined (as is the current behavior).
This fixes https://github.com/dolthub/dolt/issues/4863
=> Block branch switches when both branches have working set changes

go/cmd/dolt/commands/checkout.go, go/cmd/dolt/commands/reset.go, go/libraries/doltcore/env/actions/branch.go, go/libraries/doltcore/env/actions/reset.go
When checking out a branch, clear the source branch's working set only after the destination checkout succeeds without errors.
=> Reset source branch after checkout

go/libraries/doltcore/dbfactory/file.go, go/libraries/doltcore/doltdb/doltdb.go, go/libraries/doltcore/sqle/database_provider.go, go/store/nbs/manifest.go, go/store/nbs/manifest_cache.go, go/store/nbs/manifest_cache_test.go, go/store/nbs/store.go, integration-tests/bats/sql-server.bats
Fixes #4975 
Fix dropping and creating the same database on dolt sql-server. We were caching doltdb's using a singleton and at the manifest cache level which lead to problems.
=> Fix 'new manifest created with non 0 lock' error

.github/workflows/ci-go-tests.yaml, .github/workflows/ci-sql-server-integration-tests.yaml, go/libraries/doltcore/dbfactory/file.go, go/store/datas/pull/pull_test.go, go/store/datas/pull/puller_test.go, go/store/nbs/aws_table_persister.go, go/store/nbs/bs_persister.go, go/store/nbs/chunk_journal.go, go/store/nbs/chunk_journal_test.go, go/store/nbs/empty_chunk_source.go, go/store/nbs/file_table_persister.go, go/store/nbs/journal_writer.go, go/store/nbs/journal_writer_test.go, go/store/nbs/store.go, go/store/nbs/store_test.go, go/store/nbs/table.go, go/store/nbs/table_persister.go, go/store/nbs/table_reader.go, go/store/nbs/table_set.go, integration-tests/bats/config.bats, integration-tests/bats/remotes-sql-server.bats, integration-tests/bats/sql-charsets-collations.bats, integration-tests/bats/sql-server.bats
Cleans up chunk journal life cycle to facilitate push/pull/close paths. Prior work:
- initial implementation of chunk journal: https://github.com/dolthub/dolt/pull/4878
- enforce single in-process NBS per directory: https://github.com/dolthub/dolt/pull/4848
- enforce uniqueness for `chunkSources` within `tableSet`: https://github.com/dolthub/dolt/pull/4860
- export `getRecordRanges` from `chunkSource`: https://github.com/dolthub/dolt/pull/4909
Remaining work: 
- garbage collection support
- convert chunk journals at capacity to table files
=> [no-release-notes] go/store/nbs: progress on chunk journal sync

go/cmd/dolt/commands/read_tables.go, go/libraries/doltcore/doltdb/commit_hooks.go, go/libraries/doltcore/doltdb/doltdb.go, go/libraries/doltcore/env/actions/commitwalk/commitwalk_test.go, go/libraries/doltcore/env/actions/remotes.go, go/libraries/doltcore/sqle/cluster/commithook.go, go/libraries/doltcore/sqle/enginetest/dolt_queries.go, go/store/cmd/noms/noms_sync.go, go/store/datas/pull/pull.go, go/store/datas/pull/pull_test.go, go/store/datas/pull/puller.go, go/store/datas/pull/puller_test.go
This allows client code to be more efficient when it needs to pull multiple hashes.
=> [no-release-notes] go/store/datas/pull: Update Pull interfaces to take a slice of hashes to pull, not just one.

README.md
- make an sql
- note that this is an sql command
- note that the exactly steps done later
- i was typing `dolt create database` and got error ... and searched what is the right syntax for `dolt` command to make the step "create an database" at this point - but this was not nessesary at this point, because its explained later
- remove this lines or do a better rewording, so that an user not think he need to do here something.
added also this PR for the docs: https://github.com/dolthub/docs/pull/1095
=> docs(README): add info about sql command

go/cmd/dolt/commands/config.go, go/cmd/dolt/commands/config_test.go, integration-tests/bats/config.bats
Adds `--set` as a valid flag for `dolt config`. `--set` does the same as `--add`.
fixes: https://github.com/dolthub/dolt/issues/5050
=> adding --set as valid flag for dolt config

README.md
I was not a fan of the wording of the previous edit but thought the intent was good.
=> Change current README edit to be more out of band

go/cmd/dolt/commands/dump.go, go/libraries/doltcore/table/untyped/sqlexport/sqlwriter.go, integration-tests/bats/dump.bats
--schema-only is used for dump table schemas with no data into sql file.
=> add --schema-only flag for `dolt dump`

go/libraries/doltcore/remotesrv/grpc.go, go/libraries/doltcore/remotestorage/chunk_store.go, go/libraries/doltcore/sqle/cluster/commithook.go, go/libraries/doltcore/sqle/database_provider.go, go/store/datas/pull/pull.go
When remotestorage.DoltChunkStore was originally written, it forwarded all ChunkStore calls to the remotesapi. In reality, a client should expect a snapshot of the database on open, and the root should only change when Rebase() or Commit() is called. This fixes up that initial flaw. Rebase() becomes a refresh of the Root from the gRPC service, and Root() itself is just a read of the cached root hash.
This reduces unnecessary traffic to the remotestorage service and improves performance of things like sql-server read replicas.
=> go/libraries/doltcore/remotestorage: chunk_store: Fix semantics of Rebase and Root. Root stays fixed until a Rebase call.

go/libraries/doltcore/remotesrv/grpc.go, go/libraries/doltcore/remotesrv/http.go
Over time some trace logging snuck into remotesrv. At the same time, the logs were not as useful as they could have been and did not make use of log levels. Clean things up a bit to log more information about the amount of work done in some of the requests without being overly verbose.
=> go/libraries/doltcore/remotesrv: Reducing logging verbosity.

go/cmd/dolt/commands/cnfcmds/auto_resolve.go, go/libraries/doltcore/merge/violations_fk.go, go/libraries/doltcore/merge/violations_fk_prolly.go, go/libraries/doltcore/sqle/dprocedures/dolt_conflicts_resolve.go
Refactors `merge.AddForeignKeyViolations` by creating `merge.GetForeignKeyViolations` and the `FKViolationReceiver` interface.
Previously, our mechanic to check if edits to a root value created constraint violations was to write the constraint violations to the artifacts table and check if it was empty for all tables. 
Instead, we can now do a read-only operation to get constraint violations created by edits to a root value.
=> Add merge.GetForeignKeyViolatedTables

go/cmd/dolt/commands/dump.go, integration-tests/bats/dump.bats, integration-tests/data-dump-loading-tests/README.md, integration-tests/data-dump-loading-tests/import-mysqldump.bats
automatically adds `CREATE DATABASE IF NOT EXISTS ...; USE db;` to all dolt dump sql files, preventing errors from importing to dolt in non database directories
fixes: https://github.com/dolthub/dolt/issues/4837
=> add "create database" header to dolt dump sql files

go/libraries/doltcore/merge/violations_fk.go, go/libraries/doltcore/merge/violations_fk_prolly.go, go/libraries/doltcore/sqle/enginetest/dolt_queries_merge.go
Fix for bug reported by Fritter in Discord.
Here's what happened:
- Parent table has a simple pk
- Child table has a compound pk of length 3
- The foreign key is a single int column. It is the first column in the child table's pk, and the only column of parent's pk.
- No additional indexes are defined because we can reuse the pk index.
If we reuse the pk index, we have some special case code that builds a fake index definition. The issue is that we happened to pass sorted tags of the pks, instead the column-order tags. We then use the index definition to prefix iter secondary indexes.
This issue would not appear if you got lucky with the tags of your columns. Specifically, the sorted tag order had to match the tag order. For tables with one pk, this is always the case, and for the test we …
=> Fix `call DOLT_VERIFY_CONSTRAINTS()` false-positive

go/libraries/doltcore/branch_control/access.go, go/libraries/doltcore/branch_control/binlog.go, go/libraries/doltcore/branch_control/branch_control.go, go/libraries/doltcore/branch_control/namespace.go
The resulting database file is fully compatible with older dolt clients since the read path skips the size and noms prefix. Switching the strings to `CreateShared` also gave a decent space savings as well.
To see if there was a noticeable performance difference, I tried removing everything except for the binlog, and reconstructing the branch control tables from the binlog, and the differences were negligible. The resulting file was definitely smaller, but performance-wise there wasn't much difference when reading or writing from the file. We spend so much time in the engine that it doesn't really matter. So I decided to go this route since we still retain full compatibility.
=> Removed branch control database file size limitation

go/libraries/doltcore/sqle/dtables/diff_table.go, go/libraries/doltcore/sqle/dtables/log_table.go, go/libraries/doltcore/sqle/enginetest/dolt_queries_diff.go
`CommitClosure` methods are not nil-safe, check before calling `CommitClosure.Count()`.
=> Fix log table RowCount panic

go/libraries/doltcore/doltdb/table.go, go/libraries/doltcore/merge/merge_prolly_indexes.go, go/libraries/doltcore/merge/violations_unique_prolly.go, go/libraries/doltcore/sqle/enginetest/dolt_queries_merge.go
- The schema of the dolt_constraint_violations table was incorrect.
- Unique key violations were being thrown by merge even if the index key included a null value.
- The primary key was being built incorrectly for the unique key violations generated by merge. Previously it was assumed that the primary index's key was a suffix of the secondary index's key. This is not the case when the index key includes a column in the primary key.
=> Fix 3 merge bugs related to secondary indexes

go/cmd/dolt/commands/pull.go, integration-tests/bats/remotes.bats
`dolt pull` should not error out when there is no user name or email set. However, when `dolt pull` is run in a workspace that is already up to date with remote, the CLI returns an error `up to date` instead of printing `Everything up-to-date.`. This change fixes `dolt pull` to not return an error when the workspace is already up to date.
fixes: https://github.com/dolthub/dolt/issues/5079
=> dolt pull without configs doesnt return error when up to date

go/libraries/doltcore/remotesrv/http.go, go/libraries/doltcore/sqle/enginetest/dolt_queries.go
Also add Accept-Ranges headers in all HTTP responses for portions of table files and Content-Range headers for partial file responses.
This makes the HTTP server more correct and can improve compatibility with various HTTP middleware.
=> go/libraries/doltcore/remotesrv: Response with HTTP status code 206 when writing partial responses.

go/cmd/dolt/commands/commit.go, go/cmd/dolt/commands/reset.go, go/libraries/doltcore/env/actions/reset.go, go/libraries/doltcore/sqle/dsess/session.go, go/libraries/doltcore/sqle/dsess/transactions.go, go/libraries/doltcore/sqle/enginetest/dolt_transaction_commit_test.go, go/libraries/doltcore/sqle/enginetest/dolt_transaction_queries.go
Update the transaction logic to land a merge of current HEAD and the staged root value when we are creating a commit and the current HEAD has moved since the start of the transaction.
Dolt allows two concurrent transactions to both land commits on a branch HEAD. In the past, Dolt would simply commit the staged value on each transaction as the value of the database for the commit, and would merge the working sets so that the branch working set was updated with the latest data. This would result in histories with commits which seemed to delete previously committed data, only for it to still be present in the working set and to reappear in later commits. This was particularly problematic under remote replication, where the dolt commits themselves are replicated.
A change landed recently …
=> go/libraries/doltcore/sqle/dsess: When commiting a transaction with a  DOLT_COMMIT, merge against the current HEAD if necessary.

go/libraries/doltcore/sqle/database_provider.go, go/libraries/doltcore/sqle/dsess/variables.go, go/libraries/doltcore/sqle/system_variables.go, integration-tests/bats/sql.bats
When set to 1, will cause a revision database for each branch to appear in `show databases`, information schema tables, etc.
=> Added `dolt_show_branch_databases` system variable

go/store/nbs/mem_table.go
This keeps NBSStore from returning the same chunk twice if it appears in both memtable and a chunkSourceSet.
=> go/store/nbs: mem_table: getMany,getManyCompressed: Make certain to set getRecord.found = true.

go/libraries/doltcore/merge/violations_fk.go, go/libraries/doltcore/merge/violations_fk_prolly.go, go/store/prolly/tuple_map.go
We resolve foreign key conflicts by:
1) diffing a before/after index to generate keys
2) constructing a lookup key for the reference index
3) perform a lookup into the reference index
4) report a conflict if reference dependency is missing
For huge tables, we want the `from` keys to be ordered relative to the `to` index. When this is not the case, the `to` lookup will be random access and read a chunk from disk. Millions of random access lookups that all IO chunks from disk adds a ~1000x perf hit for validating a single FK relative to sorted lookups.
This PR does a secondary key diff -> secondary foreign key lookup. The diffs are ordered relative to one-another, and this usually makes big merges faster.
The main downside is that constraint violations still require a primary key lookup to …
=> verify fk with secondary when available

go/cmd/dolt/commands/branch.go, integration-tests/bats/remotes.bats
Git allows:
`git branch feature --track origin/feature`
`git branch --track request origin/feature`
`git branch feature --track=direct origin/feature`
`git branch --track=direct feature origin/feature`
for creating new branch that tracks given remote tracking branch
does not allow:
`git branch feature --track direct origin/feature`, but Dolt allows it as `--track direct` and `--track=direct` are considered the same
=> allow different format options for dolt branch with track flag

go/store/nbs/bs_persister.go, go/store/nbs/dynamo_table_reader.go, go/store/nbs/empty_chunk_source.go, go/store/nbs/file_table_reader.go, go/store/nbs/journal_chunk_source.go, go/store/nbs/mem_table_test.go, go/store/nbs/s3_table_reader.go, go/store/nbs/store.go, go/store/nbs/table.go, go/store/nbs/table_reader.go
With TableFileStore.WriteTableFile() being used on the clone path, we want to turn chunk sources into an io.ReadCloser. In the past, store/nbs always did this by using the ReaderAt to emulate an io.Reader. For files this maybe has OK performance, but for AWS/Blobstore remotes it causes a serial sequence of lots of small reads against blob storage as the io.Copy() implementation copies a few dozen KBs at a time.
This change makes it so a chunkSource can return an actual Reader. file_table_reader leaves the reader at emulation in place for now. One reason to potentially get rid of even that layer is to enable something like .WriteTo() -> sendfile() translations. Those are not currently directly in place because we currently instrument the returned Reader with byte counting, for example, so …
=> go/store/nbs: Make a chunkSource able to return a real io.Reader.

go/store/prolly/tree/testutils.go, go/store/skip/list.go
```py
$  GOARCH=386 GOOS=linux go build ./...
store/skip/list.go:152:21: maxCount (untyped int constant 4294967294) overflows int
```
See also https://github.com/dolthub/vitess/pull/216
=> Fix int overflow on 32-bit architectures

go/cmd/dolt/cli/arg_parser_helpers.go, go/cmd/dolt/commands/fetch.go, go/libraries/doltcore/sqle/dprocedures/dolt_fetch.go, integration-tests/bats/remotes.bats, integration-tests/bats/sql-fetch.bats
This change makes force fetch the default behavior for `dolt fetch` and removes the `-f` force flag to prevent errors when fetching after a force push.
fixes: https://github.com/dolthub/dolt/issues/4943
=> makes -f default behavior for dolt fetch

go/cmd/dolt/commands/schcmds/import.go, go/cmd/dolt/commands/tblcmds/import.go, go/libraries/doltcore/table/typed/json/reader.go, integration-tests/bats/import-replace-tables.bats
returns error message instead of panic
=> fix panic for unexpected json file format

go/store/nbs/table_index.go
A slight performance improvement for `findPrefix` when looking through table indexes that avoids a `make()` call and `bytes.Compare`
=> slightly better prefix compare

go/cmd/dolt/dolt.go
Allow the pprof server to handle connections from non-localhost machines.
This change is necessary to reach a Docker pprof server from host machine.
=> Allow the pprof server to handle connections from non-localhost

go/go.mod, go/go.sum, integration-tests/bats/sql-server.bats, integration-tests/bats/sql.bats
Depends on https://github.com/dolthub/go-mysql-server/pull/1583
DataGrip sets the `character_set_results` system variable to `utf8`, which raw binary strings cannot be encoded into. MySQL returns binary type strings in hex format.
=> add bats test for binary string encoded to utf8

go/cmd/dolt/commands/sql.go, integration-tests/bats/sql.bats
This change fixes timing for multi statement queries to print the time to execute the query instead of the time to print the results or the time since the first query started.
=> fixes timing for multi statement queries

integration-tests/bats/system-tables.bats
We had a skipped test for remote branch refs, but it is no longer needed now that we added BATS tests for the new `dolt_remote_branches` system table. 
Also fixes `system-tables: query dolt_remote_branches system table` test being flakey – it was testing for non-existence of branch `b1`, but occasionally `b1` will show up in a commit hash, so I changed the test the not select all columns.
=> [no-release-notes] Removing an unneeded skipped test

go/cmd/dolt/commands/sqlserver/server_test.go, go/libraries/doltcore/dtestutils/testcommands/multienv.go, go/store/cmd/noms/noms_root.go, go/store/datas/pull/puller_test.go, go/store/nbs/aws_chunk_source.go, go/store/nbs/aws_chunk_source_test.go, go/store/nbs/aws_table_persister_test.go, go/store/nbs/block_store_test.go, go/store/nbs/cmp_chunk_table_writer_test.go, go/store/nbs/conjoiner.go, go/store/nbs/conjoiner_test.go, go/store/nbs/file_table_persister_test.go, go/store/nbs/file_table_reader.go, go/store/nbs/file_table_reader_test.go, go/store/nbs/mem_table_test.go, go/store/nbs/quota.go, go/store/nbs/s3_fake_test.go, go/store/nbs/store.go, go/store/nbs/store_test.go, go/store/nbs/table_index.go, go/store/nbs/table_index_test.go, go/store/nbs/table_persister_test.go, go/store/nbs/table_set_test.go, go/store/nbs/table_test.go, go/store/spec/spec_test.go
Adds a paranoid mode where we noisely detect unclosed table files. The mode can be enabled by setting an environment variable.
Fixes some unit tests, including all of go/store/... to run cleanly under the paranoid mode.
Changes the quota interface to:
* Release |sz int| bytes instead of requiring a []byte with the correct length to show up.
* Work with |int| instead of |uint64|, since MaxUint64 is never allocatable and MaxInt32+z is only allocatable on 64-bit platforms.
* Not return an error on Release(). Implementations should not fail to release quota.
=> go/store/nbs: Fix some quota leaks in conjoin, GC.

go/libraries/doltcore/merge/merge_prolly_indexes.go, go/libraries/doltcore/merge/merge_prolly_rows.go, go/libraries/doltcore/merge/violations_fk.go, go/libraries/doltcore/merge/violations_unique_prolly.go, go/libraries/doltcore/sqle/dtables/conflicts_tables_prolly.go, go/libraries/doltcore/sqle/dtables/constraint_violations_prolly.go, go/store/prolly/artifact_map.go, go/store/prolly/tuple_mutable_map.go
ArtifactEditor held on to keys after flushing because it was a value receiver. Under the capacity threshold, constraint violations only flush once and we bypass this bug. For >50k constraint violations, every incremental CV will write the previous duplicate 40k CV's.
=> ArtifactEditor now resets after flushing

go/store/nbs/aws_table_persister.go, go/store/nbs/aws_table_persister_test.go
In #5307 we started returning a real io.Reader for chunkSource.reader(ctx). That means the Read() calls can come back short if they are directly attached to a net.TCPConn, for example. It is not an error for a Read() to come back short. Use io.ReadFull to correctly express the intent in the conjoin code for AWS remotes.
Fixes a bug where doltremoteapi fails commits sometimes.
=> go/store/nbs: aws_table_persister.go: Fix conjoin code to not error on a single short Read() by using io.ReadFull.

go/libraries/doltcore/sqle/database.go, go/libraries/doltcore/sqle/dtables/unscoped_diff_table.go, integration-tests/bats/sql.bats
This change corrects the `dolt_diff` system table to use the qualified database if provided instead of always defaulting to the session's current database.
fixes: https://github.com/dolthub/dolt/issues/5226
=> `dolt_diff` respects qualified database

go/go.mod, go/go.sum, go/libraries/doltcore/sqle/enginetest/dolt_harness.go
Currently, when reset scripts run between Prepared Script Tests errors will occur as tables with foreign keys get dropped and re-added. This change disables foreign key checks while tables are being dropped and re-added as to avoid these foreign key errors.
=> updates reset script to disable foreign_key_checks temporarily

go/libraries/doltcore/sqle/binlogreplication/binlog_replica_applier.go, go/libraries/doltcore/sqle/binlogreplication/binlog_replication_test.go
This PR fixes a couple of issues from binlog testing:
Now that we have visibility to the additional flags in the `Query` binlog event (https://github.com/dolthub/vitess/pull/220), this PR adds handling for those flags. 
To receive messages from the primary when `binlog_checksums` are enabled, the replica now sends a handshake signal to the primary and strips off any received checksum on binlog events. This lets us remove the requirement to disable checksums on the primary in order to use Dolt's binlog replication. 
This PR also includes a change in the test code for the replica connect to the primary with a password, to ensure we're testing password auth.
=> binlog bug fixes – stripping checksums and applying `Query` flags

go/libraries/doltcore/diff/table_deltas.go, go/libraries/doltcore/sqle/database_provider.go, go/libraries/doltcore/sqle/dolt_diff_summary_table_function.go, go/libraries/doltcore/sqle/dtables/unscoped_diff_table.go, go/libraries/doltcore/sqle/enginetest/dolt_engine_test.go, go/libraries/doltcore/sqle/enginetest/dolt_queries.go, go/libraries/doltcore/sqle/enginetest/dolt_queries_diff.go
The old version of the `dolt_diff_summary` table function was renamed to `dolt_diff_stat`
This new version of `dolt_diff_summary` returns a summary of changed tables between two refs
```sql
us_jails> select * from dolt_diff_summary("WORKING", "taylor/test");
+-----------------------------+-----------+-------------+---------------+
| table_name                  | diff_type | data_change | schema_change |
+-----------------------------+-----------+-------------+---------------+
| jails                       | modified  | true        | false         |
| test                        | dropped   | false       | true          |
| inmate_population_snapshots | added     | true        | true          |
+-----------------------------+-----------+-------------+---------------+
3 rows in set (0.01 …
```
=> Add new version of `dolt_diff_summary` table function 

go/cmd/dolt/commands/diff.go, go/libraries/doltcore/diff/table_deltas.go, go/libraries/doltcore/sqle/dolt_diff_summary_table_function.go, go/libraries/doltcore/sqle/dtables/status_table.go, go/libraries/doltcore/sqle/enginetest/dolt_queries_diff.go, integration-tests/bats/diff-stat.bats, integration-tests/bats/sql-status.bats
- Also fixes `dolt_status` system table output for renamed tables
- Table name in `dolt diff --summary` CLI command for renamed table uses arrow syntax (i.e. `from_table -> to_table`)
=> Add `from_table_name` and `to_table_name` columns to `dolt_diff_summary` table function

go/libraries/doltcore/sqle/altertests/common_test.go, go/libraries/doltcore/sqle/binlogreplication/binlog_replica_applier.go, go/libraries/doltcore/sqle/binlogreplication/binlog_replication_multidb_test.go
We were missing the call to set the session's current database for binlog `Query` events. This was causing queries to execute against the wrong database when using binlog replication with multiple databases. Our binlog tests didn't catch this because the multi-db tests used fully qualified table names, so it didn't matter what database was currently selected. 
This change adds the call to set the current database and updates the multi-db tests to use a mix of `use` statements and fully qualified table names (and also cleans up some of our query error logging to make log output more helpful for debugging).
=> bug fix: binlog multi-db support

go/libraries/doltcore/migrate/transform.go, go/libraries/doltcore/sqle/altertests/common_test.go, integration-tests/bats/migration-integration.bats
#4221 alters tuple ordering for NBF `__LD_1__` to sort `NULL` fields last. In NBF `__DOLT__`, `NULL` fields are ordered first. This change to `dolt migrate` sorts migrated tuples on-the-fly to compensate for this mismatch
=> go/doltcore/migrate: modify migrated tuples sink to sort incoming tuples

go/libraries/doltcore/sqle/binlogreplication/binlog_replication_test.go
`dolt sql-server` processes were not getting properly cleaned up by simply killing the top level process. This change switches to kill all the child processes in the process group. I'm unable to repro the lingering `dolt sql-server` processes with this change.
=> [no-release-notes] Ensure all dolt sql-server child processes get cleaned up

.github/workflows/ci-bats-unix.yaml, go/libraries/doltcore/sqle/writer/prolly_index_writer_keyless.go, go/libraries/doltcore/sqle/writer/prolly_table_writer.go
fix for: https://github.com/dolthub/dolt/issues/5442 and https://github.com/dolthub/dolt/issues/5433
tests: https://github.com/dolthub/go-mysql-server/pull/1642
=> fix keyless duplicate update

.github/workflows/label-customer-issues.yaml
Turning on a new GitHub action for the `dolt` repo. This action will label issues from non-team-members with the `customer-issue` label, and will label PRs from non-team-members (excluding dependabot) with the `contribution` label. The intent is to give us a visual indicator to help make customer issues and PRs a little more obvious and make sure they get attention. Over time, we could also get some nice metrics on incoming customer issues and contributions.
=> [no-release-notes] New GitHub Action to label issues and PRs from customers

.github/workflows/label-customer-issues.yaml
=> [no-release-notes] Re-enabling the label-customer-issues workflow after fixing permissions

go/libraries/doltcore/doltdb/doltdb_test.go, go/libraries/doltcore/doltdb/root_val.go
This fixes two dropped `err` variables in the `libraries/doltcore/doltdb`.
=> libraries/doltcore/doltdb: fix dropped errors

go/store/nbs/store.go, integration-tests/go-sql-server-driver/gc_oldgen_conjoin_test.go
This allows us to avoid huge manifests with lots of table files when we run multiple full GCs over a period of time.
=> go/store/nbs: store.go: Conjoin if we need to when we add new table files to a manifest.

go/libraries/doltcore/dtestutils/sql_server_driver/cmd.go, go/libraries/doltcore/dtestutils/sql_server_driver/server.go, go/store/nbs/journal.go, integration-tests/go-sql-server-driver/concurrent_gc_test.go, integration-tests/go-sql-server-driver/testdef.go, integration-tests/go-sql-server-driver/tests/sql-server-orig.yaml
When a repository was created with < 0.75.0, or if it was created and used with `DOLT_DISABLE_CHUNK_JOURNAL=true`, it does not have a chunk journal. If it then runs dolt in a mode where it uses the chunk journal, the journal will not be bootstrapped until a write is done against the database. In the state where `dolt` is using the chunk journal but the chunk journal is not bootstrapped, `dolt gc` and `call dolt_gc()` were broken. They would fail with the message: `concurrent manifest edit during GC, before swapTables. GC failed.`.
This fixes that by making the chunk journal forward UpdateGCGen manifest update calls in its non-bootstrapped state, the same way it forwards Update manifest calls.
=> Fix dolt_gc for repositories newly using chunk journal.

go/libraries/doltcore/sqle/cluster/commithook.go, go/libraries/doltcore/sqle/cluster/commithook_test.go
Misreporting isCaughtUp would race to allow a primary to gracefully transition to standby without true-ing up the replicas immediately after creating a new database, for example.
=> go/libraries/doltcore/sqle/cluster: commithook.go: Fix initialization of commithook so it does not report isCaughtUp right after construction.

go/libraries/doltcore/sqle/dtables/diff_iter.go, go/libraries/doltcore/sqle/dtables/diff_table.go, go/libraries/doltcore/sqle/enginetest/dolt_queries_diff.go
=> Fixed panic in dolt_commit_diff tables when referring to commits where the table doesn't exist

integration-tests/bats/README.md
Bats tests also require that remotesrv be installed.
I added instructions for that to the README.
=> Update setup instructions for bats tests

go/cmd/dolt/cli/arg_parser_helpers.go, go/cmd/dolt/commands/indexcmds/ls.go, go/libraries/utils/argparser/parser.go, go/libraries/utils/argparser/parser_test.go
A follow-up to https://github.com/dolthub/dolt/pull/5762 addressing comments in the original PR.
=> Follow-up to validating extra command line arguments.

go/cmd/dolt/commands/sqlserver/server.go, go/gen/proto/dolt/services/eventsapi/v1alpha1/client_event.pb.go, go/gen/proto/dolt/services/eventsapi/v1alpha1/client_event_grpc.pb.go, go/gen/proto/dolt/services/eventsapi/v1alpha1/event_constants.pb.go, go/gen/proto/dolt/services/remotesapi/v1alpha1/chunkstore.pb.go, go/gen/proto/dolt/services/remotesapi/v1alpha1/chunkstore_grpc.pb.go, go/gen/proto/dolt/services/remotesapi/v1alpha1/credentials.pb.go, go/gen/proto/dolt/services/remotesapi/v1alpha1/credentials_grpc.pb.go, go/libraries/doltcore/env/environment.go, go/libraries/doltcore/env/multi_repo_env.go, go/libraries/doltcore/sqle/binlogreplication/binlog_metadata_persistence.go, go/libraries/doltcore/sqle/binlogreplication/binlog_replica_applier.go, go/libraries/doltcore/sqle/binlogreplication/binlog_replica_controller.go, go/libraries/doltcore/sqle/database_provider.go, go/libraries/doltcore/sqle/dprocedures/dolt_branch.go, go/libraries/doltcore/sqlserver/dolt_server.go, integration-tests/bats/sql-server.bats
Add runtime information for the server to the sql-server.lock file. We track three pieces of information:
1) The PID. As before.
2) The port of the server, if there is one. You can grab the lock as a cli process, which has no port.
3) A secret. Currently implemented as a UUID. This will be used to ensure that the connecting through the server is only performed by user's and processes which have read access to the server.
In addition, this change modifies the sql-server.lock file to be only readable by the owner.
Step (1) of:  https://github.com/dolthub/dolt/issues/3922.
=> Add Server Runtime details to the sql-server.lock file

go/gen/proto/dolt/services/eventsapi/v1alpha1/client_event.pb.go, go/gen/proto/dolt/services/eventsapi/v1alpha1/client_event_grpc.pb.go, go/gen/proto/dolt/services/eventsapi/v1alpha1/event_constants.pb.go, go/gen/proto/dolt/services/remotesapi/v1alpha1/chunkstore.pb.go, go/gen/proto/dolt/services/remotesapi/v1alpha1/chunkstore_grpc.pb.go, go/gen/proto/dolt/services/remotesapi/v1alpha1/credentials.pb.go, go/gen/proto/dolt/services/remotesapi/v1alpha1/credentials_grpc.pb.go, go/libraries/doltcore/merge/schema_merge_test.go
This also pointed out an issue in the framework where any secondary index and check constraint definitions are silently swallowed.
=> Adding basic support for conflict validation in new schema merge test framework

go/libraries/doltcore/merge/merge_prolly_indexes.go, go/libraries/doltcore/schema/index.go, go/libraries/doltcore/sqle/enginetest/dolt_queries_merge.go
The equality functions on `Index` weren't considering `prefixLengths` or `isSpatial`, which resulted in a merge bug where dolt would get confused and match two indexes as identical when they really weren't.
=> Bug fix and test for index merge bug that didn't detect incompatible index types

go/cmd/dolt/commands/credcmds/check.go
Using `dolt creds check --endpoint <endpoint> --creds <creds>` was failing with an audience error because we were using the wrong parsing logic to get the host for the endpoint. This fixes that and adds a log if the endpoint cannot be parsed
```
% dolt creds check --endpoint doltremoteapi.awsdev.ld-corp.com:443 --creds b33diq4ht3t73hnp5bofekvsg9lk36ou2gto74f7ot02g38r70mg
Calling...
Endpoint: doltremoteapi.awsdev.ld-corp.com:443
Key: b33diq4ht3t73hnp5bofekvsg9lk36ou2gto74f7ot02g38r70mg
error: calling doltremoteapi with credentials.
cause: rpc error: code = Unauthenticated desc = jwt_token validation failed: square/go-jose/jwt: validation failed, invalid audience claim (aud)
```
=> Fix dolt creds check with specified endpoint

go/libraries/doltcore/merge/merge_schema.go, go/libraries/doltcore/schema/index_coll.go, go/libraries/doltcore/sqle/enginetest/dolt_queries_merge.go
When merging multiple indexes that cover the same set of columns (even if they are different types, such as a unique index and a prefix index), there is a race condition because of how our index support assumes the column tag set will be unique for every index. This can cause the wrong index to be matched and the wrong merge decisions to be made. 
I tried to come up with another way to opportunistically match indexes across the sides of a merge in PR https://github.com/dolthub/dolt/pull/5797, but I still found more edge cases and the extra complexity didn't seem worth it. It seemed better to have Dolt be vocal about the issue and let users resolve it, instead of trying to be clever when we can't merge that situation correctly every time.
=> Prevent merges when either side has multiple indexes covering the same set of columns

go/store/nbs/journal_index_record.go, go/store/nbs/journal_record.go, go/store/nbs/journal_writer.go, go/store/nbs/journal_writer_test.go, integration-tests/bats/chunk-journal.bats
https://github.com/dolthub/dolt/pull/5393 added a "journal index" to accelerate chunk journal bootstrapping. Unfortunately it never worked! Bugs in the journal index bootstrapping process caused sanity checks to fail and the journal index was subsequently dropped. The chunk journal itself was still valid and the bugs had no effect on correctness. However, without a valid journal index we were forced to always take the slow-path on startup.
=> go/store/nbs: reduce startup latency for chunk journal

integration-tests/MySQLDockerfile, integration-tests/mysql-client-tests/mysql-client-tests.bats, integration-tests/mysql-client-tests/ruby/Gemfile, integration-tests/mysql-client-tests/ruby/Gemfile.lock, integration-tests/mysql-client-tests/ruby/mysql2-test.rb
Issue https://github.com/dolthub/dolt/issues/5834 uncovered that we weren't testing what seems to be the [recommended Ruby MySQL connector library (`mysql2`)](https://dev.mysql.com/doc/refman/8.0/en/apis-ruby.html), so this PR adds a connector integration test for it.
=> Adding a mysql connector integ test for the Ruby mysql2 library

go/libraries/doltcore/sqle/database_provider.go, integration-tests/go-sql-server-driver/tests/sql-server-cluster.yaml
Failing to run the hook means that the cloned database is not appropriately configured for replication, for example.
Fixes: #5850
=> go/libraries/doltcore/sqle: database_provider.go: When cloning a remote into a sql-server, always run the InitDatabaseHook on it.

go/cmd/dolt/commands/diff.go, integration-tests/bats/diff.bats, integration-tests/bats/ignore.bats
=> `dolt diff` shouldn't print ignored tables.

go/libraries/doltcore/doltdb/doltdb.go, go/libraries/doltcore/env/actions/remotes.go, go/store/chunks/tablefilestore.go, go/store/datas/pull/clone.go, go/store/nbs/journal_writer.go
pull.Clone uses the TableFileStore interface to transit whole table files without needing to follow chunk references or do any reconciliation with the destination database regarding what it already has. It is much faster against every time of remote.
=> go: env/actions: remotes.go: In SyncRoots, if we are syncing to an empty destination repository, use pull.Clone instead of pull.Pull.

go/cmd/dolt/commands/engine/sqlengine.go, go/cmd/dolt/commands/sql.go, go/cmd/dolt/commands/sqlserver/server.go, go/libraries/doltcore/mvdata/engine_table_reader.go, go/libraries/doltcore/mvdata/engine_table_writer.go
- More the format flag out of the sql engine. It's only used by the sql command, and causes confusion
- Drop the Dbddl code path. It's not longer required.
=> Two code clean ups

go/libraries/doltcore/branch_control/access.go, go/libraries/doltcore/branch_control/expr_parser_node.go, go/libraries/doltcore/sqle/dtables/branch_control_table.go, integration-tests/bats/branch-control.bats
There was a bug where, under very specific conditions, we could get the branch control table to have a nil map when there shouldn't be one, which would throw a panic. This situation also seemed to cause a bug where you could "infinitely" delete branches without them actually being removed, and our duplicate key detection failed to work in these cases. The root cause of both of those issues have been fixed.
In addition, if a customer wanted to reject a user from using a particular branch, but allow others, then it was very, very verbose to implement this functionality. I've instead modified our branch control system to take the longest match (which will be the most specific one due to our folding of expressions), and also added an explicit `"read"` permission, to force some (or all) users …
=> Branch Control fixes and improvements

go/cmd/dolt/commands/tblcmds/import.go, integration-tests/bats/import-replace-tables.bats, integration-tests/bats/import-update-tables.bats
This check appears to be redundant, in order to fail early and return a more helpful error message. But it's not helpful if it's wrong... which it is. It errors fast on inputs that should be correct (such as auto-increment columns), and it not only fails on the example from https://github.com/dolthub/dolt/issues/5855, but it would prevent us from implementing a permanent fix.
Removing the check, all tests still pass, because invalid imports are still detected by the remaining checks.
=> Remove overzealous validation check.

go/libraries/doltcore/doltdb/ignore.go, integration-tests/bats/ignore.bats
This PR does two things:
- introduces % as an alias for *, since % is the SQL wildcard
- adds an additional check for dolt_ignore rules that are equivalent but have different `ignored` values.
=> Improve dolt_ignore pattern rules
