dolthub/dolt

go/libraries/utils/filesys/inmemfs.go
The current InMemFS was failing in a multithreaded context as it edits a map which is not thread safe.  Something to note is that golang locks are not re-entrant.  Some of the refactoring is related to that.  Locks are typically put on the exported methods and not the internal methods.
=> Make the InMemFS thread safe

bats/sql-shell.bats, go/cmd/dolt/commands/sql.go
Fixes Bats test as introduced in: https://github.com/liquidata-inc/dolt/pull/125
=> Fixed not returning error on invalid batch inserts

.gitignore, bats/1pk5col-ints.bats, bats/1pk5col-strings.bats, bats/1pksupportedtypes.bats, bats/2pk5cols-ints.bats, bats/advanced-sql.bats, bats/capital-letter-column-names.bats, bats/config.bats, bats/conflict-detection.bats, bats/create-tables.bats, bats/diff.bats, bats/empty-repo.bats, bats/git-dolt.bats, bats/helper/common.bash, bats/multiple-tables.bats, bats/no-repo.bats, bats/remotes.bats, bats/replace-tables.bats, bats/schema-changes.bats, bats/send_metrics.bats, bats/sql-reserved-column-name.bats, bats/sql-shell.bats, bats/update-tables.bats
This has been bothering me for a while.
=> bats: Factor setup and teardown logic out of tests, greatly reducing duplication

go/go.sum, go/libraries/doltcore/str_to_noms.go, go/libraries/doltcore/str_to_noms_test.go, go/libraries/doltcore/type_conversion.go, go/libraries/doltcore/type_conversion_test.go, go/store/types/codec.go, go/store/types/compare_test.go, go/store/types/encode_human_readable.go, go/store/types/encode_human_readable_test.go, go/store/types/inlineblob.go, go/store/types/make_type.go, go/store/types/map_test.go, go/store/types/noms_kind.go, go/store/types/simplify.go, go/store/types/subtype.go, go/store/types/subtype_test.go, go/store/types/type_test.go, go/store/types/uuid.go, go/store/types/value_decoder.go, go/store/types/walk_refs.go, go/store/types/walk_test.go
This turned out to be far smaller than I thought as far as changes go. This `types` change might be simpler than I first thought! I probably felt it was harder just because finding all of these locations was a major pain...
=> Added new InlineBlob type

go/cmd/dolt/commands/diff.go, go/cmd/dolt/commands/log.go, go/libraries/doltcore/env/actions/commit.go, proto/README.md
Just some small stuff I cherry-picked out of the dolt blame PR I'm gonna drop tomorrow. In particular, I use `getCommitSpec` in that.
=> Miscellaneous small changes

bats/blame.bats, go/cmd/dolt/commands/blame.go
```
$ dolt blame lunch-places
+--------------------+----------------------------------------------------+-----------------+------------------------------+----------------------------------+
| NAME               | COMMIT MSG                                         | AUTHOR          | TIME                         | COMMIT                           |
+--------------------+----------------------------------------------------+-----------------+------------------------------+----------------------------------+
| Boa                | Had an unhandled schema merge conflict which I ch… | Tim Sehn        | Fri Mar 22 12:21:59 PDT 2019 | ffabndafbp64r393ttghused8siip77j |
| Chipotle           | lunch-places: Added Chipotle                       | katie mcculloch | Thu Aug 29 11:38:00 PDT 2019 | …
```
=> {bats, go}: Make commit spec truly optional in blame

go/go.mod, go/libraries/events/emitter.go, go/libraries/events/file_backed_proc.go
Need to update the requests so that it reflects the current proto definitions.
=> add appid to logevents requests

bats/dolt-docs.bats, go/cmd/dolt/commands/add.go, go/cmd/dolt/commands/commit.go, go/cmd/dolt/commands/status.go, go/go.sum, go/libraries/doltcore/doltdb/root_val.go, go/libraries/doltcore/env/actions/commit.go, go/libraries/doltcore/env/actions/diffs.go, go/libraries/doltcore/env/actions/staged.go, go/libraries/doltcore/env/environment.go
<strike>I will change the base on this PR to the feature branch (#222) once #242 is merged</strike>
I updated the base to the feature branch 👍
=> {go,bats}: dolt add <doc> 

bats/sql-shell.bats, go/cmd/dolt/commands/sql.go
=> added args check to dolt sql command

go/libraries/doltcore/sql/sqltestutil/selectqueries.go, go/libraries/doltcore/sqle/log_table.go
Output of the date field was in a format that wasn't able to be sorted properly.
=> change the date field to be a Sql.DateTime

bats/create-views.bats
Added some checks for checked in views.
=> Added a bats test for committing views and referencing them later

README.md
Install instructions now point to new install scripts.
=> Changed the install instructions on dolt README.

bats/system-tables.bats
@bheni will finish this and unskip the tests that are specced
=> A start on system tables bats tests

go/cmd/dolt/commands/tblcmds/import.go
Fixes https://github.com/liquidata-inc/dolt/issues/275.
=> Fix error message when table doesn't exist

bats/system-tables.bats
Found weird behavior in dolt_diff_.
=> Added a basic tests for dolt_diff_ and dolt_history_ system tables.

bats/multiple-tables.bats, go/cmd/dolt/commands/add.go
Added corresponding bats test.
Fixes #345
=> Changed add all shortcut from lowercase a to uppercase A to match git. 

bats/1pk5col-ints.bats, go/libraries/doltcore/table/untyped/csv/reader.go
@timsehn do we want to allow whitespace column names?
=> check for nil or empty column headers

bats/arg-parsing.bats
We don't support Nix style argument parsing completely right now
=> Added 2 skipped argument parsing bats tests. 

go/store/types/map.go, go/store/types/map_iterator_test.go, go/store/types/sequence_cursor.go
=> iterate a map backward

bats/remotes.bats
Could not repro panic from #442.
=> Added a succeeding bats test for push --set-upstream. 

go/cmd/dolt/commands/sqlserver/server.go, go/cmd/dolt/commands/sqlserver/server_test.go, go/cmd/dolt/commands/sqlserver/sqlserver.go
server command by providing it the appropriate variable when instantiating SQL server object.
=> Fix the SQL 

go/cmd/dolt/commands/sql.go
Signed-off-by: Zach Musgrave <zach@liquidata.co>
=> Fixed bug caused by overzealous refactoring

benchmark/sql_regressions/run_regressions.sh
=> /benchmark/sql_regressions/run_regressions.sh: Fix mean query to include group by test_file

bats/export-tables.bats
https://github.com/liquidata-inc/dolt/issues/538
=> Added skipped bats test for issue 538

bats/aws-remotes.bats, go/libraries/doltcore/dbfactory/aws.go
Currently these get skipped in CI. Will follow up with CI changes after this lands as they will require some external state creation and some small infra work.
Push is skipped here and can be unskipped after #531 lands.
Clone is skipped here and will remain skipped until another PR fixes it. I took a pass this morning but clone logic has gotten a little hairy and I wasn't happy with the progress I was making. Going to take another pass soon.
=> bats/aws-remotes.bats: Add some smoke tests for AWS remotes interactions.

go/cmd/dolt/commands/cnfcmds/cat.go, go/cmd/dolt/commands/cnfcmds/resolve.go, go/cmd/dolt/commands/tblcmds/rm.go
I noticed some places where we were discarding some verr values. Looked quickly for open issues related to these and didn't find any, but the errors seem pretty important. The refactorings are maybe a little tricky so I appreciate as many eyes as I can get.
=> go/cmd/dolt/commands: Handle some verrs which were previously being discarded

go/cmd/dolt/commands/sql.go
=> Add json to supported output types in dolt sql --help

go/libraries/doltcore/sqle/indexes.go
Signed-off-by: Zach Musgrave <zach@liquidata.co>
=> Fixed bug for multi-key indexes

bats/1pk5col-ints.bats, bats/2pk5cols-ints.bats, bats/create-views.bats, bats/docs.bats, bats/empty-repo.bats, bats/multiple-tables.bats, bats/no-repo.bats, bats/remotes.bats, bats/schema-changes.bats, bats/sql-diff.bats, go/libraries/doltcore/env/dolt_docs.go, go/libraries/doltcore/env/environment.go, go/libraries/doltcore/env/environment_test.go
Dont stomp/save any docs if one or more docs already exist in repo
=> {bats,libraries/doltcore/env}: Fix init stomp bug

go/libraries/doltcore/sqle/expreval/expression_evaluator.go, go/libraries/doltcore/sqle/filter_reader_test.go, go/libraries/doltcore/sqle/filtered_reader.go
This is simple partial key iteration.  Certainly not optimal.
=> partial key iteration

go/libraries/doltcore/doltdb/doltdb_test.go, go/libraries/doltcore/doltdb/root_val_test.go, go/libraries/doltcore/doltdb/table_test.go, go/libraries/doltcore/dtestutils/data.go, go/libraries/doltcore/merge/merge_test.go, go/libraries/doltcore/row/noms_row_test.go, go/libraries/doltcore/schema/alterschema/addcolumn_test.go, go/libraries/doltcore/schema/alterschema/dropcolumn_test.go, go/libraries/doltcore/schema/alterschema/modifycolumn_test.go, go/libraries/doltcore/schema/encoding/schema_marshaling_test.go, go/libraries/doltcore/schema/index_test.go, go/libraries/doltcore/sqle/integration_tests/stockmarket_test.go, go/libraries/doltcore/sqle/table_editor_index_test.go
This PR is strictly the tests. All of the PR feedback and whatnot can be seen from the commit history found on the parent PR https://github.com/liquidata-inc/dolt/pull/495.
=> Secondary Indexes Pt. 1 Episode 2

bats/arg-parsing.bats, go/cmd/dolt/cli/command.go, go/cmd/dolt/commands/checkout.go
=> fixed panic for empty string args

bats/sql.bats, go/go.mod, go/go.sum
depends on go-mysql-server [PR](https://github.com/liquidata-inc/go-mysql-server/pull/108)
=> fix panic for `select 1/0 from dual`

go/libraries/doltcore/merge/merge.go, go/libraries/doltcore/merge/resolve.go
`Resolve` and `Merge` were the last two write paths that didn't use the new `TableEditor` yet, so here they are!
=> Last write paths to TableEditor

benchmark/sql_regressions/run_regressions.sh
spits out timing info for these different commands
=> /benchmark/sql_regressions/run_regressions.sh: Iterating on timing commands

bats/helper/pytest.py, bats/helper/query-server-common.bash, bats/server_multiclient_test.py, bats/sql-server.bats, go/libraries/doltcore/doltdb/doltdb.go, go/libraries/doltcore/sqle/dfunctions/commit.go, go/libraries/doltcore/sqle/dfunctions/hashof.go, go/libraries/doltcore/sqle/dfunctions/init.go, go/libraries/doltcore/sqle/dfunctions/merge.go, go/libraries/doltcore/sqle/diff_table.go, go/libraries/doltcore/sqle/dolt_session.go, go/libraries/doltcore/sqle/history_table.go, go/libraries/doltcore/sqle/log_table.go
* Merge function
* Concurrent client test which has multiple clients executing simultaneously and does branches merges, and conflict resolution.
=> SQL Merge Function

.github/workflows/bump-brew-formula.yml
My best guess at the correct syntax... not a huge fan of actions rn lol
=> /.github/workflows/bump-brew-formula.yml: Attempt to fix syntax and dispell yaml syntax error

.github/workflows/ci-go-tests.yaml
Run go tests for `dolt` on PRs
=> Db/ci GitHub actions go

.github/workflows/ci-bats-tests.yaml
Seems to run the tests for both `linux` and `macos` ... need to fix the broken tests that have specific dependency issues
=> /.github/workflows/ci-bats-tests.yaml: Add dolt bats tests ci github actions

bats/foreign-keys.bats, go/libraries/doltcore/doltdb/sessioned_table_editor.go, go/libraries/doltcore/doltdb/table_edit_session.go, go/libraries/doltcore/merge/merge.go
Here are the merge changes along with some `bats` tests
=> Foreign Keys Part 3 Episode 1

bats/foreign-keys.bats, go/cmd/dolt/commands/sql_test.go, go/cmd/dolt/commands/tblcmds/cp.go, go/gen/proto/dolt/services/eventsapi/v1alpha1/client_event.pb.go, go/gen/proto/dolt/services/eventsapi/v1alpha1/client_event_grpc.pb.go, go/gen/proto/dolt/services/eventsapi/v1alpha1/event_constants.pb.go, go/gen/proto/dolt/services/remotesapi/v1alpha1/chunkstore.pb.go, go/gen/proto/dolt/services/remotesapi/v1alpha1/chunkstore_grpc.pb.go, go/gen/proto/dolt/services/remotesapi/v1alpha1/credentials.pb.go, go/gen/proto/dolt/services/remotesapi/v1alpha1/credentials_grpc.pb.go, go/libraries/doltcore/doltdb/foreign_key_coll.go, go/libraries/doltcore/doltdb/sessioned_table_editor.go, go/libraries/doltcore/merge/merge.go, go/libraries/doltcore/schema/alterschema/dropcolumn.go, go/libraries/doltcore/schema/alterschema/dropcolumn_test.go, go/libraries/doltcore/schema/index_coll.go, go/libraries/doltcore/sqle/dolt_session.go, go/libraries/doltcore/sqle/tables.go
The last bit of things to add for foreign keys!
=> Foreign Keys Part 3 Episode 2

go/go.mod
related to https://github.com/liquidata-inc/dolt/issues/816
=> /go/go.mod: update eventsapi generated types

go/cmd/dolt/commands/branch.go
I added --show-current option to dolt branch cli.
ref. https://github.com/liquidata-inc/dolt/issues/818
=> add --show-current option to dolt branch

mysql-client-tests/MySQLDockerfile, mysql-client-tests/node/index.js
so the docker container seems to work with the following changes... my JS/Node is kinda wack these days too...
so this can run like this:
```
$ cd mysql-client-tests
$ docker build -t mysql-tests -f MySQLDockerfile .
$ docker run -it --rm mysql-tests:latest /bin/bash
root@e1fbe3c4579f:/mysql-client-tests# bats mysql-client-tests.bats 
✓ python mysql.connector client
✓ python pymysql client
✓ mysql-connector-java client
✓ node mysql client
4 tests, 0 failures
root@e1fbe3c4579f:/mysql-client-tests# exit
```
=> /mysql-client-tests/{node/, MySQLDockerfile}: POC dockerizing test env

bats/diff.bats, go/libraries/doltcore/doltdb/doltdb.go
fix for https://github.com/liquidata-inc/dolt/pull/874
=> validate ref strings when resolving ref specs

MySQLDockerfile, mysql-client-tests/mysql-client-tests.bats, mysql-client-tests/ruby/Gemfile, mysql-client-tests/ruby/Gemfile.lock, mysql-client-tests/ruby/ruby-mysql-test.rb
Not to be confused with mysql/ruby which uses the MySQL C API.
=> Working Ruby ruby/mysql test 

bats/sql-create-tables.bats
Fixes https://github.com/liquidata-inc/dolt/issues/654
=> Fixed CREATE LIKE multi-db

go/cmd/dolt/commands/merge.go, go/cmd/dolt/commands/reset.go
=> doc corrections

go/libraries/doltcore/sqle/enginetest/dolt_engine_test.go, go/libraries/doltcore/sqle/enginetest/dolt_harness.go
=> Skipped two newly added test queries that don't work in dolt yet

go/go.mod, go/go.sum, go/libraries/doltcore/sqle/logictest/dolt/doltharness.go, go/libraries/doltcore/sqle/logictest/main/main.go
=> Updated namespace for sqllogictest

README.md, windows.md
=> Rewrote the README

go/libraries/doltcore/sqle/enginetest/dolt_engine_test.go
=> Skipping tests broken by recent changes to info schema (EXTRA)

go/cmd/dolt/commands/sqlserver/serverconfig.go, go/cmd/dolt/commands/sqlserver/yaml_config_test.go
=> Increased the default sql server timeout to 8 hours

bats/import-create-tables.bats, go/libraries/doltcore/mvdata/data_mover.go
Fixes https://github.com/dolthub/dolt/issues/1096
=> Fixed table import allowing NULLs in the primary key

bats/sql-server.bats, go/libraries/doltcore/sqle/dfunctions/merge.go
=> Ensure that MERGE() works properly with fast forward.

bats/sql-status.bats, bats/system-tables.bats, go/cmd/dolt/commands/commit.go, go/cmd/dolt/commands/status.go, go/libraries/doltcore/doltdb/system_table.go, go/libraries/doltcore/merge/merge.go, go/libraries/doltcore/sqle/database.go, go/libraries/doltcore/sqle/dtables/status_table.go
Implement the dolt_status table. Schema is of the form table_name, staged(bool), status,
=> Implement dolt status table

bats/sql.bats, go/cmd/dolt/commands/sql_print.go, go/libraries/doltcore/table/untyped/csv/writer.go, go/libraries/doltcore/table/untyped/csv/writer_test.go
Longext is no longer being exported properly in json and csv. This pr fixes that. Cc linked comment.
=> Address escaping in longtext/json

go/go.mod, go/go.sum
=> Updating to latest go-mysql-server

.github/workflows/cd-release.yaml
=> fix: avoid empty commit body issue

go/libraries/doltcore/sqle/dolt_map_iter.go, go/libraries/doltcore/sqle/index_row_iter.go, go/libraries/doltcore/sqle/rows.go, go/libraries/doltcore/sqle/tables.go, go/store/types/leaf_sequence.go, go/store/types/list.go, go/store/types/map_iterator.go, go/store/types/meta_sequence.go, go/store/types/sequence.go, go/store/types/sequence_cursor_test.go, go/store/types/tuple.go, go/store/types/value_decoder.go
Read tuples from sequences directly instead of using values.
=> Read tuples from sequences directly without conversion to Values

.github/scripts/performance-benchmarking/get-job-json.sh
This PR updates the performance benchmark job args required for the latest benchmarking job image.
=> Update args for performance benchmarking workflow

bats/sql-shell.bats, go/cmd/dolt/commands/sql_print.go
fixes issues where printf formatting was being unintentionally applied for some cli output
=> cli output fix

.github/scripts/performance-benchmarking/get-dolt-dolt-job-json.sh, .github/scripts/performance-benchmarking/get-mysql-dolt-job-json.sh
This PR updates args that will run custom lua scripts as part of the standard performance sysbench tests
=> Use custom lua scripts in performance benchmarking reports

.github/scripts/performance-benchmarking/get-mysql-dolt-job-json.sh
This PR fixes the divisor in the query and adds server names and versions to results.
=> Update performance benchmark query for release email

go/store/datas/database_common.go, go/store/datas/dataset_test.go
=> change panic to error for '.' in Dataset name

.github/workflows/ci-workflow-trigger.yaml
This PR updates the testing workflow to use the repository access token.
=> Update testing workflow to use repo access token

.github/workflows/ci-performance-benchmarks-release.yaml
This PR updates a workflow for testing workflow and repository dispatch triggers.
=> Update performance benchmarking release workflow for testing

.github/scripts/performance-benchmarking/run-benchmarks.sh
This PR updates the run benchmarks script to differentiate job names allowing for multiple PR benchmark runs by a single actor.
=> Update PR benchmarking script

.github/workflows/ci-performance-benchmarks-release.yaml, .github/workflows/ci-performance-benchmarks.yaml
/.github/workflows/{ci-performance-benchmarks-release.yaml, ci-perfor…mance-benchmarks.yaml}: update emails, allow actor to specify email on workflow dispatch trigger
=> [no-release-notes] Update emails for performance reports

go/libraries/doltcore/schema/col_coll.go
This PR fixes bug that breaks the `dolthub/bounties` edit count scoreboard
=> Fix col collection bug

go/cmd/dolt/commands/sql.go, go/libraries/doltcore/sqle/enginetest/dolt_engine_test.go
Used to turn on query analyzer debugging
=> Added DOLT_SQL_DEBUG_LOG and DOLT_SQL_DEBUG_LOG_VERBOSE environment vars

.github/workflows/ci-bats-tests.yaml, .github/workflows/ci-go-tests.yaml, bats/sql-delimiter.expect, bats/sql.bats
This PR pins the mac runner and attempts to handle `timeout` and `failed` `expect` cases.
=> [no-release-notes] /{.github,bats}: pin runner, add timeouts

go/libraries/doltcore/sqle/database.go, go/libraries/doltcore/sqle/dolt_index_test.go, go/libraries/doltcore/sqle/dtables/branches_table.go, go/libraries/doltcore/sqle/dtables/commit_ancestors_table.go, go/libraries/doltcore/sqle/dtables/commits_table.go, go/libraries/doltcore/sqle/dtables/conflicts_tables.go, go/libraries/doltcore/sqle/dtables/log_table.go, go/libraries/doltcore/sqle/dtables/status_table.go, go/libraries/doltcore/sqle/index_lookup.go, go/libraries/doltcore/sqle/indexed_dolt_table.go, go/libraries/doltcore/sqle/mergeable_indexes_setup_test.go, go/libraries/doltcore/sqle/rows.go, go/libraries/doltcore/sqle/schema_table.go, go/libraries/doltcore/sqle/sqlutil/single_partition.go, go/libraries/doltcore/sqle/tables.go, go/libraries/doltcore/table/keyless_reader.go, go/libraries/doltcore/table/pk_reader.go, go/libraries/doltcore/table/table_reader.go
fixes race condition that occurs when flushing on one routine and creating row iterators on another
=> race condition fix

.github/scripts/performance-benchmarking/get-dolt-dolt-job-json.sh, .github/scripts/performance-benchmarking/get-mysql-dolt-job-json.sh
Updates performance queries to use a minimum value of 0.001
=> [no-release-notes] /.github/scripts/performance-benchmarking: update performance queries

go/libraries/doltcore/sqle/logictest/main/BUILD.bazel
=> [no-release-notes] /go/libraries/doltcore/sqle/logictest/main/BUILD.bazel: move bazel file

go/cmd/dolt/commands/cnfcmds/resolve.go
=> improve conflict resolution error messages

bats/sql.bats, go/cmd/dolt/commands/sql.go, go/go.mod, go/go.sum, go/libraries/doltcore/doltdb/system_table.go, go/libraries/doltcore/schema/reserved_tags.go, go/libraries/doltcore/sqle/database.go, go/libraries/doltcore/sqle/enginetest/dolt_engine_test.go, go/libraries/doltcore/sqle/procedures_table.go
The 1337 PR! Adds stored procedures to Dolt!
=> Bump vitess & engine & add Stored Procedure interfaces

go/cmd/dolt/commands/merge.go
Issue ID : https://github.com/dolthub/dolt/issues/1307#issue-804175419
=> Refactoring error message in merge.go [ https://github.com/dolthub/dolt/issues/1307#issue-804175419 ]

go/libraries/doltcore/row/tagged_values.go, go/libraries/utils/iohelp/read.go, go/store/valuefile/file_value_store.go, go/store/valuefile/value_file.go, go/store/valuefile/value_file_test.go
Utility library used by bounties
=> chunk store in a file no manifest needed

go/libraries/utils/iohelp/copy.go
generally useful io helper method
=> add file copy helper method to iohelp package

bats/sql-shell.bats, go/libraries/doltcore/diff/diff_sink.go, go/libraries/doltcore/merge/conflict_sink.go
Columns with % signs were being printed using printf style functions which were looking at %s and escape characters.
=> diff printing fix

go/libraries/doltcore/diff/async_differ.go, go/libraries/doltcore/diff/async_differ_test.go, go/store/diff/diff.go, go/store/types/map.go, go/store/types/map_iterator.go, go/store/types/ordered_sequences_diff.go, go/store/types/tuple.go
allows for performance improvements.  Not used in dolt yet, but used by the bounty attribution code.
=> diff between a range of values

bats/verify-constraints.bats, go/libraries/doltcore/doltdb/foreign_key_coll.go, go/libraries/doltcore/sqle/enginetest/dolt_engine_test.go
Also unskipped some of the engine tests as the skips are no longer necessary. Fixes https://github.com/dolthub/dolt/issues/1432
=> Fixed verify-constraints reporting NULLs as errors

go/go.sum, go/libraries/doltcore/doltdb/foreign_key_coll.go, go/libraries/doltcore/row/keyless_row.go, go/libraries/doltcore/row/noms_row.go, go/libraries/doltcore/row/row.go, go/libraries/doltcore/schema/alterschema/modifycolumn.go, go/libraries/doltcore/sqle/database.go, go/libraries/doltcore/sqle/table_editor_fk_test.go, go/libraries/doltcore/sqle/tables.go, go/libraries/doltcore/table/editor/index_editor_test.go, go/libraries/doltcore/table/editor/pk_table_editor.go, go/libraries/doltcore/table/editor/pk_table_editor_test.go, go/libraries/doltcore/table/editor/sessioned_table_editor.go, go/libraries/doltcore/table/editor/table_edit_session.go, integration-tests/bats/foreign-keys.bats
This only adds support for self referential foreign keys that consist of a single column, and also where the column with the constraint comes after the referenced column (in schema order).
=> Added limited self referential foreign key support

docs/quickstart.md
Just edited the lead in to be a little more hype.
=> Tim's edits to quick start guide

go/libraries/doltcore/doltdb/table.go, go/libraries/doltcore/sqle/dtables/conflicts_tables.go, integration-tests/bats/conflict-detection.bats, integration-tests/bats/sql-conflicts.bats
fix panic that occurs when a delete query against a conflict table affects 0 rows
=> panic fix for 0 rows resolved

go/libraries/doltcore/doltdb/root_val.go, integration-tests/bats/back-compat.bats
=> libraries/doltcore/doltdb: fix dropped errors

go/cmd/dolt/dolt.go
One day I will get automation right on the first try
=> Properly reverts the version string on Dolt as automation does the fix

go/libraries/doltcore/sqle/integration_test/json_value_test.go, go/libraries/doltcore/sqle/json/noms_json_value_test.go, go/libraries/doltcore/sqle/json/testutils.go, go/store/types/rolling_value_hasher.go
Final checks before releasing JSON: 
- Round trip large JSON documents
- Assert JSON values are structurally sharing
=> /go/libraries/doltcore/sqle/{integration_test, json}: Test large JSON docs

go/cmd/dolt/dolt.go, go/libraries/doltcore/schema/typeinfo/typeinfo.go, go/libraries/doltcore/schema/typeinfo/typeinfo_test.go, go/libraries/doltcore/sqle/enginetest/dolt_engine_test.go, go/libraries/doltcore/sqle/integration_test/json_value_test.go, go/libraries/doltcore/sqle/json/noms_json_value.go, integration-tests/bats/json.bats, integration-tests/bats/sql-server.bats
Removes feature flag for `json` type, making it available to users.
=> /go/libraries/doltcore/schema/typeinfo: Removing feature flag for JSON type

go/cmd/dolt/commands/reset.go, go/go.mod, go/libraries/doltcore/doltdb/commit_spec.go, go/libraries/doltcore/env/actions/reset.go, go/libraries/doltcore/sqle/json/noms_json_value_test.go, integration-tests/bats/docs.bats, integration-tests/bats/status.bats
This pr addresses the first part of this issue #1492
=> Add `dolt reset HEAD~` 

go/go.mod, go/go.sum, integration-tests/bats/auto_increment.bats
=> /go/libraries/doltcore/sqle: Fix `SELECT INTO ...` bug for `AUTO_INCREMENT` columns

go/libraries/doltcore/schema/encoding/schema_marshaling.go, go/libraries/doltcore/schema/schema_impl.go
Optimization decreases the amount of time spent unmarshalling schemas.
=> unmarshalled schema cache

README.md
I had created chocolatey package for dolt.
source: https://github.com/zverev-iv/choco-dolt
result: https://chocolatey.org/packages/dolt/
P.S. please wait for package approved before merge this PR. I'll update this PR when checks completed
=> Added info about windows chocolatey package

.github/release-drafter.yml, .github/workflows/cd-release-notes-drafter.yaml, .github/workflows/cd-release.yaml
=> Revert "Db/use release gen branch"

integration-tests/bats/system-tables.bats
Create a skipped bats test that defines the behavior we want for dolt_branches as described in this issue: #1592
=> create skipped test for dolt_branches with remotes

go/cmd/dolt/commands/merge.go, go/libraries/doltcore/doltdb/commit.go, go/store/chunks/memory_store.go, go/store/datas/database.go, go/store/nbs/file_manifest.go, go/store/spec/spec.go
Cleaned up unreachable err handling code
=> Fixed bugs in noms cat and noms show. Fixed some typos. 

go/go.sum
=> [no-release-notes] /go/go.sum: update go.sum

go/Godeps/LICENSES, go/go.mod, go/go.sum
```
$ cd ./go
$ go get -u github.com/dolthub/<dependency>/go@<commit>
```
If this PR has passing CI, a `check-suite-ok` label will automatically be applied to it.
=> [auto-bump] [no-release-notes] dependency by reltuk

go/go.mod, go/go.sum, go/libraries/doltcore/sqle/database.go, go/libraries/doltcore/sqle/dolt_session.go, go/libraries/doltcore/sqle/transactions.go
Savepoints are processed as well, but rolling back to a savepoint doesn't work yet due to a bug in table caching
=> Support for rollback

go/libraries/doltcore/table/editor/index_editor.go, go/libraries/doltcore/table/editor/pk_table_editor.go
Currently foreign keys necessitate a flush whenever you want to check a table editor's indexes for a partial key. With the recent index editor rewrite adding an efficient way to check partial keys, we can extend that and use it for foreign key checks as well.
=> Removed flushing on foreign key checks for tables with pks

go/go.mod, go/go.sum
=> [auto-bump] [no-release-notes] dependency by max-hoffman

go/go.mod, go/go.sum
=> [auto-bump] [no-release-notes] dependency by zachmu

go/go.mod, go/go.sum
=> [auto-bump] [no-release-notes] dependency by coffeegoddd

integration-tests/bats/merge.bats
Skipped BATS for: https://github.com/dolthub/dolt/issues/1782
=> [no-release-notes] added skipped bats for unique index conflicts

go/libraries/doltcore/sqle/expreval/expression_evaluator.go, integration-tests/bats/sql.bats
Lets you do IN clause on dolt table
=> Add in for filtered table

go/libraries/doltcore/merge/merge.go, integration-tests/bats/index.bats
Fixes https://github.com/dolthub/dolt/issues/1824
=> Fixed #1824: Bug with adding index on merge

integration-tests/bats/log.bats
Tested these options added in: #1831
=> Added bats tests for dolt log --merges, --parents, and --min-parents

go/go.mod, go/go.sum
=> [auto-bump] [no-release-notes] dependency by andrew-wm-arthur

go/go.mod, go/go.sum
=> [no-release-notes] Add ReadOnlyDatabase engine tests

go/cmd/dolt/commands/diff.go, integration-tests/bats/diff.bats
=> go/cmd/dolt/commands/diff.go: Return VerboseError rather than panic

go/cmd/dolt/commands/diff.go, integration-tests/bats/schema-changes.bats
This is much more descriptive IMO, but lmk if you have suggestions for how to word it.
=> Improve Error message when merge fails because of different primary keys

go/store/cmd/noms/noms_show.go, go/store/cmd/noms/noms_show_test.go, go/store/types/type.go
Old output
```
map {
"IP_OP": #mt0robnd5t9nr7gj5gch2eec60u9a8k0,
}
```
New output
```
Map<String,Ref<Map<Tuple<Union<String,Uint>>,Tuple<Union<>>>>> - map {
"IP_OP": #mt0robnd5t9nr7gj5gch2eec60u9a8k0,
}
```
=> print types in noms show command

integration-tests/bats/constraint-violations.bats
Tests for https://github.com/dolthub/dolt/pull/1852
This only tests the merge logic.
=> FK & UNQ Constraint Violation Tests

go/cmd/dolt/commands/merge.go, go/libraries/doltcore/diff/async_differ.go, go/libraries/doltcore/doltdb/errors.go, go/libraries/doltcore/doltdb/foreign_key_coll.go, go/libraries/doltcore/doltdb/root_val.go, go/libraries/doltcore/doltdb/system_table.go, go/libraries/doltcore/doltdb/table.go, go/libraries/doltcore/env/actions/commit.go, go/libraries/doltcore/env/actions/errors.go, go/libraries/doltcore/env/actions/staged.go, go/libraries/doltcore/merge/constraint_violations.go, go/libraries/doltcore/merge/merge.go, go/libraries/doltcore/merge/unique_key_error.go, go/libraries/doltcore/schema/index.go, go/libraries/doltcore/schema/reserved_tags.go, go/libraries/doltcore/sqle/database.go, go/libraries/doltcore/sqle/dfunctions/dolt_merge.go, go/libraries/doltcore/sqle/dtables/constraint_violations.go, go/libraries/doltcore/sqle/dtables/table_of_tables_with_violations.go, go/libraries/doltcore/sqle/table_editor.go, go/libraries/doltcore/table/editor/index_editor.go, go/libraries/doltcore/table/editor/keyless_table_editor.go, go/libraries/doltcore/table/editor/pk_table_editor.go, go/libraries/doltcore/table/editor/sessioned_table_editor.go, go/store/types/map_editor.go, go/store/types/tuple.go, integration-tests/bats/constraint-violations.bats, integration-tests/bats/foreign-keys.bats, integration-tests/bats/index.bats
Implements foreign key and unique key constraint violations.
Tests may be found at https://github.com/dolthub/dolt/pull/1870
=> FK & UNQ Constraint Violations

go/cmd/dolt/dolt.go, go/libraries/doltcore/table/editor/sessioned_table_editor.go
=> Small fixes

go/libraries/doltcore/sqle/dsess/session.go, integration-tests/bats/sql-checkout.bats, integration-tests/bats/sql.bats
Also fixed a bug where it wasn't being updated on a branch change
=> Allow setting head ref session var, e.g. @@mydb_head_ref to change branches

go/libraries/doltcore/doltdb/table.go, go/libraries/doltcore/env/actions/staged.go, integration-tests/bats/constraint-violations.bats, integration-tests/bats/merge.bats, integration-tests/bats/triggers.bats
delay all conflict/constraint-violation checks until commit time
=> [no-release-notes] Remove conflict/constraint checks from staging

go/libraries/doltcore/doltdb/workingset.go, integration-tests/bats/merge.bats, integration-tests/bats/sql-merge.bats
fix for https://github.com/dolthub/dolt/issues/1973
=> Reset staging index on `dolt merge --abort` 

integration-tests/bats/sql-merge.bats
added as part of a sanity check
=> [no-release-notes] Vinai/slight bats edit

integration-tests/bats/README.md
Add the prerequisites to running bats tests to the README
=> Update BATS README

.github/workflows/ci-bats-windows.yaml
This PR runs bats tests on windows in parallel using a github actions runner per test file
=> [no-release-notes] /.github/workflows/ci-bats-windows.yaml: iterating on bats, job per file

integration-tests/bats/sql-create-tables.bats
=> Fix and unskip keyword test

integration-tests/bats/config-home.bats
=> Added a test for git config and HOME env var

integration-tests/bats/config-home.bats, integration-tests/bats/status.bats
This reproduces the failures in #751
=> Skipped test for error when resetting a renamed table

go/cmd/dolt/commands/fetch.go, go/cmd/dolt/commands/schcmds/import.go
=> Fixed error handling in fetch, dropped error in schema import

integration-tests/bats/conflict-detection-2.bats
This test tests the conflict resolution workflow where you get conflicts, resolve using --ours or --theirs but still want to modify the working set. It also tests the output of `dolt conflicts cat` when there are no conflicts.
=> Added skipped bats test for some dolt conflicts and associated warnings I was seeing

go/go.mod, go/go.sum
=> [auto-bump] [no-release-notes] dependency by VinaiRachakonda

go/cmd/dolt/commands/clone.go, go/go.sum, integration-tests/bats/remotes.bats
=> Fix bug on deleting parents of user created directory

go/cmd/dolt/cli/arg_parser_helpers.go, go/cmd/dolt/commands/revert.go, go/libraries/doltcore/sqle/dfunctions/revert.go, integration-tests/bats/revert.bats
This pr adds the --author parameter for dolt revert and DOLT_REVERT.
=> Implement --author for dolt revert and DOLT_REVERT()

go/cmd/dolt/commands/sqlserver/sqlserver.go, go/cmd/dolt/dolt.go
Also install a handler for sql-server so that the server gets stopped cleanly
when we receive SIGINT or SIGTERM.
=> go/cmd/dolt: Handle SIGINT, SIGTERM with a context cancel.

integration-tests/MySQLDockerfile, integration-tests/mysql-client-tests/mysql-client-tests.bats, integration-tests/mysql-client-tests/r/mariadb-test.r, integration-tests/mysql-client-tests/r/rmariadb-test.r, integration-tests/mysql-client-tests/r/rmysql-test.r
executes the standard query/response set, and then tests prepared statements separately.
=> RMariaDB mysql-integration-test

go/libraries/doltcore/table/editor/sessioned_table_editor.go, integration-tests/bats/foreign-keys.bats, integration-tests/bats/keyless-foreign-keys.bats
=> Only show key name, not column tag number

go/cmd/dolt/dolt.go, go/libraries/doltcore/env/paths.go, integration-tests/bats/no-repo.bats
https://github.com/dolthub/dolt/issues/2147
=> no panic if HOME does not exist

go/cmd/dolt/dolt.go
I always forget how to connect to the pprof server so I've added a message that comes up when you run dolt with the --pprof-server flag.
=> pprof-server usage message on start

go/cmd/dolt/commands/tblcmds/export.go, go/libraries/doltcore/sqle/sqlfmt/row_fmt.go, integration-tests/bats/export-tables.bats
=> Bug fix for SQL export of enum columns

go/libraries/doltcore/sqle/sqlfmt/row_fmt.go, integration-tests/bats/export-tables.bats
=> Added a test for disabling foreign keys during SQL export

go/cmd/dolt/commands/dump.go, go/cmd/dolt/commands/tblcmds/export.go, go/cmd/dolt/commands/tblcmds/import.go, go/cmd/dolt/dolt.go, go/gen/proto/dolt/services/eventsapi/v1alpha1/event_constants.pb.go, go/libraries/doltcore/mvdata/data_loc.go, go/libraries/doltcore/mvdata/data_loc_test.go, go/libraries/doltcore/mvdata/file_data_loc.go, go/libraries/doltcore/mvdata/stream_data_loc.go, go/libraries/doltcore/mvdata/table_data_loc.go, go/libraries/doltcore/sqle/dsess/dolt_session.go, go/libraries/doltcore/sqle/dsess/session_state_adapter.go, go/libraries/doltcore/table/typed/json/writer.go, go/libraries/doltcore/table/untyped/csv/writer.go, go/libraries/doltcore/table/untyped/csv/writer_test.go, go/libraries/doltcore/table/untyped/sqlexport/sqlwriter.go, go/libraries/utils/filesys/fs.go, go/libraries/utils/filesys/inmemfs.go, go/libraries/utils/filesys/localfs.go, integration-tests/bats/dump.bats, integration-tests/bats/helper/employees-tbl.json
added csv file format for dolt dump command
=> doltdump - add csv format

go/cmd/dolt/commands/push.go, go/libraries/doltcore/doltdb/doltdb.go, go/libraries/doltcore/env/actions/commitwalk/commitwalk_test.go, go/libraries/doltcore/env/actions/remotes.go, integration-tests/bats/remotes.bats
dolt fetch: prints many empty newline to terminal issue - fixed
=> fix fetch newline issue

README.md, go/cmd/dolt/commands/dump.go, integration-tests/bats/dump.bats
added handling json format in dump command
=> dump - json format

go/libraries/doltcore/env/actions/remotes.go, integration-tests/bats/remotes.bats
added newline printing statements for dolt push command
=> dolt push - no newline after result printed bug

go/Godeps/LICENSES, go/go.mod, go/go.sum, go/store/nbs/benchmarks/gen/rolling_value_hasher.go, go/store/perf/hash-perf-rig/main.go, go/store/types/rolling_value_hasher.go
=> go/go.mod: github.com/kch42/buzhash -> github.com/silvasur/buzhash.

go/go.mod, go/go.sum
=> [auto-bump] [no-release-notes] dependency by JCOR11599

go/go.mod, go/go.sum, go/libraries/doltcore/sqle/dolt_index.go, go/libraries/doltcore/sqle/enginetest/dolt_engine_test.go, go/libraries/doltcore/sqle/mergeable_indexes_setup_test.go, go/libraries/doltcore/sqle/mergeable_indexes_test.go
=> [auto-bump] [no-release-notes] dependency by Hydrocharged

go/cmd/dolt/commands/blame.go, integration-tests/bats/blame.bats
added sort function in dolt blame, uses first pk to sort if there are multiple pk
=> sort dolt blame result by pk

go/cmd/dolt/cli/arg_parser_helpers.go, go/cmd/dolt/commands/checkout.go, go/libraries/doltcore/dtestutils/testcommands/command.go, go/libraries/doltcore/dtestutils/testcommands/multienv.go, go/libraries/doltcore/env/actions/branch.go, integration-tests/bats/checkout.bats, integration-tests/bats/remotes.bats
added -f 'force' flag to dolt checkout. with force flag, the current changes will be wiped
=> add force flag to dolt checkout

go/cmd/dolt/cli/arg_parser_helpers.go, go/libraries/doltcore/sqle/dfunctions/dolt_branch.go, go/libraries/doltcore/sqle/dfunctions/init.go, go/libraries/doltcore/table/editor/index_edit_accumulator.go, go/libraries/doltcore/table/editor/table_edit_accumulator_test.go, integration-tests/bats/sql-branch.bats, integration-tests/bats/sql-server-mysql.expect, integration-tests/bats/sql-server.bats
IndexEditAccumulator has the same bug TableEditAccumulator had in #2278. The result is that large edits of indexes can drop index entries.
=> doltcore/table/editor: index_edit_accumulator: Correctly order the most recently accumulated edits after all flushed edits.

go/go.mod, go/go.sum, integration-tests/bats/no-repo.bats
This fixes https://github.com/dolthub/dolt/issues/2559
Also fixes https://github.com/dolthub/dolt/issues/2534
=> Fix bad error message in SHOW TABLES when no database selected

go/cmd/dolt/commands/tblcmds/import.go, go/libraries/doltcore/mvdata/data_mover.go, go/libraries/doltcore/mvdata/engine_mover.go, integration-tests/bats/import-create-tables.bats, integration-tests/bats/import-replace-tables.bats, integration-tests/bats/import-update-tables.bats
This pr addresses #2586 and adds additional test cases for partial updates
=> Rewrite portion of the import path to better support partials

go/libraries/doltcore/env/actions/tag.go
=> Add CreateTagOnDB and DeleteTagsOnDB

integration-tests/bats/sql-check-constraints.bats, integration-tests/bats/sql.bats
Factored out bats tests for check constraints into their own file. Added skipped test for alter removing constraints.
=> Bats test refactoring for CHECK constraints

go/libraries/doltcore/dtestutils/data.go, go/libraries/doltcore/schema/alterschema/addcolumn.go, go/libraries/doltcore/schema/alterschema/addcolumn_test.go, go/libraries/doltcore/schema/alterschema/addpk.go, go/libraries/doltcore/schema/alterschema/addpk_test.go, go/libraries/doltcore/schema/alterschema/dropcolumn.go, go/libraries/doltcore/schema/alterschema/dropcolumn_test.go, go/libraries/doltcore/schema/alterschema/droppk.go, go/libraries/doltcore/schema/alterschema/modifycolumn.go, go/libraries/doltcore/schema/alterschema/modifycolumn_test.go, go/libraries/doltcore/table/untyped/sqlexport/sqlwriter_test.go, integration-tests/bats/schema-changes.bats, integration-tests/bats/sql-check-constraints.bats
Resolves: https://github.com/dolthub/dolt/issues/2672
Confirmed that alterschema tests now cover all schema properties.
=> Bug fix for dropped table check constraints when altering a table.

go/go.mod, go/go.sum
=> [auto-bump] [no-release-notes] dependency by jennifersp

go/cmd/dolt/commands/login.go, integration-tests/bats/no-repo.bats
TODO:
- <del>should also quit on error request cancelled<del>
SIGINT is what cancels request, so whole thing should just quit anyway.
=> Fix Dolt Login unable to exit on SIGINT

integration-tests/bats/drop-create.bats
added bats test for "DROP TABLE otherdb.table;" statement
=> add bats test for DROP TABLE for different database

go/cmd/dolt/commands/sqlserver/server.go
Config users were always being added. This has been fixed.
=> Config users are ignored if privilege users are present

integration-tests/bats/auto_increment.bats, integration-tests/bats/drop-create.bats, integration-tests/bats/foreign-keys.bats, integration-tests/bats/index.bats
- un-skipped some tests that are resolved
- fixed some test typos
- added test for add foreign key constraint bug
=> unskip fixed tests

go/cmd/dolt/commands/tblcmds/import.go, integration-tests/bats/import-create-tables.bats, integration-tests/bats/import-update-tables.bats
Adds a flag to skip rows that are printed by --continue.
=> Add the ignore skipped row param

go/libraries/doltcore/table/editor/keyless_table_editor.go, integration-tests/bats/import-update-tables.bats, integration-tests/bats/keyless.bats
Delete all pending changes when an error occurs.
=> Allow Rollback on Keyless Tables

go/go.mod, go/go.sum
```
$ cd ./go
```
This dependency bump fixes #2939
=> [auto-bump] [no-release-notes] dependency by druvv

integration-tests/bats/import-update-tables.bats
=> Skipped bats test for updating tables with dashes in the name using `dolt table import -u`

go/go.mod, go/go.sum, integration-tests/bats/sql-use.expect
=> Bump GoMod and Trim the sql-use.expect

go/libraries/doltcore/mvdata/engine_table_reader.go, go/libraries/doltcore/mvdata/engine_table_writer.go, integration-tests/bats/import-update-tables.bats
=> Escape the given tablename in the engine_table_reader

go/libraries/doltcore/dtestutils/testcommands/multienv.go
This fixes several `err` variables that were set but then unhandled, as well as an `os.Chdir()` that looked a little risky without one.
=> libraries/doltcore/dtestutils/testcommands: fix dropped errors

go/libraries/doltcore/schema/alterschema/droppk_test.go, go/libraries/doltcore/schema/index_coll.go, go/libraries/doltcore/table/editor/creation/foreign_key.go, integration-tests/bats/foreign-keys.bats, integration-tests/bats/sql-spatial-types.bats
Fixed https://github.com/dolthub/dolt/issues/3023
Fixes https://github.com/dolthub/dolt/issues/3028
=> Fix two bugs in foreign key creation

go/go.mod, go/go.sum, go/libraries/doltcore/sqle/enginetest/dolt_engine_test.go, integration-tests/bats/index.bats
Bump GMS to fit in multi-alter ddl changes.
=> Build Dolt against GMS to test multi-alter DDL changes

go/libraries/doltcore/sqle/system_variables.go, integration-tests/bats/sql-server-config.bats
Fix for https://github.com/dolthub/dolt/issues/3104
=> Make `dolt_replicate_heads` and `dolt_replicate_all_heads` both Global and Session variable

go/libraries/doltcore/sqle/enginetest/dolt_engine_test.go, go/libraries/doltcore/sqle/enginetest/dolt_queries.go
Following up on: https://github.com/dolthub/dolt/pull/2913 to add tests for CheckPrivileges logic
=> [no-release-notes] Adding tests for dolt_diff table function CheckPrivileges code

go/go.mod, go/go.sum, go/libraries/doltcore/sqle/enginetest/dolt_engine_test.go
=> [auto-bump] [no-release-notes] dependency by fulghum

.github/workflows/ci-go-tests.yaml, go/go.mod, go/go.sum, go/libraries/doltcore/sqle/enginetest/dolt_engine_test.go, go/libraries/doltcore/sqle/indexed_dolt_table.go, go/libraries/doltcore/sqle/tables.go, integration-tests/mysql-client-tests/r/rmariadb-test.r
GMS dependency PR: https://github.com/dolthub/go-mysql-server/pull/795
=> Prepared statement GMS bump

go/cmd/dolt/commands/pull.go, integration-tests/bats/remotes.bats
fix for: https://github.com/dolthub/dolt/issues/3113
=> `dolt pull` should do `dolt fetch` before

go/libraries/doltcore/doltdb/doltdb.go, go/libraries/doltcore/doltdb/errors.go, go/libraries/doltcore/env/actions/branch.go, go/libraries/doltcore/sqle/enginetest/dolt_queries.go
This reverts commit 8cd5f16de103f92b40a65c099b82caef558e7608, reversing
changes made to f857be6c4a4d51422f038a87706f08b019179897.
=> Fix ErrBranchNotFound

integration-tests/bats/dump.bats
- Skips keyless tables in tests
- Adds primary key where primary key was intended
@andrew-wm-arthur Do we want to add comprehensive tests for dump for each type, etc. right now?
=> integration-tests/bats: update dolt dump bats test for v1 storage format

go/cmd/dolt/commands/pull.go, integration-tests/bats/remotes.bats
Fix for: https://github.com/dolthub/dolt/issues/3309
=> Incorrectly trying to merge every branch when fetching

go/libraries/doltcore/sqle/dprocedures/init.go, integration-tests/bats/revert.bats, integration-tests/bats/sql-add.bats, integration-tests/bats/sql-branch.bats, integration-tests/bats/sql-checkout.bats, integration-tests/bats/sql-commit.bats, integration-tests/bats/sql-fetch.bats, integration-tests/bats/sql-merge.bats, integration-tests/bats/sql-pull.bats, integration-tests/bats/sql-push.bats, integration-tests/bats/sql-reset.bats, integration-tests/bats/verify-constraints.bats
```SQL
> call dbranch('-b', 'new')
> call dadd('.');
> call dcommit('-am', 'message');
> call dreset('--hard', 'main')
```
=> short dolt procs

go/libraries/doltcore/sqle/enginetest/dolt_engine_test.go, go/libraries/doltcore/sqle/enginetest/dolt_harness.go, go/libraries/doltcore/sqle/index/mergeable_indexes_test.go, go/libraries/doltcore/sqle/index/testutils.go, go/libraries/doltcore/sqle/tables.go, go/libraries/doltcore/sqle/writer/noms_fk_indexer.go, go/libraries/doltcore/sqle/writer/noms_table_writer.go, go/libraries/doltcore/sqle/writer/prolly_fk_indexer.go, go/libraries/doltcore/sqle/writer/prolly_index_writer.go, go/libraries/doltcore/sqle/writer/prolly_table_writer.go, go/libraries/doltcore/sqle/writer/prolly_write_session.go, go/libraries/doltcore/sqle/writer/sessioned_table_editor.go, go/serial/schema.fbs, go/store/prolly/mutable_map.go, go/store/prolly/mutable_map_write_test.go, go/store/prolly/range_iter.go, go/store/prolly/tree/merge.go
This adds foreign key support to the new format.
=> Implemented foreign keys for the new format

go/libraries/doltcore/sqle/dsess/session.go, go/libraries/doltcore/sqle/enginetest/dolt_transaction_queries.go
Moving a test case from GMS to Dolt, as requested in: https://github.com/dolthub/go-mysql-server/pull/1013
Depends on bug fix in: https://github.com/dolthub/go-mysql-server/pull/1013
=> [no-release-notes] Moving a Dolt-specific transaction test from GMS into Dolt repo.

go/libraries/doltcore/sqle/enginetest/dolt_engine_test.go, go/libraries/doltcore/sqle/enginetest/dolt_transaction_queries.go
Just defining some of the existing behavior.
=> [no-release-notes] go/libraries/doltcore/sqle: add transaction test for constraint violations

go/store/prolly/tree/chunker.go, go/store/prolly/tree/chunker_test.go, go/store/prolly/tree/mutator.go, go/store/prolly/tree/node_cursor.go
Logical refactor that makes it easier to add documentation for
chunker.AdvanceTo.
=> [no-release-notes] Docstrings for chunker

go/cmd/dolt/commands/init.go, go/cmd/dolt/commands/init_test.go, integration-tests/bats/helper/common.bash, integration-tests/bats/init.bats
Fixes: https://github.com/dolthub/dolt/issues/3546
=> Bug fix for not saving explicit name and email settings to local config

go/libraries/doltcore/diff/table_deltas.go, go/libraries/doltcore/sqle/dtables/unscoped_diff_table.go, go/libraries/doltcore/sqle/enginetest/dolt_queries.go
Doc updates: https://github.com/dolthub/docs/pull/631
=> Adding working set changes to unscoped `dolt_diff` system table 

integration-tests/bats/constraint-violations.bats, integration-tests/bats/helper/common.bash, integration-tests/bats/merge.bats, integration-tests/bats/sql-merge.bats
Will revert this commit when it's clear what is causing the tests to flake.
=> [no-release-notes] log $output when $status is a mismatch in merge tests

README.md
=> Add missing semicolon

integration-tests/bats/types.bats
Add a skipped bats for bug in mysql double types
=> [skip ci] [no-release-notes] Add skipped bats test for parsing double types with precision

go/libraries/doltcore/doltdb/doltdb_test.go, go/libraries/doltcore/merge/conflict_source.go, go/libraries/doltcore/rowconv/joiner.go, go/libraries/doltcore/schema/reserved_tags.go, go/libraries/doltcore/sqle/dtables/conflicts_tables_prolly.go, go/libraries/doltcore/sqle/enginetest/dolt_engine_test.go, go/libraries/doltcore/sqle/enginetest/dolt_queries.go
`our_diff_type` and `their_diff_type` reports the row diff between the base and our/their rows. It is one of `added`, `modified`, or `removed`.
=> Adds `our_diff_type` and `their_diff_type` to `dolt_conflicts_table_name`

go/go.mod, go/go.sum, go/libraries/doltcore/schema/schema.go, go/libraries/doltcore/schema/schema_test.go, go/libraries/doltcore/sqle/writer/prolly_fk_indexer.go, integration-tests/bats/foreign-keys-invert-pk.bats
=> [auto-bump] [no-release-notes] Unskip foreign-keys-invert-pk.bats for new format

go/cmd/dolt/commands/sqlserver/serverconfig.go, go/cmd/dolt/commands/sqlserver/sqlserver.go, go/cmd/dolt/commands/sqlserver/yaml_config.go, integration-tests/bats/sql-privs.bats
Fix for: https://github.com/dolthub/dolt/issues/3865
=> yaml config also initialize `.doltcfg` directories

go/go.mod, go/go.sum
=> [auto-bump] [no-release-notes] dependency by tbantle22

go/libraries/doltcore/migrate/transform.go, go/libraries/doltcore/migrate/traverse.go, go/libraries/doltcore/migrate/validation.go, go/libraries/doltcore/sqle/rows.go, go/libraries/doltcore/sqle/schema_table.go, integration-tests/bats/migrate.bats
Adds validation stages for `dolt migrate`. Patches schemas for `dolt_docs` and `dolt_schemas` tables
=> [no-release-notes] Added data validation to `dolt migrate`

go/cmd/dolt/commands/merge.go, go/libraries/doltcore/merge/merge.go, go/libraries/doltcore/merge/merge_rows.go, go/libraries/doltcore/merge/merge_schema.go
See https://github.com/dolthub/dolt/issues/3963
=> improve error message for merge when two columns have the same tag

go/store/nbs/store.go, go/store/nbs/store_test.go
Found this issue while running tests in the new format with the -race flag enabled in ld. Harmless issue as it is only used in tests.
=> Fix racey updates of NomsBlockStore putCount

go/go.mod, go/go.sum, go/libraries/doltcore/sqle/enginetest/ddl_queries.go, go/libraries/doltcore/sqle/sqlfmt/schema_fmt_test.go, integration-tests/bats/1pk5col-ints.bats, integration-tests/bats/diff.bats, integration-tests/bats/migration-integration.bats, integration-tests/bats/schema-import.bats, integration-tests/bats/types.bats
Depends on: https://github.com/dolthub/go-mysql-server/pull/1179
=> Preserve enum value case when emitting type metadata

go/cmd/dolt/commands/sql.go, go/cmd/dolt/commands/sqlserver/sqlserver.go, integration-tests/bats/sql-privs.bats, integration-tests/bats/sql-shell.bats, integration-tests/bats/sql.bats
fixes: https://github.com/dolthub/dolt/issues/4088
=> don't overwrite parent's `.doltcfg` if current is missing

README.md
Socket interface supported but not on by default.
=> Update README to reflect socket interface release

go/cmd/dolt/commands/diff.go, integration-tests/bats/diff.bats
=> Fix dolt diff --limit

go/cmd/dolt/commands/tblcmds/export.go, go/cmd/dolt/commands/tblcmds/import.go, integration-tests/bats/export-tables.bats
Fix for: 
- https://github.com/dolthub/dolt/issues/4149
=> [no-release-notes] print success not error

go/store/prolly/map.go, go/store/prolly/map_range_diff_test.go, go/store/prolly/ordered_tree.go, go/store/prolly/range.go, go/store/prolly/tree/diff.go
This PR adds `prolly.RangeDiffMaps` which can be used to get the diffs between two prolly map within a certain key range.
=> Add `prolly.RangeDiffMaps`

go/cmd/dolt/cli/arg_parser_helpers.go
Quick arg doc update for behavior change in: https://github.com/dolthub/dolt/pull/4161
=> Updating arg docs for `dolt commit -a` 

go/cmd/dolt/commands/version.go, integration-tests/bats/no-repo.bats
Fixes #4154 
Not sure if tests are required for this?
=> Fix dolt version error when repo state is missing

go/libraries/doltcore/migrate/environment.go, integration-tests/bats/migration-integration.bats
fixes https://github.com/dolthub/dolt/issues/4234
=> go/doltcore/migrate: Migrate oldgen manifest in dolt migrate

go/store/prolly/map.go, go/store/prolly/map_diff_key_range_test.go, go/store/prolly/map_diff_test.go, go/store/prolly/map_test.go, go/store/prolly/mutable_map.go, go/store/prolly/ordered_tree.go, go/store/prolly/range_iter_test.go, go/store/prolly/tree/node_cursor.go, go/store/prolly/tree/node_cursor_test.go, go/store/prolly/utils_test.go
Adds functions to support operating on a physical key range. 
Continuation of #4247 and #4258
=> [store/prolly] Add key range machinery

go/libraries/doltcore/sqle/indexed_dolt_table.go
=> PartitionRows lookupBuilder access race

go/libraries/doltcore/table/untyped/csv/reader.go, integration-tests/bats/import-create-tables.bats
Closes: https://github.com/dolthub/dolt/issues/3790
=> trim byte order mark present in UTF-8 encoded files

go/cmd/dolt/commands/cnfcmds/auto_resolve.go, go/cmd/dolt/commands/cnfcmds/cat.go, integration-tests/bats/conflict-detection-2.bats
=> Escape columns and table names in conflict commands

integration-tests/bats/README.md, integration-tests/bats/export-tables.bats
=> Updated bats README and a test to make it easier to get started

go/cmd/dolt/commands/engine/sqlengine.go, go/cmd/dolt/commands/sqlserver/server.go, go/cmd/dolt/commands/sqlserver/serverconfig.go, go/cmd/dolt/commands/sqlserver/yaml_config.go, go/libraries/doltcore/sqle/cluster/assume_role.go, go/libraries/doltcore/sqle/cluster/config.go, go/libraries/doltcore/sqle/cluster/controller.go, go/libraries/doltcore/sqle/database_provider.go, integration-tests/bats/helper/query-server-common.bash, integration-tests/bats/sql-server-cluster.bats
This is just the variable persistence and some validation and rules around how they can transition.
=> sql-server: Implement dolt_cluster_role, dolt_cluster_role_epoch variables, dolt_assume_cluster_role procedure.

go/store/types/serial_message.go, integration-tests/bats/garbage_collection.bats
- Reordered table serial message address walk to match the definitions in table.fbs
- Now walks artifact ref hash. Previously we were not walking it :(
=> Walk artifacts ref

go/cmd/dolt/commands/commit.go
Dolt tries getting system default editor if it's set, else it tries getting dolt `core.editor` if it's set, else it uses `vim` editor to get commit message. If `vim` is not installed on user's system, then it uses auto-generated commit message.
=> use auto-generated commit message if editor cannot be opened or got empty result

go/cmd/dolt/commands/sqlserver/sqlclient.go, go/cmd/dolt/dolt.go, go/libraries/doltcore/branch_control/access.go, go/libraries/doltcore/branch_control/binlog.go, go/libraries/doltcore/branch_control/branch_control.go, go/libraries/doltcore/branch_control/expr_parser.go, go/libraries/doltcore/branch_control/expr_parser_test.go, go/libraries/doltcore/branch_control/namespace.go, go/libraries/doltcore/sqle/database.go, go/libraries/doltcore/sqle/dfunctions/dolt_branch.go, go/libraries/doltcore/sqle/dsess/session.go, go/libraries/doltcore/sqle/dtables/branch_control_table.go, go/libraries/doltcore/sqle/dtables/branch_namespace_control.go, go/libraries/doltcore/sqle/enginetest/dolt_engine_test.go, go/libraries/doltcore/sqle/tables.go
This is an aggregate of
* https://github.com/dolthub/dolt/pull/4507
* https://github.com/dolthub/dolt/pull/4508
* https://github.com/dolthub/dolt/pull/4509
* https://github.com/dolthub/dolt/pull/4510
along with each PR's respective feedback.
=> Branch Control Pt. 5

go/store/val/tuple_descriptor.go
=> go/store/val: Add env var for disabling fast fixed-width access

integration-tests/bats/deleted-branches.bats, integration-tests/bats/helper/query-server-common.bash, integration-tests/bats/multidb.bats, integration-tests/bats/remotes-sql-server.bats, integration-tests/bats/schema-changes.bats, integration-tests/bats/sql-privs.bats, integration-tests/bats/sql-server.bats
Then fixed all the broken bats tests.
=> Made `server_query` error on bad queries where we expect no results. 

go/libraries/doltcore/migrate/transform.go, integration-tests/bats/migrate.bats, integration-tests/bats/migration-integration.bats
Fixes #4602
Validated changes against repos that previously failed with duplicate tag errors:
- https://dolthub.awsdev.ld-corp.com/repositories/dolthub/pdap-datasets/data/master
- https://www.dolthub.com/repositories/dolthub/us-president-precinct-results
=> Handle removed tables in //.../doltcore/migrate

go/cmd/dolt/commands/diff.go, go/cmd/dolt/commands/merge_base.go, integration-tests/bats/diff.bats
Two dot:
`dolt diff A..B`
`dolt diff A..`
Three dot:
`dolt diff A...B`
`dolt diff A...`
`dolt diff --merge-base A B`
=> Add two and three dot diff syntax to CLI

go/cmd/dolt/commands/sqlserver/sqlclient.go
Fixes the following issues regarding `dolt sql-client --query`
* https://github.com/dolthub/dolt/issues/4623
* https://github.com/dolthub/dolt/issues/4628
* https://github.com/dolthub/dolt/issues/4635
=> SQL client --query fixes

go/go.mod, go/go.sum, integration-tests/bats/helper/common.bash, integration-tests/bats/json-new-fmt.bats
=> [no-release-notes] dependency by druvv, adding some json bats for the new format

go/go.mod, go/go.sum
=> [auto-bump] [no-release-notes] dependency by PavelSafronov

go/cmd/dolt/commands/log.go, go/libraries/doltcore/sqle/dolt_log_table_function.go, go/libraries/doltcore/sqle/enginetest/dolt_queries.go, integration-tests/bats/log.bats
CLI:
`dolt log main...branchA`
`dolt log main branchA --not $(dolt merge-base main branchA)`
SQL:
`dolt_log('main...branchA')`
=> Support three dot log

go/libraries/doltcore/migrate/validation.go
=> go/doltcore/migrate: fix migration datetime bug

integration-tests/bats/branch-control.bats, integration-tests/bats/helper/query-server-common.bash
Added bats tests for the new branch control feature
=> Branch control bats tests

integration-tests/bats/sql-client.bats
This was originally working in https://github.com/dolthub/dolt/pull/4747, but failed when merged into https://github.com/dolthub/dolt/pull/4732. Figuring out and fixing why
=> [no-release-notes] Unskip bats test

go/store/prolly/tuple_map.go
At one point, we started to trim null suffixes from tuples. In versions prior to this change, tuples could have a null field at the end of the tuple. Now we always truncate the tuple.
If old versions insert rows with null values as the last column, it produces a tuple that is longer than the tuple that would be inserted by the latest version. This leads to empty diffs.
=> Skip empty diffs caused by non-canonicalized tuples.

integration-tests/bats/import-update-tables.bats
Associated GMS PR:
https://github.com/dolthub/go-mysql-server/pull/1403
=> Add bats for column truncation on import

go/libraries/doltcore/sqle/enginetest/branch_control_test.go
I was unable to fix the root cause, so this just works around the issue. I was eventually able to get new contexts to recognize created databases, but then the created branches weren't being recognized, so I'm leaving the issue alone for now.
=> [no-release-notes] Fixed db issue with branch permissions test

go/libraries/doltcore/migrate/transform.go, go/libraries/doltcore/schema/schema.go, integration-tests/bats/migrate.bats
Fixes https://github.com/dolthub/dolt/issues/4844
=> Schemas with different PK ordinals should not be equal.

docker/Dockerfile, docker/docker-entrypoint.sh, integration-tests/orm-tests/orm-tests.bats
- Added WORKDIR for client Dockerfile
- Fix path issue in dolt server docker entrypoint
- Fix ORM integration tests
=> fixes for dolt Docker images and ORM integration tests

go/go.mod, go/go.sum
=> [auto-bump] [no-release-notes] dependency by bheni

go/go.mod, go/go.sum, go/libraries/doltcore/sqle/index/dolt_index.go
fix for: https://github.com/dolthub/dolt/issues/4861
tests here: https://github.com/dolthub/go-mysql-server/pull/1425
=> use range instead of point lookups for non-unique indexes

go/cmd/dolt/commands/gc.go, go/cmd/dolt/commands/log.go, go/libraries/doltcore/doltdb/doltdb.go, go/libraries/doltcore/doltdb/gc_test.go, go/libraries/doltcore/env/environment.go, integration-tests/bats/log.bats
re: https://github.com/dolthub/dolt/pull/4920
=> ambyii's escape commit tag

go/libraries/doltcore/migrate/transform.go
In dolt versions <= 0.26.10, a working set was not created when a branch was created. In newer dolt versions it is created. Migrate expected a working set to exist for every branch ref.
Now, if a working set is missing we pretend it exists.
=> Fix working set not found error for dolt migrate

README.md
=> Fix instructions for first connect

integration-tests/bats/sql.bats
"fix" for: https://github.com/dolthub/dolt/issues/3717
issue is fixed by: https://github.com/dolthub/go-mysql-server/pull/1494
=> [no-release-notes] unskipping info schema schema test

go/go.mod, go/go.sum, go/libraries/doltcore/sqle/enginetest/dolt_engine_test.go, go/store/types/format.go
GMS PR: https://github.com/dolthub/go-mysql-server/pull/1499
=> gms bump for merge join

go/libraries/doltcore/sqle/read_replica_database.go
We already fetch all the new commits we need at once. Some lingering code had us refetching the commit values themselves from the upstream instead of directly setting the new branch to the commit hash which we just fetched.
=> go/libraries/doltcore/sqle/read_replica_database.go: Optimize the sql-server read replica case when syncing a lot of new branches.

go/libraries/doltcore/sqle/dolt_diff_summary_table_function.go, go/libraries/doltcore/sqle/dolt_diff_table_function.go, go/libraries/doltcore/sqle/dolt_log_table_function.go, integration-tests/bats/replication.bats
=> Fixed an error when running table funcs on a read replica

go/cmd/dolt/commands/branch.go, go/cmd/dolt/commands/pull.go, go/libraries/doltcore/env/actions/branch.go, go/libraries/doltcore/env/environment.go, go/libraries/doltcore/env/repo_state.go, go/libraries/doltcore/sqle/database_provider.go, go/libraries/doltcore/sqle/dprocedures/dolt_backup.go, go/libraries/doltcore/sqle/dprocedures/dolt_branch.go, go/libraries/doltcore/sqle/dprocedures/dolt_fetch.go, go/libraries/doltcore/sqle/dprocedures/dolt_pull.go, go/libraries/doltcore/sqle/dprocedures/dolt_push.go, go/libraries/doltcore/sqle/dsess/revision_db_provider.go, go/libraries/doltcore/sqle/enginetest/dolt_queries.go, integration-tests/bats/branch.bats, integration-tests/bats/sql-branch.bats
=> Fixed branch -d behavior on unmerged branches to match git

go/go.mod, go/go.sum
=> Revert "merge join correctness bump"

go/libraries/doltcore/branch_control/expr_parser_node.md
This adds rate-limiting to the branch control tables, such that we'll only write to disc once every 30 seconds. This only applies to the server context. In addition, we save when closing the server, in case there are any outstanding changes.
I've also added a doc that goes over how the new tree works, so give it a look over so I know that it's actually explaining everything in a helpful way.
=> [no-release-notes] Added document explaining how branch control works

go/cmd/dolt/cli/arg_parser_helpers.go, go/cmd/dolt/commands/backup.go, go/cmd/dolt/commands/branch.go, go/cmd/dolt/commands/checkout.go, go/cmd/dolt/commands/filter-branch.go, go/cmd/dolt/commands/ls.go, go/cmd/dolt/commands/remote.go, go/libraries/doltcore/env/actions/remotes.go, go/libraries/doltcore/env/actions/table.go, go/libraries/doltcore/env/remotes.go, go/libraries/doltcore/ref/remote_ref.go, go/libraries/doltcore/sqle/dprocedures/dolt_branch.go, go/libraries/doltcore/sqle/dprocedures/dolt_checkout.go, integration-tests/bats/remotes.bats
It is equivalent as using `--track` flag of CLI `dolt branch` command.
=> add `--track` flag for `dolt_branch()` procedure

go/cmd/dolt/commands/branch.go, go/libraries/doltcore/doltdb/system_table.go, go/libraries/doltcore/sqle/database.go, go/libraries/doltcore/sqle/dtables/branches_table.go, integration-tests/bats/system-tables.bats
New system table shows remote branches with same schema as existing `dolt_branches` table
=> dolt_remote_branches table

go/libraries/doltcore/schema/collation_comparator.go, go/libraries/doltcore/schema/collation_comparator_test.go
this improves a low-selectivity index scan for a customer query.
=> Trim compare string prefix

go/store/nbs/aws_table_persister_test.go, go/store/nbs/file_table_persister_test.go, go/store/nbs/mem_table.go, go/store/nbs/mem_table_test.go, go/store/nbs/store.go
Fixes https://github.com/dolthub/dolt/issues/5301
=> Add child refs to memtable only when a chunk was added.

docker/docker-entrypoint.sh
Fixes comments in entrypoint
Actually server starts at line 151 https://github.com/dolthub/dolt/pull/5391/files#diff-7cfc2aa3796f096105480a1a669658cfc12d2688b6300eef89d9ce94eef44e26L151
=> Fixes comments in entrypoint

go/cmd/dolt/commands/dump.go, go/libraries/doltcore/env/multi_repo_env.go, integration-tests/bats/dump.bats
=> Emit schema elements from dolt_schemas table as their DDL equivalents during `dolt dump`

go/cmd/dolt/commands/diff.go, integration-tests/bats/diff.bats
https://github.com/dolthub/dolt/issues/5388
Example new behavior:
```
lcl:~/Documents/data_dir_1/db1$ dolt diff HEAD~4 HEAD~3 dolt_schemas
diff --dolt a/dolt_schemas b/dolt_schemas
--- a/dolt_schemas @ p4j8pfq3pmub8fmketaes8ek0ghvgg1s
+++ b/dolt_schemas @ bkf872if6l5jd79ue0130c90u8qh5o36
create view males
-as select first_name
+as select first_name,last_name
from people
where gender = "M";
```
```
lcl:~/Documents/data_dir_1/db1$ dolt diff HEAD~2 HEAD dolt_schemas
diff --dolt a/dolt_schemas b/dolt_schemas
--- a/dolt_schemas @ m12an7km8tnft6hole0185ds1d91n5is
+++ b/dolt_schemas @ l8sa0c199fmng777t3v6mtjrfs1h5vdp
CREATE TRIGGER avg_age AFTER INSERT ON people
for each row
-  update average_age set average = (SELECT AVG(age));
+  update average_age set average = (SELECT AVG(age) FROM people); …
```
=> `dolt diff` behavior for dolt_schema table updated show DDL changes

go/cmd/dolt/commands/diff.go, integration-tests/bats/diff.bats
Second attempt of botched PR: https://github.com/dolthub/dolt/pull/5476
=> Display DDL for views and triggers in dolt diff

go/cmd/dolt/commands/log.go, go/libraries/doltcore/doltdb/doltdb.go
Fix for [5558](https://github.com/dolthub/dolt/issues/5558)
=> Fix dolt log HEAD detection

go/libraries/doltcore/sqle/binlogreplication/binlog_replica_applier.go, go/libraries/doltcore/sqle/binlogreplication/binlog_replica_event_producer.go, go/libraries/doltcore/sqle/binlogreplication/binlog_replication_test.go
A few small code clean ups, and a bug fix for not setting unique times in dolt commits. 
Fixes: https://github.com/dolthub/dolt/issues/5563
=> Fix incorrect recorded dolt commit times for MySQL replication

go/go.mod, go/go.sum
The initial changes contained in this PR were produced by \`go get\`ing the dependency.
\`\`\`
\$ cd ./go
\$ go get github.com/dolthub/<dependency>/go@<commit>
\`\`\`
=> [auto-bump] [no-release-notes] dependency by macneale4

go/libraries/doltcore/sqle/enginetest/dolt_engine_test.go, go/libraries/doltcore/sqle/enginetest/dolt_queries.go
https://github.com/dolthub/dolt/issues/5478
=> Added test for avoiding multiple parens issue.

go/cmd/dolt/dolt.go, go/libraries/doltcore/doltdb/doltdb.go, go/libraries/doltcore/sqle/dsess/transactions.go, go/libraries/doltcore/sqle/enginetest/dolt_engine_test.go, go/libraries/doltcore/sqle/enginetest/dolt_transaction_queries.go, go/store/spec/spec.go
Fixes https://github.com/dolthub/dolt/issues/5608
=> Correctly handle merging of staged changes across concurrent sessions

go/cmd/dolt/commands/sqlserver/sqlclient.go, integration-tests/bats/sql-client.bats
fixes: https://github.com/dolthub/dolt/issues/5518
=> updates sql-client to print query timing for more statement types

go/libraries/doltcore/sqle/index/index_lookup.go, go/store/prolly/tree/map.go, go/store/prolly/tuple_map.go
re: https://github.com/dolthub/dolt/issues/5648, test here: https://github.com/dolthub/go-mysql-server/pull/1685
=> Fix point lookup bug w/ prefix matching secondary

go/cmd/dolt/commands/engine/sqlengine.go
=> Revert "/go/cmd/dolt/commands/engine/sqlengine.go: close dbs on sql engine close"

integration-tests/bats/helper/jails.csv, integration-tests/bats/helper/states.csv, integration-tests/bats/import-create-tables.bats
add skipped bats test for https://github.com/dolthub/dolt/issues/5738
=> /integration-tests/bats: add skipped bats test for overwritten table bug

go/libraries/doltcore/sqle/globalstate/auto_increment_tracker.go, go/libraries/doltcore/sqle/globalstate/global_state.go, integration-tests/bats/auto_increment.bats, integration-tests/bats/feature-version.bats, integration-tests/bats/sql-server-remotesrv.bats
Fixes #5731
Previously auto-increment tracking was only considering locally checked out branches. It needs to consider remote branches as well.
=> Fixed a bug in auto increment tracking

go/go.mod, go/go.sum, go/libraries/doltcore/merge/violations_fk_prolly.go, go/libraries/doltcore/merge/violations_unique_prolly.go, go/libraries/doltcore/sqle/binlogreplication/binlog_replication_alltypes_test.go, go/libraries/doltcore/sqle/enginetest/ddl_queries.go, go/libraries/doltcore/sqle/json/noms_json_value.go, integration-tests/bats/blame-system-view.bats, integration-tests/bats/constraint-violations.bats, integration-tests/bats/json.bats, integration-tests/bats/migration-integration.bats, integration-tests/bats/types.bats
The initial changes contained in this PR were produced by \`go get\`ing the dependency.
\`\`\`
\$ cd ./go
\$ go get github.com/dolthub/<dependency>/go@<commit>
\`\`\`
=> [auto-bump] [no-release-notes] dependency by timsehn

go/libraries/doltcore/env/multi_repo_env.go
=> go/libraries/doltcore/env/multi_repo_env.go: Always use the GRPCDialProvider from the bootstrap env for the MultiRepoEnv RemoteDialProvider.

go/cmd/dolt/commands/commit.go, go/libraries/doltcore/sqle/dsess/session.go, integration-tests/bats/1pk5col-ints.bats, integration-tests/bats/2pk5cols-ints.bats, integration-tests/bats/empty-repo.bats, integration-tests/bats/ignore.bats, integration-tests/bats/multiple-tables.bats, integration-tests/bats/primary-key-changes.bats, integration-tests/bats/sql-reset.bats, integration-tests/bats/stash.bats, integration-tests/bats/status.bats
Fixes https://github.com/dolthub/dolt/issues/5840
=> Output for `dolt status` should say "tables", not "files"

go/cmd/dolt/commands/engine/sqlengine.go, go/cmd/dolt/commands/sql.go, go/cmd/dolt/commands/sqlserver/server.go, go/libraries/doltcore/merge/integration_test.go, go/libraries/doltcore/mvdata/engine_table_reader.go, go/libraries/doltcore/mvdata/engine_table_writer.go, go/performance/microsysbench/sysbench_test.go
Small step to untangling shell and query engine. https://github.com/dolthub/dolt/issues/3922
Existing tests cover behavior. This is a fairly straight forward refactor.
=> Drop the formatting flag from the engine

go/libraries/doltcore/sqle/dsess/session_cache.go
=> [no-release-notes] go/doltcore/sqle: add size limit to session cache

integration-tests/bats/branch-control.bats
This case was mot tested and a customer was having issues so improved our tests
=> Testing dolt commit in branch control bats tests

go/go.mod, go/go.sum, go/libraries/doltcore/sqle/database.go
Depends on https://github.com/dolthub/go-mysql-server/pull/1754
=> add support for `ALTER EVENT`

go/libraries/doltcore/sqle/enginetest/dolt_queries.go
https://github.com/dolthub/dolt/issues/5816
=> [no-release-notes] Add skipped enginetest for call dolt_checkout(table) on database revision bug

go/store/datas/pull/clone.go
Before this fix, |dolt clone| against a sql-server remote can fail with a confusing error message if the sql-server has a chunk journal. Adding the chunk journal to our destination ChunkStore causes us to update the root hash, which the Clone code was not expecting.
This change updates the Clone code to look for the possible update to the destination's root hash and to not try to set the root hash on the ChunkStore if it has already been done by the code handling the chunk journal.
=> go/store/datas/pull/clone.go: Fix to clone to interact with sql-server remotes better.

go/cmd/dolt/commands/sql.go, go/cmd/dolt/commands/stashcmds/stash.go, integration-tests/bats/no-repo.bats
Fixes https://github.com/dolthub/dolt/issues/5916
Fixes https://github.com/dolthub/dolt/issues/5920
=> Remove cry for help from `dolt sql --help`

go/libraries/doltcore/diff/table_deltas.go, go/libraries/doltcore/doltdb/foreign_key_coll.go, integration-tests/bats/diff.bats
When foreign keys are unresolved, the data on which columns they point to in the child table and the parent table is stored differently, and requires extra work to "resolve" the columns before we can test for equality. We currently do not always calculate equality correctly, which can result in confusing diff output (e.g. https://github.com/dolthub/dolt/issues/5934).
This PR adds a new `Equals` method on `ForeignKey` that takes in enough data to resolve FK column references, if needed, and test equality for any two foreign keys.
=> Handle unresolved/resolved foreign keys when determining equality

go/store/nbs/table_reader.go
Previously we would perform a linear scan of the table file index, matching up queried chunks with their location in the table file. This changes it to use a binary search, which is the right tradeoff for large table files and small(-ish) query sizes.
=> Storage optimization: Optimize GetMany operations when table files are very large.

go/libraries/doltcore/merge/merge_prolly_rows.go, go/libraries/doltcore/sqle/enginetest/dolt_queries_merge.go
Fixes check constraint evaluation during merge when a table has a primary key that does not appear as the first columns in the table schema.
=> Fix for bug when evaluating check constraints during merge 

.gitignore, go/utils/batsee/main.go
Create the batsee output directory if one doesn't exist yet.
Also adding the output directory to .gitignore.
=> Create the batsee output directory if one doesn't exist yet.

go/cmd/dolt/commands/commit.go, integration-tests/bats/commit.bats
adds missing print statements for errors occurring in `dolt commit`
=> adds print statements for errors in commit

go/cmd/dolt/commands/sqlserver/server.go, integration-tests/bats/helper/common.bash
Resolves: https://github.com/dolthub/dolt/issues/6239
=> Remove temporary workaround for loopback bug in GMS

go/cmd/dolt/commands/backup.go, integration-tests/bats/backup.bats
Fixes https://github.com/dolthub/dolt/issues/6365
=> Fixed backup to require a dolt directory

go/libraries/doltcore/sqle/enginetest/dolt_engine_test.go
There's something strange happening with Windows under CI, so I'm skipping this for now.
=> Skip test on Windows CI for now

go/cmd/dolt/dolt.go, go/libraries/doltcore/sqle/dsess/transactions.go, go/libraries/doltcore/sqle/read_replica_database.go, integration-tests/bats/replication-multidb.bats, integration-tests/bats/replication.bats
Fixes https://github.com/dolthub/dolt/issues/6400
=> Bug fix for state working sets in replication

go/libraries/doltcore/merge/merge_prolly_rows.go, go/libraries/doltcore/sqle/enginetest/dolt_queries_merge.go
Fixes https://github.com/dolthub/dolt/issues/6411
=> Coercing check constraint expressions to boolean results

.github/scripts/performance-benchmarking/validate-commentor.sh
This script validates who can trigger GitHub actions from PR comments. Jason and I should be on this list.
=> Add nicktobey and fulghum to approved commentors.

go/libraries/doltcore/merge/type_compatibility.go, go/libraries/doltcore/sqle/enginetest/dolt_queries_merge.go
Fixes https://github.com/dolthub/dolt/issues/6261
=> Auto-merge schema changes that widen `varchar` columns

.github/workflows/ci-bats-unix-remote.yaml, .github/workflows/ci-bats-unix.yaml
Update maven version used in CI tests.
=> [no-release-notes] Update maven version.

proto/dolt/services/eventsapi/v1alpha1/event_constants.proto
Adds new `EventType` for the new `dolt profile` cli command
=> adds new profile event from ld

go/cmd/dolt/cli/arg_parser_helpers.go
Restores more verbose descriptions for global arguments.
=> updates global arg descriptions to be more verbose

go/libraries/doltcore/sqle/enginetest/dolt_engine_test.go, go/libraries/doltcore/sqle/enginetest/dolt_queries_diff.go, go/libraries/doltcore/sqle/enginetest/system_table_function_index_tests.go
This was supposed to be part of https://github.com/dolthub/dolt/pull/6509 but I the push containing this commit was rejected and I didn't notice. It incorporates the testing feedback @max-hoffman suggested.
=> Pull indexed system table functions into their own test suite.

go/performance/scripts/local_sysbench.sh, go/performance/sysbench/README.md, go/performance/sysbench/cmd/main.go, go/performance/sysbench/reporting/systab.sql, go/performance/sysbench/testdata/default-config.yaml, go/performance/sysbench/testdata/index-join-scan.yaml, go/performance/sysbench/testdata/read-write.yaml, go/performance/sysbench/testdef.go
Fixes some testing setup, some changes are misc.
=> [no-release-notes] sysbench harness edits

go/cmd/dolt/commands/profile.go, integration-tests/bats/profile.bats
Fixes an issue with adding and using multiple profiles
=> fixes profiles not working with multiple profiles added

go/cmd/dolt/commands/status.go, integration-tests/bats/status.bats
fixes missing line break in `dolt status` when up to date with remote
=> fix formatting issue in status

go/cmd/dolt/commands/fetch.go, go/cmd/dolt/dolt.go, integration-tests/bats/fetch.bats, integration-tests/bats/remotes.bats, integration-tests/bats/sql-fetch.bats, integration-tests/bats/sql-local-remote.bats, integration-tests/bats/sql-server-remotesrv.bats
This change updates `dolt fetch` to use the appropriate sql engine to generate results.
=> migrates fetch to use sql queries

integration-tests/bats/sql-privs.bats
Related: https://github.com/dolthub/go-mysql-server/pull/2018
=> Test the privilege serialization doesn't write empty databases

go/libraries/doltcore/sqle/enginetest/dolt_engine_test.go, go/libraries/doltcore/sqle/writer/noms_table_writer.go, go/libraries/doltcore/sqle/writer/prolly_table_writer.go
New tests for this bug in https://github.com/dolthub/go-mysql-server/pull/2035
=> Fixed a bug in table writers where error state wasn't being appropriately cleared

go/libraries/doltcore/sqle/dprocedures/dolt_push.go, go/libraries/doltcore/sqle/dprocedures/init.go, integration-tests/bats/sql-push.bats
Adds a `message` column to the output of `dolt_push()` to provide additional information.
=> adds message column to dolt_push output

go/cmd/dolt/commands/dump_docs.go
Updates the header generated by `dump-docs`
=> change CLI reference header

go/libraries/doltcore/branch_control/branch_control.go, go/libraries/utils/filesys/fs.go, go/libraries/utils/filesys/localfs.go
Makes updates to branch_control, repo_state.json and some persisted config files atomic and crash resistant.
=> Change to use a crash resistant, atomic file update protocol for a number of file writes.

.github/workflows/ci-go-race-tests.yaml, go/cmd/dolt/commands/remote.go, go/libraries/doltcore/env/actions/branch.go, go/libraries/doltcore/env/environment.go, go/libraries/doltcore/env/environment_test.go, go/libraries/doltcore/env/memory.go, go/libraries/doltcore/env/remotes.go, go/libraries/doltcore/env/repo_state.go, go/libraries/doltcore/sqle/cluster/controller.go, go/libraries/doltcore/sqle/cluster/initdbhook.go, go/libraries/doltcore/sqle/clusterdb/database.go, go/libraries/doltcore/sqle/database.go, go/libraries/doltcore/sqle/database_provider.go, go/libraries/doltcore/sqle/dprocedures/dolt_remote.go, go/libraries/doltcore/sqle/dsess/database_session_state.go, go/libraries/doltcore/sqle/dsess/session_state_adapter.go, go/libraries/doltcore/sqle/dtables/remotes_table.go, go/libraries/doltcore/sqle/index/mergeable_indexes_setup_test.go, go/libraries/doltcore/sqle/read_replica_database.go, go/libraries/doltcore/sqle/replication.go, go/libraries/doltcore/sqle/user_space_database.go, go/libraries/utils/concurrentmap/concurrentmap.go, go/libraries/utils/concurrentmap/concurrentmap_test.go
This is a first stab at converting the remotes map to a concurrent map. A new generic concurrent map has been added to the utils folder, as I couldn't find a widespread generic implementation of a concurrent map yet. 
I am creating the PR to get some feedback, even though the following still need to be done:
- tests for the concurrent map
- probably a conversion of backups and branches needs to be done as well
This completely fixes the issue I've seen in my project tests when high concurrency is involved.
This PR attempts to fix https://github.com/dolthub/dolt/issues/6965. @zachmu when you have some time, let me know what you think.
=> Concurrent remotes map

go/libraries/doltcore/doltdb/doltdb.go, go/libraries/doltcore/env/actions/clone.go, integration-tests/bats/remotes.bats
Fixes https://github.com/dolthub/dolt/issues/7043 for the CLI.
dolt_clone() procedure has not been touched by this PR.
=> Cleaner clone CLI

go/cmd/dolt/cli/arg_parser_helpers.go, go/cmd/dolt/cli/flags.go, go/cmd/dolt/commands/diff.go, go/cmd/dolt/commands/log.go, go/cmd/dolt/commands/merge.go, go/cmd/dolt/commands/utils.go, integration-tests/bats/log.bats
Adds support for `dolt log --stat` which prints the diffstat for each commit in the log.
=> Adds support for `dolt log --stat`

go/store/nbs/cmp_chunk_table_writer.go, go/store/nbs/journal.go, go/store/nbs/table.go, go/store/nbs/table_index.go, go/store/nbs/table_reader.go
Random things I cleaned up while digging into NBS. All NoOp.
=> [no release notes] odd n ends clean up

go/libraries/doltcore/sqle/enginetest/stats_queries.go, go/libraries/doltcore/sqle/statspro/analyze.go, go/libraries/doltcore/sqle/statspro/auto_refresh.go
fixes: https://github.com/dolthub/dolt/issues/7710
=> [statspro] Avoid duplicating branch suffix when resolving stats database

.github/workflows/cd-release-pgo.yaml
add name on cd-release-pgo workflows
=> Add name on cd-release-pgo workflows

.github/workflows/cd-release-pgo.yaml
Reverts dolthub/dolt#7748 as the actions have been updated and work now
=> [no-release-notes] Revert "[no-release-notes] /.github/workflows/cd-release-pgo.yaml: revert bump of some dolthub actions"

go/libraries/doltcore/sqle/dtables/statistics_table.go
`information_schema.TABLES.DATA_LENGTH` currently reports the max possible table size for a table, and doesn't take into account table file compression or that variable length fields (e.g. TEXT) are not always fully used. Tools such as DBeaver use this metadata to display table sizes, and since the estimates can easily be orders of magnitude greater than the actual size on disk, it can cause customers to be concerned by the reported sizes (e.g. https://github.com/dolthub/dolt/issues/6624).
As a short-term fix to make these estimates more accurate, we apply a constant factor to the max table size. I came up with this scaling factor by measuring a best case scenario (where no fields are variable length) and a worst case scenario (were all fields are variable length and only use a few …
=> Apply a factor to better estimate `information_schema.TABLES.DATA_LENGTH`

go/cmd/dolt/commands/sql.go, go/libraries/doltcore/sqle/database_provider.go, integration-tests/bats/sql-create-database.bats
fixes: https://github.com/dolthub/dolt/issues/7814
=> allow database alters and case insensitive check for info schema

go/cmd/dolt/cli/command.go, go/cmd/dolt/commands/init.go, go/libraries/doltcore/env/environment.go, integration-tests/bats/sql-server.bats
Related to https://github.com/dolthub/dolt/issues/7873
Resolves https://github.com/dolthub/dolt/issues/7875
=> Improve error messages for CLI commands when a sql-server is running

go/cmd/dolt/commands/remote.go, go/cmd/dolt/dolt.go, integration-tests/bats/remote-cmd.bats, integration-tests/bats/remotes-file-system.bats
Fixes: https://github.com/dolthub/dolt/issues/7622
=> Migrate `dolt remote` to SQL

go/libraries/doltcore/sqle/dfunctions/hashof_database.go, go/libraries/doltcore/sqle/dfunctions/init.go, go/libraries/doltcore/sqle/enginetest/dolt_engine_test.go, go/libraries/doltcore/sqle/enginetest/dolt_queries.go
Implemented `dolt_hashof_db()` function which returns the root hash of a database.
=> implemented dolt_hashof_db function

go/libraries/doltcore/sqle/dprocedures/dolt_backup.go, integration-tests/bats/sql-backup.bats
The `dolt_backup()` stored procedure now supports the `restore` subcommand. Customers can use this support to create a new database from an existing backup, or to sync an existing database from a backup. Note that the `restore` subcommand currently requires root/superuser access to execute, since it can change database state (particular when the `--force` argument is used). 
Example usage to create a database named `db1` from a backup on disk:
```sql
call dolt_backup('restore', 'file:///opt/local/dolt-backups/db1', 'db1');
```
Related to https://github.com/dolthub/dolt/issues/7993
Fixes https://github.com/dolthub/dolt/issues/6074
=> Feature: Support `restore` subcommand in `dolt_backup()` 

.github/workflows/doltgres-dependency.yml
This makes the same changes for the Dolt workflow that was done to the GMS workflow:
* https://github.com/dolthub/go-mysql-server/pull/2585
=> [no-release-notes] Update integration workflow

go/libraries/doltcore/sqle/dprocedures/dolt_reset.go, go/libraries/doltcore/sqle/enginetest/dolt_engine_tests.go, go/libraries/doltcore/sqle/enginetest/dolt_queries.go
Fixes: https://github.com/dolthub/dolt/issues/6272
=> Bug fix: `dolt_reset()` should commit the active transaction

go/cmd/dolt/commands/merge.go, go/libraries/doltcore/doltdb/errors.go, integration-tests/bats/shallow-clone.bats
Fixes: https://github.com/dolthub/dolt/issues/8148
=> fix no-op merge msg in cli

go/cmd/dolt/commands/sqlserver/server.go, go/libraries/doltcore/sqle/system_variables.go, integration-tests/bats/stats.bats
fixes: https://github.com/dolthub/dolt/issues/8123
=> [stats] limit stats boostrap to server start

go/cmd/dolt/commands/admin/admin.go, go/cmd/dolt/commands/archive.go, go/cmd/dolt/dolt.go, go/store/nbs/archive_build.go, integration-tests/bats/archive.bats
Move the `dolt admin archive` command to `dolt archive`
=> Reveal dolt archive command

go/libraries/doltcore/sqle/database.go
Fixes:
https://github.com/dolthub/doltgresql/issues/442
https://github.com/dolthub/doltgresql/issues/513
=> check for `pg_catalog` table when resolving a table

go/libraries/doltcore/sqle/binlogreplication/binlog_replica_applier.go, go/libraries/doltcore/sqle/binlogreplication/binlog_replication_test.go
A MySQL primary server may send table names in `TableMap` binlog events that do not match the case of the table name. We use a case-insensitive table name lookup when getting the table's schema, but not when creating the `TableWriter` that applies row updates/inserts/deletes. This change fixes that so that mixed case table names can replicate correctly.
=> Bug fix: resolving case-sensitive table name for TableEditor

go/cmd/dolt/commands/status.go, go/libraries/doltcore/sqle/dtables/status_table.go, go/libraries/doltcore/sqle/enginetest/dolt_queries_merge.go, integration-tests/bats/cherry-pick.bats, integration-tests/bats/constraint-violations.bats
fixes: https://github.com/dolthub/dolt/issues/8114
=> add constraint violations to dolt status

go/cmd/dolt/dolt.go, integration-tests/bats/no-repo.bats
Customer issue: https://github.com/dolthub/dolt/issues/8250
=> Bug fix: Testing for invalid global configuration dir permissions earlier, to prevent a panic

go/libraries/doltcore/sqle/index/dolt_index.go, go/libraries/doltcore/sqle/index/index_reader.go, go/libraries/doltcore/sqle/kvexec/builder.go, go/store/prolly/tuple_map.go, go/store/prolly/tuple_range.go
This reverts the following PR:
* https://github.com/dolthub/dolt/pull/8242
The fuzzer found a bug that is causing incorrect results, which was traced to the above PR:
* https://github.com/dolthub/fuzzer/issues/2335
=> [no-release-notes] Revert PR causing index issues

.github/workflows/doltgres-dependency.yml
This is Dolt's counterpart to the following PR:
* https://github.com/dolthub/go-mysql-server/pull/2644
=> Fix Integration Workflow

go/libraries/utils/argparser/parser.go, go/libraries/utils/argparser/parser_test.go
support optional string arguments in the middle of command line args.
=> Optional String Argument 

go/libraries/doltcore/sqle/dprocedures/stats_funcs.go, go/libraries/doltcore/sqle/statsnoms/database.go, integration-tests/bats/stats.bats
fixes: https://github.com/dolthub/dolt/issues/8324
=> Fix issue where stats db created in wrong location

.github/workflows/doltgres-dependency.yml
Turns out I accidentally forgot to put the ID for checking for a PR link back during my last round of edits, so it'll never skip testing even if a comment is it. This fixes that.
=> [no-release-notes] Small DoltgreSQL integration test fix

go/libraries/doltcore/sqle/dfunctions/dolt_merge_base.go
`dolt_merge_base` was failing in doltgres with a `invalid type: unknown` error
=> Fix dolt_merge_base string validation for doltgres

go/libraries/doltcore/servercfg/serverconfig.go
Related: https://github.com/dolthub/doltgresql/pull/779
=> use global variable for default unix socket file path

go/cmd/dolt/commands/sqlserver/server.go
fixes: https://github.com/dolthub/dolt/issues/8443
=> log server metrics heartbeat

go/libraries/doltcore/sqle/index/index_reader.go, go/libraries/doltcore/sqle/index/prolly_index_iter.go
re: https://github.com/dolthub/go-mysql-server/pull/2737
=> reverse keyless indexscans apply reversal

go/libraries/doltcore/diff/table_deltas.go, go/libraries/doltcore/sqle/enginetest/dolt_queries_diff.go
Tag collisions exists and can lead to false positives.
=> patch with tag collision test

go/go.mod, go/go.sum, go/libraries/doltcore/sqle/binlogreplication/binlog_replication_test.go, integration-tests/bats/cli-hosted.bats, integration-tests/bats/sql-server.bats
Minor updates to test code from changes in GMS and Vitess to refactor the `AuthServer` interface. 
Depends on: https://github.com/dolthub/go-mysql-server/pull/2757
=> Refactor `AuthServer`

go/libraries/doltcore/sqle/system_variables.go, integration-tests/bats/sql-server.bats
related: https://github.com/dolthub/dolt/issues/8585#issuecomment-2494754518
=> system variables cannot have nil defaults

go/libraries/doltcore/sqle/system_variables.go, integration-tests/bats/sql-server.bats
=> replace `nil` defaults with empty string

go/libraries/doltcore/servercfg/yaml_config.go, go/libraries/doltcore/servercfg/yaml_config_test.go
fixes; https://github.com/dolthub/dolt/issues/8670
=> fix: panic on null metrics port

go/go.mod, go/go.sum
Bump for:
* https://github.com/dolthub/go-icu-regex/pull/2
=> Bump for go-icu-regex

go/store/nbs/archive_chunk_source.go, go/store/nbs/archive_test.go, go/store/nbs/chunk_source_adapter.go, go/store/nbs/empty_chunk_source.go, go/store/nbs/file_table_reader.go, go/store/nbs/journal_chunk_source.go, go/store/nbs/store.go, go/store/nbs/table.go, go/store/nbs/table_reader.go
Move it from fileTableReader onto tableReader, make it use ReadAt, have it take Stats.
=> [no-release-notes] go: nbs/store: Small cleanups to iterateAllChunks.

go/libraries/doltcore/sqle/statspro/auto_refresh.go
Deferring the SessionCommandEnd calls at the top level inside an infinite loop meant that the session tracker saw these as in progress forever.
=> [no-release-notes] go: statspro: auto_refresh: Fix session lifecycle leak in auto refresh thread.

go/go.mod, go/go.sum
The initial changes contained in this PR were produced by \`go get\`ing the dependency.
\`\`\`
\$ cd ./go
\$ go get github.com/dolthub/<dependency>/go@<commit>
\`\`\`
=> [auto-bump] [no-release-notes] dependency by nicktobey

go/libraries/doltcore/env/grpc_dial_provider.go
Allowing for this can improve some developer ergonomics when developing against local instances of remotesapi which are themselves operating against another service which is authenticating the JWTs.
=> [no-release-notes] go: doltcore: env: Add ability to override the audience for auth JWTs bound to remotesapi.

go/libraries/doltcore/merge/merge_schema.go, go/libraries/doltcore/schema/index_coll.go, go/libraries/doltcore/schema/schema.go, go/libraries/doltcore/sqle/enginetest/dolt_queries_schema_merge.go
FIxes: https://github.com/dolthub/dolt/issues/8975
=> Fix schema merge bug when schema is identical with multiple indexes on the same columns

go/go.mod, go/go.sum, go/libraries/doltcore/sqle/enginetest/dolt_queries.go
Adds a test for the bug fix in https://github.com/dolthub/go-mysql-server/pull/2892
=> Test for `INSERT ... ON DUPLICATE UPDATE` with `dolt_docs` table

go/libraries/doltcore/table/editor/table_edit_accumulator_test.go
=> Fix typo mistake of commmitted

go/libraries/doltcore/merge/merge.go, go/libraries/doltcore/sqle/enginetest/dolt_queries_schema_merge.go
Fixes: https://github.com/dolthub/dolt/issues/9014
=> Bug fix: allow dropping tables with FK constraints

go/store/datas/pull/puller.go
When a pull or push failed with an error in a HasMany call or on the initiating read of a set of chunks from the ChunkFetcher, the initiating goroutine used to close the PullChunkTracker. However, the writes to the PullChunkTracker are issued on the thread which reads and processes the chunks themselves. This meant that it was possible for the PullChunkTracker to be Closed while that thread was still issuing writes against it.
Making the chunk-reading thread responsible for the Close is more correct.
This fixes #9190.
=> go: store/datas/pull: puller.go: Fix incorrect location for Close call on PullChunkTracker.

go/libraries/utils/concurrentmap/concurrentmap.go
Optimize code using a more modern writing style.
=> refactor: replace map iteration with maps.Copy

integration-tests/bats/keyless.bats
=> Unskip keyless add/drop column test

go/libraries/doltcore/env/actions/clone.go, go/libraries/utils/iohelp/read_with_stats.go, go/store/datas/pull/clone.go
Added a defensive check to make sure remaining chunks is never less than downloading chunks. Added a file map to ensure chunks are only counted once.
=> Improved chunk tracking during clone

integration-tests/bats/1pk5col-ints.bats
Fixes #483 
Removed extra bats test
=> Fix 483 - rm already covered bats

go/libraries/doltcore/sqle/enginetest/dolt_queries.go
Fixes #9391
Add dolt_commit_ancestors table query test
=> Fix 9391 test for max1row err

go/cmd/dolt/commands/gc.go, go/store/types/value_store.go
Fixes: https://github.com/dolthub/dolt/issues/9448
=> Swallow gc NoOp err

go/libraries/doltcore/sqle/dtables/diff_iter.go, go/libraries/doltcore/sqle/enginetest/dolt_queries_diff.go
When used in a join (e.g. `LEFT JOIN`) that requires a table's partitions to be loaded multiple times, a bug in the `dolt_commit_diff` was preventing the query from running. This change fixes that by making a copy of the lookup details before the `dolt_commit_diff` system table alters them, so that the original lookup data can be preserved for any future calls to get table partitions.
=> Bug fix: Copy lookup details for `dolt_commit_diff`

go/cmd/dolt/commands/docscmds/read.go, go/cmd/dolt/commands/docscmds/write.go, go/cmd/dolt/doltversion/version.go, go/libraries/doltcore/doltdb/system_table.go, go/libraries/doltcore/sqle/dtables/docs_table.go, go/libraries/doltcore/sqle/enginetest/dolt_queries.go, go/libraries/doltcore/sqle/sqldelete_test.go, go/libraries/doltcore/sqle/sqlinsert_test.go, go/libraries/doltcore/sqle/sqlreplace_test.go, go/libraries/doltcore/sqle/sqlselect_test.go, go/libraries/doltcore/sqle/sqlupdate_test.go, integration-tests/bats/docs.bats, integration-tests/bats/init.bats, integration-tests/mysql-client-tests/node/workbenchTests/docs.js
Implementation of this feature request.
https://github.com/dolthub/dolt/issues/9509
On read returns the default agent.md if none exists.  Otherwise returns what the user has stored.
=> Agent.md dolt doc

go/libraries/doltcore/doltdb/system_table.go, integration-tests/bats/docs.bats, integration-tests/bats/init.bats
This change implements a much more comprehensive AGENT.md that covers a number of topics that may not be obvious or known to an agent using Dolt.
=> A more comprehensive default AGENT.md

integration-tests/bats/primary-key-changes.bats
Found testing Cursor Agent with GPT-5
=> A Primary Key BATS test to unskip.

go/libraries/doltcore/doltdb/root_val.go, go/libraries/doltcore/env/actions/reset.go, go/libraries/doltcore/sqle/dsess/session.go, go/libraries/doltcore/sqle/expranalysis/expranalysis.go
This contains some fixes related to calling Dolt functions in Doltgres.
Required by:
* https://github.com/dolthub/doltgresql/pull/1763
=> Fixes for Doltgres-related procedure calling

go/cmd/dolt/commands/log_test.go, go/store/util/outputpager/page_output.go, integration-tests/bats/pager.bats, integration-tests/bats/pager.expect
Fixes: https://github.com/dolthub/dolt/issues/9736
=> add DOLT_PAGER to override default pager

go/libraries/doltcore/doltdb/ignore.go, go/libraries/doltcore/merge/action.go, go/libraries/doltcore/sqle/enginetest/dolt_queries_merge.go
When a merge halts due to a conflict, the merge can be aborted by calling `dolt_merge('--abort');`, however a bug caused this to error if the merge included a table rename. The root cause of the bug was how we restore the tables to their previous values and work around ignored tables. This change alters how we restore tables – now we restore all versioned tables by reusing the pre-merge root and then applying any ignored tables.
=> Bug fix: allow aborting a merge when there is a table rename

go/cmd/dolt/commands/admin/admin.go, go/cmd/dolt/commands/admin/archive_inspect.go, go/store/nbs/archive_inspect.go, go/store/nbs/archive_reader.go, integration-tests/bats/admin-archive-inspect.bats, integration-tests/bats/helper/local-remote.bash
This will probably become useful in the future. If nothing else it's a starting point for debugging archives.
=> [no-release-notes] add `dolt admin archive-inspect` cmd

go/store/nbs/archive_chunk_source.go, go/store/nbs/archive_test.go
While hacking on the wikimedia database, we got into a situation where a chunk existed in multiple storage files. This was an edgecase which archives didn't handle correctly. This is the test and fix.
=> [no-release-notes] get records range duplication
