- go/libraries/doltcore/env/actions/remotes.go
Also avoids round-tripping to the remote to load a commit whose value we do not need yet.
> go/libraries/doltcore/env/actions: remotes.go: Have fetch pull all the branch heads at once.

- go/cmd/dolt/cli/cli_context.go
- go/cmd/dolt/cli/command.go
- go/cmd/dolt/commands/engine/sqlengine.go
- go/cmd/dolt/commands/sql.go
- go/cmd/dolt/commands/sql_test.go
- go/cmd/dolt/commands/utils.go
- go/cmd/dolt/dolt.go
- go/libraries/doltcore/doltdb/feature_version_test.go
- go/libraries/doltcore/doltdb/foreign_key_test.go
- go/libraries/doltcore/doltdb/gc_test.go
- go/libraries/doltcore/merge/keyless_integration_test.go
- go/libraries/doltcore/merge/schema_integration_test.go
- go/libraries/doltcore/migrate/integration_test.go
- go/libraries/doltcore/rebase/filter_branch_test.go
- go/libraries/doltcore/schema/integration_test.go
- go/libraries/doltcore/sqle/integration_test/database_revision_test.go
- go/libraries/doltcore/sqle/integration_test/history_table_test.go
- go/libraries/doltcore/sqle/integration_test/json_value_test.go
- go/libraries/utils/argparser/results.go
- go/performance/microsysbench/sysbench_test.go
- integration-tests/bats/replication-multidb.bats
- integration-tests/bats/sql-create-database.bats
- integration-tests/bats/sql-create-tables.bats
- integration-tests/bats/sql-multi-db.bats
- integration-tests/bats/sql-server-remotesrv.bats
- integration-tests/bats/sql-server.bats
- integration-tests/bats/sql-shell.bats
- integration-tests/bats/sql.bats
SQL Command arguments which pertain to instantiating a local SqlEngine instance are now global arguments which come before the sql subcommand. This is a breaking change for users of the `sql` command who pass in the following arguments:
- --data-dir
- --user
- --doltcfg-dir
- --privilege-file
- --branch-control-file
All of the test changes pertain to moving those arguments, and nothing else. This is by design to ensure we don't have broader impact to the interface.
With this abstraction in place, we can put a different Queryist implementation in place - specifically one which talks to a remotes server - which is the end goal.
Step on the path to: https://github.com/dolthub/dolt/issues/3922
> Refactor SQLEngine instantiation into the Queryist interface

- go/libraries/doltcore/sqle/binlogreplication/binlog_replica_applier.go
- go/libraries/doltcore/sqle/binlogreplication/binlog_replication_reconnect_test.go
- go/libraries/doltcore/sqle/binlogreplication/binlog_replication_test.go
This PR changes our handling of `io.EOF` to trigger our connection re-establishment logic. Previously, only `io.UnexpectedEOF` was triggering a connection re-establishment. 
We found this by digging into some flakiness in the `TestBinlogReplicationAutoReconnect` test:
- https://github.com/dolthub/dolt/actions/runs/4888594518/jobs/8726401205
- https://github.com/dolthub/dolt/actions/runs/4888594518/jobs/8726401205
- https://github.com/dolthub/dolt/actions/runs/4888566463/jobs/8726344999
This test is a little more complex than the other binlog replication tests – it uses Toxiproxy to simulate a dying connection to test the automatic reconnection feature. 
In each of the failures above, the test fails after timing out waiting for the replica to report it has processed the same GTID set that …
> Fix binlog connection re-establishment when connection closes between messages

- go/utils/batsee/main.go
An inevitable change to make the output directory of batsee configurable. Refactored the configuration struct to make changes like this a little easier.
```
$ batsee --help
NAME
batsee - Run the Bats Tests concurrently
SYNOPSIS
batsee [-t threads] [-o dir] [--skip-slow] [--max-time time] [--only test1,test2,...]
DESCRIPTION
From within the integration-test/bats directory, run the bats tests concurrently.
Output for each test is written to a file in the batsee_output directory.
Example:  batsee -t 42 --max-time 1h15m -r 2 --only types.bats,foreign-keys.bats
OPTIONS
-t <threads>, --threads=<threads>
Number of tests to execute in parallel. Defaults to 12
-o <directory>, --output=<directory>
Directory to write output to. Defaults to 'batsee_results'
-s, --skip-slow
Skip slow tests. This is a …
```
> batsee --output dir

- README.md
I've been maintaining the AUR recipe for dolt since 2021 and [updated it for almost all the releases since 0.28.4](https://aur.archlinux.org/cgit/aur.git/log/?h=dolt). I've now migrated the packaging from the AUR to prebuilt packages in the official Arch Linux repos.
> Mention official Arch Linux packaging in README

- go/cmd/dolt/commands/sqlserver/server.go
- go/libraries/doltcore/sqle/dsess/variables.go
- integration-tests/go-sql-server-driver/tests/sql-server-config.yaml
Written values do not persist across server restarts.
> sql-server: `dolt_log_level` system variable allows reading the current log level for the server and setting a new one.

- go/libraries/doltcore/schema/col_coll.go
- go/libraries/doltcore/schema/column.go
- integration-tests/bats/column_tags.bats
Two tables can have identical schemas, but different column tags if the columns were created in different orders (e.g. a different sequence of alters to get to the same schema). When we try to merge those two tables, we see that there is not a common ancestor, so we require the schemas to be exactly identical in order to merge the data. This results in a confusing merge error for customers because we tell them the schemas are different, but they look exactly the same (except for the different column tags). 
This change removes column tags from equality checks when testing equality of two schemas and enables the case above to merge cleanly.
> Changing schema equality to not consider tag when comparing columns

- go/cmd/dolt/dolt.go
Update the Dolt CLI To print the global flags when the --help flag is provided. New look:
```
$ dolt --help
Valid commands for dolt are
init - Create an empty Dolt data repository.
status - Show the working tree status.
add - Add table changes to the list of staged table changes.
diff - Diff a table.
reset - Remove table changes from the list of staged table changes.
clean - Remove untracked tables from working set.
commit - Record changes to the repository.
sql - Run a SQL query against tables in repository.
sql-server - Start a MySQL-compatible server.
sql-client - Starts a built-in MySQL client.
log - Show commit logs.
show - Show information about a specific commit.
branch - Create, list, edit, delete branches.
checkout - Checkout a branch or overwrite a table from HEAD.
merge - Merge …
```
> Print global arguments for 'dolt --help' but not 'dolt'

- integration-tests/bats/sql.bats
Allows tests to run on laptops which aren't in UTC.
> Use UTC timestamp in date comparison test.

- integration-tests/bats/sql-load-data.bats
A customer ran into some issues using `LOAD DATA` with Hosted Dolt. Added some additional testing in response. Pleasantly surprised with our compatibility. Adds skipped tests for #5982 and #5983.
> `LOAD DATA` bats tests improvements

- go/cmd/dolt/commands/sql.go
- go/cmd/dolt/commands/sqlserver/sqlclient.go
- go/cmd/dolt/commands/sqlserver/sqlserver.go
- go/cmd/dolt/commands/utils.go
- go/cmd/dolt/dolt.go
- go/libraries/doltcore/env/environment.go
- go/libraries/doltcore/env/multi_repo_env.go
- integration-tests/bats/replication-multidb.bats
- integration-tests/bats/sql-create-database.bats
- integration-tests/bats/sql-local-remote.bats
- integration-tests/bats/sql-server.bats
- integration-tests/bats/sql-shell.bats
- integration-tests/bats/sql.bats
When `dolt sql` commands are executed against a database which is in used by a sql server, connect to it through the sql port. Currently this does not support authenticated transport. If the root user is still active, we'll use that be default. Otherwise, the `--user` flag can be used to specify a user, but no authentication token is supported. That will come in the next round of changes.
A step towards: https://github.com/dolthub/dolt/issues/3922
> Smart routing for sql command execution against running local servers

- go/Godeps/LICENSES
- go/go.mod
- go/go.sum
- go/store/nbs/store.go
- go/store/nbs/table_reader.go
- go/store/nbs/table_set.go
- go/store/nbs/table_set_test.go
A bottleneck in sanity checks that we run when we add new chunks to the database could make commit performance slow down as the database increased in size. On some benchmarks we ran, a typical slowdown might be ~100ms per 100GBs of database size. This optimizes the code paths involved to use more efficient algorithms and to use a scan resistant LRU cache.
> Optimize COMMIT performance for large databases.

- go/cmd/dolt/commands/tblcmds/import.go
- go/libraries/doltcore/mvdata/data_mover.go
- go/libraries/doltcore/mvdata/engine_table_writer.go
- integration-tests/bats/import-append-tables.bats
- integration-tests/bats/import-tables.bats
I ended up going with @zachmu's suggestion of making this a new operation type like `-u`, `-c`, and `-r` instead of a separate flag after I realized that `-c` and `-r` already disallow overwriting fields and it didn't really make sense to add a flag that could only be used with `-u`.
This is less ambitious than what was outlined in https://github.com/dolthub/dolt/issues/5936. Notably, I made a big deal in the issue about how you can import the same file multiple times or files that contain previously imported rows without issue. This was a mostly a pet feature that I erroneously assumed would be simple to implement. Given that it wasn't a requirement, after some exploration I ultimately decided to drop it.
This should be enough to unblock the customer; we talked about implementing a …
> Add support for `dolt table import -a`

- go/cmd/dolt/commands/engine/sqlengine.go
- go/cmd/dolt/commands/sqlserver/server.go
- go/cmd/dolt/commands/sqlserver/serverconfig.go
- go/cmd/dolt/commands/sqlserver/sqlserver.go
- go/cmd/dolt/commands/sqlserver/yaml_config.go
- go/cmd/dolt/commands/sqlserver/yaml_config_test.go
- integration-tests/bats/sql-server.bats
Dolt sql-server YAML configuration can now specify `dolt_transaction_commit` in the behavior section to automatically set the global value of [`@@dolt_transaction_commit`](https://docs.dolthub.com/sql-reference/version-control/dolt-sysvars#dolt_transaction_commit) for a sql-server.
Prereq for https://github.com/dolthub/hosted-issues/issues/99
> Allow `@@dolt_transaction_commit` to be set through sql-server config

- go/cmd/dolt/commands/engine/sql_print.go
- go/cmd/dolt/commands/sql.go
- go/libraries/doltcore/mvdata/file_data_loc.go
- go/libraries/doltcore/table/typed/parquet/writer.go
- go/libraries/doltcore/table/typed/parquet/writer_test.go
- integration-tests/bats/sql.bats
Adds support for outputting the results of queries as parquet data. For example, `dolt sql -r parquet -q "select * from mytable;" > out.parquet` will select all rows from `mytable`, output them to stdout as parquet data, and redirect that output to the `out.parquet` file.
> Add support for parquet as an output format for `dolt sql`

- go/cmd/dolt/commands/blame.go
- integration-tests/bats/blame.bats
- integration-tests/bats/sql-local-remote.bats
This change updates `dolt blame` to use the appropriate sql engine to generate results. This change also allows users to specify a specific revision to annotate from.
> update dolt blame to use sql backend and accept specific revision

- .github/workflows/ci-bats-unix.yaml
- integration-tests/bats/replication-multidb.bats
- integration-tests/bats/sql-local-remote.bats
Due to a typo in the .yaml script, we weren't actually running bats tests with the `$SQL_ENGINE` environment variable set, which meant that we weren't actually testing the ability for commands to seamlessly connect to running server processes. This PR fixes this.
> Actually run bats tests in a configuration where all commands connect to a server process.

- go/libraries/doltcore/merge/violations_unique_prolly.go
- go/libraries/doltcore/sqle/dsess/transactions.go
- go/libraries/doltcore/sqle/enginetest/dolt_transaction_queries.go
Changed `ErrUnresolvedConstraintViolationsCommit` to print all the information we have on the violation for easier debugging.
> [no-release-notes] add more info to constraint violation error

- go/libraries/doltcore/merge/merge_prolly_rows.go
- go/libraries/doltcore/sqle/enginetest/dolt_queries_merge.go
Previously, we only supported evaluating column default expressions during merge when the expression only contained literals. This PR expands that support to evaluate column default expressions that contain functions and column references.
> Evaluate column default expressions during merge

- integration-tests/bats/remotes-sql-server.bats
- integration-tests/bats/sql-server.bats
This should prevent the test failures that are blocking PRs, even if I don't fully understand why these test failures are happening.
> Skip `remotes-sql-server.bats` and `sql-server.bats` when running BATS in remote-engine configuration.

- integration-tests/bats/helper/query-server-common.bash
- integration-tests/bats/sql-privs.bats
- integration-tests/bats/sql-server.bats
We've been seeing Python errors in the code that detects if a sql-server has fully started up yet. This PR removes the use of Python from `wait_for_connection` and instead just polls with bash. There is still a little bit of Python left in BATS that could be cleaned up/simplified further.
Fixes: https://github.com/dolthub/dolt/issues/6109
> [no-release-notes] Remove Python from `wait_for_connection` function in BATS

- go/cmd/dolt/cli/arg_parser_helpers.go
- go/cmd/dolt/commands/stashcmds/pop.go
- go/cmd/dolt/commands/status.go
- go/cmd/dolt/dolt.go
- go/libraries/doltcore/doltdb/ignore.go
- go/libraries/doltcore/sqle/dprocedures/dolt_count_commits.go
- go/libraries/doltcore/sqle/dprocedures/init.go
- go/libraries/doltcore/sqle/dtables/branches_table.go
- go/libraries/doltcore/sqle/sqlselect_test.go
- integration-tests/bats/replication.bats
- integration-tests/bats/sql-local-remote.bats
- integration-tests/bats/sql-server.bats
- integration-tests/bats/status.bats
- integration-tests/mysql-client-tests/node/workbenchTests/branches.js
Rewrite `dolt status` subcommand to use SQL queries to generate results.
This change adds `remote` column to the `dolt_branches` table. This column identifies the remote for the branch.
This change adds `dolt_count_commits` function, which returns the number of commits between two commits.
Added more BATS tests for `dolt status`.
> Rewrite `dolt status` subcommand to use SQL queries to generate results.

- go/performance/import_benchmarker/testdef.go
- go/performance/sysbench/testdef.go
Fixes CI for system table benchmarks and import benchmarks.
> [no-release-notes] Fix Ci; Silent error during forkExec if empty trailing arg

- go/cmd/dolt/cli/arg_parser_helpers.go
- go/cmd/dolt/commands/add.go
- go/cmd/dolt/commands/branch.go
- go/cmd/dolt/commands/commit.go
- go/cmd/dolt/commands/status.go
- go/cmd/dolt/commands/utils.go
- go/cmd/dolt/dolt.go
- go/libraries/doltcore/branch_control/branch_control.go
- go/libraries/doltcore/env/actions/branch.go
- go/libraries/doltcore/sqle/dprocedures/dolt_branch.go
- go/libraries/doltcore/sqle/dsess/session.go
- go/libraries/doltcore/sqle/dsess/session_state_adapter.go
- go/libraries/doltcore/sqle/enginetest/dolt_queries.go
- integration-tests/bats/branch-control.bats
- integration-tests/bats/branch.bats
- integration-tests/bats/deleted-branches.bats
- integration-tests/bats/remotes-sql-server.bats
- integration-tests/bats/sql-branch.bats
- integration-tests/bats/sql-local-remote.bats
- integration-tests/bats/sql-server.bats
This PR migrates `dolt branch` to invoke SQL commands instead of manipulating the database directly. This allows it to work even on remote connections.
The only thing that hasn't been migrated yet is `dolt branch --datasets`. It's not a documented flag. We're currently using it for an internal test and can migrate it if we can figure out a way to rewrite the test.
> Migrate `dolt branch` to new CLI framework.

- go/cmd/dolt/commands/branch.go
A println used while debugging the `dolt branch` migration accidentally got committed and pulled into main. This removes that.
> [no-release-notes] Remove println used for debugging that accidentally got committed.

- go/libraries/doltcore/sqle/enginetest/dolt_engine_test.go
- go/libraries/doltcore/sqle/enginetest/dolt_queries.go
- go/libraries/doltcore/sqle/tables.go
Fixes https://github.com/dolthub/dolt/issues/6178
> Use a table's `workingRoot` when getting declared FKs.

- go/libraries/doltcore/sqle/cluster/assume_role.go
- go/libraries/doltcore/sqle/cluster/commithook.go
- go/libraries/doltcore/sqle/cluster/commithook_test.go
- go/libraries/doltcore/sqle/cluster/controller.go
- go/libraries/doltcore/sqle/cluster/initdbhook.go
- integration-tests/go-sql-server-driver/tests/sql-server-cluster.yaml
This new stored procedure can be used to gracefully transition a primary to a standby while not all replicas in the cluster are up and able to become current. In contrast to `dolt_assume_cluster_role`, this stored procedure can only transition to role `standby`, but takes a second integer parameter representing the number of replica servers in the cluster which must be made current in order for the transition to succeed.
> sqle: cluster: Add dolt_cluster_transition_to_standby stored procedure.

- go/libraries/doltcore/sqle/database_provider.go
- go/libraries/doltcore/sqle/dolt_schema_diff_table_function.go
- go/libraries/doltcore/sqle/enginetest/dolt_engine_test.go
- go/libraries/doltcore/sqle/enginetest/dolt_queries.go
- go/libraries/doltcore/sqle/enginetest/dolt_queries_diff.go
- integration-tests/bats/system-tables.bats
`dolt_schema_diff` will return the schema diffs between refs and optionally will filter those changes to a specific table.
This is a new table function that provides us with the information we need for dolt diff.
The [original PR](https://github.com/dolthub/dolt/pull/6185) for this change was accidentally merged too early. The comments from that PR have been integrated into this change.
> Add `dolt_schema_diff` table function

- go/cmd/dolt/commands/commit.go
fixes `commit` to return an error when there is an error processing result rows
> fix error return code in commit

- go/cmd/dolt/commands/commit.go
- go/cmd/dolt/commands/merge.go
- integration-tests/bats/sql-local-remote.bats
The output of the commit command changed with: https://github.com/dolthub/dolt/pull/6138
This change brings back the pretty log command output when running in a local context. This is a temporary change since we probably won't get to the `log` command for awhile yet.
```
lcl:~/Documents/data_dir_1/db5$ dolt --use-db fooo commit -A -m "Create a table"
commit euckmmj63mvbjdqo53r5hmhitc8psk67 (HEAD -> main)
Author: Neil Macneale IV <neil@dolthub.com>
Date:  Tue Jun 27 08:00:24 -0700 2023
Initialize data repository
[ START SERVER IN SEPARATE TERMINAL]
lcl:~/Documents/data_dir_1/db5$ dolt --use-db fooo sql  -q "create table tbl2  (id int primary key)"
lcl:~/Documents/data_dir_1/db5$ dolt --use-db fooo commit -A -m "Create a second table" …
```
> Bring back pretty content for commit when commiting to a local db

- go/cmd/dolt/commands/assist.go
- go/cmd/dolt/commands/dump.go
- go/cmd/dolt/commands/engine/jwtplugin_test.go
- go/cmd/dolt/commands/log.go
- go/cmd/dolt/commands/sqlserver/sqlserver.go
- go/cmd/dolt/commands/status.go
- go/libraries/doltcore/mvdata/channel_row_source.go
- go/libraries/doltcore/mvdata/engine_table_writer.go
- go/libraries/doltcore/mvdata/file_data_loc.go
- go/libraries/doltcore/sqle/binlogreplication/binlog_replication_reconnect_test.go
- go/libraries/doltcore/sqle/dfunctions/active_branch.go
- go/libraries/doltcore/sqle/dprocedures/dolt_branch.go
- go/libraries/doltcore/sqle/dtables/diff_table.go
- go/libraries/doltcore/sqle/index/mergeable_indexes_test.go
- go/libraries/doltcore/sqle/integration_test/history_table_test.go
- go/libraries/doltcore/table/untyped/csv/reader.go
- go/performance/utils/sysbench_runner/mysql.go
- go/performance/utils/sysbench_runner/run.go
- go/performance/utils/tpcc_runner/run.go
- go/store/datas/stashlist.go
- go/store/prolly/benchmark/benchmark_read_test.go
- go/store/prolly/tree/node_splitter_test.go
- go/store/spec/absolute_path_test.go
unnecessary use of fmt.Sprintf
use fmt.Errorf(...) instead of errors.New(fmt.Sprintf(...))
use fmt.Printf instead of fmt.Println(fmt.Sprintf(...)) (but don't forget the newline)
> chore: fmt modify

- go/cmd/dolt/commands/status.go
`dolt status` output was missing some new lines
```bash
taylor@MacBook-Pro-3 test % dolt status
On branch main
Your branch is ahead of 'origin/main' by 1 commit.
(use "dolt push" to publish your local commits)Changes not staged for commit:
(use "dolt add <table>" to update what will be committed)
(use "dolt checkout <table>" to discard changes in working directory)
modified:         table1
taylor@MacBook-Pro-3 test % dolt status
```
```bash
taylor@MacBook-Pro-3 test % dolt status
On branch main
Your branch is up to date with 'origin/main'.nothing to commit, working tree clean
```
> Fix dolt status formatting

- go/cmd/dolt/commands/cherry-pick.go
- go/libraries/doltcore/schema/schema.go
- Update cherry-pick docs now that schema and data conflicts are supported in cherry-pick.
- Fix a bug in schema.go where the incorrect column name (`Invalid`) was being printed out due to a shadowed `col` variable.
> Fix for cherry-pick docs and PK mapping error message

- go/cmd/dolt/commands/reset.go
- go/cmd/dolt/dolt.go
- go/libraries/doltcore/sqle/dprocedures/dolt_reset.go
- integration-tests/bats/helper/local-remote.bash
- integration-tests/bats/reset.bats
- integration-tests/bats/sql-local-remote.bats
- integration-tests/bats/sql-reset.bats
- integration-tests/bats/status.bats
This change updates `dolt reset` to use the appropriate sql engine to generate results.
> updates dolt reset to use sql queries

- go/cmd/dolt/commands/commit.go
- go/cmd/dolt/commands/show.go
- integration-tests/bats/sql-local-remote.bats
Changes `commit` to print with `printCommitInfo`. This prevents seg fault errors from using `dolt log` as was previously done.
> change commit to print with printCommitInfo

- go/libraries/doltcore/env/actions/branch.go
- go/libraries/doltcore/sqle/dprocedures/dolt_branch.go
- go/libraries/doltcore/sqle/dsess/session.go
- go/libraries/doltcore/sqle/dsess/session_state_adapter.go
- integration-tests/bats/branch.bats
- integration-tests/bats/sql-branch.bats
- integration-tests/bats/sql-server.bats
This recently added implementation of `SetCWBHeadRef` was a designed to fix an issue when evalutating `call dolt_branch('-m', $ACTIVE_BRANCH, $NEW_BRANCH)` (which would cause a panic) by changing the active branch on the SQL session to match the new branch. However, this implementation has some problems.
When operating on the DB from a SQL-context, we use transactions to ensure that changes are applied atomically. However currently, renaming branches doesn't use transactions because they touch multiple branches at once and we can't really model that as a transaction. This becomes a problem when mixed with `DoltSession` operations, which do use transactions.
My original implementation attempted to work around this by calling `commitTransaction` before and after setting the new current …
> Revert transaction-unsafe implementation of `SessionStateAdapter::SetCWBHeadRef`

- go/libraries/doltcore/sqle/dprocedures/dolt_checkout.go
- integration-tests/bats/remotes.bats
I found an issue in `dolt_checkout` that occurs in the narrow case where both the `-b` and `--track` flags are provided, in order to create a new branch that tracks an upstream branch with a different name.
In that case, we fail to set the upstream correctly because we accidentally look for a local branch to mark using the remote branch name, instead of the local branch name.
I added a regression test.
> Use correct local branch name when setting upstream in `dolt_checkout`

- go/cmd/dolt/commands/stashcmds/stash.go
- go/libraries/doltcore/diff/table_deltas.go
- go/libraries/doltcore/sqle/dprocedures/dolt_cherry_pick.go
- integration-tests/bats/sql-cherry-pick.bats
This updates the `dolt_cherry_pick` procedure to properly work with ignored tables.
> Add ignore support to dolt_cherry_pick procedure.

- integration-tests/bats/reset.bats
- integration-tests/bats/sql-reset.bats
Adds tests for `dolt reset` and `dolt_reset()` to check their handling of ignored tables.
> adds test for reset handling ignored tables

- README.md
We went from 68M to 103M because of the new collations.
> Update Dolt's binary size in README

- go/libraries/doltcore/doltdb/ignore.go
- go/libraries/doltcore/sqle/dprocedures/dolt_merge.go
- go/libraries/doltcore/sqle/enginetest/dolt_queries.go
- go/libraries/doltcore/sqle/enginetest/dolt_queries_merge.go
Fix issue where unstaged ignored tables are staged after a cherry-pick abort
> Fix: unstaged ignored tables are staged after a cherry-pick abort

- go/libraries/doltcore/merge/merge_schema.go
- go/libraries/doltcore/sqle/enginetest/dolt_queries_merge.go
There were a couple of gaps in our schema merge logic and testing when convergent schema changes happen on both sides of a merge. This change fixes an issue where columns could be omitted if they changed in exactly the same way, and also an issue with spurious FK conflicts if identical FKs were added on both sides of a merge.
> Bug Fix: Merge with convergent schema changes

- go/cmd/dolt/commands/clean.go
- go/cmd/dolt/dolt.go
- integration-tests/bats/helper/local-remote.bash
- integration-tests/bats/sql-clean.bats
- integration-tests/bats/sql-local-remote.bats
The dolt_clean() stored procedure pretty much does exactly what the CLI does, so this was an easy migration. What the `dolt clean` command doesn't have is tests, and neither does the dolt_clean() procedure for that matter. Unfortunately, the command experience itself isn't great, and differs significantly from `git clean` (https://github.com/dolthub/dolt/issues/6313). So instead of spending time on testing and a full rewrite of `dolt clean`, I'm making this small tactical change to do nothing but the migration.
> Migrate the clean command to sql

- go/cmd/dolt/cli/messages.go
- go/cmd/dolt/commands/checkout.go
- integration-tests/bats/sql-local-remote.bats
Currently the `dolt checkout` can't work with a server running on a local database. There are more details to be sorted out with session persistence in the server which aren't addressed yet.
The SQLEngine execution for using SQL as the backend is complete, but now we simply print a message stating that the user should stop the server.
> dolt checkout message

- integration-tests/bats/helper/query-server-common.bash
* Pick from a random port from 2048 - 6146
* Use `nc` to check if port is in use rather than `lsof`
* Wait longer, in case the server retries successfully.
I tested by running 10 changes through GH actions. 5 jobs were controls with no changes, 5 had this change. The control group had 2 jobs which failed waiting to connect, while the group with this change had no failures.
> Small changes to help improve the wait_for_connection failures

- go/libraries/doltcore/merge/merge_prolly_rows.go
- go/libraries/doltcore/sqle/enginetest/dolt_engine_test.go
- go/libraries/doltcore/sqle/enginetest/dolt_queries_merge.go
- go/store/prolly/artifact_map.go
Issue https://github.com/dolthub/dolt/issues/6319 shows a case where our unique constraint checker reports false positives. This can happen when a row that is removed and a row that is inserted have duplicate values for columns that have a unique index declared over them. The root cause is that the deleted row is being incorrectly included in the rows checked for the unique constraint. 
I made two changes in this PR to fix this issue: 
- when row inserts or row deletes are processed by the unique constraint validator, it was previously not updating the data in it's index copy. This means if a row delete diff event comes in first, it wasn't getting removed from the index and when the row insert event comes in, it thinks there is a legitimate unique constraint violation with the deleted …
> Update unique constraint violations when rows are deleted

- go/libraries/doltcore/sqle/enginetest/dolt_engine_test.go
- go/libraries/doltcore/sqle/enginetest/dolt_queries_diff.go
- go/libraries/doltcore/sqle/sqlfmt/row_fmt.go
- integration-tests/bats/diff.bats
Current SQL formatting code converts binary values to strings, which won't round-trip back to the database correctly. This PR changes binary values to be hex-encoded. 
Fixes https://github.com/dolthub/dolt/issues/6350
> Bug fix: Encode binary values in hex for SQL patch statements

- go/cmd/dolt/commands/sql.go
- integration-tests/bats/sql-shell-empty-prompt.expect
- integration-tests/bats/sql-shell.bats
- integration-tests/bats/sql-works-after-failing-query.expect
Easy to reproduce issue:
```
mkdir foobar
cd foobar
dolt sql-server
```
```
dolt sql
> select 1;
```
And panic() follows. This actually happens for any command, so `create database dba` included.
> Allow empty databases in the shell prompt

- go/cmd/dolt/commands/sql.go
- go/cmd/dolt/dolt.go
- integration-tests/bats/no-repo.bats
- integration-tests/bats/sql-local-remote.bats
Adds warning message for unmigrated cli commands when they are attempted to be used remotely.
> add warning message for unmigrated cli commands

- go/libraries/doltcore/sqle/enginetest/dolt_queries.go
- go/libraries/utils/argparser/parser.go
- integration-tests/bats/branch.bats
Fixes: https://github.com/dolthub/dolt/issues/6001
> Allow `--` to escape arg parsing

- go/libraries/doltcore/diff/diffsplitter.go
- go/libraries/doltcore/diff/table_deltas.go
- go/libraries/doltcore/sqle/dolt_patch_table_function.go
- go/libraries/doltcore/sqle/enginetest/dolt_queries_diff.go
- go/libraries/doltcore/sqle/sqlfmt/schema_fmt.go
Adding support in `dolt_patch()` to: 
- return data diff patch statements when there are schema changes
- return schema diff patch statements for charset/collation changes
> Bug fixes for `dolt_patch`

- go/gen/fb/serial/workingset.go
- go/libraries/doltcore/doltdb/workingset.go
- go/libraries/doltcore/sqle/dprocedures/dolt_cherry_pick.go
- go/libraries/doltcore/sqle/dsess/session.go
- go/libraries/doltcore/sqle/enginetest/dolt_queries.go
- go/serial/workingset.fbs
- go/store/datas/dataset.go
- go/store/datas/workingset.go
- proto/README.md
When a cherry-pick requires conflict resolution, we set MergeState metadata in the working set to mark that a merge is in progress. `dolt commit` sees this metadata and incorrectly records the cherry-picked commit as a parent of the new, created commit. This PR fixes this, so that commits created by cherry-pick always have only one parent. To do this, we record an extra flag in MergeState that the current merge is a cherry-pick.
> Bug fix: Commits created with `cherry-pick` should only have one parent commit

- go/libraries/doltcore/sqle/enginetest/dolt_queries.go
- go/libraries/doltcore/sqle/history_table.go
The `dolt_history_...` table derives its schema from the base table + 3 additional columns [historyTableSchema()](https://github.com/dolthub/dolt/pull/6389/files#diff-bde037bd1753c546c0e70386a347eeddca4756f13d3976419a2eb3472e783867L146).
However, when we have a projection over the table, the schema returned from `HistoryTable.Schema()` is trimmed to only the columns we look at. This is problematic when we're join planning as we look over all indexes and panic when we find an index over a column that isn't in the schema; in this case, it's the Primary key.
By having `HistoryTable` implement `PrimaryKeySchema`, we can return a schema with all the columns, and the index picking portion of join planning works.
Fix for: https://github.com/dolthub/dolt/issues/6382
> fix panic in `dolt_history_<table>`

- go/libraries/doltcore/sqle/dtables/diff_table.go
- go/libraries/doltcore/sqle/enginetest/dolt_queries_diff.go
- integration-tests/bats/system-tables.bats
The `dolt_diff_<tablename>` system table uses the schema @ HEAD of the table being diff'ed. If the schema of the table has changed over time and has narrowed column types (e.g. `varchar(100)` → `varchar(10)`), then some historical values may not be valid against the table's current schema, which causes an error to be returned and no result set. This PR fixes that by changing the schema of `dolt_diff_<tablename>` to widen all of the column types to their widest size in the same family (e.g. `varchar(100)` → `TEXT`).
Fixes https://github.com/dolthub/dolt/issues/6391
> Bug fix: `dolt_diff_<tablename>` correctly shows historical values after narrowing types

- go/cmd/dolt/dolt.go
Currently if you have an unparsable config_global.json, we print a message say as much, then produce a panic attempting to use the config to print metrics. This just drops the attempt to produce the metrics.
> Don't panic when attempting to publish metrics if config is unparsable

- go/cmd/dolt/commands/sqlserver/sqlclient.go
- integration-tests/bats/sql-client.bats
Previously the --user option was forced for `sql-client` which is overly strict since users can provide it in a config.yaml file.
> Allow sql-client to get the username from the config file

- go/cmd/dolt/cli/arg_parser_helpers.go
- go/cmd/dolt/cli/flags.go
- go/cmd/dolt/commands/dump.go
- go/cmd/dolt/commands/fetch.go
- go/libraries/doltcore/env/actions/remotes.go
- go/libraries/doltcore/env/remotes.go
- go/libraries/doltcore/ref/ref.go
- go/libraries/doltcore/ref/ref_spec.go
- go/libraries/doltcore/ref/ref_spec_test.go
- go/libraries/doltcore/sqle/dprocedures/dolt_fetch.go
- integration-tests/bats/remotes.bats
- integration-tests/bats/sql-fetch.bats
`dolt fetch --prune` deletes any local remote refs that are not present on the remote being fetched. This is simpler than the equivalent git command, as it only operates on branches, not other kinds of refs.
Fixes https://github.com/dolthub/dolt/issues/6413
> Implemented --prune for fetch command procedure

- go/cmd/dolt/commands/profile.go
Updates `profile` doc string to reflect correct `dolt profile add` behavior.
> update profile doc string

- go/libraries/doltcore/sqle/dsess/transactions.go
- go/libraries/doltcore/sqle/enginetest/dolt_queries_merge.go
- integration-tests/bats/schema-conflicts.bats
- integration-tests/bats/sql-merge.bats
If `@@autocommit` is enabled, then a SQL commit will be created after every SQL statement. If a `dolt_merge()` operation results in data conflicts, then we return an error, revert the working set, and prevent the SQL commit. Schema conflicts should have the same behavior when `@@autocommit` is enabled, but they were not getting caught by our transaction logic. 
Fixes https://github.com/dolthub/dolt/issues/6469
> Bug Fix: Error on merges that produce schema conflicts when `@@autocommit` is enabled

- integration-tests/bats/bats.bats
While merging in https://github.com/dolthub/dolt/pull/6478, I wondered if there was a further step we could take to totally prevent future problems with this quirk, so I added a very quick BATS test that greps for the missing `|| false` issue that affects Mac OS and prints out any lines that are missing. Plus, it's fun to run `bats bats.bats`. 🦇
When it finds a missing `|| false`, [it fails the tests](https://github.com/dolthub/dolt/actions/runs/5814358497/job/15763874102?pr=6480#step:18:248) and outputs a list of the files and lines missing `|| false`: 
```
not ok 112 bats: all assertions work on Mac
```
> [no-release-notes] Automated check to prevent future bash test bugs on Mac

- dolt.plugin.zsh
This isn't perfect, but it's a starting point. What would be better:
* Create a separate repo for just this script (`dolthub/zsh`) for easier installation
* Change gen-zsh to output the script to stdout like `gh`, `op`, and other popular tools
You can use this via a `for` loop in zinit like:
```
zinit wait lucid for \
'https://github.com/iloveitaly/dolt/blob/zsh-plugin/dolt.plugin.zsh'
```
> feat: adding zsh plugin

- go/cmd/dolt/commands/diff.go
- go/cmd/dolt/commands/indexcmds/ls.go
- go/cmd/dolt/commands/merge.go
- go/cmd/dolt/commands/status.go
- go/libraries/doltcore/env/actions/table.go
- go/libraries/doltcore/merge/fulltext_rebuild.go
- go/libraries/doltcore/merge/merge.go
- go/libraries/doltcore/sqle/dtables/status_table.go
- integration-tests/bats/fulltext.bats
This does two primary things. First, it removes the pseudo-index tables from `dolt status`, the status table, merge, and diff outputs. This allows them to match the other index tables, which don't show up in those views anyway. Second, it fixes a bug during merge where the pseudo-index tables are the only ones that have been renamed. The setup is very unlikely, but it's been fixed nonetheless.
> Fixed Full-Text merge bug, removed pseudo-index tables from view

- go/cmd/dolt/commands/engine/sqlengine.go
- go/cmd/dolt/commands/sqlserver/server.go
- go/cmd/dolt/commands/sqlserver/serverconfig.go
- go/cmd/dolt/commands/sqlserver/yaml_config.go
- integration-tests/go-sql-server-driver/tests/sql-server-config.yaml
For example, this can be used to set `secure_file_priv` when the server starts up. That variable is non-dynamic, so it cannot be set with `SET @@GLOBAL...`
> dolt sql-server: Add a system_variables: key to config.yaml, which allows setting global system variables.

- go/libraries/doltcore/merge/merge_prolly_rows.go
- go/libraries/doltcore/sqle/enginetest/dolt_queries_merge.go
- go/store/prolly/tuple_map.go
- go/store/prolly/tuple_mutable_map.go
When processing a schema merge, we need to update existing, stored data in the primary index. We weren't updating the value descriptor in the prolly map to the new version from the changed schema, which started causing a problem with `BLOB`/`TEXT` types since validation checked that the value stored in those fields was a valid address pointing outside of the table to the real data. 
Related to https://github.com/dolthub/dolt/pull/6496 – the reason that PR wasn't able to cleanly repro the exact failure was because the merge was getting short circuited, since the right and left sides weren't both making changes, so essentially the merge was getting fast-forwarded instead.
> Bug fix: panic in schema merge when schema contains BLOB columns

- go/cmd/dolt/cli/arg_parser_helpers.go
- go/cmd/dolt/commands/remote.go
- go/libraries/doltcore/sqle/dprocedures/dolt_clone.go
- go/libraries/doltcore/sqle/dprocedures/dolt_remote.go
Apparently there are no tests for these flags because the tests don't blow up if I remove them. We still allow the flags in the CLI context though.
> Drop the aws flags from the `dolt_remote()` procedure

- go/libraries/doltcore/merge/merge_prolly_rows.go
Ensures that the tuple descriptors use the correct types, and don't do address validation on unnecessary data.
> Changing primary index to use the Rewriter function, instead of Mutate

- go/cmd/dolt/commands/version.go
- integration-tests/bats/init.bats
Remove "no valid database in this directory" from `dolt version` in the case of no dolt database found.
> `dolt version` only prints the dolt version if there is no dolt database in the directory.

- go/libraries/doltcore/doltdb/doltdb.go
- go/libraries/doltcore/doltdb/root_val.go
- go/libraries/doltcore/dtestutils/testcommands/multienv.go
- go/libraries/doltcore/env/actions/checkout.go
- go/libraries/doltcore/sqle/dprocedures/dolt_checkout.go
- go/libraries/doltcore/sqle/dprocedures/dolt_checkout_helpers.go
- integration-tests/bats/feature-version.bats
Fixes https://github.com/dolthub/dolt/issues/6524
`RootValue` is backed by a flatbuffer, but access to the flatbuffer is hidden behind interfaces. We check if two `RootValues` are equal by checking the RootValue's hash. This makes it awkward to check to see if two `RootValues` differ only by a single field.
The solution here is both simple and noninvasive: we create modified root values with the same feature version and hash them again.
This also adds an escape hatch when creating new branches, since we know that the new branches will be clean. We only do this extra check when checking out an existing branch.
> When checking out a branch, consider it clean if the working set differs from the head only by feature version.

- go/cmd/dolt/commands/branch.go
- go/libraries/doltcore/sqle/enginetest/dolt_queries.go
- integration-tests/bats/branch.bats
Previously `dolt branch foobar HEAD` would print a statement that HEAD is an invalid branch name. It would succeed though, and return an exit status of 0. So tests passed.
This is no longer the case.
> Silence branch create

- go/cmd/dolt/commands/init.go
- go/cmd/dolt/commands/sqlserver/server.go
- go/cmd/dolt/dolt.go
- go/libraries/doltcore/env/environment.go
- go/libraries/doltcore/env/multi_repo_env.go
- go/libraries/doltcore/sqle/binlogreplication/binlog_replication_test.go
- go/libraries/doltcore/sqle/database_provider.go
- integration-tests/bats/init.bats
- integration-tests/bats/sql-server.bats
- integration-tests/bats/sql.bats
WIth this change, starting `sql-server` will result in creating a .dolt/sql-server.lock file in the --data-dir (CWD by default). This file will be used for two purposes:
1) Ensuring another `dolt sql-server` is not started with the same data dir.
2) Allowing the `dolt sql` command to connect to it. See related issue: https://github.com/dolthub/dolt/issues/6508
> Empty Servers allow `dolt sql` connections without arguments

- go/libraries/doltcore/env/actions/checkout.go
- go/libraries/doltcore/sqle/dprocedures/dolt_pull.go
- integration-tests/bats/feature-version.bats
When pulling between two Dolt databases that have different feature versions, `dolt_pull()` can mistakenly interpret the difference in root value hash as being uncommitted changes. This change updates `dolt_pull()` to use the existing `actions.RootHasUncommittedChanges` function and changes that function to account for differing feature version when determining if roots have uncommitted changes.
> Bug fix:  Correctly detect uncommitted changes for `dolt_pull` when roots have different feature versions

- go/libraries/doltcore/sqle/procedures_table.go
- go/libraries/doltcore/sqle/procedures_table_test.go
Fixes: https://github.com/dolthub/dolt/issues/6579
Before, we were only migrating the table when a new stored procedure was added. This means that any branches that predate our recent change to dolt_procedures would be broken until a new stored procedure was added. This fixes that by checking to see if the table needs to be migrated whenever the stored procedures are listed or used, not just when they're added.
> Migrate the dolt_procedures table whenever stored procedures are used

- go/libraries/doltcore/sqle/read_replica_database.go
- go/libraries/doltcore/sqle/wildcard.go
- go/libraries/doltcore/sqle/wildcard_test.go
- integration-tests/bats/replication.bats
This change allows customers to use `*` as a wildcard in the [`@@dolt_replicate_heads` system variable](https://docs.dolthub.com/sql-reference/version-control/dolt-sysvars#dolt_replicate_heads) to match zero or more characters in a branch name. For example, to replicate the `main` branch and all branches that start with `feature`, the following configuration can now be applied:
```
dolt config --local --add sqlserver.global.dolt_replicate_heads main,feature*
```
Documentation: https://github.com/dolthub/docs/pull/1698
Fixes: https://github.com/dolthub/dolt/issues/6486
> Feature: Allow `*` wildcard in `@@dolt_replicate_heads`

- go/cmd/dolt/commands/version.go
- integration-tests/bats/init.bats
- integration-tests/bats/no-repo.bats
`dolt version` displayed the storage format version by default, but this information is less relevant now that almost all Dolt databases have been migrated to the new storage format. This change adds a new `--verbose` /  `-v` flag that customers can specify if they do want to see the storage format version for a repository. 
Fixes https://github.com/dolthub/dolt/issues/6528
> Move storage format version to only be displayed with `dolt version --verbose`

- go/cmd/dolt/cli/arg_parser_helpers.go
- go/cmd/dolt/commands/log.go
- go/libraries/doltcore/sqle/dolt_log_table_function.go
Creates a separate arg parser for `dolt log` and `dolt_log` to avoid supporting unneeded flags.
> Separate out log arg parsers

- go/libraries/doltcore/sqle/dprocedures/dolt_conflicts_resolve.go
- go/libraries/doltcore/sqle/enginetest/dolt_queries_merge.go
- integration-tests/bats/schema-conflicts.bats
- integration-tests/bats/sql-merge.bats
Until we fix the workflow around merging data **after** schema conflicts have been resolved, customers may be surprised by the results of `dolt_conflicts_resolve()` when there are schema changes, so putting this block in out of extra caution. 
For more details, see issue https://github.com/dolthub/dolt/issues/6616
> Temporarily restrict `dolt_conflicts_resolve()` from resolving schema conflicts

- go/cmd/dolt/commands/log.go
Allows `dolt log` to be called outside of dolt repos
> allows dolt log outside dolt repos

- go/libraries/doltcore/merge/merge_schema.go
- go/libraries/doltcore/sqle/enginetest/dolt_queries_schema_merge.go
We had a typo in the check constraint merging code that was only triggered when an existing check constraint was altered on the "source" side of the merge and the "destination" side of the merge had the exact same definition as the common ancestor. The new test shows a concrete example. Note that the schema merge tests run in both directions, from left to right, and from left to right, so they are better at catching bugs like this that only appear in one merge direction.
> Bug fix: Check constraint merging

- go/cmd/dolt/commands/log.go
Fixes panic when calling log in non-dolt repo by adding missing return statement.
> fixes log panic

- go/libraries/doltcore/sqle/dprocedures/dolt_backup.go
- go/libraries/doltcore/sqle/dprocedures/dolt_gc.go
- go/libraries/doltcore/sqle/dprocedures/init.go
Standardizes stored procedures that report a success/failure message to print `Status` of `0` on success and `Status` of `1` on failure. Changes from the old output of printing `Success` of `1` on success and `Success` of `0` on failure.
> Standardize stored procedure success output messages

- go/libraries/doltcore/sqle/dprocedures/init.go
- integration-tests/bats/sql-server.bats
The stored procedures for `dolt_checkout` and `dolt_count_commits` weren't marked as being read-only, so when run against a read-only sql-server, they resulted in an error about the database being read-only. 
Fixes: https://github.com/dolthub/dolt/issues/6730
> Bug fix: Allow `dolt_checkout()` and `dolt status` when running in read-only mode

- go/cmd/dolt/commands/branch.go
- go/cmd/dolt/commands/fetch.go
- go/cmd/dolt/commands/push.go
- go/cmd/dolt/commands/utils.go
Updates `fetch` context handling to properly exit with an error if force cancelled.
> update fetch context handling

- go/libraries/doltcore/merge/merge_prolly_rows.go
- go/libraries/doltcore/merge/row_merge_test.go
- go/libraries/doltcore/merge/schema_merge_test.go
- go/libraries/doltcore/sqle/index/prolly_fields.go
- go/store/prolly/tree/three_way_differ.go
- go/store/prolly/tree/three_way_differ_test.go
Fixes https://github.com/dolthub/dolt/issues/6660
I thought this was going to be a simple tweak, but it turns out that three-way merges in the presence of altered columns has some interesting subtleties.
First off, we don't just compare the bytes of cells when merging, we actually de-serialize them and check for equality. I suspect this doesn't matter in most cases, but is done because:
- Some types may have multiple ways to represent the same value, and
- In the event of an altered column, two distinct values (of different types) may have the same representation.
This leads to some subtle edge cases: for example, if once branch alters a column type, and then modifies a row so the cell as the same representation as the original, unaltered value, we still need to detect that as a …
> When a three-way merge contains an altered column, convert values to the new column type in order to prevent conflicts.

- go/libraries/doltcore/sqle/enginetest/dolt_queries_diff.go
It looks like this issue was fixed, but there wasn't a test for this specific case.
This PR adds tests for joining two `diff_table_function(...)` with alias.
fixes https://github.com/dolthub/dolt/issues/4798
> [no-release-notes] test for joining diff table function with alias

- go/cmd/dolt/commands/docscmds/read.go
- go/libraries/doltcore/doltdb/system_table.go
- go/libraries/doltcore/sqle/database.go
- go/libraries/doltcore/sqle/dtables/docs_table.go
- go/libraries/doltcore/sqle/sqlddl_test.go
- go/libraries/doltcore/sqle/sqlselect_test.go
- integration-tests/bats/cp-and-mv.bats
- integration-tests/bats/docs.bats
- integration-tests/mysql-client-tests/node/workbenchTests/docs.js
Currently if you are using a SQL-only interface like Hosted, you have to manually create the `dolt_docs` system table to use it. This changes that functionality to be the same as the [`dolt_ignore` system table](https://github.com/dolthub/dolt/pull/5809), which is created on writes and returns an empty index on reads. The table will always exist as far as the mysql engine is concerned.
Related to https://github.com/dolthub/dolt/issues/6809
> Automatically create `dolt_docs` table

- go/libraries/doltcore/sqle/cluster/branch_control_replica.go
- go/libraries/doltcore/sqle/cluster/controller.go
- go/libraries/doltcore/sqle/cluster/mysqldb_persister.go
- integration-tests/go-sql-server-driver/tests/sql-server-cluster.yaml
Graceful transitions to standby block on the primary until a certain number of replicas are trued up. They then return a status of whether each database on each replica is caught up, so that a control plane agent can pick a caught up server to be next primary, for example.
The newly added replication of users and grants and branch control permissions did not used to participate in this graceful transition logic. This makes it so that the state of mysql and dolt_branch_control replication is reported in the rows returned from `call dolt_cluster_transition_to_standby` and those databases must also be caught up on a replica for the replica to be considered fully caught up.
> go: sqle: cluster: When performing a graceful transition to standby, take mysql and dolt_branch_control replication state into account.

- go/cmd/dolt/commands/merge_base.go
- go/cmd/dolt/dolt.go
- integration-tests/bats/sql-local-remote.bats
This change updates dolt merge-base to use the appropriate sql engine to generate results.
> migrate dolt merge-base to use sql queries

- go/cmd/dolt/cli/arg_parser_helpers.go
- go/cmd/dolt/cli/flags.go
- go/cmd/dolt/commands/fetch.go
- go/cmd/dolt/commands/pull.go
- go/cmd/dolt/commands/push.go
- integration-tests/bats/fetch.bats
- integration-tests/bats/pull.bats
- integration-tests/bats/push.bats
Adds a `--silent` option for `push`, `pull`, `fetch` to suppress output of progress information.
Resolves: https://github.com/dolthub/dolt/issues/6828
> add --silent option for push, pull, fetch

- go/cmd/dolt/commands/tblcmds/import.go
- go/libraries/doltcore/mvdata/engine_table_writer.go
- integration-tests/bats/default-values.bats
- integration-tests/bats/import-append-tables.bats
- integration-tests/bats/import-update-tables.bats
This changes improves the error message for `dolt table import` to be more readable and useful. Notably, this change adds the column names, table name, and file line number to the error output.
Resolves: https://github.com/dolthub/dolt/issues/5718
> Improve import table error message

- go/cmd/dolt/dolt.go
- integration-tests/bats/no-repo.bats
This change allows `dolt version` to run in folders without write permissions.
Resolves: https://github.com/dolthub/dolt/issues/2898
> Allow `dolt version` in folders without full permissions

- go/libraries/doltcore/dbfactory/aws.go
- go/libraries/utils/awsrefreshcreds/creds.go
- go/libraries/utils/awsrefreshcreds/creds_test.go
Some use cases put attenuated, expiring credentials into files. It's nice to pick up the new credentials without needing to recreate the client.
> dbfactory: aws: For AWS remotes using an explicit file credentials, periodically refresh the credentials the AWS client uses from the file contents.

- go/libraries/doltcore/doltdb/commit_itr.go
- go/libraries/doltcore/sqle/enginetest/dolt_queries_diff.go
Changes parent order processing in commit iterator so that we prioritize traversing the parent of a merge commit that supplied the commits merged in that commit, before we traverse the other merge parent. 
Fixes: https://github.com/dolthub/dolt/issues/6861
> Ensure `dolt_diff_<tablename>` reports most-specific commit that changed a row

- integration-tests/bats/sql-multi-db.bats
Unskipped a bats test I added for a join across multiple databases on tables of the same name that is now fixed.
> Remove skip on now passing test for multi-db joins on tables with the same name

- go/libraries/doltcore/sqle/enginetest/dolt_queries.go
- go/libraries/doltcore/sqle/index/index_lookup.go
When filtering on an indexed column from the primary index (i.e. a pk column) if a column in the underlying table has been modified and changed its tag in previous versions, we weren't able to create the lookup builder and caused a segfault. This PR changes to use the primary index as a covering index, since it's the closest we have. This is also consistent with [how we had implemented Noms range lookups](https://github.com/dolthub/dolt/blob/1eda29268649a30ae68606f59760959e0a62ed8e/go/libraries/doltcore/sqle/index/index_lookup.go#L86). 
Related to: https://github.com/dolthub/dolt/issues/6891
> Bug fix: for `dolt_history_` system tables

- go/libraries/doltcore/diff/table_deltas.go
- integration-tests/bats/import-create-tables.bats
This change takes out the schema check for tables with the same name that get modified. Previously, only tables that get dropped and re-added with the same name and same schema would get labelled as modified. Now, tables that get dropped and re-added with the same name regardless of schema will get labelled as modified.
Fixes: https://github.com/dolthub/dolt/issues/5738
> Remove schema overlap check for tables with same name

- go/cmd/dolt/commands/filter-branch.go
- go/libraries/doltcore/rebase/filter_branch_test.go
- go/libraries/doltcore/rebase/rebase.go
- integration-tests/bats/filter-branch.bats
Fixes https://github.com/dolthub/dolt/issues/6895
The command can now process multiple queries by default, and will ignore errors executing them with a `--continue` flag. This is a breaking change:
1. Previously, certain errors were detected and ignored by default. Now this behavior is controlled by the --continue flag.
2. Previously, the query to execute was specified as an argument. Now it's a flag, `--query`, or can be read via STDIN.
> More flexibility for `filter-branch` command

- go/libraries/doltcore/sqle/enginetest/dolt_queries.go
- go/libraries/doltcore/sqle/reflog_table_function.go
- go/store/nbs/journal.go
Allows `dolt_reflog()` to be called without any arguments to list the contents of the reflog/chunk journal. Internal ref types and ref types that don't always point to a commit (i.e. working set refs) are still excluded. 
While testing this, I realized that we needed to change to iterate the chunk journal roots in order (instead of in reverse order), otherwise we don't identify the correct, **first** root where a ref was set to a new value and the ref updates don't appear in the right order in the reflog.
> Adding support for listing all entries in `dolt_reflog()`

- go/libraries/doltcore/dconfig/envvars.go
- go/store/nbs/journal.go
- go/store/nbs/journal_writer.go
- integration-tests/bats/reflog.bats
Allows customers to set `DOLT_DISABLE_REFLOG` to disable reflog data from being kept in memory.
> Adding an env var to disable reflog data tracking

- go/libraries/doltcore/dconfig/envvars.go
- go/store/nbs/journal.go
- go/store/nbs/journal_writer.go
- integration-tests/bats/reflog.bats
I'll replace this with a ring buffer very soon, but I wanted to get something in place to prevent the slice from growing too large.
> Enforce a configurable max size for reflog data

- go/cmd/dolt/commands/tblcmds/import.go
- integration-tests/bats/import-create-tables.bats
Adds a test verifying that importing a `NULL` value doesn't violate foreign key constraints.
Related: https://github.com/dolthub/dolt/issues/2108
> Importing `NULL` doesn't violate foreign key constraints

- integration-tests/bats/import-create-tables.bats
Fixes the bats test for overwriting data in an existing table with FK constraints to properly test the intended behavior.
Related: https://github.com/dolthub/dolt/issues/2281
> Fix `import` bats test for existing table with FK constraints

- go/store/nbs/journal.go
- go/store/nbs/journal_writer.go
- go/store/nbs/journal_writer_test.go
- go/store/nbs/reflog_ring_buffer.go
- go/store/nbs/reflog_ring_buffer_test.go
- integration-tests/bats/reflog.bats
Changes the in-memory reflog buffer to be a ring buffer, to limit on how much memory is used. 
Although we do have an `async.RingBuffer` type already, it has slightly different use case. This implementation is more tailored to the reflog buffer's needs, including supporting iteration, and less locking and synchronization.
> Switch reflog data to be stored in a ring buffer

- go/libraries/doltcore/merge/merge_prolly_indexes.go
- go/libraries/doltcore/merge/merge_prolly_rows.go
At the end of a merge, Dolt was rebuilding some secondary indexes that did not need to be rebuilt. https://github.com/dolthub/dolt/issues/6951 shows one example where the destination side of a merge has an existing index that does not exist on the source side of the merge. Dolt's merge code correctly updates that secondary index in place as the merge diffs are processed, but we were still doing an unnecessary full rebuild on the secondary index after processing all the diffs for that table. 
Making this optimization uncovered another bug where column default values weren't being applied when merging a new row into a secondary index. This PR also fixes that bug, by ensuring that we remap a tuple and apply the column default value, before updating the secondary index with the new tuple.
> Optimize when secondary indexes need to be fully rebuilt after a merge

- go/store/val/tuple_compare.go
- go/store/val/tuple_descriptor.go
- go/store/val/tuple_descriptor_test.go
- integration-tests/bats/sql-spatial-types.bats
The addition of the new `GeomAddrEnc` needs to be explicitly known as an address type, so that `dolt gc` doesn't delete the chunks created.
fixes https://github.com/dolthub/dolt/issues/6969
> make `GeomAddrEnc` known as an address encoding

- go/libraries/doltcore/doltdb/root_val.go
- go/libraries/doltcore/sqle/sqlselect_test.go
- integration-tests/bats/helper/common.bash
Due to bug in `GeomAddrEnc`s not getting their chunks properly registered, we were deleting them on push and garbage collection. PR https://github.com/dolthub/dolt/pull/6973 addresses the issue, but it was a storage layer change, so a feature bump is necessary.
Related issue: https://github.com/dolthub/dolt/issues/6969
> [no-release-notes] bump feature version

- go/store/nbs/file_table_persister.go
Dolt sometimes persists whole table files, instead of appending blocks to the chunk journal. In order to be as crash resistent as the chunk journal, we should fsync the writes before we add the new table file to the database.
Cases which use this code path and could have seen reduced durability across crashes include: dolt_fetch, dolt_pull, dolt_clone, dolt_gc, and dolt_push/dolt_backup to a file remote.
> go/store/nbs: file_table_persister: fsync whole table file writes.

- go/cmd/dolt/cli/arg_parser_helpers.go
The merge CLI command and SQL stored procedure both validate that the working set is clean before it will start a merge, so the warning about uncommitted changes isn't relevant.
> Update docs for merge's `--abort` param

- go/cmd/dolt/dolt.go
- integration-tests/bats/config.bats
- integration-tests/bats/no-repo.bats
- integration-tests/bats/profile.bats
This change allows`dolt config` to run in folders without write permissions.
Fixes: https://github.com/dolthub/dolt/issues/2313
> Allow `dolt config` to run in folders without write permissions

- go/libraries/doltcore/dbfactory/dirtodbname.go
- go/libraries/doltcore/dconfig/envvars.go
- go/libraries/doltcore/env/multi_repo_env_test.go
- integration-tests/bats/db-revision-specifiers.bats
- integration-tests/bats/deleted-branches.bats
- integration-tests/bats/dump.bats
- integration-tests/bats/sql-checkout.bats
- integration-tests/bats/sql-client.bats
- integration-tests/bats/sql-commit.bats
- integration-tests/bats/sql-create-database.bats
- integration-tests/bats/sql-merge.bats
- integration-tests/bats/sql-reset.bats
- integration-tests/bats/sql-server.bats
- integration-tests/bats/sql.bats
- integration-tests/bats/undrop.bats
As of Dolt version `1.27.0`, we allow hyphens in database name and replace space characters with underscores and reduce multiple underscore characters side by side into single underscore character.
This PR resolves: 
- Using the database name the same as directory name on disk allows round-trip to the database location on disk.
Note:
- A potential issue might arise when the directory name has trailing space characters. MySQL do not allow database name with trailing space characters such as `mydb `, whereas Dolt allows. This will cause failing import of dolt dump to MySQL.
> use database name that is the same as directory name on disk

- go/libraries/doltcore/merge/merge_prolly_rows.go
- go/libraries/doltcore/merge/merge_rows.go
- go/libraries/doltcore/merge/merge_schema.go
- go/libraries/doltcore/merge/schema_integration_test.go
This prevents a bunch of expensive computation in places where it isn't necessary.
Basically when computing the schema diff, we now compute:
- Whether the left side needs to be remapped to the final schema
- Whether the right side needs to be remapped to the final schema
- Whether we should invalidate all secondary indexes because a column changed its type.
The last one's the odd one out, since it's less a fact about the merge and more this derived property that could change later if we figure out a good way to update secondary indexes in the presence of schema change. But we can bikeshed the specifics once users aren't blocked by this.
We store all this data in a new `MergeInfo` struct, which gets passed around the merge logic.
> Track whether or not rows actually need to be remapped to the result schema.

- go/libraries/doltcore/merge/merge_prolly_rows.go
- go/libraries/doltcore/sqle/enginetest/dolt_queries_merge.go
This fixes one of the failures from https://github.com/dolthub/dolt/issues/7034, but it's the more important one (the panic)
Before, we would panic when attempting to compute a merged row if that row would contain a null in a non-null column.
Now, we allow this row to be generated, and we validate it before merging it into the table.
> Run nullness checking on merged rows during three-way merges.

- integration-tests/bats/ls.bats
`ls.bats` was using test table names like `t1` and `t2` and making assertions against the output of `dolt ls`. But the output of `dolt ls` also sometimes includes a commit hash, which can itself contain these strings.
Change it so that we use names which will never appear in a commit hash.
> [no-release-notes] integration-tests/bats: ls.bats: Fix a flakey failure where an unlucky hash could cause a negative assertion to fail.

- go/cmd/dolt/commands/gc.go
- go/cmd/dolt/commands/ls.go
- go/cmd/dolt/commands/query_diff.go
Updates doc strings for `query-diff` and `ls`.
> minor doc fixes

- go/cmd/dolt/commands/sqlserver/creds.go
There was an infinite loop for `dolt init` and `dolt sql` when there isn't a `.dolt` directory in current directory or any children directory. This issue was specific to windows, because we were only checking for `/` and not `\`.
> fix inf loop for creds search on windows

- go/cmd/dolt/commands/gc.go
- go/cmd/dolt/dolt.go
- integration-tests/bats/helper/local-remote.bash
- integration-tests/bats/reflog.bats
- integration-tests/bats/sql-local-remote.bats
This change updates `dolt gc` to use the appropriate sql engine to generate results.
> migrate `dolt gc` to use sql queries

- go/cmd/dolt/cli/arg_parser_helpers.go
- go/cmd/dolt/cli/flags.go
- go/cmd/dolt/commands/checkout.go
- go/libraries/doltcore/sqle/dprocedures/dolt_checkout.go
- go/libraries/doltcore/sqle/enginetest/dolt_queries.go
- integration-tests/bats/checkout.bats
Resolves Issue: https://github.com/dolthub/dolt/issues/7116
> Add support for -B flag to dolt_checkout

- go/libraries/doltcore/merge/merge_schema.go
- go/libraries/doltcore/merge/schema_merge_test.go
- go/libraries/doltcore/merge/type_compatibility.go
- go/libraries/doltcore/merge/type_compatibility_test.go
- go/libraries/doltcore/merge/violations_prolly.go
- go/libraries/doltcore/sqle/dtables/constraint_violations_prolly.go
- go/libraries/doltcore/sqle/enginetest/dolt_queries_schema_merge.go
- go/store/prolly/tree/three_way_differ.go
This allows automatic merging in the case where:
- One branch changes the collation of the column.
- The other branch modifies cells in that column.
It's still a requirement that only one branch is allowed to modify the column definition. So for instance, if one branch changes the collation, and the other branch widens the column, that will still be a schema merge conflict. There's no reason we can't allow it, but the logic is more complicated so I'm saving it for a follow-up PR.
> Allow automatic merging in the presence of collation changes.

- integration-tests/bats/performance.bats
I originally settled on a 50-second timeout for these tests because a 100-second timeout was too high to consistently detect the performance regression that motivated https://github.com/dolthub/dolt/pull/7044.
I suspect that any timeout high enough to avoid spurious failures is too high to reliably detect actual regressions. Detecting performance regressions is important, but this isn't the way to do it.
We shouldn't be blocking CI on this. We should incorporate these performance tests into our daily benchmarking instead.
> Disable performance bats test.

- go/cmd/dolt/commands/version.go
- integration-tests/bats/no-repo.bats
Changes `dolt version` out of date warning to do a check against GitHub if the current build version is ahead of the stored latest release version. Fixes inconsistencies where the current build is running a version that was released within the past week.
> fixes `dolt version` out of date warning

- go/cmd/dolt/commands/login.go
Updates the messaging for `dolt login` to have more clear instructions if a browser does not automatically open.
Resolves: https://github.com/dolthub/dolt/issues/7133
> Better messaging for `dolt login`

- go/libraries/doltcore/sqle/dtables/column_diff_table.go
- go/libraries/doltcore/sqle/enginetest/dolt_queries_diff.go
JSON types are represented as `map[string]interface{}`, which panics in Golang when used with `!=` operator. 
This PR changes the logic to use our `gmstypes.Compare()` logic instead,
fixes https://github.com/dolthub/dolt/issues/7140
> fix `column_diff_table` for modifed json columns

- go/cmd/dolt/commands/version.go
- integration-tests/bats/no-repo.bats
Fixes an issue where bad data in `version_check.txt` returns an error. This change makes version overwrite any bad data in this file instead.
Fixes: https://github.com/dolthub/dolt/issues/7138
> Poorly formatted version doesn't error

- go/libraries/doltcore/sqle/database.go
- go/libraries/doltcore/sqle/dtables/blame_view.go
- go/libraries/doltcore/sqle/enginetest/dolt_queries.go
Fixes the `dolt_blame_<tablename>` view definitions so that table names and primary key column names are backtick quoted. Without this, customers can't use the `dolt_blame_<tablename>` views if the table name or primary key columns contain characters (e.g. "-") that require identifier quoting.
> Bug fix: `dolt_blame_<tablename>` view should backtick quote identifiers

- go/libraries/doltcore/sqle/cluster/branch_control_replica.go
- go/libraries/doltcore/sqle/cluster/mysqldb_persister.go
- integration-tests/go-sql-server-driver/tests/sql-server-cluster-users-and-grants.yaml
Previously these changes would only get replicated to the first database in the cluster.
> go: sqle: cluster: Fix MySQLDb and dolt_branch_control replication for the cases where you have more than one standby server in the cluster.

- go/cmd/dolt/commands/tblcmds/import.go
- integration-tests/bats/import-append-tables.bats
- integration-tests/bats/import-create-tables.bats
- integration-tests/bats/import-replace-tables.bats
- integration-tests/bats/import-update-tables.bats
Updates the warning message for `dolt table import` to print when the import schema does not match the destination table's schema, not just when there are fewer columns in the import file. Also updates the warning message to list the column names that differ between the import file and the destination table's schema.
Resolves: https://github.com/dolthub/dolt/issues/6113
> More detailed warning message for import schema not matching

- go/libraries/doltcore/sqle/cluster/controller.go
- integration-tests/go-sql-server-driver/tests/sql-server-cluster.yaml
Previously `dolt sql-server` would error if there were existing databases and they were missing any of the remotes listed as cluster replication remotes in the config.yaml. This changes it so that those remotes are automatically created at startup instead.
> go: sqle: cluster: Create missing remotes for cluster replication on startup if they do not already exist.

- integration-tests/mysql-client-tests/cpp/mysql-connector-cpp-test.cpp
- integration-tests/mysql-client-tests/rust/src/mysql_connector_test.rs
Added assertions that result set column name metadata is populated for the C++ and Rust MySQL Connector libraries.
> Adding tests for column name metadata through MySQL C++ and Rust Connector

- go/cmd/dolt/commands/config.go
- go/cmd/dolt/commands/config_test.go
- go/cmd/dolt/dolt.go
- go/libraries/utils/config/keys.go
- integration-tests/bats/config-home.bats
- integration-tests/bats/config.bats
Prints a warning if any nonsense variables are found in global or local config files whenever any CLI command is run. Also restricts users from adding any nonsense variables with `dolt config --add` or `dolt config --set`.
Resolves: https://github.com/dolthub/dolt/issues/7165
> Warning for nonsense variables in config

- go/libraries/doltcore/doltdb/durable/index.go
- go/libraries/doltcore/doltdb/durable/table.go
- go/libraries/doltcore/merge/merge_prolly_rows.go
- go/libraries/doltcore/merge/schema_merge_test.go
- go/store/prolly/tree/mutator.go
Prior to this PR, we used the column's comparison operator when attempting to detect if concurrent changes to a column could be resolved during a merge operation.
However, this can cause a problem when a type has two different representations that compare equal.
- Some types have different representations that compare equal but can exhibit different behavior. For example, strings in a case-insensitive text column compare equal but behave differently when used in a context with a different collation and when displayed to the user. In this case, the merge algorithm should not consider them equal.
- Other types have different representations that compare equal and exhibit identical behavior. For example, we store Decimal types as a (integer, exponent) pair, but we don't normalize this pair. …
> Correctly resolve merge conflicts for types where two values with different representations can compare equal.

- go/performance/continuous_integration/config.json
We have a separate CI job to test that the `sysbench_runner` util is working. It wasn't specifying any tests, so all tests in the `ScriptDir` were being run. Once postgres specific tests landed there, it started failing this CI job. 
This changes the configuration for the `sysbench_runner` CI test job to explicitly specify which tests to run, and includes three basic tests, just for a smoke test to ensure `sysbench_runner` is working correctly (not actually for the perf results).
> [no-release-notes] Changing sysbench_runner CI test to explicitly specify script tests

- go/cmd/dolt/dolt.go
- integration-tests/bats/config.bats
Updates the config warning to print to `stderr` instead of `stdout` so as to not clutter up output
> Nonsense config warning prints to stderr

- go/libraries/doltcore/env/actions/remotes.go
- integration-tests/bats/sql-server-remotesrv.bats
Currently every push results in the message "[new branch] ..." which is misleading. Unfortunately fixing this for all updates is way harder than I want to dig into at the moment, so I'm going to make the only case we can detect easily (delete) print a better message.
> Delete branch message as a push result

- go/libraries/doltcore/sqle/dprocedures/dolt_pull.go
`dolt_pull` currently performs unnecessary FastForwards for remote branches. There is a more optimal mechanism to fetch all remotes, actions.FetchRefSpecs, and by using that we greatly increase the speed of `dolt_pull` when there are lot of remote branches.
> dolt_pull performance improvement

- go/cmd/dolt/commands/sql.go
- go/cmd/dolt/commands/utils.go
- go/libraries/doltcore/sqle/dfunctions/active_branch.go
- integration-tests/bats/sql-delimiter.expect
- integration-tests/bats/sql-shell-prompt.expect
- integration-tests/bats/sql-shell.bats
- integration-tests/bats/sql-unique-error.expect
- integration-tests/bats/sql-use.expect
Three changes to the `dolt sql` shell:
* Show the branch you are on: `mydb/main>`
* Show the workspace is dirty with a "*" in the prompt
* Add color to the DB name, branch, and dirty status.
> sql shell prompt includes branch name

- go/cmd/dolt/commands/tblcmds/import.go
- integration-tests/bats/import-append-tables.bats
- integration-tests/bats/import-create-tables.bats
- integration-tests/bats/import-replace-tables.bats
- integration-tests/bats/import-tables.bats
- integration-tests/bats/import-update-tables.bats
Adds the `--all-text` option to `dolt table import` which will default all columns to `TEXT` type.
Resolves: https://github.com/dolthub/dolt/issues/6471
> default to text option for `dolt table import`

- go/store/cmd/noms/noms_show.go
- go/store/types/serial_message.go
Previously, `noms show` was panicking whenever it encountered a CommitClosure. This change fixes that.
splunk.pl output:
```
> 1
Commit - {
Name: macneale
Desc: Commit 99
Email: neil@dolthub.com
Timestamp: 2024-01-09 09:50:00.585 -0800 PST
UserTimestamp: 2024-01-09 09:50:00.585 -0800 PST
Height: 102
RootValue: {
1)              #35dg4sptca4emt0k9orosh3la006uva5
}
Parents: {
2)              #fbouk8diedhbcn9u4en864rnicjf6o1v
}
ParentClosure: {
3)              #lpmpi89fvo7929f4vatojn6kblma3a2n
}
}
> 3
CommitClosure - {
SubTree {
1)              #ul2o0kblv5dm7jigm7aq9kbut8t1an2u
2)              #u3q2qqtah9ltt03523gnbic5ra8vra7l
}
Commits {
}
}
> 2
CommitClosure - {
SubTree {
}
Commits {
1)              #00j5cnf3fbpvil46s6fjni5hb861t3t5 (height: 92)
2) …
```
> [no-release-notes] Human Readable CommitClosure printing

- go/libraries/doltcore/doltdb/table.go
- go/libraries/doltcore/sqle/dtables/constraint_violations_prolly.go
- go/libraries/doltcore/sqle/enginetest/dolt_queries_merge.go
- integration-tests/bats/constraint-violations.bats
Keyless tables didn't expose a unique row identifier in the `dolt_constraint_violations_<table>` system tables. This manifested as a panic when trying to delete the violation artifacts from the system table, but it also meant that we couldn't uniquely identify rows in the system table by the system table's PK for keyless tables. To enable keyless tables to use constraint violation artifacts, we now return the row's identifying hash from the source keyless table in the system table. Note that the `dolt_conflicts_<table>` system table did not have a similar issue because its primary key is a unique ID generated in the `dolt_conflict_id` field. 
Related to: https://github.com/dolthub/dolt/issues/7275
> Bug fix: keyless table constraint violations

- integration-tests/bats/remotesrv.bats
Doing so can cause `dolt` to open the remotesrv database as a DoltDB, which may race with remotesrv opening it and may cause it to appear to read-only in the remotesrv process.
> [no-release-notes] integration-tests/bats: Ensure we do not run `dolt` from a parent directory of the remotesrv dir.

- go/libraries/doltcore/sqle/enginetest/dolt_engine_test.go
- go/libraries/doltcore/sqle/enginetest/dolt_queries.go
- go/libraries/doltcore/sqle/enginetest/dolt_query_plans.go
- go/libraries/doltcore/sqle/index/dolt_index.go
The analyzer rule `replacePkSort` does not work over certain types of indexes as some indexes are unordered.
Certain dolt system tables use a MockIndex because they are not backed by a datastore. 
Unfortunately, we don't have a proper `nil` check for the `idxSch`, leading to a panic when attempting to sort by columns in those mock indexes
This PR adds a nil check, so we don't try to use these indexes.
fixes https://github.com/dolthub/dolt/issues/7404
> Prevent panic when sorting by `commit_hash` in various dolt system tables

- go/libraries/doltcore/merge/action.go
- go/libraries/doltcore/sqle/enginetest/dolt_queries.go
Tables that match `dolt_ignore` in the working set should be ignored by most operations.
(CAVEAT: If we want to match git, these tables should only be ignored if there are not staged/HEAD versions of those tables. But we appear to not match git in that regard right now.)
This PR changes the logic for aborting merges to avoid modifying any tables match `dolt_ignore`
> When aborting a merge/cherry-pick, avoid resetting ignored tables.

- go/libraries/doltcore/env/actions/clone.go
- go/libraries/doltcore/sqle/database_provider.go
- go/libraries/doltcore/sqle/dprocedures/dolt_clone.go
- integration-tests/bats/sql-server-remotesrv.bats
Previously the dolt_clone() stored procedure would take the --user flag, but not use it in a gRPC call to a sql-server. This
addresses this limitation, and adds a test to verify it works.
> dolt_clone and --user

- .github/workflows/cd-release.yaml
The `homebrew-bump` step in the Dolt release workflow has been broken for a few months. New versions of Dolt still get published to brew though. Pulling out this step while we figure out how to fix it.
> [no-release-notes] Removing `homebrew-bump` step in Dolt release

- go/cmd/dolt/commands/version.go
- go/libraries/utils/config/keys.go
- integration-tests/bats/no-repo.bats
Adds a message to provide instructions on how to disable the version out-of-date check. This message will print once per version.
Related: https://github.com/dolthub/dolt/issues/7435
> add disable version check warning

- go/libraries/doltcore/env/actions/remotes.go
- integration-tests/bats/remotes-push-pull.bats
- integration-tests/bats/remotes.bats
Fix for: https://github.com/dolthub/dolt/issues/7448
> push should ignore tracking branch

- go/cmd/dolt/cli/command.go
- go/cmd/dolt/commands/sqlserver/server.go
- go/cmd/dolt/dolt.go
- go/libraries/doltcore/dbfactory/grpc.go
- go/libraries/events/collector.go
- go/libraries/events/emitter.go
- go/libraries/events/events_test.go
We make the GlobalCollector mutable.
We give the Collector a sendingThread which can have an Emitter. When the Collector collects enough events, it forwards a batch of them to the sendingThread. If the sendingThread has an Emitter, it attempts to send its current batch on that Emitter.
On shutdown, contexts get canceled, background threads get waited on, and then an accumulated un-emitted events are returned from the Collector, same as previously.
> go/libraries/events: Restructure events collection so that we can send events while the dolt process is running.

- go/cmd/dolt/commands/engine/sqlengine.go
- go/libraries/doltcore/sqle/enginetest/dolt_queries.go
- go/libraries/doltcore/sqle/indexed_dolt_table.go
`IndexedDoltTable` wasn't fully compatible with `DoltTable`'s interface, which was causing some queries to execute incorrectly due to using the wrong field indexes. This only happened with queries where the table was used in a read-only context (such as an `AS OF` query), since in a read-write context `WritableIndexedDoltTable` is used, which is composed of a `WritableDoltTable`, so fully inherits the interface. `IndexedDoltTable` is now consistent with that, and is now composed of a `DoltTable` instance. This enables the GMS code in `assignExecIndexes` to use the correct, limited schema of the secondary index and to apply the correct field indexes. 
Fixes: https://github.com/dolthub/dolt/issues/7488
> Bug fix: `IndexedDoltTable` didn't fully implement `DoltTable`'s interface

- go/libraries/doltcore/sqle/cluster/interceptors.go
- integration-tests/go-sql-server-driver/tests/sql-server-cluster.yaml
When in detected_broken_config, become standby if we see a higher numbered primary.
> go: sqle/cluster: When in standby mode, take the epoch of the primary.

- go/libraries/doltcore/sqle/database_provider.go
- integration-tests/bats/sql-create-database.bats
We have to convert windows file path separators to unix ones, when removing them from singleton cache.
Additionally, unskips some bats tests
Fixes https://github.com/dolthub/dolt/issues/7492
> Fix windows file paths for dropping databases

- docker/Dockerfile
- docker/serverDockerfile
Install both packages on one Docker layer and delete package cache after installation.
Docker image size decreased from 259 MB to 210 MB.
> Less docker layers and more compact Docker image

- .github/workflows/bump-dependency.yaml
- .github/workflows/cd-release-pgo.yaml
- .github/workflows/ci-bats-macos.yaml
- .github/workflows/ci-bats-unix-remote.yaml
- .github/workflows/ci-bats-unix.yaml
- .github/workflows/ci-bats-windows.yaml
- .github/workflows/ci-check-repo.yaml
- .github/workflows/ci-compatibility-tests.yaml
- .github/workflows/ci-go-race-tests.yaml
- .github/workflows/ci-go-tests.yaml
- .github/workflows/ci-lambdabats-unix.yaml
- .github/workflows/ci-sql-server-integration-tests.yaml
- .github/workflows/import-perf.yaml
- .github/workflows/merge-perf.yaml
- .github/workflows/sysbench-perf.yaml
Changes:
- Bump actions/setup-go
- Use Go version from go.mod file
- Move actions/checkout before actions/setup-go
> Bump actions/setup-go and use Go version from go.mod file

- go/cmd/dolt/commands/engine/sqlengine.go
- go/libraries/doltcore/sqle/enginetest/dolt_engine_test.go
- go/libraries/doltcore/sqle/enginetest/dolt_harness.go
- go/libraries/doltcore/sqle/enginetest/stats_queries.go
- go/libraries/doltcore/sqle/stats/stats_provider.go
- go/libraries/doltcore/sqle/stats/update.go
- go/store/types/serial_message.go
There's one root chunk for an empty table that needs special handling because there is no histogram bucket for it.
> [stats]: fix panic for empty table stats with one root chunk

- go/store/datas/pull/pull_chunk_tracker.go
- go/store/datas/pull/pull_chunk_tracker_test.go
- go/store/datas/pull/puller.go
The PullChunkTracker is an optimization which can concurrently call HasMany on the destination database while chunks are being pulled from the source database.
> go/store/datas/pull: Create a PullChunkTracker for keeping track of what to pull.

- go/libraries/doltcore/sqle/database.go
- go/libraries/doltcore/sqle/enginetest/dolt_engine_test.go
- go/libraries/doltcore/sqle/enginetest/dolt_queries.go
- go/libraries/doltcore/sqle/enginetest/prepared_queries.go
Found an issue with the history table while testing GORM. It's specific to the ComPrepare interface, this doesn't trigger with a simple PREPARE query.
```
DEBU[0197] preparing query                               paramsCount=2 query="SELECT column_name, column_default, is_nullable = 'YES', data_type, character_maximum_length, column_type, column_key, extra, column_comment, numeric_precision, numeric_scale , datetime_precision FROM information_schema.columns WHERE table_schema = ? AND table_name = ? ORDER BY ORDINAL_POSITION" statementId=2
ERRO[0197] mysql_server caught panic:
interface conversion: sql.Table is *sqle.WritableDoltTable, not *sqle.AlterableDoltTable
/Users/maxhoffman/go/pkg/mod/github.com/dolthub/go-mysql-server@v0.18.1-0.20240313225114-4a2f2300d770/sql/planbuilder/parse.go:16 …
```
> [sqle] don't panic reading history table

- go/libraries/doltcore/merge/fulltext_rebuild.go
- go/libraries/doltcore/merge/fulltext_table.go
- go/libraries/doltcore/merge/merge.go
- go/libraries/doltcore/schema/index_coll.go
- integration-tests/bats/fulltext.bats
This changes the Full-Text rebuild process to only trigger on tables that were changed in both roots (ours and theirs), rather than rebuilding every time a merge is performed regardless of what was actually changed. The rules here are fairly permissive, in that if a parent table _or any of the indexed child tables_ are changed in both, then we rebuild **all** Full-Text indexes for that table. I chose this behavior out of caution, as dual changes in a single child table is probably due to some kind of renaming, so it's safer to rebuild everything for that table.
> Optimize full-text to selectively rebuild

- go/cmd/dolt/commands/sqlserver/command_line_config.go
- go/cmd/dolt/commands/sqlserver/serverconfig.go
- go/cmd/dolt/commands/sqlserver/sqlserver.go
- go/cmd/dolt/commands/sqlserver/yaml_config.go
- go/cmd/dolt/dolt.go
This change:
* Decouples reading config from setting SQL globals
* Puts command line config in its own file
* Introduces new interfaces to allow alternate Config implementations. This is to support DoltgreSQL, which will have different config options than Dolt itself.
> [no-release-notes] Refactored config reading / initialization

- go/store/datas/pull/pull_chunk_fetcher.go
- go/store/datas/pull/pull_chunk_fetcher_test.go
- go/store/datas/pull/pull_chunk_tracker.go
- go/store/datas/pull/pull_chunk_tracker_test.go
- go/store/datas/pull/puller.go
We want to better pipeline I/O when pulling from a remote, and moving a streaming interface where storage can see more of the addresses that are needed at once will allow us to achieve it.
For now, we implement the streaming interface just by calling the existing batch get interface.
> go/store/datas/pull: pull_chunk_fetcher: Move chunk fetching to a streaming interface instead of batch.

- go/cmd/dolt/commands/merge.go
- integration-tests/bats/fetch.bats
- integration-tests/bats/helper/local-remote.bash
- integration-tests/bats/pull.bats
- integration-tests/bats/push.bats
This was reported by a user: https://github.com/dolthub/dolt/issues/7653
This was covered by a test, but it turns out that the pull, fetch, and push tests were all using SQL_ENGINE=remote-server incorrectly.
> Don't panic for conflicts in the `dolt pull` command

- go/cmd/dolt/commands/sqlserver/sqlserver.go
- go/cmd/dolt/commands/sqlserver/yaml_config.go
- go/cmd/dolt/commands/sqlserver/yaml_config_test.go
The [CLI docs for sql-server](https://docs.dolthub.com/cli-reference/cli#dolt-sql-server) doesn't include the `system_variables` field available in `config.yaml`.
> CLI Docs: Adding docs for `system_variables` field in config.yaml for sql-server command

- go/cmd/dolt/commands/credcmds/check.go
- go/cmd/dolt/commands/credcmds/import.go
- go/cmd/dolt/commands/send_metrics.go
- go/cmd/dolt/commands/sqlserver/server.go
- go/libraries/doltcore/dbfactory/grpc.go
- go/libraries/doltcore/remotestorage/chunk_store.go
- go/libraries/doltcore/sqle/cluster/controller.go
- go/libraries/doltcore/sqle/cluster/mysqldb_persister.go
- go/libraries/events/emitter.go
In the cluster commithook, we had a failure mode where we would leak a *grpc.ClientConn without closing it. It turns out, if an outbound request has made on a ClientConn, it will continue retrying the connection. And we would leak one on a fixed interval, resulting in ever-increasing CPU utilization.
> go/libraries/doltcore/dbfactory, misc: Ensure we close a *grpc.ClientConn when we are done with it.

- go/cmd/dolt/dolt.go
- go/libraries/doltcore/doltdb/doltdb.go
- go/libraries/doltcore/env/multi_repo_env.go
- go/store/nbs/table.go
- go/store/nbs/table_index.go
- go/store/nbs/table_index_test.go
- go/store/nbs/table_reader.go
Now that we are fairly certain that the dolt table format for compressed history files will have a new file signature, we want current versions of dolt to provide decent messages if one of those files is encountered.
Automated testing of this is tricky at the moment. I hand edited an existing table file to ensure that a sane message comes back.
Also, `dolt sql-server` doesn't currently print a message at all when a bad table file is encountered.
> Allow 'old' versions of Dolt to handle future table file versions

- go/libraries/doltcore/sqle/dsess/autoincrement_tracker.go
- go/libraries/doltcore/sqle/dsess/mutexmap/mutexmap.go
This PR refactors the AutoIncrementTracker to hold a separate mutex for each table instead of a single mutex for the entire database.
This relates to supporting the `innodb_autoinc_lock_mode` variable, described here: https://github.com/dolthub/dolt/issues/7634
Currently, the engine acquires the AutoIncrementTracker lock once per inserted row and holds it only while that row is being inserted. However, when `innodb_autoinc_lock_mode` is set to any value other than its default, the engine must instead hold the lock for the duration of the insert statement.
Unfortunately, there is a specific corner case that causes `innodb_autoinc_lock_mode` to interact poorly with a single global lock: if a table has a trigger, and that trigger attempts to insert into a different table, then a second …
> Add per-table locking for AutoIncrementTracker

- go/store/datas/commit.go
- go/store/nbs/frag/main.go
- go/store/nbs/util.go
Testing if CI works with branch in repo. Original: https://github.com/dolthub/dolt/pull/7706
> [store] use struct{} as a value in a hashset

- go/libraries/doltcore/sqle/dolt_patch_table_function.go
- go/libraries/doltcore/sqle/enginetest/dolt_queries.go
- go/libraries/doltcore/sqle/enginetest/dolt_queries_diff.go
- go/libraries/doltcore/sqle/enginetest/dolt_queries_merge.go
- go/libraries/doltcore/sqle/tables.go
- integration-tests/MySQLDockerfile
- integration-tests/bats/column_tags.bats
Currently, when a column's type changes to a new type family (e.g. changing from `varchar` to `int`), we assign a new column tag. This prevents us from easily identifying the column across type changes. For example:
* If column X is renamed and then its type is later changed, we can't track it across the rename or type change anymore. This usage pattern removes the value that column tags were intended to provide. 
* If column X changes its type, we can't easily differentiate between column X being dropped and a new column X being added. Heuristically, we can look at all the data in the table if it's all exactly identical, then we know it's a rename, but this is a somewhat hacky heuristic that can become ambiguous in more nuanced cases. This currently causes us to generate incorrect SQL …
> Don't generate new tags for column type changes

- go/store/nbs/journal_chunk_source.go
- go/store/nbs/journal_writer.go
Add read planning for journal getMany so instead of doing randIO we get seqIO. SeqIO has a large effect for disk storage systems. Also parallelize getMany calls. The biggest change here is the semantics around how reading locks the journal file. Reads hold the journal lock for longer, which could lower write throughput in some cases. If we see evidence of this, we can do more work to limit the amount of time batch reads can interruptibly holding the journal lock.
> [nbs] getMany read planning and parallelize

- go/libraries/doltcore/merge/schema_integration_test.go
- go/libraries/doltcore/sqle/dtables/conflicts_tables_prolly.go
- go/libraries/doltcore/sqle/enginetest/dolt_queries_merge.go
- go/libraries/doltcore/sqle/enginetest/dolt_queries_schema_merge.go
- go/libraries/doltcore/sqle/writer/prolly_index_writer.go
This is an old check from before we had schema merge. I'm convinced that it was never actually needed. This PR has the necessary changes in order to remove it.
It's important that the user is able to resolve data conflicts even if the table schema has changed, because otherwise it is not possible to manually resolve data conflicts after a schema merge.
This PR also contains some additional tests, some of which are currently disabled because of https://github.com/dolthub/dolt/issues/7767 and https://github.com/dolthub/dolt/issues/7762
> Allow updating conflict table even if the underlying table schema changed.

- go/cmd/dolt/commands/diff.go
- go/cmd/dolt/commands/diff_output.go
- integration-tests/bats/diff.bats
This PR adds support for `--name-only` option for `dolt diff`, which just prints the tables that have changed between the two commits. This mirrors `git diff --name-only`.
fixes: https://github.com/dolthub/dolt/issues/7797
> adding `--name-only` option for `dolt diff`

- go/cmd/dolt/commands/engine/sqlengine.go
- go/libraries/doltcore/sqle/binlogreplication/binlog_type_serialization.go
- go/libraries/doltcore/sqle/cluster/controller.go
- go/libraries/doltcore/sqle/cluster/initdbhook.go
- go/libraries/doltcore/sqle/database_provider.go
- go/libraries/doltcore/sqle/enginetest/dolt_engine_test.go
- go/libraries/doltcore/sqle/statspro/configure.go
- go/libraries/doltcore/sqle/statspro/initdbhook.go
The Dolt database provider currently has a single init hook and a single drop hook. We have a few hooks, and in order to support multiple hooks, we chain them together. Binlog replication will also need to register a similar init and drop hook to capture database create/drop actions, so to prepare for that, this PR turns the single init hook and single drop hook into a slice of init hooks and a slice of drop hooks.
> Changing database init/drop hooks to be a slice of hooks

- go/cmd/dolt/commands/diff.go
- go/cmd/dolt/commands/diff_output.go
- go/cmd/dolt/doltversion/version.go
- go/libraries/doltcore/diff/diff.go
- go/libraries/doltcore/table/typed/json/json_diff_writer.go
- integration-tests/bats/json-diff.bats
- integration-tests/bats/sql-diff.bats
This PR tidys up the code for printing diffs, specifically for JSON result format, and prints `--stat` correctly for JSON result format.
Additionally, we throw an error for SQL result format instead of just returning incorrect output. It might be worth implenting now, but I can just make an issue for it.
fixes: https://github.com/dolthub/dolt/issues/7800
> fix output for `dolt diff --stat -r json`

- go/libraries/doltcore/sqle/database_provider.go
- go/libraries/doltcore/sqle/read_replica_database.go
- go/libraries/doltcore/sqle/replication.go
- integration-tests/bats/replication-multidb.bats
Dolt SQL servers using remote-based replication will pull new databases if the [@@dolt_replication_remote_url_template system variable](https://docs.dolthub.com/sql-reference/version-control/dolt-sysvars#dolt_replication_remote_url_template) is configured, but those new databases weren't getting configured to continue pulling updates from the remote.
This change registers the newly cloned databases as `ReadReplicaDatabase` instances, so that they will poll their remote and pull new commits. It also adds some additional logging to help debug issues with remote-based replication.
> Bug fix: Apply replication settings for newly cloned databases

- go/store/nbs/journal_index_record.go
- go/store/nbs/journal_index_record_test.go
- go/store/nbs/journal_writer.go
On >10GB datasets, offsets overflow uint32. Bug from previous PR https://github.com/dolthub/dolt/pull/7780
> Journal index offset 8bytes

- go/libraries/doltcore/merge/merge_prolly_rows.go
- go/libraries/doltcore/merge/merge_schema.go
- go/libraries/doltcore/merge/schema_merge_test.go
- go/libraries/doltcore/sqle/enginetest/dolt_queries_schema_merge.go
- go/store/prolly/tree/node.go
Fixes https://github.com/dolthub/dolt/issues/7762
In certain cases, performing a schema merge when the merged schema had fewer columns than the base schema would cause a panic.
We actually had a test for this, but the test was disabled because a limitation in how the test harness generated column tags was causing incorrect detection of merge conflicts.
To re-enable these tests, this PR slightly relaxes the logic for merge conflicts wrt column tags. This is safe to do because column tags shouldn't influence the result of merges outside of helping to identify renamed columns, so long as the merge behaves the same in both directions.
> Prevent panic when dropping columns in schema merge

- go/libraries/doltcore/doltdb/root_val.go
- go/libraries/doltcore/merge/merge.go
This just adds a function to the `RootValue` for special merge logic, which is used by Doltgres.
> Added additional function to RootValue

- go/cmd/dolt/commands/sqlserver/server.go
- go/cmd/dolt/commands/sqlserver/sqlserver.go
- integration-tests/bats/sql-server.bats
The local config store (`.dolt/config.json`) can store persisted global variable values, but when `--data-dir` is used when starting a `sql-server`, the local configuration doesn't get loaded properly.
> Bug fix: `sql-server` should initialize persisted global vars

- go/cmd/dolt/dolt.go
- integration-tests/bats/global-args.bats
When using the `--data-dir` flag to work on a Dolt directory outside of the current working directory, the local configuration in the Dolt directory wasn't getting correctly loaded. This change evaluates the `--data-dir` parameter earlier, so that the first time we load the Dolt environment, we can pass the data directory and get the local configuration loaded correctly.
> Bug fix: load local config when using `--data-dir`

- go/Godeps/LICENSES
- go/utils/3pdeps/MIMALLOC_LICENSE
- go/utils/3pdeps/main.go
- go/utils/publishrelease/buildpgobinaries.sh
The new toolchain uses MUSL + mimalloc.
Include the mimalloc license in our released LICENSES notice.
> go/utils/publishrelease: Bump MUSL toolchains used for cutting releases.

- go/libraries/doltcore/sqle/dprocedures/dolt_pull.go
- integration-tests/bats/sql-pull.bats
Customer-reported bug. Two `dolt_pull()` operations on two branches in the same session when local branches are already up to date, with `@@autocommit` off, leave the session unable to commit because two branch heads are considered dirty. See new bats test for details on reproducing.
The issue is that `DoltSession.SetWorkingSet()` marks that branch head dirty until the transaction is committed.  Most merge code paths used by pull involve performing a `dolt_commit`(), which has the side effect of zeroing out the current transaction, meaning the next statement would get a new transaction and fresh working sets loaded from disk, avoiding the dirty state problem. Only the code path where the branch head is already up to date is affected by this bug. All the merge library code that actually …
> Bug fix: no-op `dolt_pull()` was leaving working set dirty

- go/go.mod
- go/libraries/doltcore/sqle/binlogreplication/binlog_replica_controller.go
- go/libraries/doltcore/sqle/binlogreplication/binlog_replication_reconnect_test.go
- go/libraries/doltcore/sqle/binlogreplication/binlog_replication_restart_test.go
- go/libraries/doltcore/sqle/binlogreplication/binlog_replication_test.go
- go/libraries/doltcore/sqle/dolt_patch_table_function.go
- go/libraries/doltcore/sqle/dsess/session.go
- go/store/val/tuple_descriptor.go
- integration-tests/go-sql-server-driver/go.mod
As part of the work for binlog source support (on [fulghum/binlog_prototype branch](https://github.com/dolthub/dolt/tree/fulghum/binlog_prototype)), these are various smaller changes to tidy up docs, packaging, small bug fixes, and add new test utils that I've pulled out into this PR to review separately.
Notable changes:
- Adds the third version component to the go version in our `go.mod`. [Two component versions indicate a development version, not a release version and cause an error about not being able to download a toolchain.](https://github.com/golang/go/issues/62278#issuecomment-1693538776)
- Allows Dolt binlog replicas to accept the `SOURCE_AUTO_POSITION` config parameter, and errors if a user attempts to disable GTID auto positioning. 
- Adds several new test util functions …
> Various test utils and small fixes

- .github/workflows/doltgres-dependency.yml
This adds a new workflow that runs a subset of the tests in [DoltgreSQL](https://github.com/dolthub/doltgresql) to check for any major integration errors. The workflow does not fail if errors are encountered. Instead, it creates a comment stating that failures were found. If no failures were found, then no comment is made.
> Added workflow for checking DoltgreSQL

- .github/workflows/ci-bats-macos.yaml
The nightly MacOS BATS tests have been failing due to the Apache Parquet archive path changing. 
We applied a similar fix for the Lambda BATS runner. This should fix the MacOS runner.
> [no-release-notes] Fixing Apache Parquet archive file path

- .github/scripts/performance-benchmarking/get-mysql-dolt-job-json.sh
Also report the tps multuple, rather than the p95 multiple, even though they track.
> [no-release-notes] label p95 latency column correctly

- go/libraries/doltcore/sqle/dsess/session.go
Adds a new session variable that is used from within Doltgres. Currently, Doltgres uses a map as there were test failures due to potential race conditions with the inner `context`, so this replaces its usage with a session object instead.
> Added new session variable

- .github/scripts/performance-benchmarking/get-mysql-dolt-job-json.sh
I think we depend on the `tpcc_tps_multiplier` name for updating docs.
> [no-release-notes] switch tps_multiplier name back

- go/libraries/doltcore/env/actions/clone.go
- go/libraries/doltcore/env/actions/remotes.go
- go/libraries/doltcore/env/remotes.go
- go/libraries/doltcore/sqle/dprocedures/dolt_fetch.go
- go/libraries/doltcore/sqle/dprocedures/dolt_pull.go
- integration-tests/bats/fetch.bats
Git fetch returns without error when you fetch the default refspec. When you fetch a specific ref you get an error. Dolt now matches this behavior.
Fixes: https://github.com/dolthub/dolt/issues/7928
> dolt fetch default spec from empty repo should return silently

- go/cmd/dolt/commands/filter-branch.go
- go/cmd/dolt/commands/utils.go
- go/libraries/doltcore/doltdb/doltdb.go
- go/libraries/doltcore/rebase/filter_branch.go
- integration-tests/bats/filter-branch.bats
This PR adds support for a `--apply-to-uncommitted` option to `dolt filter-branch`, which applies the `filter-branch` changes to the working and staged roots. 
fixes https://github.com/dolthub/dolt/issues/7902
> apply `filter-branch` changes to working/staged changes

- go/cmd/dolt/cli/cli_context.go
- go/cmd/dolt/commands/add.go
- go/cmd/dolt/commands/branch.go
- go/cmd/dolt/commands/checkout.go
- go/cmd/dolt/commands/commit.go
- go/cmd/dolt/commands/diff.go
- go/cmd/dolt/commands/log.go
- go/cmd/dolt/commands/merge.go
- go/cmd/dolt/commands/reset.go
- go/cmd/dolt/commands/sql.go
- go/cmd/dolt/commands/sql_slash.go
- go/cmd/dolt/commands/status.go
- go/cmd/dolt/commands/utils.go
- go/store/util/outputpager/page_output.go
- integration-tests/bats/sql-shell-slash-cmds.expect
- integration-tests/bats/sql-shell.bats
Add the ability to run _some_ dolt commands directly from the dolt sql shell.
Fixes: https://github.com/dolthub/dolt/issues/6874
> dolt sql slash cmds

- go/libraries/doltcore/remotesrv/grpc.go
- go/libraries/doltcore/remotesrv/grpc_test.go
> go/libraries/doltcore/remotesrv: grpc.go: Respect X-Forwarded-Proto when generating HTTP download links in the gRPC server.

- integration-tests/bats/garbage_collection.bats
- integration-tests/bats/remotes-push-pull.bats
- integration-tests/bats/remotes.bats
- integration-tests/bats/remotesrv.bats
- integration-tests/bats/shallow-clone.bats
- integration-tests/bats/system-tables.bats
Attempts to fix some observed flakiness in bats tests.
> integration-tests/bats: Add some waits on the remotesrv_pid exit for bats tests which spawn a background remotesrv.

- go/libraries/doltcore/env/actions/checkout.go
- go/libraries/doltcore/sqle/dprocedures/dolt_pull.go
- integration-tests/bats/pull.bats
This loosens the restrictions for pulling from remotes: instead of requiring that there are no working changes, we allow working changes but only to ignored tables.
If there are conflicting changes to ignored tables (which is rare, since ignored tables shouldn't be pushed to remotes in the first place), this will still abort the pull later when it's computing the new root hash.
This is, IMO, better than what git does. Git will just overwrite the ignored files without warning.
> Allow pulling from a remote if the only changes are to ignored tables.

- go/libraries/doltcore/sqle/enginetest/dolt_engine_test.go
- go/libraries/doltcore/sqle/enginetest/dolt_queries.go
- go/libraries/doltcore/sqle/temp_table.go
This PR fixes this particular collision and makes collisions with other temporary tables more unlikely, probably, by using the deterministic random number generator used for generating tags for normal persisting tables.
fixes https://github.com/dolthub/dolt/issues/7995
> Generate `TEMPORARY TABLE` tags the same as normal `TABLE`s

- go/store/nbs/archive_build.go
- go/store/nbs/archive_chunk_source.go
- go/store/nbs/archive_reader.go
- go/store/nbs/archive_test.go
- integration-tests/bats/archive.bats
Two primary issues addressed in the `dolt admin archive` command:
1) Add caching to dictionaries. This improved performance significantly.
2) Fix multiple bugs related to having multiple table files. That was a gap in testing, so added a bats test for the command.
> Archive DDict cache and multi-file bug fixes

- go/libraries/doltcore/sqle/database.go
- go/libraries/doltcore/sqle/database_provider.go
- go/libraries/doltcore/sqle/tables.go
This makes it such that `pg_catalog` is created by default when Doltgres is using Dolt. In addition, adds a new function to hook into schema functionality.
> Create pg_catalog by default for Doltgres

- go/libraries/doltcore/sqle/statspro/update.go
- go/libraries/doltcore/sqle/statspro/update_test.go
- integration-tests/bats/stats.bats
Previous bug was only saving last MCV. Fix and add better testing.
> [no-release-notes] follow up fixes to mcv calculation

- go/performance/utils/benchmark_runner/sysbench.go
- go/performance/utils/benchmark_runner/tpcc.go
It looks like sysbench and tpcc are not using stats since the recent change for doltgres. If the server name is a full specified path, I think this version will permit dolt but disable doltgres/mysql stats.
> [no-release-notes] need stats to run on dolt servers

- go/go.mod
- go/go.sum
- go/libraries/doltcore/sqle/binlogreplication/binlog_primary_controller.go
Adds a simple no-op implementation for `DoltBinlogPrimaryController.ListBinaryLogs` to keep it in sync with API changes in GMS.
Depends on https://github.com/dolthub/go-mysql-server/pull/2567
> Add initial, no-op implementation for `ListBinaryLogs` API changes

- go/libraries/doltcore/remotestorage/chunk_fetcher.go
We observe dolthubapi can crash with the following nil pointer error:
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x48 pc=0x29e14d1]
goroutine 399548427 [running]:
github.com/dolthub/dolt/go/libraries/doltcore/remotestorage.fetcherRPCDownloadLocsThread.func3()
external/com_github_dolthub_dolt_go/libraries/doltcore/remotestorage/chunk_fetcher.go:266 +0xf1
golang.org/x/sync/errgroup.(*Group).Go.func1()
external/org_golang_x_sync/errgroup/errgroup.go:78 +0x56
created by golang.org/x/sync/errgroup.(*Group).Go in goroutine 399548420
external/org_golang_x_sync/errgroup/errgroup.go:75 +0x96
```
This pr aims to prevent this.
> /go/libraries/doltcore/remotestorage/chunk_fetcher.go: fix nil pointer

- go/libraries/doltcore/sqle/database.go
- go/libraries/doltcore/sqle/tables.go
In Doltgres, whenever we would create an index, we would use the empty schema as the destination (the default value for the schema name). This meant that the updated table with an index was saved into the empty schema, which is incorrect since Doltgres always has a schema. This adds the schema to index creation, along with several other locations that it should be in.
> Added schema to index creation

- go/store/prolly/tuple_map.go
- go/store/val/extended_comparator.go
* Companion PR: https://github.com/dolthub/doltgresql/pull/452
This PR fixes two issues with creating secondary indexes for Doltgres types. The first deals with handlers, as we were not adding a `nil` handler for the additional hash type, which would cause a panic as the counts were not equal (all non-Extended types should have a matching nil handler).
The second issue was due to the reuse of an `ExtendedTupleComparator`. When creating a new `ExtendedTupleComparator`, we pass in the previous `TupleTypeHandler` to handle all non-Extended types. If the previous `TupleTypeHandler` was `ExtendedTupleComparator` and the new one was also `ExtendedTupleComparator`, then we could end up with a misinterpretation of data that could lead to incorrect results, as the handler assumed a different type …
> Fixed keyless secondary indexing for Doltgres

- docker/docker-entrypoint.sh
- docker/serverDockerfile
This PR fixes https://github.com/dolthub/dolt/issues/8079. Now when running `dolthub/dolt-sql-server` if the args `dolt sql-server` are passed to the image, it will error. This will also prevent accidentally starting two Dolt servers in the container.
> /docker/{docker-entrypoint.sh,serverDockerfile}: change image to pass all args to dolt sql-server command

- go/store/nbs/archive.go
- go/store/nbs/archive_build.go
- go/store/nbs/archive_reader.go
- go/store/nbs/archive_test.go
- go/store/nbs/archive_writer.go
The initial impl of archive indexes over optimized for space. This resulted in being 10x slower to load the index of archives than noms table files. To address this:
- Dropped the end to end compression of the index
- Dropped the use of var ints for offset deltas and chunk refs
- Altered the use of byte span offsets, and instead used a end-offset approach which requires no delta processing on load.
- Used only slices of primitive types in the index memory. Constant time read path with a little more complexity, but allows us to read directly off disk into memory.
Testing indicates that on a 41 Gb archive file, this returned load performance to match classic table files, and the size of the index increased by about 350Mb (total ~ 1Gb)
> Archive index rework to make loading faster

- go/libraries/doltcore/sqle/binlogreplication/binlog_primary_streamer.go
- go/libraries/doltcore/sqle/binlogreplication/binlog_primary_test.go
Ensure heartbeat events sent from a Dolt primary to a MySQL replica have the latest nextLogPosition populated, otherwise the MySQL replica will close the binlog event stream.
> Bug fix: Use correct log position in Dolt to MySQL replication heartbeats

- integration-tests/bats/stats.bats
This BATS test doesn't seem to run well in Lambda BATS. It failed for me four times in a row today, and I saw it failing a bunch last week, too. Disabling it in Lambda BATS.
> [no-release-notes] Disable "stats: boostrap abort over 1mm rows" BATS test in Lambda

- go/libraries/doltcore/sqle/database.go
- go/libraries/doltcore/sqle/schema_table.go
https://github.com/dolthub/doltgresql/pull/454 depends on this PR.
> define schema for dolt_schemas table

- go/libraries/doltcore/sqle/binlogreplication/binlog_primary_streamer.go
- go/libraries/doltcore/sqle/binlogreplication/binlog_primary_test.go
- go/libraries/doltcore/sqle/binlogreplication/binlog_replication_test.go
Heartbeat binlog events must have a correct `NextLogPosition` field that matches up with the previous events that have been sent in the stream. If not, the replica will shutdown the binlog stream. https://github.com/dolthub/dolt/pull/8087 fixed this issue, but didn't account for when a heartbeat event is sent after the initial Format Description event, but before any user initiated requests. The way to trigger this is to `start replica;` on the replica, then don't run any commands on the primary and let the first heartbeat go out after the binlog stream has been up for 30s.
> Bug fix: binlog heartbeat `nextLogPosition` field

- go/store/prolly/tree/json_chunker.go
- go/store/prolly/tree/json_cursor.go
- go/store/prolly/tree/json_indexed_document.go
- go/store/prolly/tree/json_indexed_document_test.go
- go/store/prolly/tree/json_location.go
This PR includes a new implementation of the `JSON_REMOVE` function that leverages the new indexed JSON storage format.
For JSON documents that span multiple chunks, only the affected chunks need to be loaded and modified, allowing operations to scale with the size of the removed value instead of the size of the entire document.
> Optimize JSON_REMOVE on `IndexedJsonDocument`

- go/store/prolly/tree/json_chunker.go
- go/store/prolly/tree/json_indexed_document.go
- go/store/prolly/tree/json_indexed_document_test.go
This PR includes a new implementation of the JSON_SET and JSON_REPLACE functions that leverage the new indexed JSON storage format.
For JSON documents that span multiple chunks, only the affected chunks need to be loaded and modified, allowing operations to scale with the size of the removed value instead of the size of the entire document.
> Optimize JSON_SET and JSON_REPLACE on `IndexedJsonDocument`

- go/go.mod
- go/libraries/doltcore/doltdb/root_val.go
- go/libraries/doltcore/sqle/database.go
- go/libraries/doltcore/sqle/dsess/session_cache.go
RootValue caches a hash of its table list, which is invalidated when we update the table address list. The hash is used to cache a map of table names in the root value and expedites table retrieval during `planbuilder`. The cache could be used elsewhere for performance in the future.
https://github.com/dolthub/doltgresql/pull/503
> cache table list

- go/store/prolly/tuple_map.go
There was an issue merging https://github.com/dolthub/dolt/pull/8025 ontop of a revert. Enable the key iteration optimization.
> enable key range iter

- go/store/nbs/archive_chunk_source.go
- integration-tests/bats/archive.bats
Error in hasMany effectively prevented writes after moving database to archives.
> Continue to support writes when archives are in play

- go/libraries/doltcore/sqle/database.go
- go/libraries/doltcore/sqle/dtables/commit_diff_table.go
- go/libraries/doltcore/sqle/enginetest/dolt_queries_diff.go
- go/libraries/doltcore/sqle/history_table.go
- go/libraries/doltcore/sqle/index/dolt_index.go
This PR adds support for `STAGED` as a commit_hash when filtering dolt diff system tables.
fixes for https://github.com/dolthub/dolt/issues/7978
> support `STAGED` as commit hash

- go/store/prolly/tree/node.go
- go/store/types/serial_message.go
- integration-tests/bats/show.bats
This PR does a couple things:
1. `dolt show #address` can now display the internals of a ProllyTreeMap message (typically used for storing indexes). Previously, only `splunk`/`noms show` could do this.
2. Both `dolt show` and `splunk` can now display the contents of a Blob message.
3. If a ProllyTreeMap leaf node contains a value that is itself an address (example: the value of text and json columns), that value is shown as a human readable address, which can be fed back into `dolt show` or `splunk` to explore the whole tree.
> Add support for visualizing prolly tree and blob messages in `dolt show`

- go/cmd/dolt/commands/admin/archive.go
- go/store/nbs/archive.go
- go/store/nbs/archive_build.go
- go/store/nbs/archive_test.go
- go/store/nbs/archive_writer.go
- integration-tests/bats/shallow-clone.bats
This change is long in coming. Several findings from building a large user database are incorporated here. Specifically:
* No longer storing all chunks in memory
* Cancellable process with `^C`
* Progress reporting for major stages of the build
* No chunk grouping by default, `--group-chunks` to enable. Pathological cgo dictionary building problem needs to be fixed before we enable by default.
* Writing a useful metadata json block with dolt version and origin table file ID.
> Build Archives more robustly

- go/cmd/dolt/commands/sql.go
- go/libraries/doltcore/doltdb/doltdb.go
- go/libraries/doltcore/sqle/database_provider.go
- go/libraries/doltcore/sqle/enginetest/dolt_queries.go
This PR makes it so tags are case-insensitive.
Additionally, fixes a display error in the sql shell.
fixes https://github.com/dolthub/dolt/issues/8147
> make tags case insensitive

- go/libraries/doltcore/sqle/binlogreplication/binlog_replica_applier.go
- go/libraries/doltcore/sqle/binlogreplication/binlog_replication_alltypes_test.go
- go/libraries/doltcore/sqle/binlogreplication/binlog_replication_filters_test.go
- go/libraries/doltcore/sqle/binlogreplication/binlog_replication_multidb_test.go
- go/libraries/doltcore/sqle/binlogreplication/binlog_replication_reconnect_test.go
- go/libraries/doltcore/sqle/binlogreplication/binlog_replication_restart_test.go
- go/libraries/doltcore/sqle/binlogreplication/binlog_replication_test.go
This fixes binlog replicas loading `@@server_id` values persisted in config.json so that they are properly converted from strings to the right type.
Also added extra connection error logging
> Bug fix: loading persisted `@@server_id` from config.json

- go/libraries/doltcore/env/actions/remotes.go
- go/store/nbs/generational_chunk_store.go
- integration-tests/bats/shallow-clone.bats
Push from a shallow clone is possible, but we should message better when it's not possible. In order to do this we need to error better from the Generational Chunk Store with a custom error.
Fixes: https://github.com/dolthub/dolt/issues/8156
> Better error message when attempting to push from a shallow clone

- go/cmd/dolt/commands/engine/sqlengine.go
- go/go.mod
- go/go.sum
- go/libraries/doltcore/sqle/enginetest/dolt_harness.go
- go/libraries/doltcore/sqle/index/index_reader.go
- go/libraries/doltcore/sqle/index/secondary_iter.go
- go/libraries/doltcore/sqle/kvexec/builder.go
- go/libraries/doltcore/sqle/kvexec/lookup_join.go
- go/libraries/doltcore/sqle/kvexec/lookup_join_test.go
I missed a test case in `nonCovLaxSecondaryLookupGen`. I tried to add more tests surrounding the specific panic query here: https://github.com/dolthub/go-mysql-server/pull/2607.
Also rename the `rowexec` to `kvexec`.
> [kvexec] Fix panic in non-covering strict lookup

- go/cmd/dolt/commands/admin/archive.go
- go/cmd/dolt/commands/backup.go
- go/libraries/doltcore/env/environment.go
- go/libraries/doltcore/env/multi_repo_env.go
- go/libraries/doltcore/remotesrv/server.go
- go/libraries/doltcore/sqle/remotesrv.go
- go/store/nbs/archive_build.go
- go/store/nbs/archive_chunk_source.go
- go/store/nbs/archive_reader.go
- go/store/nbs/metadata.go
- integration-tests/bats/archive.bats
- integration-tests/bats/helper/local-remote.bash
Add features to ensure that archive files are not used when running a remotesrv or when pushing backups.
Also provide the `--revert` flag which can return a database back to the classic format.
> archive guard rails

- go/store/types/serial_message.go
- integration-tests/bats/show.bats
Previously `dolt show` would only show some of the data for schemas, which was potentially confusing because two schemas with different hashes could have the same output.
> [no-release-notes] `dolt show` and splunk should show all the data in a TableSchemaFile

- go/cmd/dolt/commands/engine/sqlengine.go
- go/cmd/dolt/commands/sqlserver/server.go
- go/libraries/doltcore/sqle/binlogreplication/binlog_metadata_persistence.go
- go/libraries/doltcore/sqle/binlogreplication/binlog_position_store.go
- go/libraries/doltcore/sqle/binlogreplication/binlog_replica_applier.go
- go/libraries/doltcore/sqle/binlogreplication/binlog_replica_controller.go
- go/libraries/doltcore/sqle/binlogreplication/binlog_replication_test.go
Once replication has been started with `START REPLICA;`, replication now automatically restarts when the server is restarted. If replication is stopped with `STOP REPLICA;`, it is not restarted automatically on server restart. This matches MySQL's behavior. 
This PR also includes a few other small improvements to binlog replication:
* allows 'show replica status' before replication is started
* moves logging of binlog messages from `DEBUG` to `TRACE` level
* removes several references to `GetRunningServer()` global function
Resolves https://github.com/dolthub/dolt/issues/8168
> Feature: Auto-start binlog replication on server restart

- go/go.mod
- go/go.sum
Ran into issues when I ran: 
```
go install github.com/dolthub/dolt/go/cmd/dolt@main
/go/pkg/mod/github.com/dolthub/dolt/go@v0.40.5-0.20240802204753-c290ade4ea30/cmd/dolt/commands/cherry-pick.go:79:19: undefined: eventsapi.ClientEventType_CHERRY_PICK
/go/pkg/mod/github.com/dolthub/dolt/go@v0.40.5-0.20240802204753-c290ade4ea30/cmd/dolt/commands/dump.go:112:19: undefined: eventsapi.ClientEventType_DUMP
/go/pkg/mod/github.com/dolthub/dolt/go@v0.40.5-0.20240802204753-c290ade4ea30/cmd/dolt/commands/filter-branch.go:95:19: undefined: eventsapi.ClientEventType_FILTER_BRANCH
/go/pkg/mod/github.com/dolthub/dolt/go@v0.40.5-0.20240802204753-c290ade4ea30/cmd/dolt/commands/gc.go:76:19: undefined: eventsapi.ClientEventType_GARBAGE_COLLECTION
/go/pkg/mod/github.com/dolthub/dolt/go@v0.40.5-0.2024080220475 …
```
> chore: update  lib:eventsapi 2022-> 2024

- go/libraries/doltcore/env/actions/clone.go
Fixes a dropped error return in the clone implementation.
> go/libraries/doltcore/env/actions: Improve error message when a clone fails mid-download.

- go/libraries/doltcore/sqle/binlogreplication/binlog_primary_streamer.go
- go/libraries/doltcore/sqle/binlogreplication/binlog_producer.go
- go/libraries/doltcore/sqle/binlogreplication/binlog_type_serialization.go
- go/libraries/doltcore/sqle/binlogreplication/binlog_type_serialization_test.go
Small bug fixes for binlog replication while testing with the `python-mysql-replication` library:
* Adjusting `DEBUG` logging to be less verbose 
* Using MySQL's older date serialization format for compatibility 
* Adding a `nil` check for `gtidPosition`
> Bug fix: binlog replication: logging levels, use MySQL's older date serialization format

- go/libraries/doltcore/sqle/database.go
- integration-tests/bats/events.bats
Fixing an event scheduler bug that caused events to be disabled and not run when the sql-server is restarted.
Fixes https://github.com/dolthub/dolt/issues/8167
> Bug fix: events should remain enabled after sql-server restarts 

- go/cmd/dolt/commands/cherry-pick.go
- go/cmd/dolt/commands/log.go
- go/cmd/dolt/commands/show.go
- go/cmd/dolt/commands/utils.go
- integration-tests/bats/show.bats
- integration-tests/bats/sql-local-remote.bats
`dolt show` had an issue where it would not correctly display the SerialMessage for commits if provided with a hash. This came about as part of a refactor to make `dolt show` not depend on the `env.DoltEnv` object, when only exists on locally running servers, and not when connected to a remote server. Unfortunately, it looks like that refactor didn't actually remove the dependency either, as `DoltEnv` was still used in every possible invocation of `dolt show`
To get it working, I essentially rewrote the implementation of `dolt show` in such a way that it now actually only uses `DoltEnv` when it can't get the necessary information from a running server: Basically, if we need to display SerialMessages or resolve branch names, we still rely on a locally running server. This can likely be …
> Rewrite the `dolt show` implementation.

- go/store/cmd/noms/noms_show.go
This fixes an index out of bounds panic when trying to display AddressMap non-leaf nodes in `noms show`.
I didn't add a regression test, because it turns out that all `noms show` tests only work against the old deprecated format, so adding more tests to the test suite wouldn't actually do anything. It's also mostly unused: we basically only use it as part `splunk.pl` to visualize chunks for debugging.
Instead of fixing the test suite, it would be a better use of my time to fully deprecate `noms show` and switch `splunk.pl` to use `dolt show` instead. Especially now that https://github.com/dolthub/dolt/pull/8143 added support for visualizing prolly tree chunks in `dolt show`, bringing it to feature parity with `noms show`.
> Fix displaying AddressMap non-leaf nodes in `noms show`

- go/cmd/dolt/cli/cli_context.go
- go/cmd/dolt/cli/messages.go
- go/cmd/dolt/commands/checkout.go
- go/cmd/dolt/commands/merge.go
- go/cmd/dolt/commands/sql.go
- go/cmd/dolt/commands/sql_slash.go
- integration-tests/bats/sql-local-remote.bats
- integration-tests/bats/sql-shell-slash-cmds.expect
Until now there was an awkward behavior in `dolt sql` shell where the \checkout and \merge commands didn't really play nice when they could have. Specifically, if you used `dolt sql` and it was connected to a remote host, then running `\checkout` would give you an error telling you to stop the server. That is no longer the case. \checkout and \merge will work well in the `dolt sql` shell when connected to a remote host now.
Also added the \show command
And made the expect tests more correct and expanded.
> support \checkout, \merge, \show

- go/cmd/dolt/cli/arg_parser_helpers.go
- go/cmd/dolt/cli/flags.go
- go/cmd/dolt/commands/cherry-pick.go
- go/cmd/dolt/commands/rebase.go
- go/cmd/dolt/commands/utils.go
- go/gen/fb/serial/workingset.go
- go/libraries/doltcore/cherry_pick/cherry_pick.go
- go/libraries/doltcore/doltdb/workingset.go
- go/libraries/doltcore/sqle/dprocedures/dolt_cherry_pick.go
- go/libraries/doltcore/sqle/dprocedures/dolt_rebase.go
- go/libraries/doltcore/sqle/enginetest/dolt_queries_rebase.go
- go/serial/workingset.fbs
- go/store/datas/dataset.go
- go/store/datas/workingset.go
- integration-tests/bats/cherry-pick.bats
- integration-tests/bats/rebase.bats
- integration-tests/bats/sql-cherry-pick.bats
Adds support for the `--empty` option to `dolt_rebase()`. This option controls how commits that **become** empty are handled. For example, if a branch is rebased and all the changes in one commit on that branch have already been applied to the upstream branch, then when that commit is reapplied, it will end up being empty. The two initially supported values are `drop` and `keep`. (Git also supports a `stop` value, which lets the user manually intervene.)
Also adds support for the `--allow-empty` flag for `dolt_cherry_pick()`. This flag controls whether Dolt will cherry-pick empty commits (i.e. commits that start off as empty, not commits that become empty after they are applied). 
These behaviors are slightly confusing for two reasons: 1) Git distinguishes between a commit that starts off …
> Feature: support for --empty=[drop|keep] in dolt_rebase()

- go/libraries/doltcore/doltdb/system_table.go
- go/libraries/doltcore/sqle/database.go
- go/libraries/doltcore/sqle/dolt_diff_table_function.go
- go/libraries/doltcore/sqle/dolt_patch_table_function.go
- go/libraries/doltcore/sqle/dtables/column_diff_table.go
- go/libraries/doltcore/sqle/dtables/diff_iter.go
- go/libraries/doltcore/sqle/dtables/diff_table.go
- go/libraries/doltcore/sqle/dtables/workspace.go
- go/libraries/doltcore/sqle/enginetest/dolt_engine_test.go
- go/libraries/doltcore/sqle/enginetest/dolt_engine_tests.go
- go/libraries/doltcore/sqle/enginetest/dolt_queries.go
- go/libraries/doltcore/sqle/enginetest/dolt_queries_workspace.go
- integration-tests/bats/ls.bats
This is the read only addition of the `dolt_workspace_{table}` s. These dynamically generated tables are always relative to HEAD for the given session of the caller. There are no commits as a result, and the schema of the output looks like:
| ID (int) | STAGED (bool) | DIFF_TYPE (string) | to_A | to_B | ... | from_A | from_B | ... |
Currently there is no mechanism to update this table directly, but in the future that will make it possible to have fine grain modification of your workspace, similar to `git add --patch`
> Add dolt_workspace_* system tables

- go/utils/publishrelease/install.sh
1. Fixed error message mistakenly implying that dolt can be installed on 32-bit systems
2. Fixed color printing on bash (and zsh running in bash compatibility mode) installed on an OS with non-GNU coreutils (Alpine Linux, macOS)
3. Linted `install.sh` and fixed all the errors and warning that had obvious fixes. The only one left is `local error_code="$1"` in `fail` function that should be removed but may be reused for debugging purposes by manually editing the script
> Fixes for dolt installer bash-script

- go/libraries/doltcore/sqle/index/dolt_index.go
- go/libraries/doltcore/sqle/index/index_reader.go
- go/libraries/doltcore/sqle/kvexec/builder.go
- go/store/prolly/tuple_map.go
- go/store/prolly/tuple_range.go
This is the same as https://github.com/dolthub/dolt/pull/8242 with one change and new test in GMS https://github.com/dolthub/go-mysql-server/pull/2639. The change prevents string comparisons from skipping range.Matches, because the index range iterators can return false positives/prefix matches.
> Skip filter iter, with more test fixes

- go/libraries/doltcore/sqle/dprocedures/dolt_cherry_pick.go
- go/libraries/doltcore/sqle/dprocedures/dolt_conflicts_resolve.go
- go/libraries/doltcore/sqle/dprocedures/dolt_remote.go
- go/libraries/doltcore/sqle/dprocedures/dolt_tag.go
- integration-tests/mysql-client-tests/node/workbenchTests/databases.js
Most procedures that return integers return `int64`, but there are a few exceptions. The procedures that return `int` break in doltgres [here](https://github.com/dolthub/doltgresql/blob/main/server/functions/dolt_procedures.go#L144)
> More consistent return types for dolt procedures

- go/libraries/doltcore/merge/schema_merge_test.go
- go/libraries/doltcore/sqle/binlogreplication/binlog_replica_applier.go
- go/libraries/doltcore/sqle/database.go
- go/libraries/doltcore/sqle/dsess/session.go
- go/libraries/doltcore/sqle/dsess/table_writer.go
- go/libraries/doltcore/sqle/dtables/docs_table.go
- go/libraries/doltcore/sqle/dtables/ignore_table.go
- go/libraries/doltcore/sqle/dtables/workspace.go
- go/libraries/doltcore/sqle/enginetest/dolt_queries_workspace.go
- go/libraries/doltcore/sqle/tables.go
- go/libraries/doltcore/sqle/temp_table.go
- go/libraries/doltcore/sqle/writer/noms_write_session.go
- go/libraries/doltcore/sqle/writer/prolly_table_writer.go
- go/libraries/doltcore/sqle/writer/prolly_write_session.go
- go/libraries/doltcore/table/editor/pk_table_editor.go
This change adds the ability to update dolt_workspace_ tables. Updates can take two forms:
1)  The "staging" column of the table. may be toggled from it's current state. If setting from false to true, the working value will be written into the staged table. Setting from true to false will remove the row from staging, and leave the value in working as is.
2) You can delete any row which has a "staged" column of false. This will revert the workspace changes and return them to the original value.
> dolt_workspace_* update and delete support

- go/libraries/doltcore/sqle/binlogreplication/binlog_replica_applier.go
- go/libraries/doltcore/sqle/binlogreplication/binlog_replication_test.go
- go/libraries/doltcore/sqle/dsess/session.go
The binlog replication applier process is responsible for applying the replicated updates from a MySQL source to the Dolt replica. Previously, when committing SQL transactions after applying a change, the applier would attempt to commit on all known databases. This worked when the number of databases was small, but when the server is handling hundreds of databases, it adds noticeable and unnecessary delay. This change switches to use the dirty tracking data of the session to more efficiently commit to only the databases that have had changes applied. 
The old SQL transaction commit logic scaled exponentially, while the new logic scales linearly. 
| **Num Databases** | **Code Path** | **Replication Time (s)** |
|--------------------|---------------|-----------------|
| 100                | …
> Perf: Optimize SQL transaction commits in binlog replication applier

- go/cmd/dolt/commands/rebase.go
- go/gen/fb/serial/workingset.go
- go/libraries/doltcore/cherry_pick/cherry_pick.go
- go/libraries/doltcore/doltdb/workingset.go
- go/libraries/doltcore/rebase/rebase.go
- go/libraries/doltcore/sqle/dprocedures/dolt_rebase.go
- go/libraries/doltcore/sqle/dsess/session.go
- go/libraries/doltcore/sqle/enginetest/dolt_queries_rebase.go
- go/serial/workingset.fbs
- go/store/datas/dataset.go
- go/store/datas/workingset.go
- integration-tests/bats/rebase.bats
When data conflicts occur during an interactive rebase, customers can now use [Dolt's conflict resolution](https://docs.dolthub.com/concepts/dolt/git/conflicts) tools to resolve the conflicts and continue the rebase operation. Note that schema conflicts are not supported yet.
Example:
```sql
> select * from dolt_rebase;
+--------------+--------+----------------------------------+----------------------------+
| rebase_order | action | commit_hash                      | commit_message             |
+--------------+--------+----------------------------------+----------------------------+
| 1.00         | drop   | iumpo2t0hd6drcn11jo8osdack1jmafp | inserting row 1 on branch1 |
| 2.00         | pick   | us2uaji20dj77cnf1i2l698itr5392se | updating row 1 on branch1  | …
```
> Feature: Data conflict resolution during interactive rebase

- go/libraries/doltcore/sqle/statsnoms/database.go
- go/libraries/doltcore/sqle/statspro/analyze.go
- go/libraries/doltcore/sqle/statspro/auto_refresh.go
- go/libraries/doltcore/sqle/statspro/stats_provider.go
The stats provider holds a lock that was required to (1) update stats, and (2) access statistics.
The new behavior
- Reject duplicate update requests on the same database/branch/table. So an `analyze table <t>` will error if a conflicting job is active.
- Only lock the provider in critical sections. Update threads only grab the lock to read current statistics or write updates. So regular reads/writes will not hang waiting for the stats provider mutex longer than it takes to finish a critical section.
> [statspro] Avoid stopping the world during stats updates

- go/cmd/dolt/cli/flags.go
- go/cmd/dolt/commands/add.go
- go/cmd/dolt/commands/stashcmds/stash.go
- go/cmd/dolt/commands/utils.go
- go/libraries/doltcore/sqle/dtables/workspace.go
CLI update to enable the "--patch" option for dolt add.
This option is only supported in a CLI context (sql shell included) because the `dolt_add` stored procedure doesn't allow for a user interactive workflow.
Currently this change lacks tests. I'll work on that after I ship the blog post.
Fixes: https://github.com/dolthub/dolt/issues/2465
> dolt add --patch

- go/libraries/doltcore/sqle/enginetest/dolt_engine_test.go
- go/libraries/doltcore/sqle/statsnoms/database.go
- go/libraries/doltcore/sqle/statspro/analyze.go
- go/libraries/doltcore/sqle/statspro/dolt_stats.go
fixes: https://github.com/dolthub/dolt/issues/8339
The concurrency tests stopped working at some point when we were rearranging the default stats behavior. I caught a couple other issues after I got those tests running again.
> Fix more stats collection races

- go/libraries/doltcore/sqle/statspro/configure.go
- go/libraries/doltcore/sqle/statspro/initdbhook.go
- go/libraries/doltcore/sqle/statspro/stats_provider.go
- integration-tests/bats/stats.bats
Quick fix for at least one of the problems in https://github.com/dolthub/dolt/issues/8345.
The specific example fails because the restart function refreshes the stats database instance, but does not reload the stats contained within. So the contents in memory did not track the contents on disk. This was only noticeable when restart and read were called within the same shell context.
> [statspro] Restart drop db

- go/cmd/dolt/commands/diff.go
- go/libraries/doltcore/diff/diffsplitter.go
- go/libraries/utils/argparser/parser.go
- integration-tests/bats/diff.bats
This partially addresses an old bug described in the fixed issue. There are certainly more complete solutions, but this seems like the right amount of effort for something pretty edge casey.
Fixes: https://github.com/dolthub/dolt/issues/8133
> More flexible `diff` printing when schema changes type of column

- go/cmd/dolt/commands/schcmds/import.go
- go/libraries/doltcore/doltdb/root_val.go
- go/libraries/doltcore/mvdata/data_mover.go
- go/libraries/doltcore/mvdata/engine_table_reader.go
- go/libraries/doltcore/sqle/database.go
- go/libraries/doltcore/sqle/schema_override.go
- go/libraries/doltcore/sqle/sqlutil/convert.go
- go/libraries/doltcore/sqle/sqlutil/schema.go
- go/libraries/doltcore/sqle/tables.go
- go/libraries/doltcore/sqle/temp_table.go
Bug fix for schema name being lost when adding a unique index to a table through Doltgres.
Fixes: https://github.com/dolthub/doltgresql/issues/725
> Passing through schema name to fix index creation bug in Doltgres

- go/libraries/doltcore/remotestorage/internal/reliable/http.go
io.Copy into an io.PipeWriter will block until all the bytes have been delivered or the reader is closed. reliable/http StreamingResponse was constructed to only cancel the request context on Close(), not also clear the Reader. The Reader should also be closed to ensure all finalization can still happen if the Write to the PipeWriter is currently blocked when the context is canceled.
> go: doltcore/remotestorage: reliable: Fix leaked goroutines when the context is canceled while reading the HTTP response.

- go/libraries/doltcore/env/actions/branch.go
- go/libraries/doltcore/env/actions/clone.go
- go/libraries/doltcore/env/actions/workspace.go
- go/libraries/doltcore/sqle/dprocedures/dolt_checkout.go
- go/libraries/doltcore/sqle/enginetest/dolt_queries.go
- integration-tests/bats/commit_tags.bats
Changes: 
- Prevent cloning from a tag through `--branch` option
- Return detached head error for checking out branch through cli
Fixes: https://github.com/dolthub/dolt/issues/8377
> Improve Error Handling for Tags

- go/libraries/doltcore/sqle/enginetest/stats_queries.go
- go/libraries/doltcore/sqle/statsnoms/load.go
- go/libraries/doltcore/sqle/statsnoms/write.go
The PR from earlier in the week encoded stats bucket bound rows with prolly formatting. I neglected to encode MCVs in the same way, which are also rows and are subject to the same bugs.
> [statsnoms] MCV encoding needs to be delimiter safe

- go/libraries/doltcore/schema/schema_impl.go
Check for `StringType` support before casting, now that Doltgres extended types can support query types without implementing `StringType`.
> Check for `StringType` support before casting 

- go/cmd/dolt/cli/arg_parser_helpers.go
- go/cmd/dolt/cli/flags.go
- go/cmd/dolt/commands/gc.go
- go/libraries/doltcore/doltdb/doltdb.go
- go/libraries/doltcore/doltdb/gc_test.go
- go/libraries/doltcore/sqle/dprocedures/dolt_gc.go
- go/store/chunks/chunk_store.go
- go/store/chunks/memory_store.go
- go/store/chunks/test_utils.go
- go/store/datas/database.go
- go/store/datas/database_common.go
- go/store/nbs/archive_chunk_source.go
- go/store/nbs/generational_chunk_store.go
- go/store/nbs/nbs_metrics_wrapper.go
- go/store/nbs/store.go
- go/store/nbs/store_test.go
- go/store/nbs/table_set.go
- go/store/types/value_store.go
- go/store/types/value_store_test.go
- integration-tests/bats/garbage_collection.bats
Dolt GC is generational. By default, it moves all chunks reachable from commits into the old gen, and it leaves uncommitted data in the new gen. By default, it never revisits the chunks in the old gen. This means that if a branch with a lot of unique data exists during a GC, and then gets deleted, the storage taken up by that branch is never reclaimed by future garbage collection.
This PR implements `dolt gc --full`, which performs a collection on the entire database, ignoring the generational aspects of previous collections and visiting the entire set of live data. At the end of a successful `dolt gc --full`, only data which was reachable at the start of the run and data which has been written during the run will be present in the database.
Note: `dolt gc --full` visits every reachable …
> dolt gc --full: Implement a flag for GC which will collect everything, including the old gen.

- go/cmd/dolt/commands/schcmds/import.go
- go/libraries/doltcore/doltdb/commit_hooks_test.go
- go/libraries/doltcore/doltdb/doltdb_test.go
- go/libraries/doltcore/doltdb/durable/index.go
- go/libraries/doltcore/doltdb/durable/table.go
- go/libraries/doltcore/doltdb/root_val.go
- go/libraries/doltcore/doltdb/table.go
- go/libraries/doltcore/dtestutils/testcommands/multienv.go
- go/libraries/doltcore/merge/fulltext_rebuild.go
- go/libraries/doltcore/merge/merge_prolly_indexes.go
- go/libraries/doltcore/merge/merge_prolly_rows.go
- go/libraries/doltcore/merge/mutable_secondary_index.go
- go/libraries/doltcore/merge/violations_fk.go
- go/libraries/doltcore/sqle/alterschema_test.go
- go/libraries/doltcore/sqle/common_test.go
- go/libraries/doltcore/sqle/dtables/conflicts_tables_prolly.go
- go/libraries/doltcore/sqle/dtables/diff_table.go
- go/libraries/doltcore/sqle/enginetest/validation.go
- go/libraries/doltcore/sqle/tables.go
- go/libraries/doltcore/sqle/temp_table.go
- go/libraries/doltcore/sqle/testutil.go
- go/libraries/doltcore/sqle/writer/prolly_table_writer.go
- go/libraries/doltcore/table/editor/creation/external_build_index.go
- go/libraries/doltcore/table/editor/creation/index.go
- go/libraries/doltcore/table/untyped/sqlexport/sqlwriter_test.go
- go/store/datas/statistics.go
- go/store/prolly/shim/shim.go
- go/store/prolly/tuple_map.go
This is a refactor that eliminates a hack in how we deal with secondary indexes on keyless tables.
Keyless tables are unique in that the tuples stored in their prolly maps don't match their schemas: they have a hidden key column which doesn't appear in their schema; this key column stores a hash of the value tuple, and is used as a hidden primary key.
This mismatch between schema and structure poses some problems when creating secondary indexes. The current solution is to first make an index using the schema, and then conditionally create a second index with the correct descriptors. This is inefficient and error-prone: if we forget to perform this correction, we'll have an index that is invalid and unusable. It also ties the process of working with indexes to a specific implementation …
> [no-release-notes] Replace ConvertToSecondaryKeylessIndex with AddHashToSchema

- go/cmd/dolt/commands/engine/sqlengine.go
Fixes a race between setting the debug log output on `DoltDb` and running statistics configuration.
> Fix server init race

- go/cmd/dolt/commands/sql_statement_scanner.go
- go/cmd/dolt/commands/sql_statement_scanner_test.go
fixes: https://github.com/dolthub/dolt/issues/8495
The before code checks whether `s.i` is valid after doing the buffer access:
```go
for ; unicode.IsSpace(rune(s.buf[s.i])); s.i++ {
if s.i >= s.fill {
s.read()
}
}
```
The after code inverts the check to make sure `s.i` is valid before indexing into the buffer.
```go
for {
if s.i >= s.fill {
s.read()
}
if !unicode.IsSpace(rune(s.buf[s.i])) {
break
}
s.i++
}
```
> Fix bounds check in import scanner

- go/libraries/doltcore/sqle/binlogreplication/binlog_primary_streamer.go
- go/libraries/doltcore/sqle/binlogreplication/binlog_primary_test.go
- go/libraries/doltcore/sqle/binlogreplication/system_variable_utils.go
* Convert `@@server_id` to uint32 value when it gets loaded as a string from config.json
* Send binary logfile name in server heartbeat events, now required in MySQL 8.4
> Bug fixes for replication

- go/libraries/doltcore/sqle/enginetest/stats_queries.go
- go/libraries/doltcore/sqle/statsnoms/database.go
- go/libraries/doltcore/sqle/statspro/analyze.go
- go/libraries/doltcore/sqle/statspro/auto_refresh.go
- go/libraries/doltcore/sqle/statspro/interface.go
- integration-tests/bats/stats.bats
fixes: https://github.com/dolthub/dolt/issues/8504
Use schema hash to detect when database statistics might be incompatible. Drops all statistics for schema update. This could be improved to a subset of statistics if we wanted in the future.
> Fix panics on schema changes

- go/libraries/doltcore/env/grpc_dial_provider.go
- go/libraries/doltcore/remotestorage/chunk_store.go
Improves performance of fetches from DoltHub, sql-server, and doltlab.
Improves some situations where routers and network access points do not respond well to clients which open a great number of connections to the same TCP endpoint, many of which live for a very short period of time.
http.DefaultClient comes with a default MaxIdleConnsPerHost of 2. Fetching with a high number of concurrent downloads results in many connections not being reused efficiently because they cannot get back into the idle pool because it is so small. Here we increase the MaxIdleConnsPerHost to be large enough so that our active connections during a fetch will fit within it.
Note: S3 limits a single HTTP connection to 100 requests, after which it is closed server-side. So currently dolt can still require a large …
> libraries/doltcore/remotestorage: Improve connection reuse when fetching chunks from remote storage.

- go/libraries/doltcore/doltdb/root_val.go
- go/libraries/doltcore/sqle/database.go
- go/libraries/doltcore/sqle/schema_table.go
Binding a table name to a catalog symbol previously always loaded the schemas table from disk to first attempt binding a view. Now we cache `dolt_schemas` using its hash. If the table does not exist, no views are defined, and we short circuit attempting to bind a name to a view.
> Better view caching

- go/cmd/dolt/commands/diff.go
- integration-tests/bats/diff.bats
Fixes https://github.com/dolthub/dolt/issues/8511
Not all implementations of `sql.Type` are comparable. In particular, the enum type has a map field which makes the entire type incomparable.
To avoid doing this comparison in the `chooseMostFlexibleType` function, we modify it to compare the underlying type tag instead. This PR also short-circuits computing a unified schema unless the schema has changed.
> Avoid comparing `sql.Types` in `dolt diff`

- go/store/prolly/tree/indexed_json_diff.go
- go/store/prolly/tree/json_diff_test.go
- go/store/prolly/tree/json_scanner.go
If all of the following are true during a JSON diff operation:
1. One document fits in a single chunk and the other doesn't
2. The location of the chunk boundary in the larger document is also present in the smaller document. (It doesn't correspond to a location that was added or removed)
3. The chunk boundary falls at the end of a value in the document (before the next key or comma/right brace/etc)
Then the differ would fail to advance the prolly tree cursor and would incorrectly see the larger document as corrupt.
This fixes that issue and improves the error messaging to make it seem less like the database is corrupt, since the error is much more likely to be a parsing bug like this one.
> Fix issue where JSON diff would fail under specific circumstances.

- go/store/prolly/tree/indexed_json_diff.go
- go/store/prolly/tree/json_cursor.go
- go/store/prolly/tree/json_diff_test.go
If:
- A chunk begins with an object "A"
- A value "A.b" within this object was modified
- The previous chunk was also modified
Then the differ would incorrectly report that the entire "A" object had been modified, instead of the sub-value "A.b"
This could then lead to situations where the merge cannot be auto-resolved, because the differ claims that an object has been modified divergently, when it's actually two unrelated fields in the object that have been modified.
This PR fixes that scenario by properly detecting when the next chunk marks the start of an object.
> Fix JSON merge issue that would report imprecise diffs in some situations

- go/cmd/dolt/commands/diff.go
- integration-tests/bats/diff.bats
When modifying column from a decimal with a certain scale/precision to another decimal with different scale/precision, we should display diffs using the new decimal type instead of the old one.
related: https://github.com/dolthub/dolt/pull/8359
fixes: https://github.com/dolthub/dolt/issues/8551
> use new decimal type for `dolt diff`

- go/libraries/doltcore/sqle/database.go
- go/libraries/doltcore/sqle/enginetest/dolt_queries_diff.go
When we added support for showing diffs for the `STAGED` root through `dolt_commit_diff_` system tables, we didn't take into account that in detached head mode, there wouldn't be a valid staged root. This change detects if we're in detached head mode and replaces the staged root with the root of the detached head.
> Bug fix: `dolt_commit_diff` support for detached head mode

- go/cmd/dolt/commands/utils.go
In preparation for refactoring the auth server interface in Vitess/GMS, this change makes LateBindQueryist call `mysql.NewSalt()` directly, instead of relying on the `NewSalt()` method on the `MySQLDb` instance (which internally calls `mysql.NewSalt()`).
> Change LateBindQueryist to use `mysql.NewSalt()`

- go/store/nbs/table_index.go
Support suffix arrays larger than 4GB by avoiding uint32 overflows when matching chunk suffixes.
> go/store/nbs: table_index.go: Improve support for large table files.

- go/go.mod
- go/go.sum
- go/libraries/doltcore/sqle/binlogreplication/binlog_replication_test.go
This syntax is deprecated and will be removed in future MySQL versions (`SHOW REPLICA STATUS` should be preferred instead). However, some tools (e.g. Dolphie, MyDumper) still rely on this deprecated syntax, so we're adding support for it to keep compatibility with those tools.
Depends on: 
* https://github.com/dolthub/vitess/pull/381
* https://github.com/dolthub/go-mysql-server/pull/2767
> Add testing for `show slave status`

- go/libraries/doltcore/sqle/enginetest/dolt_queries.go
- go/libraries/doltcore/sqle/writer/prolly_index_writer.go
- go/libraries/doltcore/sqle/writer/prolly_index_writer_keyless.go
- go/store/val/tuple_descriptor.go
Certain types are stored out of band (like `TEXT` and `BLOB`), so we compare their addresses to test for existence. Consequently, the error message would contain the hash rather than the contents.
This PR fixes the formatting to print the prefix.
fixes: https://github.com/dolthub/dolt/issues/8629
> fix error message for duplicate unique key violation on out of band types

- go/libraries/doltcore/branch_control/access.go
- go/libraries/doltcore/branch_control/namespace.go
- go/libraries/doltcore/sqle/dtables/branch_control_table.go
- integration-tests/bats/branch-control.bats
- integration-tests/bats/helper/query-server-common.bash
This is primarily to fix issues with:
* https://github.com/dolthub/dolt/issues/8622
* https://github.com/dolthub/dolt/issues/8623
For the first issue, we did not actually update the longest match counter, and it was therefore being ignored. The variable existed, but it was not being updated. I think this went so long without being caught (even with all of the tests in `enginetests` and `bats`) due to how we handle expression folding, where subset entries are completely ignored if a superset already exists.
The second issue is somewhat similar to the first, in that we were not checking the permission set when determining whether a new row is actually a subset. If an existing row is a superset, but the permissions are more restrictive than the new row, then it's _not an actual superset_, …
> Fixed issues with branch control

- go/libraries/doltcore/diff/table_deltas.go
- go/libraries/doltcore/sqle/dtables/status_table.go
- integration-tests/bats/sql-status.bats
- integration-tests/bats/status.bats
Sometimes tables can change their hashes despite having no visible changes. The two ways I identified where this can happen are:
- The table has different column tags from the ancestor because it was originally a different table that got renamed.
- The table stores whether it's in a conflict and stores the hash of the other branch's table and the common ancestor table.
If these are the only changes to a table, we shouldn't report it as changed in `dolt status`.
These tables can still be staged and report as modified once staged.
> Update sql status to not report changes for unstaged tables that have changed but not visibly.

- go/libraries/doltcore/branch_control/branch_control.go
- integration-tests/bats/branch-control.bats
This is an actual fix for the following issue. Additional information was added, which actually exposes the root issue at hand. It's possible for the db/revision combo to make it to branch control, which expects just the branch name (since the revision is given under "branch"). This adds the proper split, so that we always get the database name.
* https://github.com/dolthub/dolt/issues/8623
> Fix for updated issue 8623

- go/libraries/doltcore/sqle/read_replica_database.go
- integration-tests/bats/replication.bats
Our logic to update refs in a read replica was tracking updated refs by path, so when branch `b1` was deleted and tag `b1` was added, the code was mixing them up and trying to update the branch with the tag ref. 
The fix is to track replicated refs by ID, instead of by path, to avoid collisions. This also changes the first return parameter of the `pullBranches` function, but none of the three places that call this function assign that first return param to a variable, so that change doesn't affect anything.
> Bug fix: replication fails when a branch is deleted and tag with same name is created

- go/cmd/dolt/commands/sqlserver/command_line_config.go
- go/libraries/doltcore/servercfg/serverconfig.go
- go/libraries/doltcore/servercfg/testdata/minver_validation.txt
- go/libraries/doltcore/servercfg/yaml_config.go
Its only member was 'query_parallelism`, which was unused. Existing config files with this key will still parse.
> Removed the `performance` server config block

- go/libraries/doltcore/sqle/enginetest/dolt_procedure_queries.go
- go/libraries/doltcore/sqle/procedures_table.go
Increase the supported stored procedure length from 1K to 8K.
> Enable larger statements for dolt_procedures

- go/cmd/dolt/dolt.go
use errors.New to replace fmt.Errorf with no parameters
> chore: use errors.New to replace fmt.Errorf with no parameters

- go/libraries/doltcore/schema/schema.go
- go/libraries/doltcore/schema/schema_test.go
- go/libraries/doltcore/sqle/dtables/diff_iter.go
- go/libraries/doltcore/sqle/dtables/prolly_row_conv.go
- go/libraries/doltcore/sqle/enginetest/dolt_queries_diff.go
This PR fixes the panic when attempting to view a diff on a table with virtual generated columns by just skipping over the values.
Ideally, we'd be able to resolve the generated column values themselves and show the diff, but that is not near at hand.
Fixes: https://github.com/dolthub/dolt/issues/8665
> fix panic for virtual columns in `dolt_diff_<tbl>`

- go/cmd/dolt/commands/sqlserver/server.go
- go/libraries/doltcore/servercfg/testdata/minver_validation.txt
- go/libraries/doltcore/servercfg/yaml_config.go
- go/libraries/doltcore/servercfg/yaml_config_test.go
- integration-tests/bats/sql-server.bats
The variable defined for the YAML Marshaller to write user variables to was defined as a `map[string]string`, which caused all variables to be read as a string even when they weren't quoted. Changing it to a `map[string]interface{}` fixes that.
fixes: https://github.com/dolthub/dolt/issues/8672
> parse user vars as `interface{}` instead of always `string`

- go/libraries/doltcore/sqle/dtables/commit_diff_table.go
- go/libraries/doltcore/sqle/dtables/diff_table.go
- go/libraries/doltcore/sqle/dtables/prolly_row_conv.go
- go/libraries/doltcore/sqle/enginetest/dolt_queries_diff.go
- integration-tests/bats/sql-diff.bats
This change makes the dolt_diff_* system table a little more forgiving when schema changes occur that we can _kind of_ map from one commit to the next. In the case of the issue, adding a primary key to a key keyless table. This doesn't work in both directions though - if you can't map the schema, we stop walking history (same as before).
Minor bump required due to behavior of the dolt_diff_* table changing are a result of this change.
Fixes: https://github.com/dolthub/dolt/issues/8625
> Give a little more information in dolt_diff_* when there is a pk change

- go/cmd/dolt/commands/schcmds/import.go
- go/libraries/doltcore/doltdb/commit_hooks_test.go
- go/libraries/doltcore/doltdb/doltdb_test.go
- go/libraries/doltcore/doltdb/durable/index.go
- go/libraries/doltcore/doltdb/root_val.go
- go/libraries/doltcore/doltdb/table.go
- go/libraries/doltcore/dtestutils/testcommands/multienv.go
- go/libraries/doltcore/merge/fulltext_rebuild.go
- go/libraries/doltcore/merge/violations_fk.go
- go/libraries/doltcore/sqle/alterschema_test.go
- go/libraries/doltcore/sqle/common_test.go
- go/libraries/doltcore/sqle/dtables/conflicts_tables_prolly.go
- go/libraries/doltcore/sqle/dtables/diff_table.go
- go/libraries/doltcore/sqle/tables.go
- go/libraries/doltcore/sqle/temp_table.go
- go/libraries/doltcore/sqle/testutil.go
- go/libraries/doltcore/table/editor/creation/external_build_index.go
- go/libraries/doltcore/table/editor/creation/index.go
- go/libraries/doltcore/table/untyped/sqlexport/sqlwriter_test.go
Instead of continuing to add parameters to `NewEmptyIndex`, I'm breaking it out into multiple functions that are more clear about where and how they're being used.
> [no-release-notes] Refactor NewEmptyIndex to avoid adding parameters for keyless and vector indexes

- go/go.mod
- go/go.sum
- go/performance/import_benchmarker/testdef.go
Currently, we are using two versions of the same package for xxHash:
https://github.com/dolthub/dolt/blob/d98baafd3e8248a9818e21442f4dfbdeffe78ac4/go/go.mod#L56-L57
`github.com/cespare/xxhash/v2` is the latest version, which includes bug fixes and improvements. This PR updates the codebase to replace `github.com/cespare/xxhash` with `github.com/cespare/xxhash/v2`.
No breaking changes, see https://go.dev/play/p/ZXuwERoBlEi.
> Replace `cespare/xxhash` with `cespare/xxhash/v2`

- go/cmd/dolt/cli/cli_context.go
- go/cmd/dolt/commands/init_test.go
- go/cmd/dolt/commands/signed_commits_test.go
- go/cmd/dolt/commands/sql_test.go
- go/cmd/dolt/commands/sqlserver/command_line_config.go
- go/cmd/dolt/commands/sqlserver/server.go
- go/cmd/dolt/commands/sqlserver/server_test.go
- go/cmd/dolt/commands/sqlserver/sqlserver.go
- go/cmd/dolt/commands/utils.go
- go/cmd/dolt/dolt.go
- go/cmd/dolt/system_checks.go
- go/libraries/doltcore/doltdb/feature_version_test.go
- go/libraries/doltcore/doltdb/foreign_key_test.go
- go/libraries/doltcore/doltdb/gc_test.go
- go/libraries/doltcore/dtestutils/testcommands/multienv.go
- go/libraries/doltcore/env/environment.go
- go/libraries/doltcore/merge/keyless_integration_test.go
- go/libraries/doltcore/merge/schema_integration_test.go
- go/libraries/doltcore/migrate/integration_test.go
- go/libraries/doltcore/rebase/filter_branch_test.go
- go/libraries/doltcore/schema/integration_test.go
- go/libraries/doltcore/sqle/integration_test/database_revision_test.go
- go/libraries/doltcore/sqle/integration_test/history_table_test.go
- go/libraries/doltcore/sqle/integration_test/json_value_test.go
- go/libraries/utils/argparser/parser_test.go
- go/libraries/utils/argparser/results.go
- go/performance/microsysbench/sysbench_test.go
- integration-tests/bats/profile.bats
- integration-tests/bats/sql-server.bats
This change alters the way we resolve the data-dir and initialized dolt processes. It originated from discovering that the tmp dir `replace` test at startup was leaving a test file in the current working directory. Long story short - the resolution of data-dir was too late in the process startup when sql-server was starting.
External behavior which will change:
1) Specifying `data_dir` in sql-server config file will correctly test the ability to rename files on the same partition, and override the TMPDIR environment variable when necessary, using $DATADIR/tmp when the user specified directory is on the wrong partition
2) Fail to start the server when the data-dir is specified multiple times. This will result in server startup failure for existing deployments which "work" (we choose the …
> dolt bootstrap refactor

- go/store/prolly/message/address_map.go
- go/store/prolly/message/blob.go
- go/store/prolly/message/commit_closure.go
- go/store/prolly/message/item_access.go
- go/store/prolly/message/merge_artifacts.go
- go/store/prolly/message/message.go
- go/store/prolly/message/prolly_map.go
- go/store/prolly/message/prolly_map_test.go
- go/store/prolly/message/serialize.go
- go/store/prolly/tree/node_test.go
- go/store/val/codec.go
- go/store/val/codec_test.go
- go/store/val/tuple_compare.go
- go/store/val/tuple_descriptor.go
This change allows future node messages to use 32 bit offsets in their encoding.
This increases the side of the Node struct, but given that each Node is much smaller than the message that it backs, this isn't really a memory concern.
Currently, none of the node types use this, so this change shouldn't have any immediate effect on observable behavior.
> Allow storing/reading 32 bit offsets in nodes.

- go/cmd/dolt/commands/show.go
- integration-tests/bats/show.bats
Currently the show command can print internal objects, which requires a local environment. This goes against the sql migration expectations that there is no environment. This change only makes the situation less bad. Splitting out the admin operations into another command is the right approach.
Fixes: https://github.com/dolthub/dolt/issues/8727
> Make show command more resilient when resolving references

- go/libraries/doltcore/sqle/dtables/workspace_table.go
- go/libraries/doltcore/sqle/enginetest/dolt_queries_workspace.go
Previously a panic was very likely if any update to dolt_workspace_* involved a schema change. This change restricts the updates to the workspace tables only in cases where the schemas have not changed.
> Don't panic when attempting to update workspace table

- go/cmd/dolt/cli/arg_parser_helpers.go
- go/cmd/dolt/commands/pull.go
- go/libraries/doltcore/sqle/dprocedures/dolt_pull.go
- integration-tests/bats/pull.bats
Expose in CLI and test too.
See: https://github.com/dolthub/dolt/issues/8734
> Add --prune option to dolt_pull procedure

- go/cmd/dolt/commands/utils.go
- integration-tests/bats/sql-privs.bats
From the command line, when a sql-server is not running, `dolt sql` implicitly uses the `root` account to log, but if the `root` account exists with a password, `dolt sql` will fail to log in. Since the user has access to the host and the database data directory, we should allow `dolt sql` to log into the SQL shell, even if the `root` user has a password set. This change also makes this behavior match when a sql-server is running, and we allow superuser login through the `__dolt_local_user__` account (which only exists while a sql-server is running).
> Allow `dolt sql` to always log in as the `root` superuser

- docker/docker-entrypoint.sh
- docker/serverREADME.md
- go/cmd/dolt/commands/engine/sqlengine.go
- go/cmd/dolt/commands/sqlserver/command_line_config.go
- go/cmd/dolt/commands/sqlserver/server.go
- go/cmd/dolt/commands/sqlserver/server_test.go
- go/cmd/dolt/commands/sqlserver/sqlserver.go
- go/cmd/dolt/commands/utils.go
- go/go.mod
- go/go.sum
- go/libraries/doltcore/dconfig/envvars.go
- go/libraries/doltcore/servercfg/serverconfig.go
- go/libraries/doltcore/servercfg/testdata/minver_validation.txt
- go/libraries/doltcore/servercfg/yaml_config.go
- go/libraries/doltcore/servercfg/yaml_config_test.go
- go/libraries/doltcore/sqle/binlogreplication/binlog_replica_controller.go
- go/libraries/doltcore/sqle/enginetest/dolt_server_tests.go
- go/performance/replicationbench/replica_test.go
- go/performance/serverbench/bench_test.go
- integration-tests/bats/events.bats
- integration-tests/bats/sql-local-remote.bats
- integration-tests/bats/sql-privs.bats
- integration-tests/bats/sql-server.bats
Previously, Dolt would only create a `root` superuser on sql-server startup when no other user accounts had been created. This resulted in a behavior where users would run `dolt sql-server`, create user accounts, then the next time they restart the sql-server, the `root` account would no longer be present. This behavior has surprised several customers (see https://github.com/dolthub/dolt/issues/5759) and is different from MySQL's behavior, which creates a persistent `root` superuser as part of initialization. 
This change modifies this behavior so that a `root` superuser is created, and persisted, the first time a SQL server is started for a database, unless the `--skip-root-user-initialization` flag is specified, or if an ephemeral super user is requested with the `--user` option. …
> Initialize persisted `root` superuser on SQL server startup

- go/libraries/doltcore/sqle/dprocedures/dolt_gc.go
This allows `call dolt_gc()` to more quickly and realibly establish a safepoint if the call to safepointF() races with a new query beginning and being registered for the connection in the process list.
> go/libraries/doltcore/sqle/dprocedures: dolt_gc.go: Retry canceling running queries when waiting for safepoint establishment.

- go/libraries/doltcore/doltdb/doltdb.go
- go/libraries/doltcore/env/actions/remotes.go
- go/libraries/doltcore/env/actions/tag.go
A user remarked that `dolt pull` took 2 hours to pull changes. This was the result of wasting time for every tag which had not changed. This change alters the tag iteration code to defers the loading of metadata until it's actually required. Testing against user takes less that 1min now.
> Speed up fetch when there are many tags which haven't changed

- .github/workflows/ci-bats-macos.yaml
- .github/workflows/ci-check-repo.yaml
Testing Dolt's `caching_sha2_password` auth support with the `mysql` client on MacOS [recently started failing with](https://github.com/dolthub/dolt/actions/runs/12894448219/job/35953113732?pr=8773#step:17:222): `mysql: command not found`
These tests were previously working, but the `mysql` client seems to no longer be available. This change adds a new step to ensure the current LTS `mysql` client is installed. 
These tests normally run nightly, but they [passed in an earlier CI run on this PR that triggered them](https://github.com/dolthub/dolt/actions/runs/12895036783/job/35955067001?pr=8773).
> Fix failing MacOS BATS tests

- go/store/chunks/chunk_store.go
- go/store/chunks/memory_store.go
- go/store/nbs/cmp_chunk_table_writer.go
- go/store/nbs/gc_copier.go
- go/store/nbs/store.go
- go/store/nbs/store_test.go
- go/store/types/value_store.go
During GC if we encounter an error we should cleanup the table writer. We can do it without finalizing the file, writing its index, etc. This improves the error path to be more correct and to leave less lingering state around.
> [no-release-notes]: go/store/nbs: Improve cleanup if we encounter an error during GC.

- go/libraries/doltcore/sqle/read_replica_database.go
- go/libraries/doltcore/sqle/replication_test.go
- integration-tests/bats/replication.bats
The read replica code that compares remote refs and local refs to determine which local refs need to be deleted when synchronizing a read replica from a remote had a problem where certain patterns of ref names could cause the code to select the wrong local refs to remove. These removed refs would not be present on the replica until a future synchronization run recreated them. 
The fix for this is to use the `Ref.String()` method (instead of `Ref.GetPath()`) to get a unique identifier for the ref (e.g. `refs/tags/t1`) and to ensure that the remote and local ref lists are both sorted by that unique identifier.
> Bug fix: ref conflict can cause tags to be temporarily removed on a replica

- go/libraries/doltcore/sqle/dtables/branches_table.go
- go/libraries/doltcore/sqle/sqlselect_test.go
- go/libraries/doltcore/sqle/testutil.go
- integration-tests/bats/sql-server.bats
- integration-tests/mysql-client-tests/node/workbenchTests/branches.js
This change allows users, particularly on servers, to quickly determine which branches have a dirty working set.
> Add the `dirty` column to the dolt_branches table

- go/store/nbs/archive_build.go
- go/store/nbs/archive_chunk_source.go
- go/store/nbs/archive_test.go
- go/store/nbs/aws_table_persister.go
- go/store/nbs/aws_table_persister_test.go
- go/store/nbs/bs_persister.go
- go/store/nbs/cmp_chunk_table_writer_test.go
- go/store/nbs/conjoiner_test.go
- go/store/nbs/empty_chunk_source.go
- go/store/nbs/file_table_persister.go
- go/store/nbs/file_table_persister_test.go
- go/store/nbs/frag/main.go
- go/store/nbs/generational_chunk_store.go
- go/store/nbs/ghost_store.go
- go/store/nbs/journal.go
- go/store/nbs/journal_chunk_source.go
- go/store/nbs/journal_test.go
- go/store/nbs/journal_writer_test.go
- go/store/nbs/mem_table.go
- go/store/nbs/mem_table_test.go
- go/store/nbs/no_conjoin_bs_persister.go
- go/store/nbs/root_tracker_test.go
- go/store/nbs/store.go
- go/store/nbs/store_test.go
- go/store/nbs/table.go
- go/store/nbs/table_persister.go
- go/store/nbs/table_reader.go
- go/store/nbs/table_set.go
- go/store/nbs/table_set_test.go
- go/store/nbs/table_test.go
Previously GC was constructed to walk the transitive closure of reachable chunks from when it started, and to take additional dependencies on any chunks that were written to the ChunkStore during the GC process. This change makes it so that we can additionally take dependencies on any chunks that are read from the ChunkStore during the GC process.
For the `nbs` layer to signal a new dependency during a GC, it makes use of a `keeperFunc`, which is passed into the `BeginGC` call. The contract is that, if `keeperFunc` is non-`nil` and it returns `false`, the chunk address which was given to the function will make its way back to a call to `SaveHashes` on some `MarkAndSweeper` whose contents  will end up in the final store once the GC is completed. `keeperFunc`, however, is allowed to return …
> [no-release-notes] go/store/nbs: During a GC process, take dependencies on chunks that are read through the ChunkStore.

- go/cmd/dolt/commands/engine/sqlengine.go
- go/libraries/doltcore/sqle/binlogreplication/binlog_metadata_persistence.go
- go/libraries/doltcore/sqle/binlogreplication/binlog_primary_test.go
- go/libraries/doltcore/sqle/binlogreplication/binlog_replica_applier.go
- go/libraries/doltcore/sqle/binlogreplication/binlog_replica_controller.go
- go/libraries/doltcore/sqle/binlogreplication/binlog_replica_event_producer.go
- go/libraries/doltcore/sqle/binlogreplication/binlog_replication_restart_test.go
- go/libraries/doltcore/sqle/binlogreplication/binlog_replication_test.go
This makes small clean ups to the lifecycle around replica applier and the ownership and lifecycle of the mysql.Conn read connection.
This PR also includes some changes to slightly improve the performance and reliability of the tests when running them locally. In particular, some of the changes include:
1) Since `go run ./cmd/dolt` takes about four seconds to validate the existing
cached build on my laptop, we just go ahead and use a cached build everywhere.
2) We use t.Log{f,} instead of fmt.Prin.. to improve the ergonomics of test
running and getting output from a failure in particular.
3) We try to minimize global process state changes like unnecessary `os.Chdir`
calls, since it would be nice to parallelize these tests eventually.
4) We get rid of the unused and seemingly unnecessary …
> [no-release-notes] go: binlogreplication: Add Session{{Begin,End}Command,End} lifecycle callbacks to the replica controller execution context session.

- go/cmd/dolt/commands/engine/sqlengine.go
- go/cmd/dolt/commands/sqlserver/server.go
- go/libraries/doltcore/sqle/cluster/controller.go
- go/libraries/doltcore/sqle/cluster/jwks.go
- go/libraries/doltcore/sqle/remotesrv.go
This PR changes each RPC invocation against the gRPC and HTTP servers
implementing remotesapi and cluster replication to create a sql.Context
which lives the duration of the call. The Session for that call gets
SessionCommand{Begin,End} and SessionEnd lifecycle callbacks so that it
can participate in GC safepoint rendezvous appropriately.
Previously the remotesrv.DBCache and the user/password remotesapi
authentication implementation would simply create new sql.Contexts
whenever they needed them. There could be multiple sql.Contexts for the
single server call.
> [no-release-notes] go: sqle,remotesrv: Implement sql.Session lifecycle callbacks for sql.Contexts used in remotesrv RPCs.

- go/libraries/doltcore/sqle/binlogreplication/binlog_primary_test.go
- go/libraries/doltcore/sqle/binlogreplication/binlog_replication_alltypes_test.go
- go/libraries/doltcore/sqle/binlogreplication/binlog_replication_filters_test.go
- go/libraries/doltcore/sqle/binlogreplication/binlog_replication_multidb_test.go
- go/libraries/doltcore/sqle/binlogreplication/binlog_replication_reconnect_test.go
- go/libraries/doltcore/sqle/binlogreplication/binlog_replication_restart_test.go
- go/libraries/doltcore/sqle/binlogreplication/binlog_replication_test.go
- go/libraries/doltcore/sqle/binlogreplication/cmd_attributes_unix_test.go
- go/libraries/doltcore/sqle/binlogreplication/cmd_attributes_windows_test.go
Move the global state to a harness struct, and change all interactions to go through the harness, so that we can run these tests in parallel.
We also clean up the process management a bit, since it was subject to leaving straggling sql-server and mysqld instances for me, usually because I would ^C it when it took too long after I ran `go test ./...`. The two major changes are:
1) In the happy case, we now gracefully terminate the child and assert that it exited success.
2) We now explicitly try to get helpful signals to all children when the test binary itself receives a SIGINT.
> [no-release-notes] go: binlogreplication: tests: Parallelize the test suite, slightly improve process management.

- go/libraries/doltcore/dconfig/envvars.go
- go/store/nbs/journal_record.go
- go/store/nbs/journal_record_test.go
- go/store/nbs/journal_writer.go
Before this change, the code that iterates over journal records would silently stop processing journal records once it encountered any invalid record. This change turns those invalid records into errors so that data isn't silently ignored. Customers can opt-in to the previous behavior by setting the `DOLT_SKIP_INVALID_JOURNAL_RECORDS ` environment variable to any value.
> Tidy up journal writer code comments and error handling

- go/store/nbs/generational_chunk_store.go
- go/store/nbs/ghost_store.go
Fixes a bug in the current implementation of GenerationalNBS.refCheck where things that are found in the GhostBlockStore are not marked in the hasRecords as being found.
> [no-release-notes] go: store/nbs: GhostBlockStore: Add refCheck which participates in updating hasRecords.

- go/libraries/doltcore/schema/schema_impl.go
This PR allows certain Doltgres extended types to be correctly serialized as part of keys
> Bug fix for encoding extended types in keys

- go/store/prolly/message/blob.go
- go/store/prolly/message/commit_closure.go
- go/store/prolly/message/item_access.go
- go/store/prolly/message/prolly_map_test.go
- go/store/prolly/tree/json_chunker.go
- go/store/prolly/tree/json_indexed_document.go
- go/store/prolly/tree/json_scanner.go
- go/store/prolly/tree/node_test.go
- integration-tests/bats/json.bats
`ItemAccess` is a class used to read data out of prolly tree nodes. Because the `itemWidth` field was limited to 16 bits, reading any value larger than 2^16 bytes would result in silent truncation.
We don't usually store values this large, although it should be safe to do so. 
This issue was discovered because the new JSON chunker (introduced in https://github.com/dolthub/dolt/pull/7912) always stores embedded strings as a single chunk, so a document containing a string larger than 32KB would result in a node with a single value whose length didn't fit in 16 bits.
While we were investigating this issue, we created https://github.com/dolthub/dolt/pull/8723 to disable the new JSON chunker in the presence of these long strings. This PR partially reverts that one, resuming the smart chunking …
> Expand `ItemAccess::itemWidth` to 32 bits

- go/libraries/doltcore/env/config.go
- go/libraries/doltcore/env/environment.go
- integration-tests/bats/init.bats
This PR changes `dolt init` to allow the dolt repo to still be created when there are no global users, but there are local users in `.dolt/config.json`.
In order to get to that state you must do
```shell
mkdir .dolt
dolt config --add user.email <email>
dolt config --add user.name <name>
```
related: https://github.com/dolthub/dolt/issues/8835
> allow `dolt init` on dolt repo with just `config.json`

- go/cmd/dolt/cli/stdio.go
- go/cmd/dolt/commands/sql.go
- integration-tests/bats/sql.bats
fixes: https://github.com/dolthub/dolt/issues/8839
> move status messages from parquet to stderr

- go/store/nbs/store.go
In certain cases, the work that SaveHashes does doesn't naturally see a context cancelation in a timely manner. Make certain we do return after we see one.
> [no-release-notes] go/store/nbs: Check for context cancelation in SaveHashes.

- go/libraries/doltcore/doltdb/doltdb.go
- go/libraries/doltcore/doltdb/gc_test.go
- go/libraries/doltcore/sqle/dprocedures/dolt_gc.go
- go/store/nbs/gc_copier.go
- go/store/nbs/journal_chunk_source.go
- go/store/nbs/store_test.go
- go/store/prolly/tree/node_cache.go
- go/store/prolly/tree/node_cache_test.go
- go/store/prolly/tree/node_store.go
- go/store/prolly/tree/testutils.go
- go/store/types/value_store.go
- go/store/types/value_store_test.go
- go/store/valuefile/file_value_store.go
- integration-tests/go-sql-server-driver/concurrent_gc_test.go
The right place to do this is in the safepoint controller, at BeginGC. We need to do it after keeperFunc is installed on the NomsBlockStore, so that all read dependencies are taken. We also need to do it before we register all sessions whose cached state we need to visit.
> [no-release-notes] go: sqle: dolt_gc: Purge read caches associated with the DoltDB as we begin GC.

- go/cmd/dolt/commands/engine/sqlengine.go
- go/cmd/dolt/commands/filter-branch.go
- go/cmd/dolt/commands/sql_test.go
- go/libraries/doltcore/sqle/commit_hooks.go
- go/libraries/doltcore/sqle/commit_hooks_test.go
- go/libraries/doltcore/sqle/database_provider.go
- go/libraries/doltcore/sqle/database_provider_test.go
- go/libraries/doltcore/sqle/enginetest/dolt_harness.go
- go/libraries/doltcore/sqle/index/mergeable_indexes_setup_test.go
- go/libraries/doltcore/sqle/logictest/dolt/doltharness.go
- go/libraries/doltcore/sqle/replication.go
- go/libraries/doltcore/sqle/replication_test.go
- go/libraries/doltcore/sqle/show_create_table.go
- go/libraries/doltcore/sqle/sqlddl_test.go
- go/libraries/doltcore/sqle/testutil.go
This PR moves aims to add session lifecycle callbacks to the async replication thread that each push-on-write replication database runs. In order to accomplish this, we move the initialization of those background threads to be later in the process of our construction of the SqlEngine. We also have to move the installation of the InitDatabaseHook which is responsible for setting up replication on newly created databases to be later in the initialization, as opposed to installing it immediately when we construct the DatabaseProvider.
> [no-release-notes] go: sqle: Change how we run background threads for replication hooks. Add session lifecycle callbacks for replication hooks.

- go/libraries/doltcore/doltdb/system_table.go
- go/libraries/doltcore/sqle/database.go
- go/libraries/doltcore/sqle/dtables/backups_table.go
- go/libraries/doltcore/sqle/enginetest/dolt_engine_test.go
- go/libraries/doltcore/sqle/enginetest/dolt_queries.go
- go/libraries/doltcore/sqle/enginetest/dolt_system_table_queries.go
- integration-tests/bats/ls.bats
Read only table which only lists the name and url of backups created by the dolt_backups procedure
> Add the dolt_backups table

- go/store/val/tuple_descriptor.go
The previous PR missed the case where an address column contained NULL values. This was caught in the Doltgres version bump, which has a test for it.
> [no-release-notes] Account for null values in AddressTypeHandler columns.

- go/store/nbs/store.go
This brings them in line with AddTableFilesToManifest.
UpdateManifest{,WithAppendix} are used by some implementations of dolt.services.remotesapi.v1alpha1.ChunkStoreService. Opening the table files is only less efficient if updateManifestAddFiles encounters an error, but it is safer because it ensures the table files are able to be opened before the added to the manifest itself. We do not expect updateManifestAddFiles to encounter errors - its only error condition is an I/O error on updating the manifest itself, or, previously, errors on opening the newly added table files.
> [no-release-notes] go/store/nbs: NomsBlockStore.UpdateManifest{,WithAppendix} pre-open table files before the manifest updates.

- integration-tests/bats/garbage_collection.bats
These bats tests perform some GCs and inspect filesystem state to assert that either nothing changed for a noop GC or that things actually did change for a non-noop GC. When the inspect the filesystem state, the `ls` output includes mtimes for the files and directories. `.dolt/stats` actually does, or at least can, change across these runs, and so it is explicitly removed before the comparison is done. That means the mtime on the `.dolt` directory itself changes. These timestamps are at minute resolution, and so the tests normally pass, but if the interactions happen in two separate minutes, they fail.
This change removes the directories themselves from the listing, leaving the files all in place. This asserts that the files' sizes and mtimes haven't (or have) changed across the `dolt gc` …
> [no-release-notes] integration-tests/bats: garbage_collection.bats: Fix flakiness stemming from times appear in ls output that we use for cmp.

- go/cmd/dolt/commands/blame.go
- go/cmd/dolt/commands/cvcmds/verify_constraints.go
- go/cmd/dolt/commands/engine/sql_print.go
- go/cmd/dolt/commands/schcmds/tags.go
- go/cmd/dolt/commands/sql.go
- go/cmd/dolt/commands/sql_slash.go
Adds the `\pager [on|off]` capability to `dolt sql`.
Fixes: https://github.com/dolthub/dolt/issues/8883
Currently no tests. Would require expect, and is probably beyond the investment in time for this feature.
> add pager support to sql shell

- go/store/nbs/aws_table_persister.go
- go/store/nbs/store.go
UpdateManifest{,WithAppendex} accidentally dropped an error when opening the new table files failed. Make them correctly return the error.
awsTablePersister was not respecting the namespace setting when checking for an archive file's existence when opening a table file.
> [no-release-notes] go/store/nbs: Fix some minor bugs affecting doltremoteapi in nbs/store.

- go/cmd/dolt/commands/sqlserver/server.go
- go/cmd/dolt/commands/sqlserver/server_test.go
- go/cmd/dolt/commands/sqlserver/sqlserver.go
- go/libraries/doltcore/sqle/enginetest/dolt_server_tests.go
- go/performance/replicationbench/replica_test.go
- go/performance/serverbench/bench_test.go
Allow configuring the ProtocolListenerFactory through ConfigureServices.
> go: cmd/dolt: sqlserver: Create a Config struct to encapsulate arguments that control sqlserver.ConfigureServices behavior.

- go/cmd/dolt/commands/debug.go
- go/libraries/doltcore/doltdb/durable/index.go
- go/libraries/doltcore/sqle/enginetest/stats_queries.go
- go/libraries/doltcore/sqle/statspro/analyze.go
- go/libraries/doltcore/sqle/statspro/auto_refresh.go
- go/libraries/doltcore/sqle/statspro/update.go
Stats collection skips non-prolly indexes. A more complete/safe refactoring of index use is in the new stats PR.
fixes: https://github.com/dolthub/dolt/issues/8964
> [statspro] stats ignore non prolly indexes

- .github/workflows/cd-push-docker-image.yaml
referencing this https://docs.github.com/en/rest/releases/releases?apiVersion=2022-11-28#update-a-release and this https://docs.github.com/en/actions/writing-workflows/choosing-what-your-workflow-does/using-github-cli-in-workflows
> [no-release-notes] /.github/workflows/cd-push-docker-image.yaml: use gh api

- go/libraries/doltcore/sqle/dsess/session.go
Adds the ability to queue notice messages in the session, for them to be sent to the client during the execution phase. Related to https://github.com/dolthub/doltgresql/pull/1255.
> Add support for setting notices in the session

- go/libraries/doltcore/sqle/dsess/session.go
- integration-tests/go-sql-server-driver/tests/sql-server-cluster.yaml
Cluster replication creates a system database, `dolt_cluster`, which does not support transactions. There are also UserSpaceDatabases which do not support CreateTransaction. CreateTransaction has special code to avoid visiting them when recording the start transaction state. CreateSavepoint needed to be updated with that logic as well.
> go: sqle/dsess: session.go: Fix transaction savepoint creation when cluster replication is enabled.

- go/store/nbs/archive_writer.go
- integration-tests/bats/archive.bats
Missed compressing the dictionary when building an archive streaming writer.
Added test which fails without the fix.
> [no-release-notes] compress dictionary

- go/libraries/doltcore/sqle/dsess/session_cache.go
- go/store/hash/hash.go
- go/store/util/sizecache/size_cache.go
This is a [new built-in function](https://pkg.go.dev/builtin@go1.21.0#clear) added in the go1.21 standard library, which can make the code more concise and easy to read.
> refactor: using clear to simplify the code

- go/go.mod
- go/go.sum
- go/go.work.sum
- go/libraries/doltcore/sqle/enginetest/dolt_queries.go
We are already using `github.com/google/uuid` for UUIDs. I think this dependency was accidentally introduced.
https://github.com/dolthub/dolt/blob/b7c0ddb4aac3702114c4e060651007d590a8be8c/go/go.mod#L24
https://github.com/dolthub/dolt/blob/b7c0ddb4aac3702114c4e060651007d590a8be8c/go/go.mod#L71
> Remove unnecessary `hashicorp/go-uuid` dependency

- go/libraries/doltcore/schema/typecompatibility/type_compatibility.go
- go/libraries/doltcore/schema/typecompatibility/type_compatibility_test.go
The following query caused a panic in Doltgres, because `DoltTable` was using `TypeCompatibilityChecker` to test if the column type change was compatible. `TypeCompatibilityChecker` wasn't able to handle the `ExtendedType` instance and panic'ed. This change makes `TypeCompatibilityChecker` ignore extended types, since it doesn't know enough about them to determine if a type change is compatible or not.
> Bug fix for TypeCompatibilityChecker to ignore ExtenedTypes

- go/store/nbs/store.go
1.50.0 introduced a perf regression which mainly effects taking backups to AWS or GCS. This is a partial fix which makes backups perform as before when they are going to a completely new destination. Incremental backups to an existing store are still slower. We continue to work on addressing the regression.
> go/store/nbs: Fix perf regression in taking backups.

- go/Godeps/LICENSES
- go/cmd/dolt/commands/add.go
- go/go.mod
- go/libraries/doltcore/sqle/dtablefunctions/dolt_patch_table_function.go
- go/store/prolly/tree/indexed_json_diff.go
The experimental functions in `golang.org/x/exp/slices` are now available in the standard library in Go 1.21.
Reference: https://go.dev/doc/go1.21#slices
> Replace `golang.org/x/exp/slices` with stdlib `slices`

- go/cmd/dolt/cli/stdio_test.go
- go/go.mod
- go/go.sum
https://github.com/dolthub/dolt/blob/b7c0ddb4aac3702114c4e060651007d590a8be8c/go/cmd/dolt/cli/stdio.go#L28
https://github.com/dolthub/dolt/blob/b7c0ddb4aac3702114c4e060651007d590a8be8c/go/cmd/dolt/cli/stdio_test.go#L23
It's weird that we use the tagged `v8` version in the source code but non-tagged version in the test.
> Remove duplicate `github.com/vbauerster/mpb` dependency

- go/Godeps/LICENSES
- go/go.mod
- go/go.sum
- go/store/nbs/s3_object_reader.go
This is a drop-in replacement.
Both [`github.com/jpillora/backoff`](https://pkg.go.dev/github.com/jpillora/backoff) and [`github.com/cenkalti/backoff/v4`](https://pkg.go.dev/github.com/cenkalti/backoff/v4) provide exponential backoff implementations. Since we already use `github.com/cenkalti/backoff/v4` elsewhere in the codebase, this change standardizes our dependency by using a single implementation consistently.
> Replace `jpillora/backoff` with `cenkalti/backoff/v4`

- go/cmd/dolt/commands/engine/sqlengine.go
- go/cmd/dolt/commands/sqlserver/server.go
- go/cmd/dolt/commands/utils.go
- go/libraries/doltcore/doltdb/durable/index.go
- go/libraries/doltcore/sqle/enginetest/dolt_harness.go
- go/libraries/doltcore/sqle/statspro/controller.go
- go/libraries/doltcore/sqle/statspro/jobqueue/serialqueue.go
- go/libraries/doltcore/sqle/statspro/listener.go
- go/libraries/doltcore/sqle/statspro/stats_kv.go
- go/libraries/doltcore/sqle/statspro/worker.go
- go/libraries/doltcore/sqle/statspro/worker_test.go
- avoid harness session re-use and sharing between test execution and stats
- move stats background threads outside of the harness re-use lifecycle of one query
- organize stats initialization in a way that plays nice with doltgres, dolt server, and shell
- fix when serialQueue synchronous callback exits early but still runs async in background
- fix various stats races
> [no-release-notes] Fix races in doltgres

- go/libraries/doltcore/dtestutils/sql_server_driver/server.go
- integration-tests/go-sql-server-driver/auto_gc_test.go
- integration-tests/go-sql-server-driver/concurrent_gc_test.go
- integration-tests/go-sql-server-driver/gc_oldgen_conjoin_test.go
- integration-tests/go-sql-server-driver/genjwt_test.go
- integration-tests/go-sql-server-driver/main_test.go
- integration-tests/go-sql-server-driver/sqlserver_info_test.go
- integration-tests/go-sql-server-driver/testdef.go
- integration-tests/go-sql-server-driver/tests/sql-server-cluster-read-only.yaml
- integration-tests/go-sql-server-driver/tests/sql-server-cluster-tls.yaml
- integration-tests/go-sql-server-driver/tests/sql-server-cluster-users-and-grants.yaml
- integration-tests/go-sql-server-driver/tests/sql-server-cluster.yaml
- integration-tests/go-sql-server-driver/tests/sql-server-config.yaml
- integration-tests/go-sql-server-driver/tests/sql-server-jwt-auth.yaml
- integration-tests/go-sql-server-driver/tests/sql-server-orig.yaml
- integration-tests/go-sql-server-driver/tests/sql-server-remotesapi.yaml
- integration-tests/go-sql-server-driver/tests/sql-server-tls.yaml
Takes local runtime from 500+s to ~100s.
> [no-release-notes] integration-tests/go-sql-server-driver: Add dynamic port allocation and run these tests in parallel.

- go/libraries/doltcore/sqle/database_provider.go
Fixes: https://github.com/dolthub/dolt/issues/9031
> Be more flexible for missing working sets when loading db

- go/cmd/dolt/commands/dump.go
- go/cmd/dolt/commands/engine/sqlengine.go
- go/cmd/dolt/commands/tblcmds/export.go
- go/cmd/dolt/commands/tblcmds/import.go
- go/libraries/doltcore/mvdata/data_loc_test.go
- go/libraries/doltcore/mvdata/data_mover.go
- go/libraries/doltcore/mvdata/engine_table_reader.go
- go/libraries/doltcore/mvdata/engine_table_writer.go
- go/libraries/doltcore/mvdata/file_data_loc.go
Pass the SqlEngine along and reuse it in the operations where we dump table contents, parse import schemas, etc.
> go: mvdata: Improve dump, import and export so that these commands create a single SqlEngine over their lifetime.

- go/libraries/doltcore/doltdb/doltdb.go
- go/store/datas/pull/pull_chunk_fetcher.go
- go/store/datas/pull/pull_chunk_fetcher_test.go
- go/store/datas/pull/pull_chunk_tracker.go
- go/store/datas/pull/pull_chunk_tracker_test.go
- go/store/datas/pull/pull_table_file_writer.go
- go/store/datas/pull/pull_table_file_writer_test.go
- go/store/datas/pull/puller.go
- go/store/datas/pull/puller_test.go
Our old heuristic was to cut a file and start uploading it when it reached a fixed number of chunks. We chose that number of chunks as just `(1<<30 / 4096)`, which is the average chunk size the chunker targets. But the chunk targets pre-compressed sizes. So file uploads which were hitting the target could vary a lot in size. It's better to just track how many bytes we've written so far and cut it when (approximately) appropriate. This is still best effort and only approximately.
Also improves error handling and structured concurrency a bit. Moves a number of goroutines up to the top-level errgroup in `Pull()`. Avoids creating – and thus potentially leaking – goroutines in `NewPuller()`, deferring them until `Pull` actually gets called. Gets rid of an unnecessary request-response thread …
> go: store/datas/pull: Error handling improvements. Target an approximate file size instead of a number of chunks when uploading files.

- go/cmd/dolt/commands/sql.go
- integration-tests/bats/sql-shell.bats
The migration to subcontexts of the Queryist sql.Context meant that we lost the default setting of the query start time. Restore it in the sql command implementation itself.
> go: cmd/dolt: commands/sql: Fix the displayed query time in interactive mode after a query completes.

- go/libraries/doltcore/doltdb/durable/table.go
- go/libraries/doltcore/sqle/tables.go
- integration-tests/bats/auto_increment.bats
When the AUTO_INCREMENT field is unset, the value of the next AUTO_INCREMENT column defaults to 1. Thus, setting it to 0 and 1 produce identical behavior.
By normalizing the value as its written, we ensure that both operations produce the same table hash as if the value was unset.
> Normalize AUTO_INCREMENT values in tables.

- go/store/nbs/generational_chunk_store.go
Use the built-in max/min from the standard library in Go 1.21 to simplify the code.  https://pkg.go.dev/builtin@go1.21.0#max
> refactor: use the built-in max/min to simplify the code

- go/libraries/doltcore/doltdb/commit.go
- go/libraries/doltcore/env/actions/commit.go
- go/libraries/doltcore/migrate/progress.go
- go/libraries/doltcore/sqle/dsess/session.go
- go/store/datas/commit_options.go
- go/store/datas/database_common.go
- integration-tests/go-sql-server-driver/sql_server_commit_concurrency_test.go
Fixes: https://github.com/dolthub/dolt/issues/9072
> Don't alter branch head outside of transactions when amending a commit

- go/store/prolly/tree/prolly_fields.go
- go/store/val/adaptive_value.go
- go/store/val/tuple_builder_test.go
- go/store/val/value_store.go
These types can now get returned by the engine, as alternate representations of text and blob types respectively.
Implementing the `driver.Value` interface ensures that they work correctly with go's SQL drivers.
> [no-release-notes] Have TextStorage and ByteArray implement driver.Value

- go/cmd/dolt/commands/archive.go
- go/store/nbs/archive_build.go
- integration-tests/bats/archive.bats
The `dolt archive` command is extra safe, and doesn't cleanup table files is converts. The --purge flag will delete table files after the conversion is done.
> Add the archive --purge flag to clean up table files

- go/store/val/value_store.go
For structs that are exclusively used in interfaces, there's no reason to not use pointer receivers instead of value receivers. Using value receivers can cause the struct to be copied every time the method is invoked.
Pointer receivers are also more correct here: copying the struct means that changes to the ImmutableValue field (such as setting its Buf field in ImmutableValue.GetBytes) won't be saved when the method exits, defeating the caching of values loaded from storage.
> Consistently use pointer receivers for TextStorage methods.

- go/store/prolly/tree/prolly_fields.go
In a check to see whether we could get the address of a wrapped value without unwrapping it, we were accidentally checking if the value was a `val.ByteArray` or `val.TextStorage`, when we should be checking to see if the value is a pointer to one of these types. This was causing us to unwrap unnecessarily.
> [no-release-notes] Correctly identify when we can get the address of a ByteArray or TextStorage without unwrapping it.

- go/libraries/doltcore/sqle/dtables/unscoped_diff_table.go
Use higher precision date type in the `dolt_diff` table - matching `dolt_diff_{table}` now
Fixes: https://github.com/dolthub/dolt/issues/9126
> More precision on the date column in the dolt_diff table

- go/go.mod
- go/go.sum
- go/libraries/doltcore/doltdb/foreign_key_coll.go
- go/libraries/doltcore/sqle/tables.go
MySQL parses the `ON UPDATE/DELETE SET DEFAULT` syntax, but does not actually support executing it. These minor changes allow the `SET DEFAULT` referential action to be used from Doltgres, but do not enable it for Dolt, to preserve MySQL compatibility. 
Depends on: https://github.com/dolthub/go-mysql-server/pull/2944
> Minor changes to support `SET DEFAULT` FK referential action

- go/cmd/dolt/cli/arg_parser_helpers.go
- go/cmd/dolt/cli/flags.go
- go/cmd/dolt/commands/gc.go
- go/cmd/dolt/commands/sqlserver/command_line_config.go
- go/cmd/dolt/commands/sqlserver/server.go
- go/cmd/dolt/commands/sqlserver/server_test.go
- go/libraries/doltcore/doltdb/doltdb.go
- go/libraries/doltcore/doltdb/gc_test.go
- go/libraries/doltcore/servercfg/serverconfig.go
- go/libraries/doltcore/servercfg/yaml_config.go
- go/libraries/doltcore/servercfg/yaml_config_test.go
- go/libraries/doltcore/sqle/auto_gc.go
- go/libraries/doltcore/sqle/auto_gc_test.go
- go/libraries/doltcore/sqle/dprocedures/dolt_gc.go
- go/store/chunks/chunk_store.go
- go/store/chunks/memory_store.go
- go/store/chunks/test_utils.go
- go/store/datas/database.go
- go/store/datas/database_common.go
- go/store/nbs/archive_writer.go
- go/store/nbs/cmp_chunk_table_writer.go
- go/store/nbs/gc_copier.go
- go/store/nbs/generational_chunk_store.go
- go/store/nbs/nbs_metrics_wrapper.go
- go/store/nbs/store.go
- go/store/nbs/store_test.go
- go/store/nbs/table_persister.go
- go/store/types/value_store.go
- go/store/types/value_store_test.go
- integration-tests/bats/garbage_collection.bats
Enable the GC operation to output archive format storage files. This is exposed as the `--archive-level` argument in both the server config and as a `dolt_gc()` option.
> Enable the GC process to write to archive files

- go/libraries/doltcore/sqle/enginetest/dolt_queries.go
The stored procedures rewrite fixed an issue where temporary tables aren't able to be created and selected within a stored procedure; this PR adds tests to specifically test for that case.
fixes: https://github.com/dolthub/dolt/issues/8762
> test for temporary tables in stored procedures

- go/store/val/value_store.go
Similar to https://github.com/dolthub/dolt/pull/9100
For structs that are exclusively used in interfaces, there's no reason to not use pointer receivers instead of value receivers. Using value receivers can cause the struct to be copied every time the method is invoked.
Pointer receivers are also more correct here: copying the struct means that changes to the ImmutableValue field (such as setting its Buf field in ImmutableValue.GetBytes) won't be saved when the method exits, defeating the caching of values loaded from storage.
> Consistently use pointer receiver for ByteArray

- go/cmd/dolt/commands/status.go
- integration-tests/bats/status.bats
Fix #9130 and  #9069.
```bash
$ dolt clone timsehn/docs
$ cd docs
$ dolt remote -v
origin https://doltremoteapi.dolthub.com/timsehn/docs
$ dolt remote rm origin
$ dolt status
On branch main
Your branch is up to date with 'origin/main'.
nothing to commit, working tree clean
```
> fix status command after removing origin from remote

- go/libraries/doltcore/sqle/dprocedures/dolt_fetch.go
- go/libraries/doltcore/sqle/dprocedures/dolt_pull.go
- go/libraries/doltcore/sqle/dprocedures/dolt_push.go
- integration-tests/go-sql-server-driver/auto_gc_test.go
- integration-tests/go-sql-server-driver/concurrent_gc_test.go
- integration-tests/go-sql-server-driver/gc_oldgen_conjoin_test.go
- integration-tests/go-sql-server-driver/sql_server_commit_concurrency_test.go
- integration-tests/go-sql-server-driver/sql_server_max_conns_test.go
- integration-tests/go-sql-server-driver/sqlserver_info_test.go
- integration-tests/go-sql-server-driver/testdef.go
- integration-tests/go-sql-server-driver/tests/sql-server-orig.yaml
- integration-tests/go-sql-server-driver/valctx_enabled_test.go
We need to rebase a remote in order to see its latest changes.
Fixes #9164.
> go: sqle/dprocedures: fetch,pull,push: Rebase the remote database before we interact with it.

- go/libraries/doltcore/sqle/dprocedures/dolt_gc.go
- go/libraries/doltcore/sqle/dprocedures/stats_funcs.go
- go/libraries/doltcore/sqle/statspro/controller.go
- go/libraries/doltcore/sqle/statspro/listener.go
- go/libraries/doltcore/sqle/statspro/listener_test.go
- go/libraries/doltcore/sqle/statspro/worker_test.go
Add pre-finalize blocking on the worker thread shutdown to dolt_gc safepoint controllers.
Add blocking on the worker thread shutdown to dolt_stats_stop(), so that a caller knows that stats have actually stopped by the time it returns.
> go: statspro: Make it possible for callers of StatsController.Stop() to block on the worker thread shutdown.

- go/cmd/dolt/commands/status.go
- go/cmd/dolt/dolt.go
- integration-tests/bats/global-args.bats
Fix issue #6979 
We define ```noValidRepository``` to ensure the command has a valid target, but in that definition we call ```mrEnv.GetEnv()``` on the wrong string, so it's always null with the --branch flag. We should call it just on the name of the database, excluding the branch. 
A string with the database and branch is also needed later, so we need to save both variables.
> Fix --branch global option always flagging error "no valid repository"

- go/libraries/doltcore/doltdb/root_val.go
- go/libraries/doltcore/merge/merge.go
- go/libraries/doltcore/schema/tag.go
- go/libraries/doltcore/sqle/alterschema.go
- go/libraries/doltcore/sqle/database.go
- go/libraries/doltcore/sqle/dtables/schema_conflicts_table.go
- integration-tests/bats/cherry-pick.bats
- integration-tests/bats/merge.bats
- integration-tests/bats/sql-cherry-pick.bats
Currently, attempting to merge when a table has been drop on one branch and had its data modified on the other produces an immediate error that aborts the merge. This error does not necessarily have enough context to determine the affected table, which makes resolving the merge difficult.
Given that we already handle a simultaneous drop + schema modification (by treating it as a schema conflict), we should be able to handle the simpler case of data modifications as well.
Since dropping a table is technically a schema change, this should now get reported as a schema conflict, and pause the merge, allowing the user to query dolt_schema_conflicts for more information.
After this PR, conflicts involving a dropped table will present the same as other schema conflicts: the user still won't be …
> When a table is deleted on one branch and has its data modified on the other, record this as a schema conflict.

- go/cmd/dolt/cli/arg_parser_helpers.go
- go/cmd/dolt/commands/schcmds/update-tag.go
- go/libraries/doltcore/sqle/dprocedures/dolt_update_column_tag.go
- go/libraries/doltcore/sqle/dprocedures/init.go
- integration-tests/bats/sql-update-column-tag.bats
Adds the `dolt_update_column_tag()` stored procedure to update a column's tag. This is an advanced operation that most users will not need to use. [This blog explains more about column tags and column tag conflicts](https://www.dolthub.com/blog/2025-05-15-column-tags/). 
**Example usage:**
```sql
CALL dolt_update_column_tag('myTable', 'col1', 4321);
```
**Follow ups:** 
* Add docs for the new `dolt_schema_update_tag()` stored procedure
* The `dolt schema update-tag` CLI command should be updated to use this stored procedure.
> Adding `dolt_update_column_tag()` stored procedure

- go/cmd/dolt/commands/tblcmds/import.go
- go/libraries/doltcore/mvdata/csv_helper.go
- go/libraries/doltcore/mvdata/data_mover.go
- go/libraries/doltcore/mvdata/file_data_loc.go
- go/libraries/doltcore/mvdata/stream_data_loc.go
- integration-tests/bats/helper/local-remote.bash
- integration-tests/bats/import-no-header-csv.bats
- integration-tests/bats/import-no-header-psv.bats
- integration-tests/bats/import-no-header.bats
- Add --no-header flag to treat the first row in CSV/PSV files as data instead of column names
- Add --columns option to specify column names when importing files without headers
- Fix nil pointer panic when importing from stdin with --create-table
In short, this feature makes Dolt more compatible with MySQL/SQLite workflows and provides users with more flexibility when importing data.
Previously, Dolt always expected the first row of CSV/PSV files to contain column names. This differs from MySQL and SQLite which support importing files where the first row contains data. Users migrating from these systems or working with headerless data files couldn't import them without modifying their files.
Additionally, when users attempted to import data from stdin using --create-table, they would …
> feat(import,csv,psv): Add support for importing CSV and PSV files without header rows

- go/libraries/doltcore/sqle/statspro/stats_kv.go
- integration-tests/go-sql-server-driver/stats_gc_test.go
For sql-server instances with many databases, many branches or many tables and indexes, flushing stats could cause queries to block until stats were finished flushing. StatsController attempted to rate limited how much I/O bandwidth would be used to flush stats, but this is currently counter-productive because all queries are blocked from analyzing successfully until stats are flushed.
This changes it back to flush stats to disk as quickly as possible when we need to do it. Computing stats is already rate limited, so for large flushes this should not happen too often.
We will continue to improve things here so that stats writes have less impact on server resource utilization and do not block user-facing work as they proceed.
> go: sqle/statspro: prollyStats: FlushFromMem: Fix long-held lock when flushing stats to disk.

- go/libraries/doltcore/sqle/binlogreplication/binlog_replica_applier.go
When a SQL error is sent from the replication source to the replica, the connection is closed out, but the error wasn't getting logged. This made it difficult to debug why the replication connection was erroring out.
> Log errors on a binlog connection

- go/cmd/dolt/cli/command.go
- go/cmd/dolt/commands/blame.go
- go/cmd/dolt/commands/cvcmds/verify_constraints.go
- go/cmd/dolt/commands/engine/sql_print.go
- go/cmd/dolt/commands/schcmds/tags.go
- go/cmd/dolt/commands/sql.go
- go/cmd/dolt/commands/sql_slash.go
- go/cmd/dolt/commands/sqlserver/queryist_utils.go
- go/libraries/doltcore/sqle/system_variables.go
- integration-tests/bats/sql-shell.bats
- integration-tests/bats/sql-show-warnings.expect
- integration-tests/bats/sql-warning-detail.expect
- integration-tests/bats/sql-warning-summary.expect
Fix issue https://github.com/dolthub/dolt/issues/8875
This pr adds support for warnings in the sql shell. There is now both a summary and detailed list of warnings.
Running `select 1/0;` will produce, after the table:
```1 row in set, 1 warning (0.0 sec)
Warning (Code 1365): Division by 0```
You can disable/enable the ending list with \w and \W, respectively.
> Sql shell warnings

- go/cmd/dolt/commands/diff_output.go
- integration-tests/bats/sql-diff.bats
Fixes #7817
From Claude:
```
⏺ Perfect! The changes are working correctly. Let me summarize what I've
implemented:
Summary
I successfully implemented the fix for GitHub issue #7817. The issue was
that dolt diff --stat -r sql was throwing a generic "unsupported" error,
but it should return a more specific error message explaining that SQL
format diffs are only for schema or data changes.
Changes Made:
1. Updated the error message in
/Users/timsehn/dolthub/git/dolt/go/cmd/dolt/commands/diff_output.go:
- Changed from: "diff stats are not supported for sql output"
- Changed to: "SQL format diffs only rendered for schema or data 
changes"
2. Updated the test in
/Users/timsehn/dolthub/git/dolt/integration-tests/bats/sql-diff.bats:
- Updated the expected error message in the test case to match …
```
> Made dolt diff --stat -r sql an error

- go/libraries/doltcore/sqle/sqlfmt/row_fmt.go
- integration-tests/bats/export-tables.bats
This prevents an issue where commands like `dolt dump` would fail when trying to export a table as SQL statements if the table has a `BLOB` column, since it would fail to unwrap the text wrapper value to access the underlying bytes.
> Allow dumping wrapper values to SQL

- go/cmd/dolt/cli/arg_parser_helpers.go
- go/cmd/dolt/commands/log.go
- integration-tests/bats/log.bats
Issue #8200 
Adds a `--all` option for dolt log. You can also specify tables after the all option, with `dolt lot --all table1 table2`. 
I still want to work on:
> --all option for dolt log

- go/libraries/doltcore/sqle/binlogreplication/binlog_position_store.go
- go/libraries/doltcore/sqle/binlogreplication/binlog_replica_applier.go
Fixes: https://github.com/dolthub/dolt/issues/9241
Fixes: https://github.com/dolthub/dolt/issues/8697
Testing for this is currently manual. To add automated tests for MariaDB integration, we'll need some larger changes to the binlog replication testing framework to support launching a MariaDB server. We should do that work eventually, especially if we hear more customer requests for MariaDB replication integration.
> Add support for MariaDB's GTID format

- integration-tests/bats/sql.bats
Claude insists that this behavior matches MySQL. It consulted the docs and ran tests against MySQL. 
I can confirm the tested behavior matches MariaDB which I have installed:
```
MariaDB [(none)]> CREATE DATABASE test_replace;
ERROR 1007 (HY000): Can't create database 'test_replace'; database exists
MariaDB [(none)]> DROP DATABASE IF EXISTS
->       test_replace;
Query OK, 1 row affected (0.057 sec)
MariaDB [(none)]> USE test_replace;
ERROR 1049 (42000): Unknown database 'test_replace'
MariaDB [(none)]> CREATE DATABASE test_replace;
Query OK, 1 row affected (0.003 sec)
MariaDB [(none)]> USE test_replace;
Database changed
MariaDB [test_replace]> CREATE TABLE test(pk BIGINT
->       PRIMARY KEY, v BIGINT);
Query OK, 0 rows affected (0.030 sec)
MariaDB [test_replace]> REPLACE INTO test
-> …
```
> Fix replace count test

- go/cmd/dolt/commands/init.go
- integration-tests/bats/init.bats
This flag really makes no sense any more
This is a claude change. $0.80, two prompts.
> Remove the --new-format flag from dolt init

- go/cmd/dolt/commands/tblcmds/import.go
- go/libraries/doltcore/env/actions/infer_schema.go
- go/libraries/doltcore/env/actions/infer_schema_test.go
- go/libraries/doltcore/schema/typeinfo/varstring.go
- integration-tests/bats/import-create-tables.bats
- integration-tests/bats/schema-import.bats
Length is 200 instead of 1023.
Fixes: #8972
> Added a new constant for string columns created during schema import.

- go/store/nbs/file_manifest.go
- go/store/nbs/store_test.go
Recent user report of a manifest landing that was missing it's format. This will at least prevent the generation of such a file in the future.
> manifest safety checks

- go/store/nbs/archive_chunk_source.go
- integration-tests/go-sql-server-driver/auto_gc_test.go
This avoids delivering the chunk more than once, which parts of the application layer are not expecting.
> go/store/nbs: archive_chunk_source.go: Make sure we skip getRecords marked found when fetching chunks.

- go/cmd/dolt/dolt.go
- go/libraries/doltcore/env/actions/remotes.go
- go/libraries/utils/dynassert/dynassert.go
- go/libraries/utils/dynassert/dynassert_test.go
- go/store/datas/database_common.go
- go/store/nbs/file_table_persister.go
- go/store/nbs/file_table_reader.go
- go/store/nbs/store.go
- go/store/nbs/table_reader.go
- go/store/nbs/table_set.go
- integration-tests/bats/helper/common.bash
- integration-tests/go-sql-server-driver/auto_gc_test.go
- integration-tests/go-sql-server-driver/testdef.go
A push to a remote works by uploading the missing content and then adding references to it in the remote datastore. If the remote is running a GC during the push, it is possible for the newly added data to be collected and no longer be available when the references are added.
This should cause a transient failure which is safe is retry. There were a couple bugs which could instead cause a panic. This makes some changes to safeguard against those case.
> go: store/datas/database_common: store/nbs/store.go: Fix some issues when pushing to a dolt sql-server that is itself running GC.

- docker/docker-entrypoint.sh
- docker/serverREADME.md
Fixes: #9374
Add support for MYSQL_USER/MYSQL_PASSWORD environment variables
> 9374 support mysql user mysql password env vars

- go/libraries/doltcore/sqle/dprocedures/dolt_gc.go
- go/libraries/doltcore/sqle/statspro/controller.go
- go/libraries/doltcore/sqle/statspro/worker.go
- go/libraries/doltcore/sqle/statspro/worker_test.go
- integration-tests/go-sql-server-driver/auto_gc_test.go
Previously GC, even with the session-aware safepoint controller, such as is used with Auto GC, would cancel any ongoing stats work and would restart it at the end of the run. Because Auto GC can run quite frequently and because stats can take a while to run to completion, this meant that on some workloads stats would never successfully populate.
This PR changes stats so that it more correctly integrates with the session-safe GC safepoint controller. That allows GC to ensure that the stuff stats is currently working on gets carried over to the collected view of database, and stats itself has a chance to run to completion regardless of what GC work is going on.
This PR leaves the cancel-stats-on-collect behavior enabled for the kill-connections safepoint controller, where that behavior is …
> go: sqle/statspro: Rework the way stats manages its session in order to make it safe to continue collecting stats during a GC run.

- go/libraries/doltcore/sqle/dtablefunctions/dolt_diff.go
- go/libraries/doltcore/sqle/dtablefunctions/dolt_patch.go
- go/libraries/doltcore/sqle/dtables/column_diff_table.go
- go/libraries/doltcore/sqle/dtables/commit_diff_table.go
- go/libraries/doltcore/sqle/dtables/diff_iter.go
- go/libraries/doltcore/sqle/dtables/diff_table.go
- go/libraries/doltcore/sqle/index/dolt_index.go
- integration-tests/bats/sql-commit-diff.bats
The `dolt_commit_diff_` system tables allow for comparing a table at two different commits. They require a filter on the `to_commit` and `from_commit` fields, which the table exposes as an index.
This PR extends those indexes to have additional columns based on the primary keys of the underlying table. This allows a user to efficiently compare only a specific range of that table.
Specifically, if the table's primary key columns are named `pk1`, `pk2`, ... `pkN`, then the system table now provides two indexes:
- `to_commit`, `from_commit`, `from_pk1`, `from_pk2`... `from_pkN`
- `to_commit`, `from_commit`, `to_pk1`, `to_pk2`... `to_pkN`
If the select filter uses a prefix of either of these indexes, then we can implement the select as a Diff on only the intended range.
Because the `to_` …
> Add indexes to dolt_commit_diff_ tables that include the primary key of the underlying table

- go/cmd/dolt/commands/archive.go
Make lambabats more reliable.
Also, catch an error which was previously ignored.
> Flush outputs in archive command. Fixes flaky test

- go/store/nbs/archive_reader.go
- go/store/nbs/archive_writer.go
- go/store/nbs/file_table_reader.go
- go/store/nbs/gc_copier.go
- go/store/nbs/store.go
- go/store/types/value_store.go
- integration-tests/go-sql-server-driver/auto_gc_test.go
A bug in the usage of dynassert meant that clone() was always opening a new table file, instead of using the existing open file.
There were a few known consequences:
* the window of opportunity when unlocked reads could try to read a closed chunk source and receive an error was much larger than typical. As a result, auto_gc on a standby replica in a cluster was much more likely to fail spuriously.
* the number of file descriptors a running server would churn was higher than typical, and some operations were a bit slower / more prone to context switches than they needed to be.
This PR also updates some errors to be slightly more verbose about their origin.
This PR also updates TestAutoGC in go-sql-server-tests to run less iterations in CI and in -test.short mode. The iterations should be …
> [no-release-notes] go: store/nbs: file_table_reader.go: Fix clone() so that it actually uses the reference count.

- go/cmd/dolt/commands/admin/admin.go
- go/cmd/dolt/commands/admin/newgen_to_oldgen.go
- go/store/nbs/admin_newgen_to_oldgen.go
GC is prohibitively expensive for the media_wiki repo, and we know that the table files downloaded from DoltHub don't contain garbage. This admin tool moves everything from newgen to oldgen so that GC won't spend it's time on moving chunks we know aren't garbage.
> [no-release-notes] NewGen -> OldGen admin script

- go/cmd/dolt/commands/tblcmds/import.go
- integration-tests/bats/import-tables.bats
This addresses the second comment/request in #1083. It improves the error messages for dolt table import when incorrect argument counts are provided.
Previously, when users provided the wrong number of arguments to dolt table import, they would see:
`expected 1 or 2 arguments`
This message didn't indicate how many arguments were actually provided, making it difficult to debug command issues.
Updated the argument validation to show the actual argument count:
- For 0 arguments: 
`expected 1 argument (for stdin) or 2 arguments (table and file), but received 0`
- For >2 arguments: 
`"expected at most 2 arguments (table and file), but received N`
Additionally, the argparser now shows all provided arguments when there are too many, e.g.:
error: import has too many positional arguments. …
> refactor(import): show actual arg count in import error messages

- go/libraries/doltcore/schema/col_coll.go
- go/libraries/doltcore/schema/schema_impl.go
- go/libraries/doltcore/schema/schema_test.go
Remove database-side auto_increment type validation to allow GMS to handle all validation logic.
Fixes dolthub/dolt#9481
- Removed ErrNonAutoIncType error from col_coll.go
- Removed auto_increment validation logic from ValidateForInsert in schema_impl.go
- Removed unused helper functions isAutoIncrementKind and isAutoIncrementType
- Added comprehensive tests for auto_increment on various data types
> dolthub/dolt#9481 - Move auto_increment validation to GMS

- go/cmd/dolt/commands/checkout.go
- go/libraries/doltcore/sqle/dprocedures/dolt_checkout.go
- go/libraries/doltcore/sqle/enginetest/dolt_queries.go
- integration-tests/bats/checkout.bats
Fix #9392 
Enhances the dolt_checkout stored procedure to handle missing table specifications
more gracefully by processing valid tables while providing detailed warnings for
invalid ones, instead of failing immediately on the first missing table.
- Enhanced Error Handling: Modified checkoutTablesFromHead() to collect warnings
for missing tables instead of failing fast
- Improved User Experience: Valid tables are now processed successfully even when
some specified tables don't exist
- Better Error Reporting: Multiple missing tables now show aggregated error
messages
- Added Test Coverage: Comprehensive tests for single and multiple missing table
scenarios
Before: call `dolt checkout valid_table missing_table` would fail entirely
After: call `dolt_checkout valid_table missing_table` …
> Improve `dolt checkout` error handling for missing tables

- go/cmd/dolt/cli/arg_parser_helpers.go
Documentation bug. We have tests to ensure you can't specify `--archive-level 2`
Fixes: https://github.com/dolthub/dolt/issues/9521
> Update GC docs to have correct max for archive level

- integration-tests/bats/feature-version.bats
It looks like someone has fixed this feature version issue and Codex identified it:
https://github.com/dolthub/dolt/issues/6303
> Unskip feature version bats test that now passes

- go/libraries/doltcore/sqle/dtablefunctions/dolt_branch_status_table_function.go
- go/libraries/doltcore/sqle/dtablefunctions/dolt_log.go
- go/libraries/doltcore/sqle/dtablefunctions/dolt_log_test.go
- integration-tests/bats/system-tables.bats
Fixes #9508
Fix dolt_log table function to support bind variables in prepared statements
Implemented deferred argument parsing to allow proper bind variable handling during prepare phase
> #9508 - Fix dolt_log table function to support bind variables in prepared statements

- go/store/prolly/tree/json_location.go
- integration-tests/bats/json.bats
Fixes dolthub/dolt#9556
Fixed dolt's JSON path parser to accept unnecessarily quoted field names like $."a".
The issue was in the lexer logic that incorrectly detected empty quoted strings when processing unnecessarily quoted simple field names.
> dolthub/dolt#9556 - Fix JSON path parsing for unnecessarily quoted field names

- go/go.mod
- go/libraries/doltcore/sqle/dsess/autoincrement_tracker.go
- integration-tests/bats/auto_increment.bats
Fixes dolthub/dolt#9530
Companion PR: dolthub/go-mysql-server#3103
Fixed auto-increment display discrepancy in SHOW CREATE TABLE by adding type checking to prevent incrementing beyond integer type maximums.
>  dolthub/dolt#9530 - Fix auto-increment display for SHOW CREATE TABLE

- .github/workflows/ci-check-repo.yaml
This change adds `gofmt` and `goimports` steps to the protobuf generation process to ensure that generated `.pb.go` files are consistently formatted.
> Run gofmt and goimports on generated protobuf files to ensure clean diffs

- go/libraries/doltcore/merge/merge_prolly_rows.go
- go/libraries/doltcore/merge/violations_fk_prolly.go
- go/libraries/doltcore/sqle/enginetest/dolt_queries_schema_merge.go
During a merge, Dolt applies diffs to existing indexes to sync their data with the changes being merged in. If the table schema has changed between the merge base and the left/right branches of the merge, Dolt was using the incorrect value tuple to remove the row from the index. This resulted in a customer issue where the secondary index still contained rows and the foreign key validation logic was incorrectly detecting FK violations, even though the child table was empty. 
As a follow-up to this, we need to investigate other similar cases in the secondary index merger and see if other diff types have a similar issue.
> Bug fix: Update secondary index correctly during a merge with a schema change

- go/cmd/dolt/commands/engine/sqlengine.go
- go/libraries/doltcore/sqle/clusterdb/database.go
- go/libraries/doltcore/sqle/database.go
- go/libraries/doltcore/sqle/database_provider.go
- go/libraries/doltcore/sqle/dsess/auto_increment_tracker_test.go
- go/libraries/doltcore/sqle/dsess/autoincrement_tracker.go
- go/libraries/doltcore/sqle/dsess/globalstate.go
- go/libraries/doltcore/sqle/dsess/session_db_provider.go
- go/libraries/doltcore/sqle/user_space_database.go
This lets us more cleanly close DoltDB instances, which we should not be accessed after we close them.
> go: sqle: autoincrement_tracker: When we close the engine.SqlEngine, finalize any ongoing initialization of AutoIncrementTrackers.

- proto/Makefile
With the removal of the circular symlink in go/gen/proto/github.com, we need grpc-go_out path to be source relative as well.
> [no-release-notes] proto/Makefile: Fix the generation of _grpc.pb.go files.

- go/cmd/dolt/commands/ci/ci.go
- go/cmd/dolt/commands/ci/run.go
- go/cmd/dolt/commands/ci/view.go
- go/libraries/doltcore/env/actions/dolt_ci/utils.go
- go/libraries/doltcore/env/actions/dolt_ci/workflow_manager.go
- integration-tests/bats/ci.bats
Adds `dolt ci run`:
Usage: `dolt ci run <workflow name>`
Runs all defined saved queries and asserts the given column or row count against those queries.
> Add `dolt ci run`

- go/cmd/dolt/commands/ci/import.go
- go/libraries/doltcore/env/actions/dolt_ci/workflow_config.go
- integration-tests/bats/ci.bats
Two small changes to CI:
1. `dolt ci import` now requires that the branches you list under `on.action`, `on.pull_request` are valid branch names. This also blocks off attempting to use the `*` wildcard identifier, which we do not support.
2. I also expanded the `dolt ci import --help` page to include the specification for the workflow yaml files.
> Small fixes to ci, --help & valid branch names

- go/libraries/doltcore/doltdb/system_table.go
I notice that Claude Code likes auto_increment primary keys but Dolt likes UUID keys better. So, I added a section to AGENT.md.
> Add UUID key recommendation to default AGENT.md

- go/libraries/doltcore/sqle/dprocedures/dolt_checkout.go
- integration-tests/bats/sql-server-remotesrv.bats
`dolt_checkout()` already had logic to initialize a branch's working set if one was not available, but the error it expected to see to trigger that logic was not being returned by the functions it called. This changes the `checkoutExistingBranch()` function so that it also resolves the working set for that branch and returns a `doltdb.ErrWorkingSetNotFound` error if the working set is not available.
> Bug fix: ensure `dolt_checkout()` initializes a branch's working set

- go/performance/scripts/local_sysbench.sh
- go/performance/scripts/local_tpcc.sh
Sysbench requires that dolt specify TLS key and cert for scripts to run locally now.
This PR updates the scripts to copy over our testing `.pem` files from elsewhere in the directory.
> [no-release-notes] fix local sysbench scripts to use SSL

- go/libraries/doltcore/doltdb/system_table.go
Dolt CI does not support wildcards in branch specs.
> Remove references to branch wildcards in Dolt CI YAML in AGENT.md

- .github/workflows/ci-binlog-tests.yaml
- .github/workflows/ci-go-tests.yaml
The binlog tests take a long time to run, so I pulled them out into a separate CI job. 
When I tested the CI job, the [new binlog job ran in about 40 minutes](https://github.com/dolthub/dolt/actions/runs/16923116715/job/47953453703), and the [ubuntu Go tests ran in about 20 minutes](https://github.com/dolthub/dolt/actions/runs/16923116719/job/47953453846).
> [no-release-notes] Move binlog tests to a separate CI job

- go/libraries/events/collector.go
- go/libraries/events/emitter.go
- go/libraries/events/events_test.go
Changes the event collector/emitter to drop old events and not grow unbounded when events can't be delivered.
The event collector already batched 64 events per request when `LogEvent` messages were being sent successfully. However, when there are issues sending `LogEvent` messages, the events queue up, with no upper bound, and each `LogEvent` request gets larger and larger. This change limits the tracked "unsent" events to that existing 64 event batch size.
> Drop old event messages

- go/performance/scripts/local_sysbench.sh
- go/performance/scripts/local_tpcc.sh
- go/performance/utils/benchmark_runner/dolt_server_config.go
- go/performance/utils/benchmark_runner/results_test.go
- go/performance/utils/benchmark_runner/run_test.go
Since our group validation much more closely aligns with MySQL, we discovered that sysbench script `groupby_scan.lua` is not valid in MySQL without disabling `ONLY_FULL_GROUP_BY` in `sql_mode`. This PR fixes the local test scripts and the benchmark runners to accept a `config.yaml` with the `sql_mode` set.
> disable `only_full_group_by` in sysbench

- go/libraries/doltcore/doltdb/system_table.go
- go/libraries/doltcore/sqle/database.go
- go/libraries/doltcore/sqle/dtables/query_catalog_table.go
- go/libraries/doltcore/sqle/dtables/tests_table.go
- go/libraries/doltcore/sqle/enginetest/dolt_engine_test.go
- go/libraries/doltcore/sqle/enginetest/dolt_engine_tests.go
- go/libraries/doltcore/sqle/enginetest/dolt_queries_test_table.go
Adds `dolt_tests` system table. The table currently has no functionality, but behaves similarly to the other writable system tables like `dolt_ignore` and `dolt_query_catalog`.
> dolt_tests system table

- go/libraries/doltcore/remotesrv/grpc.go
- go/store/nbs/archive.go
- go/store/nbs/archive_build.go
- go/store/nbs/archive_chunk_source.go
- go/store/nbs/archive_reader.go
- go/store/nbs/archive_test.go
- go/store/nbs/archive_writer.go
- go/store/nbs/aws_table_persister.go
- go/store/nbs/metadata.go
Mostly refactoring to prepare for archive conjoins.
Main change is dropping the use of checksums for datablocks stored in the archive footer. This path is unworkable with cloud conjoin because we create the index in memory without the datablocks to generate the checksums. This also effects how we name artifacts.
> [no-release-notes] conjoin prep

- go/libraries/doltcore/sqle/cluster/controller.go
- integration-tests/go-sql-server-driver/tests/sql-server-cluster.yaml
Fixes #9725
Newly promoted primary could reuse AUTO_INCREMENT values due to a stale in-memory tracker. On promotion, we now synchronously refresh AUTO_INCREMENT trackers for databases already loaded in the session, aligning sequences with the current working sets so the first post-promotion inserts do not reuse existing IDs.
> dolthub/dolt#9725 - Fix AUTO_INCREMENT reuse after HA failover by refreshing trackers

- go/cmd/dolt/commands/sqlserver/command_line_config.go
- go/cmd/dolt/commands/sqlserver/server_test.go
- go/cmd/dolt/commands/sqlserver/sqlserver.go
- go/libraries/doltcore/servercfg/serverconfig.go
- go/libraries/doltcore/servercfg/testdata/minver_validation.txt
- go/libraries/doltcore/servercfg/yaml_config.go
- integration-tests/bats/sql-server-mcp-config.bats
This PR is part two of supporting mcp directly in Dolt. This one adds the `mcp_server` key to the `dolt sql-server` `config.yaml`, allowing users to start/configure the http dolt-mcp server here, instead of only with cli arguments. If both the config file defines `mcp_server` and mcp related cli arguments are supplied, the cli args take precendence over the config file definitions.
> support `mcp_server` in the the `dolt sql-server` configuration file

- go/cmd/dolt/commands/archive.go
- go/libraries/doltcore/doltdb/commit_itr.go
- go/libraries/doltcore/doltdb/doltdb.go
- go/libraries/doltcore/env/actions/commitwalk/commitwalk.go
- go/libraries/doltcore/rebase/rebase.go
- go/libraries/doltcore/sqle/database.go
- go/libraries/doltcore/sqle/dolt_procedures_diff_table.go
- go/libraries/doltcore/sqle/dolt_schemas_diff_table.go
- go/libraries/doltcore/sqle/dprocedures/dolt_count_commits.go
- go/libraries/doltcore/sqle/dtablefunctions/dolt_log.go
- go/libraries/doltcore/sqle/dtables/column_diff_table.go
- go/libraries/doltcore/sqle/dtables/commit_ancestors_table.go
- go/libraries/doltcore/sqle/dtables/commits_table.go
- go/libraries/doltcore/sqle/dtables/diff_table.go
- go/libraries/doltcore/sqle/dtables/log_table.go
- go/libraries/doltcore/sqle/dtables/unscoped_diff_table.go
- go/libraries/doltcore/sqle/history_table.go
- go/performance/dolt_log_bench/.gitignore
- go/performance/dolt_log_bench/dolt_log_test.go
- go/store/datas/database_common.go
Changes:
- use the commitMetadata and commitHeight (if available) in iterator
- reduce string and regex operations when resolving a known hash commit spec
- directly access parent rather than allocating slice
The result of these changes is roughly 1.7x speed up in `select * from dolt_log()` queries.
Addresses: https://github.com/dolthub/dolt/issues/9743
> Optimize commit iterator

- go/libraries/doltcore/doltdb/doltdb.go
- go/libraries/doltcore/env/memory.go
- go/libraries/doltcore/migrate/integration_test.go
Changes:
- store a cache of all resolved commit hashes on doltdb
This results in another ~2.3x speed up, so ~4.7x in total.
> Cache materialized commits on `doltdb`

- go/libraries/doltcore/env/actions/test_table_helpers.go
- go/libraries/doltcore/sqle/dtablefunctions/dolt_test_run.go
- integration-tests/bats/dolt-test-run.bats
Changes: 
- delete  `Close()` calls missed in https://github.com/dolthub/dolt/pull/9811
- adds a test for single result assertion
- add missing cases for int types
> fix missed `context canceled` error for `dolt_test_run()`

- go/libraries/doltcore/sqle/dtablefunctions/dolt_patch.go
- go/libraries/doltcore/sqle/dtables/branches_table.go
- go/libraries/doltcore/sqle/dtables/dtable_fk_editor.go
- go/libraries/doltcore/sqle/enginetest/dolt_engine_test.go
- go/libraries/doltcore/sqle/enginetest/dolt_engine_tests.go
- go/libraries/doltcore/sqle/enginetest/dolt_queries.go
- go/libraries/doltcore/sqle/fk/fk_references.go
- go/libraries/doltcore/sqle/index/dolt_index.go
- go/libraries/doltcore/sqle/sqlutil/convert.go
- go/libraries/doltcore/sqle/tables.go
Allows creating foreign keys on user tables that reference the `name` column on the `dolt_branches` table. 
Fixes: https://github.com/dolthub/dolt/issues/9712
> Allow foreign keys to reference `dolt_branches` system table

- go/libraries/doltcore/sqle/dtables/docs_table.go
Moving the dolt_docs system table to use the new UserSpaceSystemTable struct broke some tests Dolthub.
This was a less safe change because dolt_docs has additional functionality (it contains an "AGENT.md" file by default. Having DocsTable embed a UserSpaceSystemTable is theoretically safe as long as references to the underlying UserSpaceSystemTable don't leak and get used instead of the DocsTable.
Rather than try and identify the underlying cause, it makes more sense to just revert this change for DocsTable and only use UserSpaceSystemTable for tables that don't have any extra behavior. It means some code duplication, but it's safer.
> Revert refactor of dolt_docs table.
